### ISSUE TITLE
pbts generates file .d.ts no Long type is needed

### ISSUE THREAD

**Issue by tomoat** [dcodeIO/protobuf.js#1005]
The Int64 defined in the.Proto file generates Number|Long, and actually returns the string type, and there is no way to make the file generated by the ptjs contain the Long type？

**Comment by dcodeIO** [comment]
I'm not sure that I'm understanding your question correctly, but there is this option to pbjs that generates the JS file used by pbts to generate the TSD file:

```
--force-long     Enfores the use of 'Long' for s-/u-/int64 and s-/fixed64 fields.
```

**Comment by tomoat** [comment]
Thanks @dcodeIO
