### ISSUE TITLE
Can not load *.proto file with abs path

### ISSUE THREAD

**Issue by grandkarabas** [dcodeIO/protobuf.js#1027]
protobuf.js version: 6.8.6

<please describe the expected and actual behavior>
Expected - non-empty initialized root object here:

```js
<head>
    <script src="https://cdn.rawgit.com/dcodeIO/protobuf.js/6.8.6/dist/protobuf.js"></script>
</head>
<body>
  <script type="text/javascript">
    const ProtoPath = 'file:///home/john/protocol/ac_admin.proto';
    protobuf.load(ProtoPath, function(err, root) {
      console.log(root);
    });
  </script>
</body>
```
Actual - empty root object.

I'm sure I'm doing something wrong. Could you please explain to me what kind of 'filename' I should provide here (this code it taken from the exmaple): absolute path to the .proto file, URL or something else.
```js
protobuf.load("awesome.proto", function(err, root) {
...
```

Thank you in advance.

**Comment by grandkarabas** [comment]
I have found a solution with URL.

My backend currently returns the content of appropriate .proto file as the response to frontend `protobuf.load(url)`.

Please, explain to me, whether correctly I use `protobuf.load()`?

**Comment by dcodeIO** [comment]
Under the hood, this becomes a `fs.readFile` call under node and an XHR in the browser, using [this simple](https://github.com/dcodeIO/protobuf.js/tree/master/lib/fetch) (maybe too simple) fetch shim.

**Comment by grandkarabas** [comment]
Many thanks for the answer, now I understand.
