### ISSUE TITLE
Version 5.0.3 is currently tagged as "latest" on npm

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/protobuf.js#1043]
This means that users who just run `npm install protobufjs` will get 5.0.3 by default instead of 6.8.6, which is a better choice. If you're not familiar with the npm tagging system, the documentation is [here](https://docs.npmjs.com/cli/dist-tag). The command you want to run to fix this is `npm dist-tag add protobufjs@6.8.6 latest`

**Comment by murgatroid99** [comment]
Yes, 6.8.6 now displays with the "latest" tag on npmjs.org

**Comment by mko** [comment]
@dcodeIO It should be noted that as of right now, it's impossible to install (at least for myself or my coworkers) any version of `protobufjs` from NPM. Not sure when it broke. Have you gotten any other reports of it?

**Comment by ssbarbeee** [comment]
I can confirm this started happening on my EC2 just now.

**Comment by murgatroid99** [comment]
That is a different problem from the one I reported here. I would recommend opening a separate issue.
