### ISSUE TITLE
Protobuf 404 on npm install (package dependencies and npm i)

### ISSUE THREAD

**Issue by dannypaz** [dcodeIO/protobuf.js#1056]
`protobufjs` is being installed via dependencies from `grpc` however I am unable to install protobufjs standalone as well.

Time of issue: 4:03pm PST

```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^5.0.0
```

```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@6.8.6
```

EDIT for full stack

```
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose npm-session 7bed9828e33a7a1f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/protobufjs 210ms
8 silly fetchPackageMetaData error for protobufjs@6.8.6 404 Not Found: protobufjs@6.8.6
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 437ms
11 verbose stack Error: 404 Not Found: protobufjs@6.8.6
```

I'm currently 404ing with `npm i protobufjs@5.0.0` and `npm i protobufjs`. Im not sure if this is an issue w/ npm but wanted to give yall a headsup.

**Comment by rafcioka** [comment]
Same here. It was working like an hour ago, but now it is not.
https://registry.npmjs.org/protobufjs works but it may be some internal npm issue.

**Comment by Joe-mcgee** [comment]
Same here

**Comment by SippieCup** [comment]
Same here, although I'm stuck on the extremely outdated `protobufjs@^3.5.0`. Thanks pkgcloud

**Comment by jwahlin** [comment]
It's not just npm. I have the same issue with `yarn add protobufjs`.

**Comment by daywednes** [comment]
same here :) i'm looking forward to the fix.

**Comment by Negan1911** [comment]
Same here :/

**Comment by dcodeIO** [comment]
Very strange. There haven't been any updates to the package for 14 days, so my assumption for now is that this is some sort of npm issue.

**Comment by Negan1911** [comment]
@dcodeIO i guess that could be related with this? 
https://status.npmjs.org/
![image](https://user-images.githubusercontent.com/3399236/40691323-637d9446-6379-11e8-8d6b-984f8c8e650b.png)

Do you mind to republish your package?

**Comment by dcodeIO** [comment]
Yeah, except that the package hasn't been updated between "Monday night and Tuesday morning".

**Comment by issackpgit** [comment]
Same here

**Comment by fabiofgpavan** [comment]
Same here

`npm ERR! 404 Not Found: protobufjs@^5.0.3`

**Comment by bradysheridan** [comment]
+1

**Comment by nickpestov** [comment]
Doing `npm cache clean --force` fixed the issue for me.

**Comment by bruno-visor** [comment]
I am facing the same issue, there is a problem with npm, I temporary solved the problem by downgrading the NPM with this code
  "engines": {
    "npm": "4.6.1"
  }, - package.json

**Comment by nickpestov** [comment]
Also, `yarn` works fine

**Comment by khalilit** [comment]
Same issue for me

**Comment by xuanyue202** [comment]
I don't think yarn works. Maybe @nickpestov uses local cache?
![image](https://user-images.githubusercontent.com/8772715/40694112-94359af6-63ed-11e8-8f3b-caedc8007cbb.png)

**Comment by khalilit** [comment]
Downgrade npm to version 4 via : npm install -g npm@4 solved the problem and now npm i protobufjs@latest works fine

**Comment by nickpestov** [comment]
@jporsay & @xuanyue202, I was getting the 404 Not Found for protobufjs locally and `npm cache clean --force` seemed to fix the issue. But I am still experiencing the issue remotely (Google Cloud Builder).

**Comment by artz** [comment]
This issue is currently affecting me, using both `npm` and `yarn` fwiw. 

```
1724 verbose stack Error: 404 Not Found: protobufjs@^6.8.0
1724 verbose stack     at fetch.then.res (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
1724 verbose stack     at tryCatcher (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1724 verbose stack     at Promise._settlePromiseFromHandler (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
1724 verbose stack     at Promise._settlePromise (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
1724 verbose stack     at Promise._settlePromise0 (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1724 verbose stack     at Promise._settlePromises (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1724 verbose stack     at Async._drainQueue (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
1724 verbose stack     at Async._drainQueues (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
1724 verbose stack     at Immediate.Async.drainQueues (/Users/artz/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
1724 verbose stack     at runCallback (timers.js:789:20)
1724 verbose stack     at tryOnImmediate (timers.js:751:5)
1724 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
1725 verbose cwd /Users/artz/Sites/lightbox
1726 verbose Darwin 17.5.0
1727 verbose argv "/Users/artz/.nvm/versions/node/v8.9.1/bin/node" "/Users/artz/.nvm/versions/node/v8.9.1/bin/npm" "install"
1728 verbose node v8.9.1
1729 verbose npm  v5.6.0
1730 error code E404
1731 error 404 Not Found: protobufjs@^6.8.0
1732 verbose exit [ 1, true ]
```

**Comment by raman2072** [comment]
This is NOT fixed. I tried 5 minutes ago.

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^5.0.3

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-05-30T01_21_58_490Z-debug.log
"
Command failed

**Comment by artz** [comment]
Also fwiw, to reproduce:
```
npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
 artz@axcelibur  ~/Sites/lightbox   develop ●✚ >M<  npm install @google-cloud/language
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^6.8.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/artz/.npm/_logs/2018-05-30T01_53_33_243Z-debug.log
```

**Comment by xuanyue202** [comment]
@nickpestov  I tried your solution but no luck :(
```
➜  /tmp npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
➜  /tmp npm install protobufjs@^5.0.0
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^5.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yaoliang/.npm/_logs/2018-05-30T01_54_00_021Z-debug.log
```

**Comment by rahulk-kikani** [comment]
Same here!
```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@latest
```

**Comment by raman2072** [comment]
Why is this NOT yet reported in https://status.npmjs.org/? According to the site apparently there are no issues?

**Comment by Koshukey** [comment]
same here.

```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@^5.0.0
```

when i try npm  install firebase, i faced this issue

**Comment by sigoden** [comment]
It is really an npm issue, change the registry temporarily, `npm i  protobufjs@^5.0.3  --registry=https://registry.npm.taobao.org`

**Comment by markgoho** [comment]
@raman2072 I see:
![image](https://user-images.githubusercontent.com/9759954/40696068-1abde76a-6392-11e8-88d2-4a092301446a.png)

**Comment by chfabbro** [comment]
Also installing Firebase functions (for the first time) and hitting this issue. @sigoden's tip did the trick.

> change the registry temporarily, `npm i protobufjs --registry=https://registry.npm.taobao.org`

**Comment by zuohuadong** [comment]
```
npm --registry https://registry.npm.taobao.org install protobufjs@5
```

**Comment by defaultbr** [comment]
for me the trick about registry did not worked, what worked was:


nvm use 4
npm install the package i need
nvm use 6

**Comment by shaunpersad** [comment]
Is it wise to trust some random NPM registry?

**Comment by gDelgado14** [comment]
@jwahlin yarn uses the npm registry, so it's not a yarn problem.

**Comment by arnabmitra** [comment]
@markgoho that notice is from May23rd

**Comment by korziee** [comment]
@Koshukey @sigoden 
LEGENDS! 

```
npm install --registry=https://registry.npm.taobao.org
```

solved it.

**Comment by ravihugo** [comment]
Is this taobao safe?

**Comment by xuanyue202** [comment]
This taobao is a repo mirror run by Alibaba which aims to solve the network problem from China to npmjs. Personally I think it is ok, but it is no more than a temporary solution.

**Comment by KeanuTomatoMomotaro** [comment]
I just tried installing the module normally. The original registry seems to be running now.

NPM version 6.1.0
Node Version 8.10.0

**Comment by ravihugo** [comment]
Confirmed, it works without using the alternative registry.

**Comment by mikeInkerz** [comment]
Confirmed as well. But I'm curious, what happened?

And also, how not be dependent on this and how to prevent what happened to @Phineas 
> all my deployment pipelines failed earlier which caused my kubernetes pods to scale down making my service unavailable

**Comment by MikeBailleul** [comment]
Confirmed as well. But I'm curious, what happened?

And also, how not be dependent on this and how to prevent what happened to @Phineas 
> all my deployment pipelines failed earlier which caused my kubernetes pods to scale down making my service unavailable

**Comment by rendaw** [comment]
Still not working here:
```
$ yarn add protobufjs@6.7.3
...
error An unexpected error occurred: "https://registry.npmjs.org/protobufjs/-/protobufjs-6.7.3.tgz: Request failed \"404 Not Found\"".
```

`yarn add protobufjs` works though.  This is part of a complex build process in a dependency so changing the registry/version to work around won't be easy.

**Comment by gDelgado14** [comment]
Maybe we can close this issue and open an issue within NPM's repo?

https://github.com/npm/npm

**Comment by rendaw** [comment]
https://github.com/npm/npm/issues/20809

**Comment by trusktr** [comment]
They emailed back this morning:

> Thanks for reaching out and for the heads up. Our ops team believe they've identified the issue with the protobufjs package. We rolled out a fix last evening. We believe all versions of the package should once again be available.

**Comment by rendaw** [comment]
@trusktr is there any public discussion of this?  I just checked and still getting 404:
```
$ npm install protobufjs@6.7.3
...
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@6.7.3
```

**Comment by gDelgado14** [comment]
I got a twitter reply:

link: https://twitter.com/npm_support/status/1001877600690679811

<img width="602" alt="screen shot 2018-05-30 at 1 30 11 pm" src="https://user-images.githubusercontent.com/10621548/40737055-a29277b6-640d-11e8-9d12-5cc304260266.png">

**Comment by daywednes** [comment]
can i get a npm loves you tweet? lol

**Comment by dannypaz** [comment]
Closing this issue as this particular 404 case looks to be resolved. If anyone continues to problems, feel free to comment or open another issue.

**Comment by scream314** [comment]
I do not think it is resolved:
```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@https://registry.npmjs.org/protobufjs/-/protobufjs-4.1.3.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-31T15_29_30_145Z-debug.log
```
Strangely if I try to open https://registry.npmjs.org/protobufjs/-/protobufjs-4.1.3.tgz in a browser, it starts to downloat the tgz...

**Comment by cconcise** [comment]
When I open https://registry.npmjs.org/protobufjs/-/protobufjs-4.1.3.tgz it gives me an error page. I'm also unable to install @google-cloud/speech which uses protobufjs-6.8.6

**Comment by rdlowrey** [comment]
I've been npm installing all evening and this just started happening to me in the last ~20 minutes as well.

```
npm ERR! code E404
npm ERR! 404 Not Found: protobufjs@6.8.6
```

**Comment by jwahlin** [comment]
Just started happening to me (again) about 20 minutes ago.

**Comment by kylehotchkiss** [comment]
It's back! Tweet @npm_support about it if you are also experiencing https://twitter.com/npm_support/status/1001877600690679811

**Comment by aalexand** [comment]
Experiencing it too.

**Comment by rohitjmath** [comment]
me too

**Comment by kylehotchkiss** [comment]
https://twitter.com/npm_support/status/1002354019355037697 they've alerted ops team

**Comment by shaunpersad** [comment]
This really is a sad state of affairs. NPM has become a single point of failure for build processes everywhere. This package is downloaded about 115k times a week. There must be a better way to get high availability on packages, especially essential ones!

**Comment by tmauricio** [comment]
fix it!!!!

**Comment by briandeheus** [comment]
if you're running into this issue when you need to install both private and public packages:

```
npm install protobufjs@5 --registry https://registry.npm.taobao.org
npm install
```

The second time around npm will notice profobufjs is installed and won't attempt to re-install it...

**Comment by edahood** [comment]
So https://registry.npmjs.org/protobufjs/-/protobufjs-4.1.3.tgz  Still fails, but
http://registry.npmjs.org/protobufjs/-/protobufjs-4.1.3.tgz  Seems to be the right file

Unfortunately, this is a dependency of a dependency of a dependency, and i think one is using shrink wrap.
Really not sure what to do to fix this quickly

**Comment by scream314** [comment]
The 404 was gone after I switched from `npm 5.6.0` to `npm 6.x.x`. But this introduced a bunch of other issues.
But finally I was able to install all my dependencies... by installing and using `yarn` ;)
