### ISSUE TITLE
你好，关于生成代码，大小的问题，

### ISSUE THREAD

**Issue by 253056965** [dcodeIO/protobuf.js#1070]
protobuf.js version: 6.8

<please describe the expected and actual behavior>

您好，我用你写的工具对proto 生成了代码，但是我是原来做前端的，发现生成的文件都非常大，请问这个生成的时候能改小吗

**Comment by CcaoWei** [comment]
？？？？
------------------------------------------------------------------
发件人：郑州|boy <notifications@github.com>
发送时间：2018年6月12日(星期二) 15:51
收件人：dcodeIO/protobuf.js <protobuf.js@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[dcodeIO/protobuf.js] 你好，关于生成代码，大小的问题， (#1070)

protobuf.js version: 6.8
您好，我用你写的工具对proto 生成了代码，但是我是原来做前端的，发现生成的文件都非常大，请问这个生成的时候能改小吗

**Comment by dhlolo** [comment]
为啥毫无解释的就关掉了。。应该和[这个问题](https://github.com/protocolbuffers/protobuf/issues/2303)一样，应该很多人都遇到这个问题了~
