### ISSUE TITLE
defining a array of reflected type inside another reflected type

### ISSUE THREAD

**Issue by denismurphy** [dcodeIO/protobuf.js#1110]
protobuf.js version: v6.8.6

Just wondering if there example of using protobuf.js reflection for the following

` let typeB = new protobuf.Type("TypeB").add(new protobuf.Field("id", 1, "int32"));`

` let typeA = new protobuf.Type("TypeA").add(new protobuf.Field("typeB", 1, "TypeB"));`

how would i define a array of TypeB inside TypeA using reflection for example

`... .add(new protobuf.Field("typeB", 1, "Array<TypeB>"));`

Thanks.
Denis

**Comment by dcodeIO** [comment]
That should be

```js
new protobuf.Field("typeB", 1, "TypeB", "repeated")
```

**Comment by denismurphy** [comment]
Perfect! Thanks for quick reply.
