### ISSUE TITLE
ProtoBuf.Message.Field is not a constructor

### ISSUE THREAD

**Issue by jackatfp** [dcodeIO/protobuf.js#1128]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>

I use the lib to generate the js code and it looks like below
```
Everything looks fine until I used webpack to pack the code and then it stops working. I can tell the code is in the bundle js and the libarary. It doesn't complain ProtoBuf.Message.apply it means the protobufjs is imported but it doesn't recognise ProtoBuf.Message.Field. Does any have any idea?

```
<please provide a code snippet for reproduction>
```
var ProtoBuf  = require('protobufjs');

function GameConfig() {
    ProtoBuf.Message.apply(this, arguments);

    this.addField(new ProtoBuf.Message.Field('required', 'int64', 'id', 1));
}

GameConfig.prototype = Object.create(ProtoBuf.Message.prototype);
GameConfig.prototype.constructor = GameConfig;

module.exports = GameConfig;

```
<please paste the stack trace of the error if applicable>
VM1486:1 gameThirdScriptError
ProtoBuf.Message.Field is not a constructor
TypeError: ProtoBuf.Message.Field is not a constructor
    at new GameConfig (http://127.0.0.1:34772/game/js/app.bundle.js:13519:27)
    at PreloaderController.addModel (http://127.0.0.1:34772/game/js/app.bundle.js:9714:34)
    at Function.create (

**Comment by dcodeIO** [comment]
Did you mean: [protobuf.Field](https://github.com/dcodeIO/protobuf.js/blob/master/src/index-light.js#L86) ?

**Comment by jackatfp** [comment]
No worry. I uploaded to the latest version and the problem disappeared.
