### ISSUE TITLE
Envoy protos with protobuf.js

### ISSUE THREAD

**Issue by alexshv** [dcodeIO/protobuf.js#1185]
Hi. Im failing to run grpc server with envoy protobufs.
Here's protobufs repo:
[https://github.com/envoyproxy/data-plane-api/tree/master/envoy](url)

Here's my code:
```
'use strict';

const utils = require('./utils');
const path = require('path');
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const googleprotoFiles = require('google-proto-files');

const PROTO_PATH = '/envoy/api/v2/cds.proto';
const IMPORT_PATH = path.join(__dirname, '/data-plane-api');
const GOOGLE_PROTOS = path.join(__dirname, '/node_modules/google-proto-files');
const VALIDATE_PATH = path.join(__dirname, '/data-plane-api/validate');
const ENVOY_PATH = path.join(__dirname, '/data-plane-api/envoy');
const GOGO_PATH = path.join(__dirname, '/data-plane-api/google/protobuf');

const packageDefinition = protoLoader.loadSync(path.join(IMPORT_PATH, PROTO_PATH), {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
    includeDirs: [ENVOY_PATH, GOOGLE_PROTOS, IMPORT_PATH, VALIDATE_PATH, GOGO_PATH]
});

const CDSProto = grpc.loadPackageDefinition(packageDefinition);
```

The problem is that if I load discovery.proto alone - it works. When I try to load cds.proto it says that DiscoveryRequest is not found, still though discovery.proto is loaded in cds.proto.

/Users/aleksey.shevchenko/Projects/cds/data-plane/node_modules/protobufjs/src/namespace.js:382
        throw Error("no such type: " + path);

Error: no such type: DiscoveryRequest

**Comment by ricardobeat** [comment]
Since this most likely involves the `includeDirs` config and how the imports are defined, I'd encourage you to open this issue in the `@grpc/proto-loader` repo instead.

**Comment by tomsamwel** [comment]
I'm running into the same issue. Did you, and if so, how did you solve it @alexshv ?
