### ISSUE TITLE
Self-describing Messages support

### ISSUE THREAD

**Issue by zh99998** [dcodeIO/protobuf.js#144]
seems original C++ and Java protobuf provides Self-describing Messages support
https://developers.google.com/protocol-buffers/docs/techniques?hl=zh-CN#self-description

but here ProtoBuf.js i can't find anything about that...
do i must process it manually?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
