### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by englercj** [dcodeIO/protobuf.js#188]
Apologize for the long post, wanted to give as much detail as possible! I really see this as the only big problem with this library that is preventing me from being able to use it on my projects.

I've been looking around but haven't seen a good way to generate JS code based on the protobuf. The normal workflow for using protobuf as an IDL in other languages is to generate models based off the protobuf and commit/use the generated code at runtime.

Unfortunately the `proto2js` script only generates json documents and for non-trival protobuf systems actually causes a lot of duplication of imports and data to the point of not being useful. It also actually decreases the discoverability of what the built models would actually do.

Imagine a service described by protobuf IDL and a client that consumes it based on the IDL. A user of that client cannot look at the code and know what it is doing, everything is "magically" created so only extensive docs specific to the client can help. Or the user has to be intimently familiar with the IDLs of the service, neither of those are reasonable assumptions at large team scale.

It would be great if I could run some code generator on protobuf that looks like this:

file: _something.proto_

``` protobuf
package my.namespace;

message SomethingRequest {
    required int64 id = 1;
}
```

and it generated a javascript file like this:

file: _my/namespace/SomethingRequestMessage.js_

``` js
var ProtoBuf  = require('protobufjs');

function SomethingRequest() {
    ProtoBuf.Message.apply(this, arguments);

    this.addField(new ProtoBuf.Message.Field('required', 'int64', 'id', 1));
}

SomethingRequest.prototype = Object.create(ProtoBuf.Message.prototype);
SomethingRequest.prototype.constructor = SomethingRequest;

module.exports = SomethingRequest;
```

(gist with more complete example: https://gist.github.com/englercj/787423108d85a049f0a2)

The idea here is that the base `ProtoBuf.Message` object that it inherits from here is similar to the `clazz` [implementation for Message](https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/Builder/Message.js) that contains all the functionality necessary to encode/decode and use this protobuf definition, but the .proto is **not** required at runtime.

For example, you could use the above code like:

``` js
var SomethingRequest = require('./my/package/SomethingRequest');

var reqData = new SomethingRequest({ id: 10 });

console.log(reqData.encode());
```

There are a lot of benefits to this:
- not having to expose the .proto files to the client (say a browser)
- consistency with workflow of protobuf in other languages
- no need to dynamically build descriptors at runtime
- clearer code description of what your generated models look like (right now it is black-box)
- more natural usage of project code, protobuf is hidden away from end user

I've started writing a script similar to `proto2js` that does this, but since the actual Message and Service implementations are not exposed the only way for me to accomplish this is to maintain a parallel version of the Message/Service implementations in my own project. I'd love to see this as a core feature.

**Comment by dtracers** [comment]
How would you feel about a generator that generates actual js classes that optionally extend from the message class but instead have a majority of the code duplicated and pulled in

The main reason is that I want to use the js version of the proto objects as normal js objects containing methods.  and assign a bunch of proto values to them.

The other issue is that I am not using a js library so having all of the files being stored in a value called _root which is then overwritten every time I import the scripts

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
