### ISSUE TITLE
negative numbers in an int field cause exception

### ISSUE THREAD

**Issue by vrecan** [dcodeIO/ProtoBuf.js#211]
Uncaught Error: Illegal value for Message.Field .com.logrhythm.justonemorething.query.Search.ownerId: -100 (TypeError: undefined is not a function)

[This is the proto message.](http://pastebin.com/kDRZ3wcS)

if I put a positive number in the field the error goes away.

**Comment by dcodeIO** [comment]
Is this still an issue?

**Comment by vrecan** [comment]
I can't reproduce it any more.
