### ISSUE TITLE
Question/Feature request:  Equality check of messages

### ISSUE THREAD

**Issue by dtracers** [dcodeIO/protobuf.js#216]
Is there a way to have a message check if it is equal (in terms of contained data) to another message?

If not what would be the best way to check this?
right now I compile it to base64 and compare the base64 values.

due to the fact that I dynamically add new proto files the messages themselves may from different instances but the data they contain could be exactly the same.  So doing naive field-value checking could fail.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
