### ISSUE TITLE
Possible Bug in pbjs tool

### ISSUE THREAD

**Issue by dimitrirostavo** [dcodeIO/ProtoBuf.js#222]
I have a simple testProto.proto file

message UrlMessage            
{
    repeated string url= 1;
}

To create the runtime structure in JS I run the pbjs tool as follows 
node pbjs testProto.proto -source=proto -target=js

The output is printed as follows 
var _root = dcodeIO.ProtoBuf.newBuilder({})['import']({
    "package": null,
    "messages": [
        {
            "name": "UrlMessage",
            "fields": [
                {
                    "rule": "optional",
                    "type": "string",
                    "name": "url",
                    "id": 1
                }
            ]
        }
    ]
   }).build(); 
======================================================
The bug is that the "rule" field should be set to "repeated" and not optional IMO. 

Please let me know. 

Thanks,
H

**Comment by alusco** [comment]
This is happening to me as well, pbjs seems to not handle repeated fields (though they're handled fine in the normal protoFromFile api).

**Comment by alusco** [comment]
This line is busted
https://github.com/dcodeIO/ProtoBuf.js/blob/master/cli/pbjs/targets/json.js#L179

If you change that function so it does this instead:
 var fieldType = fld.repeated ? "repeated" : (fld.required ? "required" : "optional");
    return {
        "rule"    : fieldType,

The world works, I'll try to send a pull request but it will probably not be until monday

**Comment by alusco** [comment]
Pull request opened that fixes the problem

**Comment by schwiet** [comment]
could you publish this fix to npm, please.
