### ISSUE TITLE
What's the support of ProtoBuf.js in the browser?

### ISSUE THREAD

**Issue by tleunen** [dcodeIO/ProtoBuf.js#224]
What's the support of ProtoBuf.js in the browser? IE9 and above?
And what happen for an old browser?

Trying to know if we need to do something specific for old browsers or everything is fine

**Comment by dcodeIO** [comment]
ByteBufferAB requires a working ArrayBuffer and DataView implementation. For these, there are polyfills available for IE8, but it's not super performant.

**Comment by tleunen** [comment]
So the best thing is to check the browser, potentially display an error or something for IE8 and make a require(ProtoBuf.js) only if we know it's supported?
I guess it should work to require a module with browserify inside an if statement...
The app I'm working on only needs IE9 and above, but I'm wondering what will be the best way to handle old browsers to display an error in the case ProtoBuf would not be optimal/doesn't work.

**Comment by dcodeIO** [comment]
You could feature-test for ArrayBuffer and DataView, yes.

**Comment by tleunen** [comment]
Thanks :)

**Comment by tleunen** [comment]
Just FYI, ArrayBuffer is only in IE10 and above
