### ISSUE TITLE
Build a browser specific version instead of using require fs/path

### ISSUE THREAD

**Issue by tleunen** [dcodeIO/ProtoBuf.js#225]
Would it be possible to build a separate browser specific version instead of having this kind of code in the output?
```js
Util.IS_NODE = false;
try {
    // There is no reliable way to detect node.js as an environment, so our
    // best bet is to feature-detect what we actually need.
    Util.IS_NODE =
        typeof require === 'function' &&
        typeof require("fs").readFileSync === 'function' &&
        typeof require("path").resolve === 'function';
} catch (e) {}
```

I'm saying this because browserify will include the fs and path module in the output when we require ProtoBuf, but these modules are not needed for ProtoBuf to work.
You could dynamically inject a value for `Util.IS_NODE` during building/bundling.

What do you think?

**Comment by gegles** [comment]
I have the same need.... I am using webpack and it complains about the "fs" module.

**Comment by w3dot0** [comment]
It looks like the latest protobufjs version on npm does not have this fix yet. Is it possible to tag/deploy 4.0.1 to npm? As a workaround I added the module dependency as git URL inside my project's package.json (but that's dangerous since it points to master).

**Comment by watsoncj** [comment]
It looks like this can be solved by adding an instruction to ignore the fs require.

https://gist.github.com/defunctzombie/4339901#user-content-ignore-a-module
