### ISSUE TITLE
how I can save a byte type in file

### ISSUE THREAD

**Issue by marcosbergamo** [dcodeIO/ProtoBuf.js#227]
Hi Guys!

I'm trying save a file using a byte type instead my proto file. When I put the value on log, is like a message, not an buffer.

How I can get the value(in bytes) to save to an file using node.js?

**Comment by dcodeIO** [comment]
First you need to encode your message / convert it to a buffer:

```js
var myMessage = new MyMessage(...);
var buf = myMessage.toBuffer();
... save buf ...
```

**Comment by marcosbergamo** [comment]
I decode the message and recovert ?

```javascript
var frameBuff = proto.FrameBuffer.decode(data); // data is a buffer
```

instead frameBuff my options "frame" is a byte type. For I write a file, need a convert again to an Message?

**Comment by dcodeIO** [comment]
If you already have a proper buffer, you may of course save that directly.

**Comment by marcosbergamo** [comment]
My return of decode message is:

```javascript

{ screenBuffer: 
   { buffer: <Buffer 10 06 1a dc b6 49 0a d8 b6 49 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 02 d0 00 00 05 00 08 06 00 00 00 6e ce 65 3d 00 00 00 04 73 42 49 54 ...>,
     offset: 10,
     markedOffset: -1,
     limit: 1203042,
     littleEndian: true,
     noAssert: false },
  realSize: null,
  scaledSize: null,
  bufferArea: null,
  bufferAreaCoordinate: null,
  bytesPerPixel: null,
  red: null,
  green: null,
  blue: null,
  transparency: null }
```

I want to save the screenBuffer, but when I write the file using fs, the image is broken.

**Comment by dcodeIO** [comment]
When accessing a buffer inside of a protobuf message, it is a ByteBuffer instance. Try:

```js
var buf = myMessage.screenBuffer.buffer.toBuffer();
... save buf ...
```

**Comment by marcosbergamo** [comment]
not yet. :/


´´´javascript
/srv/nodejs/bitbucket/node-bdp/lib/bdp.js:59
        img = frameBuff.screenBuffer.buffer.toBuffer();
                                            ^
TypeError: Object ܶI
ضI�PNG

´´´

**Comment by dcodeIO** [comment]
Mhh, looks like it's already a proper buffer. In that case, I assume that the PNG data is actually corrupted somehow.

**Comment by marcosbergamo** [comment]
but, the size and properties received is not corrupted :/ the original  message is givin from C module.

**Comment by dcodeIO** [comment]
Now I see: screenBuffer is a ByteBuffer instance, hence try:

```js
var buf = myMessage.screenBuffer.toBuffer();
```

`screenBuffer.buffer` contains the backing buffer, which is not sliced identically to the PNG data portion.

**Comment by marcosbergamo** [comment]
Is not the same at above?

**Comment by marcosbergamo** [comment]
The image yet broken.
This is a piece of my code.
```javascript
fs = require('fs');

        img = frameBuff.screenBuffer.toBuffer();

        fs.writeFile('ss.png', img, function(err){
          if(err)
            throw err;

            console.log('image writed');
            return;
        });
```

**Comment by marcosbergamo** [comment]
the problem isn't in protobufjs sorry. My code when I read the socket, a chunk value isn't received correctly.
