### ISSUE TITLE
Feature suggeston: a shortcut function to encode an object

### ISSUE THREAD

**Issue by seishun** [dcodeIO/ProtoBuf.js#228]
I think it's a common use case to turn a plain object (not a Message instance), e.g. an object literal, into a Buffer (or perhaps some other representation of encoded data). However, currently it requires initializing a Message instance only to call `toBuffer` (or whatever else) on it and throw it away immediately:

```js
var buf = new MyProtoClass({a: 1234}).toBuffer();
```

Not very elegant, and also not symmetrical to the opposite operation:

```js
// buf is a Buffer from somewhere
var obj = MyProtoClass.decode(buf);
```

The suggestion is to add a similar "static" function to do the encoding operation on an arbitrary object:

```js
var buf = MyProtoClass.toBuffer({a: 1234});
```

What do you think?

**Comment by dcodeIO** [comment]
Currently, it's possible to construct a message instance from a data object:

```js
var myMessage = new MyMessage({ ... });
var buf = myMessage.toBuffer();
```

Would that do the job for you ?

**Comment by seishun** [comment]
This is just a rephrasing of my first snippet. It still involves the creation of a throwaway object.

**Comment by Alex7Kom** [comment]
@dcodeIO I think he meant that `MyProtoClass.toBuffer(obj)` should initialize a `MyMessage` internally automatically using object `obj`.

**Comment by dcodeIO** [comment]
Thought so, just wanted to hint towards `new MyProtoClass(obj).toBuffer()` as its already available today
