### ISSUE TITLE
reflection

### ISSUE THREAD

**Issue by rangercyh** [dcodeIO/ProtoBuf.js#230]
I have create a tcp connection with remote client,and I designed the proto message,the client then pass a stream of bytes to me,I receive the bytes,and how to figure out what message it is.
I know that I can pass the message name in front of the bytes,but I want to do it in a elegant way,I have read google protobuf fucking manual, It says there is something called reflection can do this,I check out the C++ implement,I know that I can define a container message, and extend the message with my real wanted message, and then create container message builder, use this builder to setExtension for my real wanted message,and pass it to server, in server side, I also can create container message builder, and use function like hasExtension() to judge what real message type the bytes is, and use getExtension() to get the wanted message from the bytes. I want to know how I do this in protobuf.js.
thanks a lot if someone can help me!

**Comment by dcodeIO** [comment]
Maybe use something like this: https://github.com/dcodeIO/ProtoBuf.js/wiki/Changes-in-ProtoBuf.js-3.7
