### ISSUE TITLE
How to build and parse message with extension?

### ISSUE THREAD

**Issue by richzw** [dcodeIO/ProtoBuf.js#231]
Now I have defined several messages as following 

```
message MsgHead
{
	extensions 80 to max;
	
	enum Type
	{
		REQ = 1;
		RESP = 2;
	}
	required string version = 1;
	required Type type = 2;
}

message Req
{
	extend MsgHead
	{
		required Req msg = 81; // unique message extend number
	}
	
	optional string id = 1;
	optional string ip_address = 2;
}

message Resp
{
	extend MsgHead
	{
		required Resp msg = 82;
	}
	
	optional string id = 1;
	optional string time = 2;
}
```
And I try to build the message `Req` and `Resp`

```
var builder = ProtoBuf.loadProtoFile('msg.proto');
var Header = builder.build('MsgHead');
var req = builder.build('Req');
var resp = builder.build('Resp');

		var req = new req({
			"id": "50",
			"ip_address": "172.16.63.50",
		});
		var msg_head = new Header();
		msg_head.set('version', '1.0');
		msg_head.set('type', 1);
		msg_head.set('.Req.msg', req);

```

It seems the above codes is not correct, and I try to find some example codes but failed. 
Could you please give me some example codes for that? Also with the message parsing.
Thanks in advance.

**Comment by dcodeIO** [comment]
See: https://github.com/dcodeIO/ProtoBuf.js/wiki/Changes-in-ProtoBuf.js-3.5

**Comment by richzw** [comment]
I want to get the `Req` message through 

```javascript
var req = msg_head.Extensions[req.msg];
```
Some API like [this](http://www.indelible.org/ink/protobuf-polymorphism/).

Is there any API like that?

**Comment by richzw** [comment]
With the above codes, I get the following error as following

`{ version: '1.0',
  type: 1,
  '.Req.msg': { id: '90', ip_address: '172.16.63.90' },
  '.Resp.msg': null }
{ [Error: Missing at least one required field for Message .MsgHead: .MsgHead..Re
sp.msg]`

**Comment by jfromaniello** [comment]
I've been able to construct with the same example on that link: [Protocol Buffer Polymorphism](http://www.indelible.org/ink/protobuf-polymorphism/):

```javascript
var animal  = new Animal({ type: Animal.Type.cat });
var cat = new Cat({ declawed: true });

animal.set('.Animal.cat', cat);

console.log(animal);
/*
{ type: 1,
  '.Animal.cat': { declawed: 1 },
  '.Animal.dog': null }
*/

var buff = resp.encodeDelimited().toBuffer();
```

There is an error in the proto of the mentioned link.. Both extensions are required and I think they should be optional.
