### ISSUE TITLE
Dynamic Message support?

### ISSUE THREAD

**Issue by richzw** [dcodeIO/ProtoBuf.js#232]
Does the [dynamic message](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.dynamic_message) supported in ProtoBuf?

If not, is there any better solution to can emulate message types which are not known at compile-time?

For example, there are several messages type defined as below

```
message msg1
{
    require string version = 1;
    require int type = 2;
    optional string data = 3;
    //...
}

message msg2
{
     require string version = 1;
     require int type = 2;
     optional string time = 3;
     //...
}
```

How can I distinguish those two different message in recipient application?

**Comment by dcodeIO** [comment]
That's not supported yet. A clean approach would be to use a container message, like in: https://github.com/dcodeIO/ProtoBuf.js/blob/master/examples/protoify/json.proto

**Comment by richzw** [comment]
Thank you very much
