### ISSUE TITLE
XMLHttpRequest warning in Chrome Console

### ISSUE THREAD

**Issue by hellofunk** [dcodeIO/ProtoBuf.js#233]
I'm getting this from the ProtoBuf.min.js file:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```
Is this something I should worry about?

**Comment by dcodeIO** [comment]
Ideally, you should convert your .proto files to a common JSON file using the [pbjs CLI utility](https://github.com/dcodeIO/ProtoBuf.js/wiki/pbjs) and then use `ProtoBuf.loadJsonFile` by providing a callback to make it asychronous.

**Comment by sjames1958gm** [comment]
I cloned the most recent version and running pbjs results in Cannot find module 'bytebuffer'. my nodejs is 0.10.25 -

**Comment by englercj** [comment]
You can just do `npm i -g protobuf.js`, and then pbjs will be on your path.

**Comment by sjames1958gm** [comment]
Thanks

**Comment by sjames1958gm** [comment]
When I sudo npm install -f protobuf.js I don't get pbjs
nodejs -v
v0.10.25
npm -v
1.3.10
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

protobuf.js/
protobuf.js/README.md
protobuf.js/node_modules
protobuf.js/node_modules/long
. . .
protobuf.js/test
protobuf.js/test/basic.js
protobuf.js/test/schema.json
protobuf.js/test/repeated.js
protobuf.js/test/conversion.js
protobuf.js/test/embedded.js
protobuf.js/package.json
protobuf.js/lib
protobuf.js/lib/varint.js
protobuf.js/.npmignore
protobuf.js/.jshintignore
protobuf.js/.jshintrc
protobuf.js/index.js

**Comment by dcodeIO** [comment]
The package is named "protobufjs" (without dot) on npm.

**Comment by sjames1958gm** [comment]
Duh, sorry. Since protobuf.js loaded some stuff I didn't look further.

**Comment by englercj** [comment]
you also need `-g` not `-f`
