### ISSUE TITLE
ProtoBuf.loadProtoFile with http URL on node.js

### ISSUE THREAD

**Issue by jkarjala** [dcodeIO/ProtoBuf.js#234]
I am trying to build a JavaScript module which uses Protocol buffers, and should work on both browsers and node.js.

ProtoBuf.loadProtoFile("http://some.server/some.proto", function(....)) works fine in browsers.

However, it seems that under node.js all I get is  [Error: Failed to fetch file]. 
With the URL replaced with a local file, it works fine.
Is this a bug or by design?

I guess i can work around it by loading the proto to memory first, and then using loadProto?

**Comment by dcodeIO** [comment]
There is no HTTP logic implemented on the node.js side, yeah. In the browser it just doesn't matter.

Closing this for now. Feel free to reopen it again if there are still some issues.
