### ISSUE TITLE
how to load proto which import multiple proto?

### ISSUE THREAD

**Issue by ucchen** [dcodeIO/ProtoBuf.js#235]
here is my proto files
pb_12.proto which import pb_10.proto and pb_11.proto, those files are all in the same path, i have no idea to load pb_12.proto. actually, i can't use ProtoBuf.loadProtoFile to load .proto, beacause my javascript runtime does not support XmlHttpRequest. So i only can use ProtoBuf.loadProto to load .proto which not import proto files or only import one proto.

**Comment by jozzas** [comment]
I'm currently using a setup like this successfully. My usage would have two lines at the top of `pb_12.proto`:

    import "pb_10.proto";
    import "pb_11.proto";

And my code imports `pb_12.proto` directly:

    ProtoBuf.loadProtoFile(path.join(__dirname, "somesubdirectoty", "pb_12.proto"))

Given that the above works fine for me, what are you having trouble with?

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen it again if there are still some issues.
