### ISSUE TITLE
Text format support

### ISSUE THREAD

**Issue by nodirt** [dcodeIO/protobuf.js#236]
Does ProtoBuf.js support text format? Any plans to support it?

**Comment by develar** [comment]
Any news on this issue? Or https://github.com/brotchie/protobuf-textformat is the solution?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by demohi** [comment]
+1 to support pbtxt file

**Comment by demohi** [comment]
@dcodeIO

**Comment by dcodeIO** [comment]
To me it appears that adding text format support to the core library would increase library size while most use cases won't actually use it. Maybe as an [extension](https://github.com/dcodeIO/protobuf.js/tree/master/ext)?

**Comment by demohi** [comment]
@dcodeIO  yes, this is not a core feature
