### ISSUE TITLE
distribute from CDN

### ISSUE THREAD

**Issue by belm0** [dcodeIO/ProtoBuf.js#239]
Would you make ProtoBuf.js and dependencies available from a CDN (e.g. cdnjs.com)?

While raw files exist in dist/, the mime type is not suitable, and github doesn't want files served from raw.github.org.

Thanks for considering.

**Comment by englercj** [comment]
https://rawgit.com/

**Comment by dcodeIO** [comment]
Added this to the project homepage, thanks!
