### ISSUE TITLE
Long.js is really a production dependency...

### ISSUE THREAD

**Issue by belm0** [dcodeIO/ProtoBuf.js#240]
I noticed that the enum fields are encoded as longs.  Since use of enums is fairly common it may be a little misleading to only advertise ByteBuffer as a dependency.

**Comment by dcodeIO** [comment]
Where exactly did you make that finding? Long.js is meant to be optional, so this would be a bug.

**Comment by belm0** [comment]
Indeed I can't reproduce-- whatever I hit was unrelated to enums.  Sorry for the noise.
