### ISSUE TITLE
proto2js with large number of .proto files

### ISSUE THREAD

**Issue by schwiet** [dcodeIO/ProtoBuf.js#241]
I'm dealing with a project that produced, for the most part, a .proto file per message, of which there are many. What is the recommended way to use proto2js in this scenario?

I supposed I could run proto2js per .proto file to produce each corresponding .js file, but I see that each resulting .js file contains the definition of the message contained in that .proto, plus all of the dependent (imported) messages in an `imports` array (using `-commonjs`). Seems like this would  result in a lot of redundant code? I suspect I'm doing something wrong or there is a better way to handle this scenario.

Thanks.

**Comment by dcodeIO** [comment]
You could create a new .proto file that imports all the files of importance, and run proto2js on the newly created one to build a namespace of everything.

**Comment by schwiet** [comment]
ok, that's the direction I was leaning. Thanks for the prompt response and for maintaining this very useful project!
