### ISSUE TITLE
Binary data is not read correctly in Protobuf.js

### ISSUE THREAD

**Issue by danesh-d** [dcodeIO/ProtoBuf.js#244]
Hello,

I am using Protobuf.js 4.0.0-pre and have used the file ByteBufferAB.js which is shipped with the package in examples..../dist directory. In my code, I have a server which is written in C++ and two versions of clients in Java and Javascript, where the messaging is totally done by Protobuf. The server and the Java client can successfully communicate without any problem. As I am using Protobuf.js in my Javascript client code, the binary data which is defined as "bytes" is Protobuf cannot be decoded in Javascript client using Protobuf.js. I have read in other threads that binary data should be decoded as UTF8 string, but when I call readUTF8Stirng, then I get the error:

Uncaught RangeError: Illegal starting byte: 146

On the other hand, when I call "readByte(0)" to check whether the first byte is transferred correctly or not, no matter what I have at the server side (I have tested with different data) but the data is always constant and it is 8. Would you please point me to a solution to be able to correctly read the data?

Thanks in advance.

D.

**Comment by danesh-d** [comment]
One more thing! When I try to convert the data into string using utf8 encoder I still get an error and it is:

Uncaught RangeError: Illegal range: Truncated data, 40 != 2002

**Comment by Capriolo88** [comment]
I have the same problem, I think :) .
I use Protobuf to parse the binary data of Google Safe Browsing API v3 as shown in this [link](https://developers.google.com/safe-browsing/developers_guide_v3#HTTPResponseForData)

message.proto
```proto
// Chunk data encoding format for the shavar-proto list format.
message ChunkData {
  required int32 chunk_number = 1;

  // The chunk type is either an add or sub chunk.
  enum ChunkType {
    ADD = 0;
    SUB = 1;
  }
  optional ChunkType chunk_type = 2 [default = ADD];

  // Prefix type which currently is either 4B or 32B.  The default is set
  // to the prefix length, so it doesn't have to be set at all for most
  // chunks.
  enum PrefixType {
    PREFIX_4B = 0;
    FULL_32B = 1;
  }
  optional PrefixType prefix_type = 3 [default = PREFIX_4B];
  // Stores all SHA256 add or sub prefixes or full-length hashes. The number
  // of hashes can be inferred from the length of the hashes string and the
  // prefix type above.
  optional bytes hashes = 4;

  // Sub chunks also encode one add chunk number for every hash stored above.
  repeated int32 add_numbers = 5 [packed = true];
}
```
when protobuf parse the chunk data as the message.proto specify (hashes data is bytes) I obtain this result: 
```json
{"chunk_number":167672,
"chunk_type":0,
"prefix_type":1,
"hashes":{"buffer":{},"view":{},"offset":8,"markedOffset":-1,"limit":40,"littleEndian":true,"noAssert":false},
"add_numbers":[]}
```
but according to the documentation, I expect chunks like:

example
```javascript
ChunkData <
  chunk_number: 4
  // chunk_type not set, default value of ADD
  // prefix_type not set, default value of PREFIX_4B
  hashes: 0x1122334455667788  // 2 4-byte hash prefixes
>
```
Why ProtoBuf parse bytes data like ***{"buffer":{},"view":{},"offset":8,"markedOffset":-1,"limit":40,"littleEndian":true,"noAssert":false}***?
How can I get hashes data like the example?

**Comment by danesh-d** [comment]
I manages to solve the problem! The problem was that ByteBuffer.js adds a header to the data which starts from the first byte and ends at the "offset - 1" value. So the actual data starts from "offset" to "offset + remaining()".

Gabriele: in your case the field "hashes" says that the actual data starts from "offset" which is equal to "8" here. You can simply iterate from 8 to 8 + hashes.remaining() and read each value like hashes.readByte(i), something like:

for (in = hashes.offset; i < hashes.offset + hashes.remaining(); ++i)
  data[i - hashes.offset] = hashes.readByte(i);

Then you will get the actual data.

Hope this helps!

**Comment by dcodeIO** [comment]
Right, ByteBuffer's actually are slices on a message's data to reduce copying overhead. Bytes of interests are those between ByteBuffer#offset and ByteBuffer#limit. Calling ByteBuffer#toBuffer() for example returns a copied Buffer instance with the data of interest.
