### ISSUE TITLE
How to read comments?

### ISSUE THREAD

**Issue by financedemo** [dcodeIO/ProtoBuf.js#245]
Is it possible to extract comments in the json result?

**Comment by dcodeIO** [comment]
The parser strips all comments upon parsing, so there is no more comment information available afterwards.

**Comment by adematte** [comment]
bumping this old issue. @dcodeIO any reason why we can't keep comments when generating a json bundle from multiple protofiles? This would be very useful to generate api documentation.

**Comment by crdev** [comment]
:+1:
