### ISSUE TITLE
Maps support

### ISSUE THREAD

**Issue by amiorin** [dcodeIO/ProtoBuf.js#247]
Is https://developers.google.com/protocol-buffers/docs/proto#maps in the road map?

**Comment by cfallin** [comment]
I'm not the ProtoBuf.js author, but I have a patch for maps support and a few other proto3 features that's undergoing internal code-review at the moment. I'll be doing a PR once I get the OK.

**Comment by amiorin** [comment]
Nice

**Comment by sunwenteng** [comment]
would you please offer the link the moment you finish the patch?

**Comment by cfallin** [comment]
Just got approval to submit the patch: PR #254

**Comment by amiorin** [comment]
thx!
