### ISSUE TITLE
protobuf.js and FileDescriptorSet

### ISSUE THREAD

**Issue by runn1ng** [dcodeIO/protobuf.js#250]
Hello, I have a question about protobuf.js, I am not sure if what I want to do is even possible.

In my protobuf.js file, I recieve data defined in following .proto file:

```
message Info {
       required google.protobuf.FileDescriptorSet protocol = 1;
}
```

In the field "protocol", I have described protobuf messages, as protobuf files. I want to "dynamically" load this protocol (which is actually a few serialized proto files) and make a `Builder` out of it.

Is this somehow possible?

I can build and parse the Info message correctly, and I see the "files", but I cannot find what to do with it.

One way would be to somehow convert it "back" into ".proto" file and load it again, but I am not sure how to do it either, and it doesn't seem very nice anyway.

**Comment by runn1ng** [comment]
OK, I got it working, but just barely

I realized I can load the definition from JSON. So I go through the parsed FileDescriptorSet, convert it to JSON (I tried to get as close to pb2js output as possible), and then convert *that* to protobuf builder.

It feels very dirty and hacky, and kind of weird (because I am converting it from protobuf's own format to JSON so I can convert it back to protobuf), but it works.

**Comment by murgatroid99** [comment]
I would also find it useful to have this be easy. This would also be useful for loading the output of `protoc --descriptor_set_out=FILE`

**Comment by dcodeIO** [comment]
With [pbjs](https://github.com/dcodeIO/ProtoBuf.js/wiki/pbjs) there is the command line option "-legacy" that will include the descriptor with the generated output. Doesn't this do the trick for you?

**Comment by murgatroid99** [comment]
This issue isn't about *generating* anything. The problem here is *loading* a binary serialized descriptor and getting a `Builder`.

**Comment by dcodeIO** [comment]
I see. Well, currently there is no straight way to load a binary serialized descriptor to a builder. Making this possible would either require some sort of conversion from the decoded descriptor (loading it using descriptor.proto first, then converting the messages to the internal reflection structure) or reworking the internal reflection structure entirely.

**Comment by runn1ng** [comment]
If someone was interested. My hacked solution (very specific to my case) is here

https://github.com/trezor/trezor-chrome-extension/blob/master/src/protobuf/to_json.js

basically I am taking FileDescriptorSet, then I am going through it, making it similar to the internal reflection structure, and then, later, loading it to protobuf.js [here](https://github.com/trezor/trezor-chrome-extension/blob/master/src/protobuf/parse_protocol.js#L55).

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by runn1ng** [comment]
It seems like there is filedescriptorset already in google/protobuf!

Great, is there any example how to use them?

**Comment by runn1ng** [comment]
oh ok, I can parse them OK, but I still cannot make a Message out of that. :/

**Comment by dcodeIO** [comment]
protobuf.js does not use descriptor.proto internally. Instead, there is a more JavaScript-y reflection mechanism in place that you can use to create messages.

If you are using protobuf.js 6, you can read more about it in its README and the API documentation linked there. There are also some basic examples.
