### ISSUE TITLE
pbjs generates illegal proto syntax

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/ProtoBuf.js#255]
If I have a proto file `test.proto` that contains the line `package test` and I run `pbjs test.proto -target=proto`, the output starts with `package "test"`. This syntax is illegal, and causes the ProtoBuf.js parser to crash.

**Comment by sunwenteng** [comment]
why do you parse a .proto file to a .proto file?

**Comment by murgatroid99** [comment]
One thing pbjs does is move all included files into a single `.proto` file, which can be useful for distribution.

In any case, pbjs has a proto output format, and if it outputs invalid `.proto` syntax, that's a bug.
