### ISSUE TITLE
String encoding issue

### ISSUE THREAD

**Issue by saste** [dcodeIO/ProtoBuf.js#259]
Current ProtoBuf.js code is apparently not encoding strings correctly. Encoded strings are padded with zero, resulting in error when decoding the message containing them with a libprotobuf-c program.

Example code is provided below:
test.proto ------------------------------8<---------------

    message TestString {
            required string s = 1;
    }
test.proto ------------------------------8<---------------

protobuf-test.js ----------------------8<-----------------

    var testBuilder = ProtoBuf.protoFromFile("test.proto");
    var test = testBuilder.build();
    
    var msgObj = {s:"xxxx"};
    
    var msg;
    var encodedMsg;
    try {
        msg = new test.TestString(msgObj);
        encodedMsg = msg.encode();
    } catch (e) {
        console.log("Error occurred encoding message: " + e);
    }
    
    // show encoded message
    var b = new Uint8Array(encodedMsg.buffer);
    console.log("encoded msg (size: " + encodedMsg.buffer.byteLength + "): " + printPacket(b));
   
    // decode message
    var decodedMsg = test.TestString.decode(encodedMsg);
    console.log("Decoded message: " + JSON.stringify(decodedMsg));
protobuf-test.js ----------------------8<-----------------

I got this encoded buffer:

    encoded msg (size: 16): 0a047878787800000000000000000000

Now if I use a custom protobuf-test.c program:
protobuf-test.c ---------------------------8<----------------

    #include <stdio.h>
    #include <stdlib.h>
    #include "test.pb-c.h"
    
    static void print_packet(uint8_t *data, size_t size)
    {
        int i, j;
        const int linesize = 80;
        for (i = 0, j = 0; i < size; i++) {
            printf("%02x", data[i]);
            j++;
            if (j == linesize) {
                j = 0;
                printf("\n");
            }
        }
        printf("\n");
    }

    int main (int argc, const char * argv[])
        TestString ts = TEST_STRING__INIT;
        void *buf;
        size_t buf_size;
    
        /* fill the structure */
        ts.s = "xxxx";
        buf_size = test_string__get_packed_size(&ts);
        buf = malloc(buf_size);
        if (!buf) {
            fprintf(stderr, "No memory available\n");
            return 1;
        }
        test_string__pack(&ts, buf);
    
        fprintf(stderr,"Writing %zd serialized bytes\n", buf_size); // See the length of message
        print_packet(buf, buf_size);
        /* fwrite(buf, len, 1, stdout); // Write to stdout to allow direct command line piping */
    
        free(buf); // Free the allocated serialized buffer
    
        return 0;
    }
protobuf-test.c ---------------------------8<----------------

I get this output:

    Writing 6 serialized bytes
    0a0478787878

Note that the protobuf.js buffer contains padding data. In particular I notice that the protobuf.js string is always padded with zeros so that the size is always a multiple of 16.

Not sure this is a protobuf.js issue, as opposed to an API misuse.

**Comment by dcodeIO** [comment]
ProtoBuf.js holds byte values as [ByteBuffer](https://github.com/dcodeIO/ByteBuffer.js) objects, which are capable of automatic resizing and enabled zero copy operations where possible. These use backing buffers that may be larger than the actual data.

To get a properly sliced buffer object, use:

```js
encodedMsg = msg.encode().toBuffer();
```

**Comment by saste** [comment]
Thanks for the explanation, I'll close the issue as it looks like a misunderstanding on my side.

**Comment by maelp** [comment]
Hmmmm it seems the `toBuffer` no longer exists and we need to use `.finish` no? but then we have wrongly-sized buffer (at least in the browser?)
