### ISSUE TITLE
No decodeJSON function / method

### ISSUE THREAD

**Issue by Phoenix1708** [dcodeIO/ProtoBuf.js#261]
When I build the example Car schema like this:

var builder = ProtoBuf.loadJsonFile("complex.json"),
    Game = builder.build("Game"),
    Car = Game.Cars.Car;

the "Message" object returned was:

{ [Function]
  decode: [Function],
  decodeDelimited: [Function],
  decode64: [Function],
  decodeHex: [Function],
  Speed: { FAST: 1, SUPERFAST: 2 },
  Vendor: 
   { [Function]
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function],
     Address: 
      { [Function]
        decode: [Function],
        decodeDelimited: [Function],
        decode64: [Function],
        decodeHex: [Function] } },
  Holder: 
   { [Function]
     decode: [Function],
     decodeDelimited: [Function],
     decode64: [Function],
     decodeHex: [Function] } }

There's no function called "decodeJSON" as what is listed on the doc [ https://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/ProtoBuf.js/master/docs/ProtoBuf.Builder.Message.html ]

I do apologies if I miss understand something.

I installed via npm install protobufjs

UPDATE: there certainly some issue with code in NPM. probably out of date

**Comment by dcodeIO** [comment]
Should have made it to npm meanwhile.
