### ISSUE TITLE
Allow calling service methods with Buffers/ByteBuffers

### ISSUE THREAD

**Issue by seishun** [dcodeIO/ProtoBuf.js#266]
Currently, calling a generated service method with anything other than an instance of the request type is an error. I propose that it automatically convert Buffers and ByteBuffers into request type instances by decoding them.

Here's my use case.

Valve's Steam sends notifications to the client by using a convoluted scheme. The header of the message contains the service method name, and the body is an encoded message of the request type of the service method. Example:

```protobuf
service ParentalClient {
	rpc NotifySettingsChange (.CParental_ParentalSettingsChange_Notification) returns (.NoResponse) {
		option (method_description) = "Notification from server to client of a change in parental settings";
	}
}
```

If Steam wants to notify the client about a change in parental settings, they send a message whose header contains the string "ParentalClient.NotifySettingsChange", and the body is an encoded message of type `CParental_ParentalSettingsChange_Notification`.

Currently, to handle such a notification, I would have to use reflection, which seems complicated and I'm not exactly sure how to do it at the moment. If service methods could accept Buffer/ByteBuffers, I could instead call the specified method with a trivial RPC implementation that just passes the method name and the decoded message object to the user.

**Comment by dcodeIO** [comment]
I haven't tested this properly, yet, so please let me know if it does the trick for you.

**Comment by seishun** [comment]
It's working just fine, thanks!
