### ISSUE TITLE
Not able to decode the message in ProtBuf.js

### ISSUE THREAD

**Issue by bhatanku1** [dcodeIO/protobuf.js#268]
Hello All,

I am trying to send a message over MQTT making use of the google protocol buffer in javascript (ProtoBuf.js)

I was able to encode the message using the following code:

``` js
var ProtoBuf = dcodeIO.ProtoBuf;
            var builder = ProtoBuf.loadProtoFile("./complex.proto"),
                Game = builder.build("Game"),
                Car = Game.Cars.Car;
            var car = new Car({
                "model" : "Rusty",
                "vendor" : {
                    "name" : "Iron Inc.",
                    "address" : {
                        "country" : "USa"
                    }
                },
                "speed" : "FAST"
            });
            var buffer = car.encode();
            console.log(buffer);
            var messagegpb = buffer.toBuffer();
console.log(messagegpb ); //This prints "ArrayBuffer { byteLength: 29 }"
```

Now for decoding when I tried the following, it just doesn't do anything. I see no logs in the browser as well.

``` js
var dec = builder.build("Game"); //nothing after this line gets executed
var msg = dec.decode(messagegpb);
console.log(msg);
```

This is the link of the .proto file I am using. https://github.com/dcodeIO/ProtoBuf.js/blob/master/tests/complex.proto

Could someone point me where I am going wrong? 

Thanks a ton

**Comment by dcodeIO** [comment]
If you do not see any console logging, there must be an exception thrown somewhere. Have you tried it with the latest build, yet?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
