### ISSUE TITLE
pbjs fails with an out of memory error processing a proto3 proto

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/ProtoBuf.js#269]
I got this error trying to process a proto file from the [googleapis](https://github.com/google/googleapis) repository. I can reproduce this error with the following shell commands:

```shell
git clone https://github.com/google/googleapis.git
npm install dcodeIO/Protobuf.js
./node_modules/protobufjs/bin/pbjs ./googleapis/google/pubsub/v1beta2/pubsub.proto -path=./googleapis/google -legacy
```

This outputs

```
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)
```

And the `core` file doesn't contain any useful information.

**Comment by dcodeIO** [comment]
This should also be fixed with the previous commit. Can you confirm that it is working?
