### ISSUE TITLE
Message field without "optional" inside "extend" block in proto3

### ISSUE THREAD

**Issue by w4-sjcho** [dcodeIO/ProtoBuf.js#270]
In order to parse:
https://github.com/google/googleapis/blob/master/google/api/annotations.proto

Seems like
        // proto3 syntax style: optional fields without 'optional' keyword.
        else if (Lang.TYPE.test(token) || Lang.TYPEREF.test(token))
            this._parseMessageField(ext, "optional", token);

Must be put near:
https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/DotProto/Parser.js#L765

**Comment by dcodeIO** [comment]
Should be fixed with https://github.com/dcodeIO/ProtoBuf.js/commit/09c62788da7d0ba636c62ea3e319afa170d35c61#diff-dd1aeff8da684f31500e05252abdf2b3L1366
