### ISSUE TITLE
option [packed=true] on repeated objects has odd behavior

### ISSUE THREAD

**Issue by carbip** [dcodeIO/ProtoBuf.js#272]
Hi, 
At first I had the following .proto

message Data {
  required int32 version = 1;
  repeated Value values = 2 [packed=true];
}

message Value {
  required int32 timestamp = 1;
  required double item1 = 2;
  required double item2 = 3;
}

I nested several different 'Value' objects in the 'values' array,  but [packed=true] caused the decode() function to only parse the last 'Value' object of this array.

I now suspect [packed=true] to only work on predefined types, but I think the behavior I observed is quite strange and it could be wise raising an error when [packed=true] is applied on user-defined message types.

What do you think?

**Comment by dcodeIO** [comment]
From https://developers.google.com/protocol-buffers/docs/encoding#packed-repeated-fields

```
Only repeated fields of primitive numeric types (types which use the varint, 32-bit, or 64-bit wire types) can be declared "packed".
```

Currently the packed option should be ignored if a field is not packable. There have been some merges recently, which could have broken this.

https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/Reflect/Message/Field.js#L411

**Comment by carbip** [comment]
thanks for your response. Yes i figured out this while debugging. Now it seems there's something broken.
