### ISSUE TITLE
issues with float type encoding

### ISSUE THREAD

**Issue by carbip** [dcodeIO/ProtoBuf.js#273]
Hi, 

First, many thanks for your great software.

In order to optimize may payload size, I moved from double to float on decimal numbers.
.proto looks like this:

```protobuf
message Data {
  required uint32 version = 1;
  repeated Value values = 2 [packed=true];
}

message Value {
  required float item1 = 2;
}
```

Now I'm having the following issue: say I'm initialising my builder with 

```js
var builder = ProtoBuf.loadProtoFile("mySpec.proto");
      MyData = builder.build("Data");

var myData = MyData({ version:0, 'values': [{item1: 37.335009} ] })
```

then MyData.decode(myData.encode()) will return 37.33501052856445 for item1 value, instead of 37.335009.

If I use double all is fine, but the resulting ByteBuffer is larger.

What is happening here? What should I do differently?

**Comment by dcodeIO** [comment]
Floats use 32 bits to represent the value, while doubles use 64 bits. Hence, floats are less accurate.

More on floating point arithmetic: http://en.wikipedia.org/wiki/Floating_point

Excerpt:
```
In computing, floating point is the formulaic representation which approximates a real number so as to support a trade-off between range and precision. 
```
