### ISSUE TITLE
function to return Message objects as JSON string?

### ISSUE THREAD

**Issue by carbip** [dcodeIO/ProtoBuf.js#274]
Hi, 

Is there a way to get a Message object content as a JSON string?
when doing console.log(<Message object>), it outputs the object in JSON format in the console
when doing Message.Attribute, I can get the value of  Attributes

but I can't find a way to get the full JSON representation of the Message object.

Although close to it, the .toRaw() function does not provide pure JSON representation

Thanks,

**Comment by dcodeIO** [comment]
JSON cannot represent bytes fields, so you need to decide how to represent these. The Message#toRaw function accepts two arguments for this: `Message#toRaw(binaryAsBase64, longsAsStrings)`

Try
```js
var jsonString = JSON.stringify(myMessage.toRaw(true, true));
```
