### ISSUE TITLE
Example for encoding a bytes field?

### ISSUE THREAD

**Issue by snakecharmer1024** [dcodeIO/ProtoBuf.js#276]
Hey great repo! I've been looking around, trying to find an example of how to encode a bytes field and can't seem to find one. Would you be willing to give an example?

**Comment by dcodeIO** [comment]
There are a few general examples on how to use the library here: https://github.com/dcodeIO/ProtoBuf.js/tree/master/examples

A bytes field basically takes a Buffer under node.js or an ArrayBuffer/Uint8Array in the browser. Alternatively, a [ByteBuffer](https://github.com/dcodeIO/ByteBuffer.js), which is used internally, is fine on both. Just assign it to the respective field and you are ready to encode the message.

When decoding, the field is represented as a ByteBuffer instance, which can be converted to a native buffer object through its `ByteBuffer#toBuffer()` method.

**Comment by snakecharmer1024** [comment]
Thanks! Ok I'm satisfied.

**Comment by reebalazs** [comment]
Hi,

I was also looking for a working example to get and set values in field type 'bytes'.

The examples https://github.com/dcodeIO/ProtoBuf.js/tree/master/examples actually contain no  'bytes'. Although the wiki, indeed, covers it, adding an example would be nice, too.

I also noticed an inconsistency. @dcodeIO, you mention "Alternatively, a ByteBuffer, which is used internally, is fine on both." However on node, passing in the buffer directly fails, while toBuffer() gives the correct result.

Do you think this is a bug? If yes, please let me know and I create a ticket.

    var bytes = new ByteBuffer.fromHex('40414243');
    var request = new Message({
      // 'proto_message': bytes.toBuffer(),    // WORKS on node
      'proto_message': bytes,                       // FAILS on node ? (TypeError: Illegal buffer)
    });

**Comment by dcodeIO** [comment]
This should work:

```js
var bb = ByteBuffer.fromHex('40414243');
var request = new Message({
  'proto_message': bb
});
```

Maybe the misplaced "new" operator made it fail. Otherwise, with ProtoBuf.js 4, make sure that ByteBuffer.js is at least version 4, as the method to test for an object being a ByteBuffer has changed lately.

**Comment by reebalazs** [comment]
Thanks! The "new" was wrong, but it did not cause the problem.

It was indeed the version mismatch. (ByteBuffer.js must be at least version 4, and I had 3.5.5.)
