### ISSUE TITLE
pbjs interface is non-standard

### ISSUE THREAD

**Issue by englercj** [dcodeIO/ProtoBuf.js#277]
Pbjs is acting differently than what most people would expect a cli app to be like. Here are a few specific examples of what I mean:

Doesn't implement the standard help flags. Running `pbjs -h` or `pbjs --help` both generate an error instead of printing help output. I had to look at the source to figure out how to use the cli.

Implements non-standard flag format. Instead of using the normal short/long format (`-h`, and `--help`) everything is a single dash long name, which is unlike most other apps.

Would you be open to using something [`yargs`](https://www.npmjs.com/package/yargs) or [`commander`](https://www.npmjs.com/package/commander) to help normalize some of these unintuitive things and provide a bit more robust option parsing?

**Comment by dcodeIO** [comment]
yargs looks good to me. When I get some time, I'll give it a shot.
