### ISSUE TITLE
ProtoBuf.js does not load google/protobuf dependencies

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/ProtoBuf.js#278]
When I try to load a proto with a dependency on a google/protobuf proto, it fails to resolve those dependencies. I can reproduce this with the following shell commands:

```sh
git clone https://github.com/google/googleapis
cd googleapis
npm install dcodeIO/Protobuf.js
node -p 'require("protobufjs").loadProtoFile("google/pubsub/v1beta2/pubsub.proto")'
```

I have tracked this problem down to [this line of Builder.js](https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/Builder.js#L448), which explicitly ignores those dependencies.

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/ProtoBuf.js/tree/master/src/google/protobuf

**Comment by murgatroid99** [comment]
OK, I see that this behavior is documented. But even if it is reasonable to prevent people from loading `google/protobuf/descriptor.proto`, I don't see why that should prevent me from loading `google/protobuf/empty.proto`.

**Comment by murgatroid99** [comment]
With that change, the above code works if I use the `{root: ".", file: "google/pubsub/v1beta2/pubsub.proto"}` argument form in the final line.

**Comment by zyklus** [comment]
I'd like to chime in here that many of the `google/protobuf/*.proto` files are generally useful boilerplate protos.  There are a few (`any`, `duration`, `empty`, and `timestamp`) I use all the time.

While I understand the reasoning behind not including google structural protobufs that this library doesn't need, I don't see what the harm is in including these.  It would prevent me from having to copy the `google` directory from project to project for functionality that works with the `protoc` compiler.

**Comment by rhagigi** [comment]
Agree with @zyklus unless something has changed since August. Especially as this library is used in the [official grpc library for node](https://github.com/grpc/grpc/tree/master/src/node) it's incredibly annoying to manually load in all the `google/protobuf/*.proto` files I need into my protos directory. Am I missing somehting or is this the only way to use `empty` `any` and others?

**Comment by englercj** [comment]
Are there any licensing concerns with shipping Google's protobuf files with this library?
