### ISSUE TITLE
MessagePrototype add should probably return `this`

### ISSUE THREAD

**Issue by dweinstein** [dcodeIO/ProtoBuf.js#279]
https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/Builder/Message.js#L68

it would probably be nice if it worked like [`set`](https://github.com/dcodeIO/ProtoBuf.js/blob/master/src/ProtoBuf/Builder/Message.js#L106)

**Comment by dcodeIO** [comment]
Looks good to me. No need to build, I am always doing a post-merge step.

**Comment by dweinstein** [comment]
thanks for the quick turnaround!

**Comment by dweinstein** [comment]
could you let me know when you release/publish the new version w/ fix applied? thanks!

**Comment by dcodeIO** [comment]
Just pushed it to NPM

**Comment by dweinstein** [comment]
Sweet, thanks!
