### ISSUE TITLE
Convert Longs to strings and ByteBuffers to Buffers

### ISSUE THREAD

**Issue by seishun** [dcodeIO/protobuf.js#281]
My library passes decoded protobuf messages directly to users. Since I don't want to tie the library to Long.js and ByteBuffer.js, I run all objects through a function that converts any Long objects to strings and any ByteBuffer objects to Buffers. It gets a bit messy when there are nested messages.

Do you think adding options to convert Longs to strings and/or ByteBuffers to Buffers on decode would be a meaningful addition to ProtoBuf.js?

**Comment by dcodeIO** [comment]
`Message#toRaw(false, true);` should do that for you.

**Comment by seishun** [comment]
Cool, that works. I think the description of that method could be a bit clearer, though. It's not obvious what "raw payload" means.

Is there perhaps also a way to remove all the `null` fields? Removing also fields with a default value that haven't been set would be even better, but I understand it's work-in-progress (#200).

**Comment by zhiqingchen** [comment]
Customize your toRaw method
```
function toRaw(obj) {
    var clone = {};
    for (var i in obj) {
        if (obj.hasOwnProperty(i)) {
            if (obj[i] === null){
            }else if(typeof obj[i] !== 'object') {
                clone[i] = obj[i];
            } else if (obj[i] instanceof ProtoBuf.ByteBuffer) {
                clone[i] = obj[i].toHex();
            } else if(obj[i] instanceof ProtoBuf.Long){
                clone[i] = obj[i].toString();
            } else {
                clone[i] = cloneRaw(obj[i]);
            }
        }
    }
    return clone;
}
```

**Comment by englercj** [comment]
`obj[i] instanceof ProtoBuf.ByteBuffer`

Don't do that, use `ByteBuffer.isByteBuffer()`

**Comment by zhiqingchen** [comment]
@englercj 
```
ByteBuffer.isByteBuffer = function(bb) {
     return (bb && bb instanceof ByteBuffer) === true;
};
```

I don't understand, they look the same

**Comment by englercj** [comment]
@zhiqingchen You are using/looking at an old version of ByteBuffer. This is the latest version of that method:

https://github.com/dcodeIO/ByteBuffer.js/blob/master/src/methods/static/isByteBuffer.js

See this issue for more info: https://github.com/dcodeIO/ByteBuffer.js/issues/52

**Comment by zhiqingchen** [comment]
@englercj
get it, thanks.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
