### ISSUE TITLE
(suggestion) Maintain type definitions file.

### ISSUE THREAD

**Issue by ttowncompiled** [dcodeIO/protobuf.js#283]
Hey dcode, 

I just wanted to let you know that I took the trouble of writing a TS type definitions file for protobufjs. My team is currently working in TS with protos, and I heavily recommended that we lean on your project to parse them. I love working with protobufjs and that's why I was happy to write a definitions file for the project which can be found here

https://github.com/borisyankov/DefinitelyTyped/pull/4580

I wanted to let you know because I'm not going to have the time to maintain it. It being your project, I was hoping that you would be willing to take the time to look it over, make sure the types are correct, and also take the time to maintain it over the course of your build for those of us working in TypeScript who love using your project.

**Comment by wwwsevolod** [comment]
Hello. It would be really great!
thank you @ttowncompiled for d.ts and @dcodeIO for awesome project, if i found issues and\or time i'll try to add fixes to d.ts.

May be it would be better to move this file here, bcz typescript can work with types from node_modules without questions, and would be easier not to forget about it.

also i'll try to create generation of proto classes in TS soon.

**Comment by LoungeFlyZ** [comment]
+1!  Currently the .d.ts file is over in DefinitelyTyped, however now with the 'typings' CLI being able to install typings from anywhere it would be good to get this moved and maintained here if possible. 

@wwwsevolod do you have any pointers on generation of proto classes in TS? either TS to Proto or the other way around?

Thx!

**Comment by wwwsevolod** [comment]
@LoungeFlyZ I just switched off from typescript. Cost of supporting dependencies is higher with it, than cost reductions that it gave

**Comment by paulsouche** [comment]
+1

**Comment by stasberkov** [comment]
+1

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
