### ISSUE TITLE
Support multiple file inputs to cli parser

### ISSUE THREAD

**Issue by englercj** [dcodeIO/ProtoBuf.js#285]
It would be great to accept a glob as input for the files to parse. A lot of times I have multiple files I want to have converted, but right now I have to do something with `find` to run this process many times to convert all the different protobuf files.

**Comment by englercj** [comment]
Just to add to this ideally I would want something like this:

```protobuf
// something.proto
message SomethingRequest {
    required uint32 id = 1;
}

message SomethingResponse {
    // ...
}
```

```protobuf
// something-service.proto
import "something.proto"

service SomethingService {
    rpc get(SomethingRequest) returns (SomethingResponse);
}
```

To compile into something like:

```js
// something.js
module.exports = require('protobufjs').newBuilder(...).import({ ... }).build();
```

```js
// something-service.js
var Something = require('./something');

module.exports = require('protobufjs').newBuilder(...).import({ ... }).build();
```

Either that, or all the data gets put into a single json are the two methods that would be the most useful. My current tool (using ProtoBuf.js v3) generates actual JS code that creates a JS object that is an instance of `ProtoBuf.Message` and such (instead of using import). That is the optimal case to me, real JS prototype objects using commonjs to load the necessary files, and a single `index.js` that exports the objects that were generated.

I'll see if I can share my proto2js implementation that will hopefully shed light on one way of doing this.

**Comment by dcodeIO** [comment]
Something like this would ideally be implemented as a new [target](https://github.com/dcodeIO/ProtoBuf.js/tree/master/cli/pbjs/targets), taking an additional option specifying the output directory.

**Comment by englercj** [comment]
Absolutely, I just wanted to give context around what the feature could be useful for. Having multiple proto definition files is the first step to making that target a reality.

**Comment by englercj** [comment]
Hey @dcodeIO I got this working in my branch, but I'm doing it using the `.loadXFile()` methods instead of a custom `.load()` that then gets passed into `.loadX()`. The reason for this is since each `.load()` call for each file will resolve import independently, it means there will be duplicate names in namespace errors.

Is there a reason for doing the custom import and not just using the `.loadXFile()` methods, they seem to resolve imports as well.

**Comment by dcodeIO** [comment]
`ProtoBuf.loadJson/Proto(...)` basically serves as a one-shot convenience entry point that parses, if necessary, imports and also resolves, while `Builder#import(...)` just imports the JSON counterpart.

In this case I believe that creating a new builder and calling import for each file is the correct approach, as it reduces the number of resolve passes to a single one. It also skips duplicates if filename is provided.

**Comment by englercj** [comment]
@dcodeIO That could be it, let me try to get it working.

**Comment by dcodeIO** [comment]
> May have something to do with me calling .loadJson/Proto() repeatedly?
Possible. You may however create a Builder first, and then hand that as a parameter to loadJson, so that is reuses it for each file.

**Comment by englercj** [comment]
Oh of course, that is exactly what I am doing:

https://github.com/englercj/ProtoBuf.js/blob/feature/cli-multiple-files/cli/pbjs/sources/proto.js#L32-L41

```js
/**
 * pbjs source: Plain .proto descriptor
 * @exports pbjs/sources/proto
 * @function
 * @param {string[]} filenames Source files
 * @param {!Object.<string,*>=} options Options
 * @returns {!ProtoBuf.Builder}
 */
var proto = module.exports = function(filenames, options) {
    options = options || {};
    var builderOptions = util.getBuilderOptions(options, "using");
    var builder = ProtoBuf.newBuilder(builderOptions);
    if (builderOptions.importRoot) {
        builder.importRoot = builderOptions.importRoot;
    }
    filenames.forEach(function (filename) {
        ProtoBuf.loadProtoFile(filename, builder);
    });
    return builder;
};
```

**Comment by dcodeIO** [comment]
https://github.com/dcodeIO/ProtoBuf.js/commit/acf4d0a40f095e3f649749b588806d3444603b6b

**Comment by englercj** [comment]
Generates fine, but I get the same error when trying to load the commonjs file it outputs.

**Comment by dcodeIO** [comment]
Could have something to do with convertFieldsToCamelCase. Did you try it without?

**Comment by englercj** [comment]
Still fails without it, I am using:

```
./bin/pbjs -t commonjs -p ../dir ../dir/*.proto
```

And I get this output:

```js
module.exports = require("protobufjs").newBuilder({})['import']({ ... }).build();
```

And this error trying to load it:

```
$ node
> require('./output')
TypeError: undefined is not a function
    at ProtoBuf.Reflect.NamespacePrototype.resolve (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:1672:37)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4850:130)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4845:30)
    at ProtoBuf.Builder.BuilderPrototype.build (c:\Users\cengler\repos\ProtoBuf.js\dist\ProtoBuf.js:4909:26)
    at Object.<anonymous> (c:\Users\cengler\repos\....\output.js:12386:4)
```

**Comment by dcodeIO** [comment]
Can you post me the .proto files causing this? Doesn't need to be complete, a portion that raises this error is sufficient.

**Comment by englercj** [comment]
@dcodeIO Unfortunately I cannot do that, but I will try to build a set that reproduces. I'll post back when I have it.

Thanks!

**Comment by englercj** [comment]
Just saw you made commits, and it works now. Loads properly! I think you found the issue!

**Comment by englercj** [comment]
So this is building and importing now, but it looks like after the import/build I do not have everything that was in the protobuf. Most notably the output does not contain the services at all.

**Comment by dcodeIO** [comment]
This is working for me:

```js
var root = require("..").newBuilder({})['import']({
    "package": null,
    "messages": [
        {
            "name": "RequestType",
            "fields": []
        },
        {
            "name": "ResponseType",
            "fields": []
        }
    ],
    "enums": [],
    "services": [
        {
            "name": "MyService",
            "rpc": {
                "MyMethod": {
                    "request": "RequestType",
                    "response": "ResponseType"
                }
            }
        }
    ]
}).build();

console.log(root.MyService);
```

**Comment by englercj** [comment]
In my protobufs the services are in namespaces below the root one. For example:

```js
module.exports = require("protobufjs").newBuilder({
    "convertFieldsToCamelCase": true,
    "populateAccessors": false
})['import']({
    "package": "my.namespace",
    "messages": [
        {
            "name": "something",
            "fields": [],
            "messages": [
                {
                    "name": "v1",
                    "fields": [],
                    "messages": [],
                    "enums": [],
                    "services": [
                        "name": "SomeService",
                        "rpc": {
                            "get": {
                                "request": "GetRequest",
                                "response": "GetResponse"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}).build();
```

Perhaps it has something to do with that.

**Comment by englercj** [comment]
Looks like this is mostly working now, except that I see namespaces as Messages. That is, if I do `obj.$type.className` I get `'Message'` even though it should be a namespace. I think this is simply an import issue.

**Comment by englercj** [comment]
Ping! Wondering if you had a chance to fix this yet?

**Comment by dcodeIO** [comment]
Think of namespaces being messages as if you'd be writing a proto definition without a `package` option. You also have to encapsulate everything in messages in that scenario to form namespaces, which basically is the reason why ProtoBuf.js does the same.

**Comment by kjvalencik** [comment]
:+1: It looks like this works for encoding, but not for decoding. This does not work:

```protobuf
message test {
    service Foo {}
}
```
