### ISSUE TITLE
.toBuffer() output param.

### ISSUE THREAD

**Issue by englercj** [dcodeIO/ProtoBuf.js#286]
Right now .toBuffer() will allocate and return a buffer object.

I have a protocol that involves sending multiple protobuf messages in a single packet, this means allocating a buffer for each message, allocating a container buffer, and copying the messages into it.

It would be great if I could instead allocate a single buffer and just have the messages written to it. For example:

```js
// assume I have `header` and `body` which are both ProtoBuf.Message objects

// Here I use 'byteLength' to refer to a property that has the length of the message in bytes
// but that doesn't require an allocation to gather. Not sure if this exists yet.
var buffer = new Buffer(2 + header.byteLength + body.byteLength);

// write the size of the "header" message so it can be extracted later on the other side
message.writeUint16BE(header.byteLength, 0);

// write the header to the output buffer
// params are (outputBuffer, byteOffset);
// Where byteOffset defaults to `0`
header.toBuffer(message, 2);

// write the body to the output buffer
body.tobuffer(message, 2 + header.byteLength);

// at this point I only allocated a single buffer, and the messages were serialized directly to it.
```

I use browserify, so even in browser I still use `Buffer` objects which act just like node buffers.

**Comment by dcodeIO** [comment]
ProtoBuf.js is built upon [ByteBuffer.js](https://github.com/dcodeIO/ByteBuffer.js) internally, which already accounts for that. Basically, you could reuse a single ByteBuffer instance forever, passing it to decode/encode etc. Calling `Message#toBuffer()` returns a slice on the ByteBuffer's (which is returned by `Messsage#encode()`) backing node Buffer under node, respectively a slice on the ByteBuffer's backing ArrayBuffer in the browser.

**Comment by englercj** [comment]
So I guess I am confused about a few things then:

1. How do I tell how big of a buffer (or ByteBuffer) to allocate to include my messages + 2 bytes?
2. How do I tell the encode method at which offset to write itself to?

Can you give me an exmaple of how to accomplish my previous code example using the current tools in ProtoBuf.js?

**Comment by dcodeIO** [comment]
Looks good to me. `Message#encode` returns a flipped ByteBuffer only when creating a new ByteBuffer, i.e. none is provided when calling the method. Otherwise it just writes to the specified one and advances the offset.

**Comment by englercj** [comment]
Gotcha, I will try this out tomorrow and post the results here:

```js
var buffer = new ByteBuffer(2 + header.calculate() + body.calculate());

buffer.writeUint16(header.calculate());
header.encode(buffer);
body.encode(buffer);

buffer.flip();

// send backing buffer down the pipe
transport.send(buffer.toBuffer());
```

Thanks!

**Comment by englercj** [comment]
Was able to get this working, thanks!
