### ISSUE TITLE
noAssert in MessagePrototype.set() doesn't work for an undefined field.

### ISSUE THREAD

**Issue by nonelove** [dcodeIO/ProtoBuf.js#287]
I'd like to set a field value which isn't defined in a proto file. To avoid throwing the error, I tried to use the 'noAssert' parameter. But, it still throws error because the following code doesn't check if the field exists.

https://github.com/dcodeIO/ProtoBuf.js/blob/master/dist/ProtoBuf.js#L2535

```
var field = T._fieldsByName[keyOrObj];
if (!noAssert) {
    if (!field)
        throw Error(this+"#"+keyOrObj+" is not a field: undefined");
    if (!(field instanceof ProtoBuf.Reflect.Message.Field))
        throw Error(this+"#"+keyOrObj+" is not a field: "+field.toString(true));
    this[field.name] = (value = field.verifyValue(value)); // May throw
} else {
    this[field.name] = value;                 <=== here
}
if (field.oneof) {
    ...
}
```

Is it intended or just a bug? What about changing it to the following code?

```
} else {
    if (field) {
        this[field.name] = value;
    } else {
        this[keyOrObj] = value;
    }
}
if (field && field.oneof) {
    ...
}
```

**Comment by dcodeIO** [comment]
The `noAssert` parameter is meant to speed things up a bit in case that an operation is already known to succeed. With `Message#set`, this is if you are sure that the field exists and that the value is correct for its type, which saves you a relatively expensive call to `Reflect.Message.Field#verifyValue`.

I have now hardened this a bit to not throw in most cases (not sure if this is a good idea though), but you should just assign a property to the message as with normal JS if it is not a field, as `Message#set`, by contract, is meant to be used to set values for fields only.

`Message#add` for example will still throw if you are trying to add a value to a non-repeated field respectively custom property which is not an array.
