### ISSUE TITLE
Http posted ArrayBuffer can't be parsed by Java parseFrom()

### ISSUE THREAD

**Issue by Blazingspike** [dcodeIO/ProtoBuf.js#288]
Hi there,

I tried to post a message using angular like this:

```js
var buff = ProtoBuf.toArrayBuffer()
var request = {
				method: 'POST',
				url: 'url',
				headers: {'Content-Type': 'application'},
				data: buffer,
				responseType: 'arraybuffer'
		};
```
on server side, the java code proto.parseFrom(bytes) throws error:
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

The response is also ByteArray of a protobuf which is generated by Java toByteArray(). ProtoBufJs can parse it properly using decode().

Tried many ways but still can't get the POST request part working, any ideas?

Thanks.

**Comment by dcodeIO** [comment]
I assume that your buffer becomes corrupted on the way from the browser to your server. There are a couple of steps where this may happen, but regarding your snippet:

Did you mean `'Content-Type': 'application/octet-stream'`?

Other than that, [Sending and Receiving Binary Data](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) might give some additional hints.

**Comment by Blazingspike** [comment]
Thanks for quick response. It does seem that the buffer is corrupted somehow. But I can't find out how it's corrupted. Here is what I tried to compare the values:
For the same proto message
1) Use ProtoBufJs .toArrayBuffer(), it converted into 4 bytes [8, 0, 16, 1]
2) Use Java .toByteArray(), it converted into 4 bytes and content is the same [8, 0, 16, 1].
3) Use http POST ProtoBufJs generated ArrayBuffer to server (4 bytes in POST body), on server side, received HttpServletRequest, but .getInputStream().avaliable() only reports 2 bytes received [123, 126]

For the http header, I used 'Content-Type': 'application/octet-stream'

Tried to convert ArrayBuffer to Uint8Array, but that basically turn the byte into int array, where makes it even worse.

**Comment by dcodeIO** [comment]
I'd guess that it's either caused by the HTTP library used to send the data (does it accept ArrayBuffer payloads? any special requirements missing to make it work? does it add any additional headers that could cause the server to misinterpret the payload?), or by the HTTP server used to receive it.

**Comment by Blazingspike** [comment]
After some research, it turn out to be the issue of AngularJs. The buffer is not POSTed in the payload using AngularJs $http, I have to use XHR2 (which AngularJs wraps around) to POST the buffer directly, which is successful. Thanks for helping though. ProtoBufJs is awesome!
