### ISSUE TITLE
Trying to understand the API, "encode".

### ISSUE THREAD

**Issue by chrisdew** [dcodeIO/ProtoBuf.js#290]
I'm trying to understand the API, in particular the results of "encode()".

I'm using the npm package in NodeJS.

It seems to not return a simple Buffer object, but instead an JS object with a buffer field and offset. markedOffset, limit, littleEndian and noAssert.

What am I doing wrong?

**Comment by dcodeIO** [comment]
These are [ByteBuffer](https://github.com/dcodeIO/ByteBuffer.js) objects.

See also:
* [ByteBuffer.js API](https://github.com/dcodeIO/ByteBuffer.js/wiki/API)
* [ProtoBuf.js API](http://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/ProtoBuf.js/master/docs/ProtoBuf.html)
* [ProtoBuf.js Wiki](https://github.com/dcodeIO/ProtoBuf.js/wiki)

**Comment by chrisdew** [comment]
That explains it.

Many thanks,

Chris.
