### ISSUE TITLE
Mock/Fake data from proto

### ISSUE THREAD

**Issue by CWSpear** [dcodeIO/protobuf.js#294]
We are using gRPC with protobuf schema and it would be awesome to mock some of that data so we can test underlying functionality in unit tests. We were gonna just use the parser to build out an object to send to something like [Faker.js](https://github.com/marak/Faker.js/), but I wanted to see if you guys had already built something like this or had any other clever ideas.

**Comment by CWSpear** [comment]
As an example, I have this schema:

```proto
message Order {
    float         total = 1;
    repeated Item items = 2;

    message Item {
        string name  = 1;
        float  price = 2;
    }
}
```

and do something like this:

```js
var testData = protoMocker('/path/to/order.proto');

console.log(testData);
```

and have it output something like:

```js
{
    Order: {
        total: 24.4,
        items: [{
            name: 'banana',
            float: 1.2
        }, {
            name: 'apple',
            float: 5.22
        }]
    }
}
```

Not asking you to build it or anything, but just trying not to reinvent the wheel and figured this'd be a good place to start since I couldn't find anything on Google, etc! =)

**Comment by dcodeIO** [comment]
There is [pbjs](https://github.com/dcodeIO/ProtoBuf.js/wiki/pbjs) which is capable of processing .proto files to json. So you have two options:
* Call pbjs to produce your json, located here: https://github.com/dcodeIO/ProtoBuf.js/blob/master/cli/pbjs.js
* Use the parser (if you do not require pulling imports)

**Comment by CWSpear** [comment]
Well, both those options convert it to the JSON object of the structure definition, but it's not "mock data" based off of the schema... does that make sense? Or am *I* missing something?

And yeah, I can take that JSON structure and convert it into mock data; I'm just seeing if it's been done before.

**Comment by dcodeIO** [comment]
If you need to populate messages with some dummy data, I suggest taking a look at [reflection](https://github.com/dcodeIO/ProtoBuf.js/wiki/Reflection). Afaik nothing like this has been implemented yet, so your best bet is to inspect the field types and generate the data your own.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by shanshanzhu** [comment]
+1
It feels really tedious to generate mock data based on the proto definition, and manually change it when protofile updates
Also +1 for creating flow-typed type file for mock data type.

**Comment by uchaoxi** [comment]
> As an example, I have this schema:
> 
> ```proto
> message Order {
>     float         total = 1;
>     repeated Item items = 2;
> 
>     message Item {
>         string name  = 1;
>         float  price = 2;
>     }
> }
> ```
> 
> and do something like this:
> 
> ```js
> var testData = protoMocker('/path/to/order.proto');
> 
> console.log(testData);
> ```
> 
> and have it output something like:
> 
> ```js
> {
>     Order: {
>         total: 24.4,
>         items: [{
>             name: 'banana',
>             price: 1.2
>         }, {
>             name: 'apple',
>             price: 5.22
>         }]
>     }
> }
> ```
> 
> Not asking you to build it or anything, but just trying not to reinvent the wheel and figured this'd be a good place to start since I couldn't find anything on Google, etc! =)

I need the same function you descriped，do you have a implement？

**Comment by TusharKoul** [comment]
is there a solution for this yet?

**Comment by baigod** [comment]
is there a solution for this yet?

**Comment by JasonkayZK** [comment]
Guys, i made a cli tool to solve this problem:

https://github.com/JasonkayZK/mock-protobuf.js

Just install this tool:

```bash
npm i mock-pb-cli -g
```

And use it to generate the mock data:

```bash
$ cat proto/demo.proto 
syntax = "proto3";

message Order {
  float         total = 1;
  repeated Item items = 2;

  message Item {
    string name  = 1;
    float  price = 2;
  }
}

$ mock-pb g 
Mocked .Order: 
{
  "total": 6469889040645664,
  "items": [
    {
      "name": "Egnggifux sqxu ojkvmbw jnmp.",
      "price": -7675849680425321
    },
    {
      "name": "Bsdbmperi uiuanqaij wmjsrevsi zfwfsxjz.",
      "price": 4068287669927304
    }
  ]
}
```
