### ISSUE TITLE
pbjs: command not found

### ISSUE THREAD

**Issue by ahsandar** [dcodeIO/ProtoBuf.js#297]
getting the following error when trying to use pbjs in terminal with protobufjs@4.0.0 
        
           pbjs: command not found 

any help would be great as to why it can't find

**Comment by englercj** [comment]
How did you install `protobufjs`, and how are you trying to run it?

**Comment by ahsandar** [comment]
> npm install protobuf -g

            > pbjs -h
             pbjs: command not found

**Comment by englercj** [comment]
This package is `protobufjs`, not `protobuf`. That is a different package.

**Comment by ahsandar** [comment]
thanks
