### ISSUE TITLE
Missing dependency "fs" in bower.json

### ISSUE THREAD

**Issue by ungerik** [dcodeIO/protobuf.js#298]

**Comment by dcodeIO** [comment]
Are you experiencing a specific error? The "fs" dependency isn't available in the browser, as it is node's fs module, which is just featured tested and used if available only.

**Comment by ungerik** [comment]
On Fri, Jul 10, 2015 at 3:09 PM, Daniel Wirtz <notifications@github.com>
wrote:

> Are you experiencing a specific error?


Yes, my Gulp build script is throwing the require as error. Seems that it
is not picking up your feature test.

-Erik


-- 
+43 650 58 33055
erik@erikunger.com
Skype: ungerik
http://erikunger.com
http://github.com/ungerik
http://twitter.com/ungerik
http://facebook.com/ungerik
http://www.linkedin.com/in/ungerik
http://www.xing.com/profile/Erik_Unger2

**Comment by dcodeIO** [comment]
I changed the way require calls are performed internally in an attempt to make build tools skip them. I haven't published this to npm yet and it would be great if you could give it a try and let me know of your findings.

**Comment by samuelmesq** [comment]
@dcodeIO, it would be better to move all functions to a namespace that handles files? so the lib protobufjs itself, would not be responsible for loading files, only parse. This way the browser version would be smaller.

ps: Another opinion, do build using Webpack or browserify, so it would be compatible with node and browser.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
