### ISSUE TITLE
Can I use this library to create a typed javascript class without protobuf?

### ISSUE THREAD

**Issue by ceram1** [dcodeIO/ProtoBuf.js#301]
As proto3 supports json, I want to use json over http 1.1, for web clients.

I'll also use https://github.com/google/googleapis/blob/master/google/api/http.proto to declare rest api on .proto file.

Is this supported?

**Comment by dcodeIO** [comment]
You could use ProtoBuf.js to create the JSON representations of messages, not using `Message#encode` but `Message#encodeJSON`, and sending the result over HTTP, decoding it with `Message.decodeJSON`.

**Comment by ceram1** [comment]
Sorry for delay.
I meaned I want to create plain javascript class with this, and now I find it available, but I want to know if this library supports additional thngs in rpc {} from [google/api/http.proto](https://github.com/google/googleapis/blob/master/google/api/http.proto)

**Comment by dcodeIO** [comment]
ProtoBuf.js is be able to parse the http.proto you linked so that you can work with its structures, but it does not implement the API it describes.

**Comment by ceram1** [comment]
Thanks for yout help.
But now I found that this [drops comment](https://github.com/dcodeIO/ProtoBuf.js/issues/245).
