### ISSUE TITLE
pbjs traslates "repeated" into "optional"

### ISSUE THREAD

**Issue by novellizator** [dcodeIO/ProtoBuf.js#304]
when I run `pbjs -t proto my_test.proto`, all the "repeated" field modifiers are replaced with "optional"...

**Comment by dcodeIO** [comment]
What version of ProtoBuf.js are you using? This works for me on master:

```
pbjs tests/example1.proto -t proto
```

**Comment by novellizator** [comment]
I am talking about REPEATED field, not REQUIRED.
I slightly modified the the code (replaced required with repeated and here's the output:

    tomasnovella@Tomass-MacBook-Pro:~/workspace/playground/protobuf/ProtoBuf.js/bin$ cat ../tests/example1.proto
    message Test1 {
        repeated int32 a = 1;
    }

    // Test1 should encode to "08 96 01" with Test1#a=150
    tomasnovella@Tomass-MacBook-Pro:~/workspace/playground/protobuf/ProtoBuf.js/bin$ pbjs ../tests/example1.proto -t proto

     Processing: ../tests/example1.proto ...

    message Test1 {
        optional int32 a = 1;
    }


     pbjs OK Converted 1 source files to proto (44 bytes, 11 ms)
    tomasnovella@Tomass-MacBook-Pro:~/workspace/playground/protobuf/ProtoBuf.js/bin$


The current version was using is this:
    
    * c211f9f - (HEAD, origin/master, origin/HEAD, master) More Builder cleanup (Sat, 18 Jul 2015 01:06:48 +0200, 7 days ago) <dcode>

**Comment by novellizator** [comment]
does that work with you?
