### ISSUE TITLE
Automatic conversion of types

### ISSUE THREAD

**Issue by crudbetter** [dcodeIO/ProtoBuf.js#305]
Hi there,

Definitely a question more than an issue.  Apologies if this isn't the right forum.

Can ProtoBuf.js be configured to automatically attempt type conversions?  For example a .proto file containing: 

    message SetApvControlSpeedForLocationRequest {
      required string location_id = 2;
      required float apv_control_speed = 3;
      extensions 100 to 120;
    }

Can `apv_control_speed` be passed as a string value of "4.0" and ProtoBuf.js attempt to convert it?  At the moment I get an "Illegal value for [object Object] of type float: string (not a number)" error.

Many thanks in advance,
Mike

**Comment by englercj** [comment]
I wouldn't want this to happen in most of my apps using this library. Implicit type conversions is not desirable for a lot of apps. Just my 2 cents.

**Comment by crudbetter** [comment]
@englercj wholeheartedly agree - and I would be explicit if I were starting an app from scratch.  I omitted the context of my question - I'm mid upgrading Node from v0.8 to vLatest for our app, and the protobuf client we currently use (which must do some form of implicit conversion) is a blocker which I'm (happily) forced to move away from.

I was hoping I wouldn't have to take on the risk of updating all ProtoBuf message creation to explicit typing, at the same time as the Node upgrade. I was hoping for some magic flag a bit like the `ProtoBuf.convertFieldsToCamelCase`...

**Comment by crudbetter** [comment]
In case it helps anyone I ended up writing a helper function to convert based on the reflection properties provided by a built message:

    function convertToExpectedMessageFormat (msg, fields) {
        var val;
        Object.keys(msg).forEach(function(key) {
            var field = _.where(fields, { name: key })[0];

            if (typeof msg[key] == 'object') {
                if (field) {
                    convertToExpectedMessageFormat(msg[key], field.resolvedType._fields);
                }
            } else {
                if (field && _.contains(['int32', 'float', 'double'], field.type.name)) {
                    val = Number(msg[key]);
                    delete msg[key];
                    msg[key] = val;
                }
            }
        });
        return msg;
    }
