### ISSUE TITLE
loadJsonFile return status of 406 Not Acceptable

### ISSUE THREAD

**Issue by doronbrikman** [dcodeIO/protobuf.js#306]
Hi,

I trying to create a builder with:

``` javascript
ProtoBuf.loadJsonFile("filename.json", function (err, builder) {
 Object = builder.build("Object");
});
```

and I'm getting response from the server that said: Failed to load resource: the server responded with a status of 406 (Not Acceptable)
I think when you using jquery you don't use the 'application/json' option.

Or maybe I'm doing something else wrong..

Thanks

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
