### ISSUE TITLE
How to use symbolic names when checking enum constants?

### ISSUE THREAD

**Issue by saste** [dcodeIO/ProtoBuf.js#308]
When creating a JSON object to serialize it is possible to use symbolic strings to represent an enum constant, for example setting:
msg_type: "INVITE"

It would be useful for increasing readability to be able to use symbolic names when reading a deserialized object, while at the moment I do something like this:

 if (msg.msg_type == 11) // INVITE 

This would also avoid the need to rewrite the constants in case the .proto file changes.
It is not very clear from the documentation if this can be done in any way. So the question is: is this possible, and how to do that?

Thanks for your time and for the cool project.

**Comment by dcodeIO** [comment]
If only readability is your issue, you could simply use the runtime enum object:

```protobuf
message Foo {
  required Bar bar = 1;
  
  enum Bar {
    SOME = 0;
    THING = 1;
  }
}
```

```js
...
var Foo = builder.build("Foo");
var foo = new Foo(Foo.Bar.SOME);
if (foo.bar != Foo.Bar.THING) {
   ...
}
```

**Comment by dcodeIO** [comment]
This adds a C#-like helper function:

```js
var name = ProtoBuf.Reflect.Enum.getName(Foo.Bar, 0);
console.log(name); // prints "SOME"
```

Or short:

```js
var name = Foo.Bar.getName(0);
console.log(name);
```

**Comment by saste** [comment]
Your answer addresses my question. (I wonder if I missed something from the documentation, or that bit of information is just missing). Thank you so much.
