### ISSUE TITLE
myMessage.toBuffer() does not work in browser, although works in nodejs

### ISSUE THREAD

**Issue by novellizator** [dcodeIO/ProtoBuf.js#309]
Hi,
I'm not sure if it's a bug or a feature, but I tried to send the buffered message via node.js and everything worked. When I ran the same script inside a browser (browser extension) it failed at the point that (probably) the recipient didn't receive any data in the body...
 
  
    // https://www.npmjs.com/package/request
    request.post({
      url: SOME_URL,
      headers: {
        'Content-Type': 'application/octet-stream',
        'Authorization': 'Bearer '+ accessToken
      },
      encoding: null, //  if you expect binary data
      body: myMessage.toBuffer()
    }, (error, response, body) => {
      console.log('error, body', error, body);
      if (!error) {
        //readSyncRequest(body, cb);
      }
    });
Plus one more funny thing - I tried to analyze the myMessage.toBuffer() and it turns out it's an ArrayBuffer anyway. 

Do you please have any idea, what may be wrong?

**Comment by englercj** [comment]
toBuffer() returns a node buffer in node, and an ArrayBuffer in the browser. What isn't working for you?

**Comment by novellizator** [comment]
Uh-huuh. The npm request module I'm using does not send any data, when it gets ArrayBuffer in the body.
Is there any way _within the browser_ to convert this arraybuffer to buffer so that I could send it via that function? https://github.com/dcodeIO/node-memcpy seems to be only for nodejs...

**Comment by dcodeIO** [comment]
As far as I know https://github.com/feross/buffer is used to emulate node buffers in the browser, when browserify'ing it. Looks like its constructor [can handle ArrayBuffers](https://github.com/feross/buffer/blob/master/index.js#L100).

**Comment by englercj** [comment]
Request may also support sending a typed array (worth a try):

```js
new Uint8Array(myMessage.toBuffer());
```

**Comment by novellizator** [comment]
Tried both, and they did not work...

What I observed: both solutions (new Buffer() and Uint8Array) return something that is "instanceof Uint8Array", unlike the node buffer. 
Also, new Buffer(myArrayBuffer).length === 0 (the UInt8Array and node native buffer return the right non-zero length).

Any ideas? I guess I may try substituting request module for something else and then try the UInt8Array...

**Comment by englercj** [comment]
You need to pass a typed array to the buffer ctor:

```js
new Buffer(new Uint8Array(myMessage.toBuffer()))
```

Also you should never do `obj instanceof Buffer`, you should only do `Buffer.isBuffer(obj)` which is what request does. The polyfil ensures this method works correctly.

**Comment by novellizator** [comment]
ok, found it. Part of the problem was solved by using an alternative library browser-request https://github.com/iriscouch/browser-request/issues/16 and the second issue was totally unrelated - the webrequest library kept appending cookies that belonged to that domain without my consent, and the google server turned the request down the moment it saw cookies.

In the end I didn't even need Buffer, converting to Uint8Array was enough.

Thanks.
