### ISSUE TITLE
toRaw throws if the message was decoded from external ByteBuffer

### ISSUE THREAD

**Issue by seishun** [dcodeIO/protobuf.js#310]
Steps to reproduce:

```
npm install protobufjs
npm install bytebuffer
```

This ensures there are two separate installations of ByteBuffer (each with their own Long).

``` js
var ByteBuffer = require('bytebuffer');
var ProtoBuf = require('protobufjs');

var CMsgGameserverCrash = ProtoBuf.loadProto(
'message CMsgGameserverCrash {\n' + 
'  optional uint64 match_id = 1;\n' +
'}').build('CMsgGameserverCrash');

var crash1 = new CMsgGameserverCrash({
  match_id: 1234
}).toBuffer();

var bb = ByteBuffer.wrap(crash1);
var crash2 = CMsgGameserverCrash.decode(bb);
console.log(crash2);
crash2.toRaw(false, true);
```

Output:

```
{ match_id: { low: 1234, high: 0, unsigned: true } }
/home/drkoljan/reproduce-protobufjs/node_modules/protobufjs/dist/ProtoBuf.js:2949
    clone[i] = cloneRaw(value, binaryAsBase64, longsAsStrings, field.type, fie
                                                                    ^
TypeError: Cannot read property 'type' of undefined
    at cloneRaw (/home/drkoljan/reproduce-protobufjs/node_modules/protobufjs/dist/ProtoBuf.js:2949:97)
    at cloneRaw (/home/drkoljan/reproduce-protobufjs/node_modules/protobufjs/dist/ProtoBuf.js:2949:44)
    at MessagePrototype.toRaw (/home/drkoljan/reproduce-protobufjs/node_modules/protobufjs/dist/ProtoBuf.js:2964:28)
    at Object.<anonymous> (/home/drkoljan/reproduce-protobufjs/test.js:16:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by dcodeIO** [comment]
Should not happen with ProtoBuf 4.X. Which version are you using?

**Comment by seishun** [comment]
ProtoBuf.js version 4.0.0.

**Comment by paralin** [comment]
I'm still having this with the latest master version. Any ideas?

**Comment by seishun** [comment]
Have you been able to reproduce the crash using the steps provided?

**Comment by dcodeIO** [comment]
Shouldn't crash anymore with that fix. However, there is still an issue with Longs from different packages that might prevent such objects to be properly converted to strings when the option is set. This needs a fix in `Long.isLong` itself.

**Comment by seishun** [comment]
I confirm that it no longer crashes, but it doesn't convert the Long to a string either.

**Comment by dcodeIO** [comment]
Can you test this with [Long.js master](https://github.com/dcodeIO/Long.js)? Basically, just replace `dist/Long.js` under bytebuffer/long and protobuf/bytebuffer/long.

**Comment by seishun** [comment]
It converts correctly now.

**Comment by dcodeIO** [comment]
Thanks, going to push a release soon.

**Comment by code-guru** [comment]
I am having this issue in 5.0.1, can you please confirm this? What is the workaround for this?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
