### ISSUE TITLE
Immutable protobufs

### ISSUE THREAD

**Issue by mhahn** [dcodeIO/ProtoBuf.js#315]
Is there a way to support immutable protobufs?

I know in the java implementation there is a `mergeFrom` method on the builder, the swift implemenation has a `toBuilder` method so you can make changes and build a new instance.

The only way I can see to do something similar with this library is:

```
var car = Object.freeze(new Car("Rusty", new Car.Vendor("Iron Inc.", new Car.Vendor.Address("US")), Car.Speed.SUPERFAST));
var updatedCar = car.$type.decode(car.encode());
updatedCar.setSpeed(1);
```

**Comment by dcodeIO** [comment]
Well, immutable stuff isn't really a property of JavaScript. So yes, using Object.freeze and friends might be your best shot here, maybe applying it recursively.

**Comment by mhahn** [comment]
Yea, I was more just curious what the fastest/best way to clone protobufs was. the `car.$type.decode(car.encode())` seemed a little heavy handed.

**Comment by dcodeIO** [comment]
Since 4.0.0 it's possible to create a new instance by just copying from an existing one: `var myCar2 = new Car(myCar1);`

**Comment by mhahn** [comment]
oh awesome, thats great. thanks!

**Comment by DouglasHeriot** [comment]
I also need this for React.js immutable props.
I’ve been trying to use the `new Car(myCar1)` thing, but found it doesn’t actually make a deep copy.

See my pull request #399 for an implementation of deep copying. What is your expected behaviour?

**Comment by mhahn** [comment]
I've been using the decode/encode behavior for the same thing and it's been
working well. I would love was a helper method on the object that returned
a copy

**Comment by joshkel** [comment]
Note that the `car.$type.decode(car.encode())` approach may run into problems with big endian versus little endian in 5.0.1. See #647.
