### ISSUE TITLE
Losing full declaration of field in version 4.0.0

### ISSUE THREAD

**Issue by ibaileyStingray** [dcodeIO/protobuf.js#316]
Hi, I was using protoBufjs 3.8.2 to generate typescript description of the protobuf. one of the example i used is a depth enum declaration
```
message First {
	message Second {
		enum Colors {
                RED = 1;
                YELLOW = 2;
                GREEN = 3;
                BLUE = 4;
            }
	}

    required First.Second.Colors content = 1;
}
```
in version 3.8.2 i got the json i want
```
{
    "package": "enumInsideMessageInsideMessage",
    "messages": [
        {
            "name": "First",
            "fields": [
                {
                    "rule": "required",
                    "options": {},
                    **"type": "First.Second.Colors",**
                    "name": "content",
                    "id": 1
                }
            ],
  
...
}
```
but in version 4.0.0, the type is missing my full specifier
```
{
    "package": "enumInsideMessageInsideMessage",
    "messages": [
        {
            "name": "First",
            "fields": [
                {
                    "rule": "required",
                    "options": {},
                    **"type": "Second.Colors",**
                    "name": "content",
                    "id": 1
                }
            ],
 ..
}
```
is it an optimization? can we have a setting to preserve the full type?
thanks for your time.

**Comment by dcodeIO** [comment]
It should use the shortest possible, non-conflicting reference. You could of course load it to a builder to obtain the fully qualified name, but an option might also be worth to be considered here.

**Comment by ibaileyStingray** [comment]
I would argue that if the .proto use a fully specified type like 
required First.Second.Colors content = 1; instead of required Second.Colors content = 1; its probably because the user want it that way but I will look at the builder option right away. Thanks.

**Comment by ibaileyStingray** [comment]
I was able to work around it. Feature not needed anymore.
