### ISSUE TITLE
Getting various decoding errors trying to parse Protobuf own encodings

### ISSUE THREAD

**Issue by SyRenity** [dcodeIO/ProtoBuf.js#318]
Trying to decode own Protobuf.js message buffers, I'm getting exceptions of the following kind:
```
Illegal wire type for unknown field 301989887 in Message .RspPacket#decode: 7
Illegal wire type for field Message.Field .RspPacket.params: 0 (2 expected)
```

Same error appears on the receiving Java side as well.
What is the correct method to preserve encoded byte buffers integrity?

**Comment by SyRenity** [comment]
Found out I shouldn't use the .buffer directly, but rather properly wrap it into base64.

Is this the only way to ensure proper data exchange between Protobuf.js and Java, or there a faster method that does not involve the overhead?

**Comment by dcodeIO** [comment]
There is some documentation here: https://github.com/dcodeIO/ProtoBuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F

When using a proper binary read/write, it is possible to exchange the binary data directly.

**Comment by SyRenity** [comment]
Had this before, and received the error messages above. What content type
should be used on request and response, and should the byte buffer plainly
passed in body in them both?

**Comment by englercj** [comment]
`application/octet-stream` or `application/x-protobuf` should work fine. The important XHR part is `xhr.responseType = 'arraybuffer'`. Make sure you use that and `xhr.response` (*not* `xhr.responseText`).

**Comment by SyRenity** [comment]
@englercj I actually use Node.JS and Java client, so I guess I should simply respond with message.toBuffer()?

**Comment by englercj** [comment]
Sure, if you are speaking from the node side.

**Comment by SyRenity** [comment]
@englercj Thanks, this did the trick (used .buffer directly before).
