### ISSUE TITLE
proto2 default optional fields construction behaviour

### ISSUE THREAD

**Issue by frarees** [dcodeIO/protobuf.js#319]
Hi, 

Reading the [official language guide](https://developers.google.com/protocol-buffers/docs/proto#optional), I came across the following clause:

> If the default value is not specified for an optional element, a type-specific default value is used instead: for strings, the default value is the empty string. For bools, the default value is false. For numeric types, the default value is zero. For enums, the default value is the first value listed in the enum's type definition.

When using ProtoBuf.js, I construct via builder a message (`new MyMessage ()`). All optional fields are `null`, but I guess they should be set to its type's default value, as stated above i.e. integers as zero, booleans as false and strings as empty strings. Even after decoding, if optional fields were not in the wire data they will remain `null` instead of having their protocol default values. 

Does this means ProtoBuf.js construction is not compliant with the protocol?

**I've edited the description to better state the issue**

**Comment by dcodeIO** [comment]
It is compliant with how the wire format looks. The API might differ for a lot of reasons, most notably the fact that this library has been built from scratch without having the goal to be API compatible to other implementations, which is inevitable anyway because this is JavaScript.

**Comment by frarees** [comment]
I see. Currently we're using this library to serve a REST API. Clients are implemented in C# using another implementation, so basically we need interop pretty much... Are there any downsides you spotted of using _typed_ construction? 

If my message field is defined as `optional bool foo = 0` I expect js object `m.foo` to be `true` or `false` but not `null`. Otherwise, we'd have to write conditionals per field and assigning default values by ourselves when needed, making decoding dirtier and error prone. 

Anyway, if you think it's not a good move I could always fork and manage that by ourselves I guess..

**Comment by seishun** [comment]
It's not compliant in the sense that `optional bool foo = 0;` should be equivalent to `optional bool foo = 0 [default = false];`, but they are treated differently by ProtoBuf.js.

Despite the fact that this is JavaScript, there is a way to have an API that works the same as the official implementations, which I described here: [#200 (comment)](https://github.com/dcodeIO/ProtoBuf.js/issues/200#issuecomment-98153230).

**Comment by frarees** [comment]
Explicitly exposing default values made it work for us. It's a sensible workaround ATM. #200 +1

**Comment by atomizer** [comment]
Looks like this can be fixed by changing this logic: https://github.com/dcodeIO/protobuf.js/blob/72bc66ccdfcf66c1645c5de311bf26078d411cac/src/ProtoBuf/Reflect/Message/Field.js#L148-L155
Line 151 must also run in case of proto2 syntax and optional field with no explicit default value.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
