### ISSUE TITLE
Trying to implement ProtobufJS in Cordova app

### ISSUE THREAD

**Issue by dustycoder** [dcodeIO/protobuf.js#320]
I've posted the question at StackOverflow, if anyone seeing this has any insight I would appreciate it.  Thank you: http://stackoverflow.com/questions/32681257/errors-implementing-protobufjs-in-cordova-app

**Comment by dcodeIO** [comment]
At first glance these `undefined` and not defined issues look like an issue with how protobuf.js is loaded.

Reference: https://github.com/dcodeIO/ProtoBuf.js/blob/master/dist/ProtoBuf.js#L24

Which of the loader `if`s is executed in your case?

**Comment by dustycoder** [comment]
I actually started coming to that conclusion myself.  I thought I ready that I only needed ProtoBuf.js if I wasn't using this in node which turns out to be wrong (not sure where I read it or if I made that up).

Let me ask a different question then (because I don't know the answer to what you asked):  If I'm using this as straight javascript what order (or how) should I load all the dependent files.  Right now I've manually added all of the JS files (ProtoBuf/Reflect/Service.js, etc) manually as <script> tags in my index.html and I'm slowly working through the dependency failures.  Is there a better way to do this, or do you have the order in which these files should be loaded?

Thanks,
- Dustycoder

**Comment by dcodeIO** [comment]
You need [Long.js](https://github.com/dcodeIO/Long.js/tree/master/dist), [ByteBuffer.js](https://github.com/dcodeIO/ByteBuffer.js/tree/master/dist) and [ProtoBuf.js](https://github.com/dcodeIO/ProtoBuf.js/tree/master/dist) in that order. No need to include anything from `src/` (like the Reflect/Service).

**Comment by dustycoder** [comment]
That is exactly how I had it when I created the post.  Back to your question then "Which of the loader ifs is executed in your case?".  How can I tell which is used if I'm just including ProtoBuf.js in a `<script>` tag?

**Comment by Xazzzi** [comment]
@dustycoder You have `package ForeverRPG;` defined in your `.proto` file, so, assuming you are using `-t=js` when compiling your protobuf, you should write:
```
var msg = new _root.ForeverRPG.ClientMessage();
/* Theese are wrong:
var blah = new ForeverRPG.ClientMessage();
var blah = new _root.ClientMessage();
*/
```
Also posted answer on stackoverflow.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
