### ISSUE TITLE
builder.build() returns null on staging host

### ISSUE THREAD

**Issue by SyRenity** [dcodeIO/ProtoBuf.js#321]
Encountered a strange issue, where same method working fine on development machine, returns null on the staging machine.

The version of protobuf is the same (4.0.0), the only difference is the operating system (dev - Windows, stage - Linux).

I've checked the API and it only mentions an exception, which does not happen in this case:

'''
Throws:

If a type could not be resolved

Type
    Error 
'''

Any idea?

**Comment by SyRenity** [comment]
Following more testing, the builder.files array is empty.
Does it mean no proto files have been found?

**Comment by dcodeIO** [comment]
Probably, yes. Looks like somehow the proto definitions haven't been loaded correctly.

**Comment by SyRenity** [comment]
Indeed, for some reason relative paths are not working on Linux (Ubuntu 14.04 64-bit).
