### ISSUE TITLE
Detecting message type

### ISSUE THREAD

**Issue by SyRenity** [dcodeIO/protobuf.js#324]
Is there a way to detect the incoming message type?
Or the solution is to iterate through decoders and see what manages to parse the message?

**Comment by dcodeIO** [comment]
One solution might be to define an envelope like this, holding all of the possible message types but with only one of them being set:

```protobuf
message Envelope {
  oneof message {
    optional MyMessage1 = 1;
    optional MyMessage2 = 2;
    ...
  }
}
```

After decoding, check the virtual `message` property for which inner message is actually present.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
