### ISSUE TITLE
create a protobuf-loader module for webpack

### ISSUE THREAD

**Issue by samuelmesq** [dcodeIO/ProtoBuf.js#327]
Something like:
```js
import MyPackage from './my_package.proto';
import MyMessage from './my_message.proto';
import {MyOtherMessage} from './my_package.proto';
```
as pbjs currently does, but automagically.

**Comment by watsoncj** [comment]
Have you tried this one?: https://github.com/brianchirls/proto-loader

**Comment by samuelmesq** [comment]
what I saw here, he does pretty much what we currently do, in place of **raw-loader** and `loadProto`, it uses **json-loader** and` loadJson`.

My intention was to do something that would eliminate that step.

As there is already a project called **proto-loader**, better discuss that there.

Thanks @watsoncj.
