### ISSUE TITLE
Invalid value in optional field causes exception in Protobuf.js, no exception from protoc/Java

### ISSUE THREAD

**Issue by forestjohnsonilm** [dcodeIO/protobuf.js#328]
Hello. I am storing protocol buffers in a database as a test project to learn more about them. I really like your library but I have identified a small inconsistency with protoc (2.6.1).

PLEASE NOTE: this only occurs if you are trying to do something wrong. But it is still inconsistent behavior. 

I started out with a buffer:
optional int32 id = 1;
optional string greeting = 2;

and saved the value:
{
  id: 1,
  greeting: ' :) '
}

to the database. Later on I expanded the buffer definition:
optional int32 id = 1;
optional int32 categoryId = 2;
optional string blahblahblah = 3;
etc etc.

When I read the value out of the database in java, I can call parseFrom just fine, with getcategoryId() returning 0..

After the value is returned to the client and I attempt to decode it using protobuf.js, i get an exception.

You can argue that I have violated rule # 1 of protocol buffers, don't change the tag names, or rule # 2, don't change the type of a field unless the two types can be cast back and forth. But the fact remains that I get an exception in protobuf.js, and a silent reversion to the default value from protoc. 

Do with this information what you will ;)

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
