### ISSUE TITLE
Issues with retaining default oneof values

### ISSUE THREAD

**Issue by stephenplusplus** [dcodeIO/ProtoBuf.js#329]
I'm working on implementing support for the protobuf API of Google Cloud Datastore into [gcloud-node](http://gitnpm.com/gcloud). I've hit a sticking point, and I'm not sure exactly where to look in the stack to find the problem.

I made a fork to reproduce: https://github.com/stephenplusplus/protobuf.js. I eliminated all of the tests other than mine that fails: https://github.com/stephenplusplus/ProtoBuf.js/blob/master/tests/suite.js

When I mocked the structure of the Google proto files into one test proto file, the tests passed. But when I plug in the real files, it fails.

Sorry to dump a bunch of code on you; if you think this should be asked somewhere else, feel free to close. Thanks for any help!

**Comment by pcostell** [comment]
I think this is related to a oneof inside of map values. [Here is a PR](https://github.com/pcostell/ProtoBuf.js/compare/master...pcostell:oneof?expand=1) which has a test that fails on decoding a default value inside a map but not on decoding a default value outside of a map.

**Comment by pcostell** [comment]
Ah sorry, I messed up my test, they actually pass as expected.

**Comment by dcodeIO** [comment]
Currently debugging this without success. Is there still an issue?

**Comment by stephenplusplus** [comment]
Thanks for checking it out. It's still reproducible for me, but only with my setup from the first post when loading the real proto files, no mocks.

The specific issue is any falsy values in the [`Value.value_type` oneof](https://github.com/stephenplusplus/ProtoBuf.js/blob/c88a581dee8395f68c9e0ef28bb267e0a70c29e6/googleapis/google/datastore/v1beta3/entity.proto#L109) (integer_value of 0, boolean_value of false), end up getting a `null` "value_type" when decoded: https://github.com/stephenplusplus/ProtoBuf.js/blob/c88a581dee8395f68c9e0ef28bb267e0a70c29e6/tests/suite.js#L97

**Comment by dcodeIO** [comment]
Still pinpointing. A minimal .proto causing the error seems to be:

```protobuf
syntax = "proto3";

message Entity {
    map<string, Value> properties = 3;
}

message Value {
    oneof value_type {
        // A boolean value.
        bool boolean_value = 1;
    }
}
```

With that test:
```js
        var builder = ProtoBuf.loadProtoFile("./test.proto");
        var Entity = builder.build("Entity");
        var entity = new Entity({
            properties: {
                isTrue: {
                    boolean_value: true
                },
                isFalse: {
                    boolean_value: false
                }
            }
        });
        var bb = entity.encode();
        var entity2 = Entity.decode(bb);
        test.log("isTrue");
        test.strictEqual(entity2.properties.map.isTrue.value.value_type, "boolean_value");
        test.log("isFalse");
        test.strictEqual(entity2.properties.map.isFalse.value.value_type, "boolean_value");
        test.done();
```

**Comment by dcodeIO** [comment]
Seems to be an issue with `Reflect.Message.Field#hasWirePresence`. That's contributed code, going to debug this now.

**Comment by dcodeIO** [comment]
This is what happens: When `boolean_value` is set to `false`, it is set to the default value of the field (proto3), which results in the field not being encoded on the wire.

When decoding, the message is empty on the wire, so it will decode with `boolean_value` being `false` again - but ProtoBuf.js doesn't know which field was actually set explicitly to it's default value.

Do you know how this is handled in the official implementation? Is it even possible?

**Comment by pcostell** [comment]
I believe it does encode the values. I'm not totally familiar with the implementation, but I think the relevant portion is here:
https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L656

**Comment by stephenplusplus** [comment]
Thanks very much! It works perfectly. Any chance of tagging a release soon?

**Comment by dcodeIO** [comment]
4.1.0 is now on npm
