### ISSUE TITLE
Generated JSON can't be protobuf encoded

### ISSUE THREAD

**Issue by zyklus** [dcodeIO/protobuf.js#330]
I'm trying to encode the generated JSON so that I can send it to a client and not need to include as much compilation code on the client.

So I'm happily writing a `.proto` file for the JSON and then I hit the `oneofs` and `rpc` types (and others?) which can't be encoded because they use variable field names.

From what I can tell, _everything else_ in the JSON uses structs like `{name: "...", type: "..."}` except for these two types.  Is there a reason for this?

example:

``` json
"services": [
    {
        "name": "Build",
        "options": {},
        "rpc": {
            "JavaScript": {
                "request": "CodeRequest",
                "response": "CodeResponse",
                "options": {}
            },
```

could be converted to:

``` json
...
"rpc": [{
    "name": "JavaScript",
    "request": "CodeRequest",
    "response": "CodeResponse",
    "options": {}
},
```

**Comment by dcodeIO** [comment]
There is no specific reason for this but there are other things with that format, like `options`. Might be better to have `google/protobuf/descriptor.proto` support eventually.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
