### ISSUE TITLE
Issue with raw encoding on large struct

### ISSUE THREAD

**Issue by zyklus** [dcodeIO/protobuf.js#333]
I'm wondering if you know what might be going on here.  If not, I can upload a demo app.

I have a bunch of `.proto` files that I'm trying to encode.  I can encode and decode them just fine via `base64` or `json`, but if I try "raw" encoding (via `.encode` or `.toBuffer`) it doesn't work.  The data has a bunch of "crap" at the end that isn't part of what I'm actually encoding (and of course won't decode because of this):

```sh
�$�% %0&`(�'�(�)x*���!٥�8���#	!�]bX��������������(���`l���$x� �]p����������.A@��X���]X�	 �8�������X���h��8A��R��x����@�8�8�[��@����%@P�X���& �0�h
0e�X�o�������&@�����������h
0�����
```

The first 7,748 bytes of this data are _identical_ to the base64 output (once base64 decoded).  It then has another 5,811 bytes of gibberish.

Any idea?

**Comment by dcodeIO** [comment]
Hard to tell. Could be trailing data of the encoded ByteBuffer's backing buffer or something. Could you paste the relevant part of your JS code where you are encoding the data?
