### ISSUE TITLE
How to get an enum's descriptor?

### ISSUE THREAD

**Issue by zyklus** [dcodeIO/protobuf.js#334]
Sorry to open an issue for a question, but not sure how else to ask.

How to I get an object's enum descriptor?  Other than encoding it to JSON, deserializing it and reading it?  :)

```js
> field
{ rule: null, type: 7, name: 'seconds', id: 1 }
> field.encodeJSON()
'{"rule":null,"type":"uint32","name":"seconds","id":1}'
> // I want 'uint32'
```

[edit] So I can apparently do this (dug out from the source), but I think it's _really_ ugly, especially considering that it walks an object using `Object.keys`.  Is there a better way?:

```js
function getEnumName(obj, fieldName) {
  return pbjs.Reflect.Enum.getName(obj['$' + fieldName].clazz[obj['$' + fieldName].name], obj[fieldName]);
}

getEnumName(field, 'type'); // uint32
```

**Comment by dcodeIO** [comment]
There is a runtime object (key=name, value=id) of the enum, just like there are runtime classes for messages.

**Comment by zyklus** [comment]
Okay, so that is the only way?

Unfortunately this requires knowledge of the proto structure to get the exact path to the enum, and if you ever move the enum it requires changing code.  This is a fairly major issue IMO since the code built by protoc has references via `.enum_type`.  Would it be possible to add a reference from within the object or class?

**Comment by dcodeIO** [comment]
I am not exactly sure what you are trying to do there. What's the starting point? And which object should include the reference you propose?

**Comment by zyklus** [comment]
My primary issue is that I don't want my app to need knowledge of the structure of .proto files.  These two examples produce different structures:

```proto
enum Foo {
  ... 
}

message Bar {
  foo foo = 1;
}
```
```proto
message Bar {
  foo foo = 1;

  enum Foo {
    ... 
  }
}
```

with `protoc` generated files, there's a reference to the enum from within the class, so both of the above work with the same code.

**Comment by vans163** [comment]
I have the same issue. The problem is this:

fruit_enum = builder.lookup("fruittype_Enum")
myCurrentFruit = fruit_enum.ORANGE

Essentially we both want to do this in a clean way.
myCurrentFruit = fruit_enum.ORANGEE 
Should throw a JS error.

Currently reading docs the only way to do this is:

myCurrentFruit = fruit_enum["ORANGE"]
Which defeats the purpose as the whole idea with static type is to eliminate this:
myCurrentFruit = fruit_enum["ORANGEE"]  (oops I wrote an extra E, now I need to spend 10 hours finding why its not working)

**Comment by dcodeIO** [comment]
`builder.lookup("fruittype_Enum")` should actually return a `ProtoBuf.Reflect.Enum` as lookup is used with reflection.

Runtime enums on the other hand are just plain JS objects and as such behave like them. You can obtain the runtime object from a Reflect.Enum through its `.object` property.

@zyklus Regarding `field.$type._fieldsByName['field'].resolvedType.object`, this looks a bit strange to me. If you have a `Reflect.Message` in `message`, you could do:

```protobuf
message Bar {
  foo foo = 1;
  enum Foo {
    ... 
  }
}
```
```js
var message = builder.lookup("Bar"); // here: instanceof Reflect.Message
var field = message.getChild("foo"); // here: instanceof Reflect.Message.Field
var fieldType = field.resolvedType; // here: instanceof Reflect.Enum
var runtimeEnumObject = fieldType.object;
```
Alternatively you could also query all fields and iterate:
```js
var fields = message.getChildren(ProtoBuf.Reflect.Message.Field);
...
```

**Comment by vans163** [comment]
Thank you. I think it should be a documented example. very important feature for many.

**Comment by vans163** [comment]
I cannot get it to work

    ProtoBuf = dcodeIO.ProtoBuf;
    builder = ProtoBuf.loadProtoFile("include/proto/main.proto");

    fruit_E = builder.lookup("fruit_E").resolvedType;

    console.log(fruit_E); 
    //undefined
