### ISSUE TITLE
How to use pbjs

### ISSUE THREAD

**Issue by saste** [dcodeIO/ProtoBuf.js#335]
Sorry for the silly question.

I want to use pbjs to generate JS files to use in place of creating a corresponding builder from the proto file with `.protoFromFile()`.

When I use a proto file I usually do:
```javascript
var builder = dcodeIO.ProtoBuf.protoFromFile("PingPong.proto"); // Load .proto file
var foobar = builder.build("foobar"),
```

and now I can use the `foobar.PingPong` object defined the `PingPong.proto` (supposing `PingPong` is a message defined in the foobar package).

Now I generate a JS file with pbjs:
    nodejs pbjs PingPong.proto -t js  > PingPong.js

Seeing that the PingPong.js is something like:
```javascript
var _root = dcodeIO.ProtoBuf.newBuilder({})['import']({
    "package": "foobar",
    "messages": [
...
    ]
}).build();
```
it is not obviously clear how I should use the generated file.

Can you provide some explanations? Thanks.

**Comment by dcodeIO** [comment]
What pbjs basically does is to turn a .proto into its json counterpart, and in case of `-t js|commonjs|amd` makes these loadable right away. For `-t js` for example, you can simply include the generated file in a ´<script src="...">`.

**Comment by saste** [comment]
I thought that the default `_root` export var had some magic into it, indeed what I was missing was the `--export` command. Thanks.
