### ISSUE TITLE
extensions on multilpe messages yield unloadable files

### ISSUE THREAD

**Issue by zyklus** [dcodeIO/protobuf.js#336]
``` proto
message A {
}

message B {
}

extend A {
}

extend B {
}
```

yields two blocks for the extensions:

``` json
{
  "name": "",
  "ref": "A",
  ...
}, {
  "name": "",
  "ref": "B",
  ...
}
```

which means the file is unloadable: `Error: Duplicate name in namespace Namespace :`

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
