### ISSUE TITLE
Errors deserializing proto with large number of items in repeated field

### ISSUE THREAD

**Issue by terranmoccasin** [dcodeIO/protobuf.js#342]
Hello there. First off, I'd like to thank you for creating all of these awesome libraries!

I'm running into a strange problem where I am getting an error on [line 3542 of ByteBufferAB.js](https://github.com/dcodeIO/ByteBuffer.js/blob/master/dist/ByteBufferAB.js#L3542) when deserializing a proto that has a large number items in a repeated field.

Here are my protos:

```proto
message LibraryDto {
  optional string id = 1;
  optional string ownerUsername = 2;
  optional int64 createdTimeMillis = 3;
  optional int64 lastModifiedTimeMillis = 4;
  repeated LibraryTrackRefDto trackRefs = 5;
}

message LibraryTrackRefDto {
  optional string id = 1;
  optional SourceType sourceType = 2;
  optional string name = 3;
}

enum SourceType {
  TEST = 0;
}
```

My backend gives my JS client a LibraryDto, which is fetched using [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) and [es6-promise](https://www.npmjs.com/package/es6-promise). Here is the gist of how I'm doing the decoding:

```javascript
return fetch({
  // some_fetch_params...
}).then(response => {
  if (response.ok) {
    return response.body.getReader().read();
  } else {
    console.log('bad get proto');
  }
}).then(buffer => {
  return buffer.value;
}).then(bytes => {
  return ens.LibraryDto.decode(bytes)
}).catch(err => {
  console.log(err);
});
```

In my specific case, when I pass ~200 items in the trackRefs field within LibraryDto, things start to get dicey. Anything under 100 seems to work perfectly all the time. Other quantities have inconsistent behavior. When things break, I get this error on the line linked above in ByteBufferAB.js:

```
Uncaught (in promise) TypeError: undefined is not a function(…)
utfx.UTF8toUTF16 @ ByteBufferAB.js:3542
(anonymous function) @ ByteBufferAB.js:3575
utfx.decodeUTF8 @ ByteBufferAB.js:3492
utfx.decodeUTF8toUTF16 @ ByteBufferAB.js:3574
ByteBufferPrototype.readVString @ ByteBufferAB.js:2281
ProtoBuf.Reflect.ElementPrototype.decode @ ProtoBuf.js:2137
ProtoBuf.Reflect.FieldPrototype.decode @ ProtoBuf.js:3689
ProtoBuf.Reflect.MessagePrototype.decode @ ProtoBuf.js:3201
ProtoBuf.Reflect.ElementPrototype.decode @ ProtoBuf.js:2153
ProtoBuf.Reflect.FieldPrototype.decode @ ProtoBuf.js:3689
ProtoBuf.Reflect.MessagePrototype.decode @ ProtoBuf.js:3196
Message.decode @ ProtoBuf.js:2896(anonymous function) @ LibraryService.js:35
```

If I remove the sourceType and name fields from LibraryTrackRefDto, I get no serialization problems no matter what the array size is.

Do you have any insights on what could be going on? Please let me know if I can provide more information or help debug in any way. I'm pretty invested in using ProtoBuf.js in my project and really want to make things work!

Possibly useful facts:
- Some of the LibraryTrackRefDto names have non-ASCII characters (Chinese, Korean, etc).
- My backend is written in Java and uses [dropwizard-protobuf](https://github.com/dropwizard/dropwizard-protobuf)

Thanks!

**Comment by dcodeIO** [comment]
Followed the stacktrace until here: https://github.com/dcodeIO/ByteBuffer.js/blob/master/src/types/strings/vstring.js#L80

This uses `offset`, which isn't asserted (probably should be), to read all the bytes of a varint-prefixed string. Hence, if offset becomes larger than the maximum capacity of the buffer that is decoded, the anonymous function returns ´undefined`, resulting in your provided exception somewhere down the road.

Thus, the underlying issue might be that the buffer you are decoding is somehow truncated in the middle of a string value. You should be able to debug that by wrapping your buffer in a ByteBuffer (if it isn't already), printing out the last couple of bytes, like so:

```js
var buffer = someArrayOrNodeBuffer;
var bytesToInspect = 100;
var bb = ByteBuffer.wrap(buffer);
bb.slice(bb.limit - bytesToInspect, bb.limit).compact().printDebug();
```

Right before the string there should be a varint indicating its length in bytes. Please let me know if my assumptions are correct as that would make things a lot easier here. This might of course still be a bug produced by either of the libraries involved.

**Comment by dcodeIO** [comment]
[This commit](https://github.com/dcodeIO/ByteBuffer.js/commit/64f0e87fb55f36c0ea4c692045e9d17a11d5dd1e) to ByteBuffer should at least take care of proper assertion.

**Comment by terranmoccasin** [comment]
Thanks for the prompt response! I'm going to have no internet for a couple of days (traveling), but will look into your suggestions and comment after I've tried debugging some more.

**Comment by terranmoccasin** [comment]
Seems like your suspicious are correct. Here are some examples of the debug dumps:

**Message with only one item in the repeated field:**
```
bb.compact().printDebug()
bytebuffer.js:2700 ByteBufferAB(offset=0,markedOffset=-1,limit=71,capacity=71)
-------------------------------------------------------------------
<0A 45 0A 18 35 36 33 38 30 32 34 32 32 64 66 61   .E..563802422dfa
 39 38 30 36 64 32 66 30 30 39 37 37 10 00 1A 27   9806d2f00977...'
 43 68 69 6C 64 69 73 68 20 47 61 6D 62 69 6E 6F   Childish.Gambino
 20 2D 20 46 72 65 61 6B 73 20 61 6E 64 20 47 65   .-.Freaks.and.Ge
 65 6B 73 2E 6D 70 33>                             eks.mp3
```

**Message with two items in the repeated field:**
```
bb.compact().printDebug()
bytebuffer.js:2700 ByteBufferAB(offset=0,markedOffset=-1,limit=116,capacity=116)
-------------------------------------------------------------------
<0A 45 0A 18 35 36 33 38 30 33 34 32 32 64 66 61   .E..563803422dfa
 39 38 30 36 64 32 66 30 30 62 62 34 10 00 1A 27   9806d2f00bb4...'
 43 68 69 6C 64 69 73 68 20 47 61 6D 62 69 6E 6F   Childish.Gambino
 20 2D 20 46 72 65 61 6B 73 20 61 6E 64 20 47 65   .-.Freaks.and.Ge
 65 6B 73 2E 6D 70 33 0A 2B 0A 18 35 36 33 38 30   eks.mp3.+..56380
 33 34 32 32 64 66 61 39 38 30 36 64 32 66 30 30   3422dfa9806d2f00
 62 62 35 10 00 1A 0D 31 31 2E 20 47 6F 20 44 4A   bb5....11..Go.DJ
 2E 6D 70 33>                                      .mp3
```

**Message with lots of items in the repeated field (last 100 bytes):**
```
bb.slice(bb.limit - 100, bb.limit).compact().printDebug()
bytebuffer.js:2700 ByteBufferAB(offset=0,markedOffset=-1,limit=100,capacity=100)
-------------------------------------------------------------------
<72 65 61 6C 2E 6D 70 33 0A 40 0A 18 35 36 33 38   real.mp3.@..5638
 30 32 36 65 32 64 66 61 39 38 30 36 64 32 66 30   026e2dfa9806d2f0
 30 62 35 30 10 00 1A 22 31 2D 30 32 20 EC A7 A7   0b50..."1-02....
 EC 9D 80 20 EC B9 98 EB A7 88 20 28 4D 69 6E 69   ...........(Mini
 73 6B 69 72 74 29 2E 6D 70 33 0A 2E 0A 18 35 36   skirt).mp3....56
 33 38 30 32 36 65 32 64 66 61 39 38 30 36 64 32   38026e2dfa9806d2
 66 30 30 62>                                      f00b
```

Doesn't look like things end on what appears to be the "name" field in the last example, which seems to indicate that some kind of truncating is happening!

**Comment by terranmoccasin** [comment]
Just pinging this thread to see what's going on and/or how I can help - I'm not certain how to proceed from here.

Does it seem like this is a deserialization problem somewhere in ByteBuffer.js or Protobuf.js that's truncating the values?

**Comment by dcodeIO** [comment]
Have you checked the buffers that you received prior to decoding? I'd guess that these are already truncated.

**Comment by terranmoccasin** [comment]
Yes - just figured out the problem!

It was a small error on my part.
Instead of using a buffered reader as in my first post, I should have just done this:
```javascript
return fetch({
  // some_fetch_params...
}).then(response => {
  if (response.ok) {
    return response.arrayBuffer();
  } else {
    console.log('bad get proto');
  }
}).then(bytes => {
  return ens.LibraryDto.decode(bytes)
}).catch(err => {
  console.log(err);
});
```

The byte stream reader was truncating the bytes by preset chunks, and once the size of my proto grew past a certain length it would fail.

Thanks for all of the help!
