### ISSUE TITLE
Incompatible values for optional fields when no default value is defined

### ISSUE THREAD

**Issue by aliok** [dcodeIO/protobuf.js#343]
```
message Msg{
    optional int32 foo = 1;
    optional int32 bar = 2 [default=23];
}
```

In Google's official Protobuf Java/C client when no values are set for those fields, here are the values:

```
msg.getFoo() ==> 0
msg.getBar() ==> 23
```

In Protobuf.js:

```
msg.getFoo() ==> null
msg.getBar() ==> 23
```

From https://developers.google.com/protocol-buffers/docs/proto?hl=en#optional

> If the default value is not specified for an optional element, a type-specific default value is used instead: for strings, the default value is the empty string. For bools, the default value is false. For numeric types, the default value is zero. For enums, the default value is the first value listed in the enum's type definition.

Similar logic is mentioned in [Proto3 documentation](https://developers.google.com/protocol-buffers/docs/proto3#default) as well.

In Protobuf.js this is not the case. Of course, one can argue that the values defined above are dependent on the programming language.

I am not saying that this is a bug, it is more like a feature (I enjoyed checking if field is set by by simply checking `msg.getFoo()===null`; equivalent to Java call `msg.hasFoo()` ).

I just want to make sure this is well thought. If that is the case, let's add some documentation about that in the wiki (I can send a pull request).

**Comment by mhahn** [comment]
this is more of a bug when dealing with enums in proto3. if the value of the enum is the default, then its as if the value wasn't set. this library returns `null` if the default value is used though.

**Comment by marcboeker** [comment]
I've encountered the same. Is there any plan to set the enum's value to its default value instead of null? This would make working with the data much more easier. Thanks!

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
