### ISSUE TITLE
Best way to get string representation of enum value?

### ISSUE THREAD

**Issue by terranmoccasin** [dcodeIO/protobuf.js#349]
After decoding the byte buffer into a proto, my enum values are being returned (correctly) as integers. I'd like to convert them into their name if possible.

For example, I have a sourceType enum:

``` proto
enum SourceType {
  TestSource = 0;
}
```

``` javascript
var foo = proto.decode(bytes);
// foo.sourceType => 0
```

What's the best way to convert this integer into the enum value of SourceType?

**Comment by dcodeIO** [comment]
You can get the runtime enum, which is a plain object, just like you'd get messages:

```js
var SourceType = builder.build("SourceType");
// { TestSource: 0 }
```

Afterwards, you can use that to look up the enum name from a value manually, or simply use a reflection helper:

```js
...
var sourceTypeName = ProtoBuf.Reflect.Enum.getName(SourceType, foo.sourceType);
// "TestSource"
```

**Comment by tobilg** [comment]
@dcodeIO: I tried this, but for nested messages I see the effect that once I use the object defined as above, it falls back to the "integer behavior", even if I set the enum name manually.

I also asked a [StackOverflow question](http://stackoverflow.com/questions/37687316/how-to-get-protobuf-js-to-output-enum-strings-instead-of-integers).

I'm working with the [mesos.proto](https://github.com/apache/mesos/blob/1fbc69fbac123e6e844ececf949a8e46da0dde91/include/mesos/v1/mesos.proto) which is rather large.

**Comment by michaelhogg** [comment]
[`ProtoBuf.Builder.Message.toRaw()`](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L540) seems to work.

It calls [`cloneRaw()`](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L486) which ["converts enum values to their respective names"](https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L488-L493).

@terranmoccasin: You should find this works:
```js
var foo = proto.decode(bytes);
// foo.sourceType => 0

foo = proto.decode(bytes).toRaw();
// foo.sourceType => "TestSource"
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by MaheshSasidharan** [comment]
I was able to convert then using decode options as following:

```
var fooDecoded = proto.decode(bytes);
var foo = proto.toObject(fooDecoded, {
            enums: String,
            longs: String,
            arrays: true,
            objects: true
        });
```
