### ISSUE TITLE
Serializing protobufs to json

### ISSUE THREAD

**Issue by mhahn** [dcodeIO/protobuf.js#351]
with proto3, protocol buffers now have a standard json format, is there a way to leverage this with this library?

my use case is caching protocol buffers in local storage. currently i've been base64 encoding the messages before storing them. this becomes more complex with the `Map` type.

**Comment by dcodeIO** [comment]
Have you tried [Message#encodeJSON](https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Builder/Message.js#L548)?

**Comment by lanttu** [comment]
The method doesn't seem to use canonical proto3 JSON encoding as specfied in here: https://developers.google.com/protocol-buffers/docs/proto3?hl=en#json

**Comment by joeblew99** [comment]
Did you sort out if Google's support for json, makes bufferjs redundant ?

I suspect that bufferjs allows marshalling between json and PB client side, and grpc allows marshalling between the two server side at the facade.

I would like to know what the answer to this is from an architectural perspective.

**Comment by leeyeh** [comment]
+1.

My use case is to encode to and decode from the canonical formatted JSON data, since React Native's js-native bright is text-based.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by aidansteele** [comment]
@dcodeIO Sorry, it's not clear to me - is the issue closed because any changes discussed here are no longer relevant (due to rewrite) or because protobuf.js 6.x now supports the functionality?

**Comment by dcodeIO** [comment]
> or because protobuf.js 6.x now supports the functionality

Not quite, but the default toJSON imlpementation of message instances should be close.

```js
someMessage.toJSON();
// or
SomeMessage.toObject(someMessage, util.toJSONOptions);
```

Not yet supported:
* "NaN", "Infinity" strings for floats
* Any, Timestamp, Duration, Struct, Wrappers, FieldMask, ListValue, Value, NullValue are handled like messages

Feel free to reopen!

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/protobuf.js/issues/677
