### ISSUE TITLE
Protobufjs doesn't convert longs to int

### ISSUE THREAD

**Issue by novellizator** [dcodeIO/protobuf.js#354]
Not sure if bug or a feature, but when the server sends me object with {low:<num>, hight:<num>, unsigned:<bool>} I receive just the same way. Should it rather natively transofrm the thing into long int?

**Comment by dcodeIO** [comment]
Please see:
https://github.com/dcodeIO/ProtoBuf.js/wiki/Long
https://github.com/dcodeIO/long.js

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
