### ISSUE TITLE
encoding a modified decoded protobuf messsage fails.

### ISSUE THREAD

**Issue by mrafsan** [dcodeIO/protobuf.js#356]
I keep encountering this : 
 node: ../src/node_buffer.cc:115: size_t node::Buffer::Length(v8::Handle<v8::Object>): Assertion `obj->HasIndexedPropertiesInExternalArrayData()' failed.
Aborted (core dumped)

When I am using it like this :
var decoded = ProtoBuf.Instruction.decode(in_request.instructions[i]); 
decoded.set_effect(ProtoEffectType.AUTO);
decoded.toArrayBuffer(); // fails with that error above.

**Comment by dcodeIO** [comment]
Looks like .toArrayBuffer is somehow broken on your version of node (probably memcpy as used by ByteBuffer doesn't work with it). What version of ProtoBuf.js are you using?

Meanwhile, try to get a Buffer instead, and convert it to an ArrayBuffer in a way suitable for your version of node...

```js
var buffer = decoded.toBuffer();
var arrayBuffer = convertToArrayBuffer(buffer);
```

...or maybe delete the memcpy dependency at `node_modules/protobufjs/node_modules/bytebuffer/node_modules/memcpy`

**Comment by mrafsan** [comment]
It looks like that the encode is broken in my configuration : nove 0.12.0 and Protobuf.js 3.2.2.
An upgrade to node 0.12.7 seems to have fixed it. 
This issue can be closed.

Thanks!
