### ISSUE TITLE
failing to parse valid 'extensions' syntax

### ISSUE THREAD

**Issue by zzo** [dcodeIO/protobuf.js#357]
This is valid proto2 extensions syntax:

```
extensions 5, 22
```

But protobufjs doesn't like it (error messages says ',' must be 'to').  This syntax is the same as the 'reserved' keyword.

**Comment by dcodeIO** [comment]
It's implemented just as mentioned here: https://developers.google.com/protocol-buffers/docs/proto#extensions

Do you have a link to a resource stating that the comma-syntax is valid, too? Or can anyone else confirm? (Sorry, I don't have an instance of the official implementation atm)

**Comment by zzo** [comment]
Well the documentation for 'reserved' is here:
https://developers.google.com/protocol-buffers/docs/proto?hl=en#reserved

The official Google protobuf compiler https://github.com/google/protobuf parses that syntax correctly.

**Comment by zzo** [comment]
See here: https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/parser.cc#L1421

**Comment by dcodeIO** [comment]
Thank you for the clarification, I'll see what I can do!

**Comment by dcodeIO** [comment]
That should fix it. The internal reflection structure has changed to an array of ranges instead of a single range, and a fallback has been applied to continue supporting descriptors prior to this patch.

Please let me know if you see any issues.

**Comment by zzo** [comment]
spectacular thanks - that's quite a mongo diff!
Any thoughts when this will get pushed to npm?

**Comment by zzo** [comment]
To close the loop on this:
https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#extensions

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
