### ISSUE TITLE
new Message(object) doesn't work

### ISSUE THREAD

**Issue by cauil** [dcodeIO/protobuf.js#361]
proto:

    message IMPacket{                                       
      required IMPacketHeader header = 1;                   
      required bytes content = 2;                           
    }

    message IMPacketHeader{                                 
      required uint64 routeid= 1 [default = 0];             
      optional bool encryption = 2 [default = false];       
      optional bool compression = 3 [default = false];      
      required bytes encoding = 4 [default = "protobuf"];   
    }

code:

        var imPacketHeaderMsg = {routeid: 7, encryption: false, compression: false, encoding: "protobuf"};
        var imPacketMsg = {header: imPacketHeaderMsg, content: "hello"};

        var _Msg = Builder.build("IMPacket");
        var msg4 = new _Msg(imPacketMsg);
        var msg4 = msg4.encode();
        console.log("msg4.toArraybuff()")
        console.log(msg4.toArrayBuffer());

when do "var msg4 = new _Msg(imPacketMsg);" get "Illegal str: Length not a multiple of 4");"

I can see it was in ByteBuffer.fromBase64() throw typeError.

 Is the new Message() can't use the object? Can someone help me?

**Comment by cauil** [comment]
i use it just from https://github.com/dcodeIO/ProtoBuf.js/wiki/Builder  the  car example.

**Comment by dcodeIO** [comment]
This is from using `bytes` instead of `string`. In this case, protobuf.js expects a base64 encoded string when constructing from plain objects.

**Comment by cauil** [comment]
I think i get the point from #99 . Thank u very much. 谢谢！
