### ISSUE TITLE
Question - how can i get  back the uint64 number?

### ISSUE THREAD

**Issue by cauil** [dcodeIO/protobuf.js#362]
hi @dcodeIO 

I get the bytebuffer from the server, and decode it, there is a field-appid is defined by uint64 type, but i can't get the raw number. 

proto: 

    message IMDataHeader{           
      required uint32 ptype = 1;    
      required uint32 btype = 2;    
      required string sid = 3;      
      required uint64 uid = 4;      
      optional uint32 dtype = 5;    
      optional uint64 appid = 6;    
    }

the decode appid i got was msg = {high: 0, low: 7, unsigned: true}.

then i use the Long.toNumber(msg) or toString() or toInt() the result is 0; 

but the appid is 7 from server;

what is wrong?

**Comment by cauil** [comment]
i get it.  Maybe the data can't pass to param. Just the data is a Long object. Just call it's method.

Can't use:
    
    var _long = new Long();
    msg = _long.toNumber(msg);

use:
    msg.toNumber()

**Comment by dcodeIO** [comment]
Just remember that a number cannot reliably store 64 bits of information. That's why there is a Long object in the first place. See: https://github.com/dcodeIO/long.js
