### ISSUE TITLE
protobuf.js for chrome app

### ISSUE THREAD

**Issue by neuraltoys** [dcodeIO/protobuf.js#363]
Hello,
I am implementing a chrome app that uses protobuf.js for data transfer and I have two questions:
- I need to load .proto files asynchronously because chrome apps do not allow for synchronous calls. I've managed to do this so far for one file but how do I load multiple files (into the same builder)? if that's not possible, what is the solution here?
- how do I load and use an enum definition? I have an enum that specifies the message type and I want to use the predefined int values when creating a new message, so I don't have to hard-code the int values.

thank you

**Comment by dcodeIO** [comment]
Ideal way is to bundle all your .proto files using the pbjs command line utility. See: https://github.com/dcodeIO/ProtoBuf.js/wiki/pbjs

Regarding enums: https://github.com/dcodeIO/protobuf.js/issues/349

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
