### ISSUE TITLE
Does it work with Node 4.2.2?

### ISSUE THREAD

**Issue by robertcasanova** [dcodeIO/protobuf.js#364]
I'm having compiling errors trying to install this module on Node 4.2.2 with NPM 3.4.1 on Mac Osx. Does anybody using it with new version of Node?

**Comment by rektide** [comment]
v5.0.0 linux amd64, behaving normally for me. Not a maintainer, but can you post more info on the errors you are seeing, perhaps we can help debug?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
