### ISSUE TITLE
Error on reading repeated primitives when decoding bytes message

### ISSUE THREAD

**Issue by markaren** [dcodeIO/protobuf.js#366]
I have a proto definitition which looks like 

```
syntax = "proto3";

message VP {

        enum MessageType {
            CORE = 0;
            PLOT = 1;
            KINE = 2;

        }

        MessageType messageType = 1;
        bytes message = 2;

    }
```

This allows me to choose the appropriate decoder by looking at the messageType, and worked until I had a repeated float or double field in one of the messages.

The error I get is some variant of: Illegal wire type for field Message.Field 

I guess the bytes gets corrupted somehow, but I'm at a loss on how to fix it.

I'm using WebSockets with "arraybuffer" set. The messages are encoded and sent from Java.

**Comment by markaren** [comment]
Seems that I get the same result when encoding both the initial proto file and the message field  as base64 string

**Comment by markaren** [comment]
Setting [packed=false] on the repeated field in question seems to resolve the issue.
Bug?

**Comment by dcodeIO** [comment]
Depends on what is set on the Java side. `packed` is encoded differently, and both sides need to use the same format.
