### ISSUE TITLE
Unable to deserialize message buffer

### ISSUE THREAD

**Issue by arpanmukherjee1** [dcodeIO/protobuf.js#367]
@dcodeIO 

Below is the `.proto` file and the data file attached.

```
message GenericTable {
  required Header header = 1;  
  optional Table data = 2;
  optional bytes compresseddata = 3;
  message Header{
            required double version=1;
            required bool iscompressed=2;
            required string schema=3;
            required string exception=4;
  }

  message Table{
            repeated Row rows=1;
  }

  message Row{
            repeated Cell cells=1;
  }

  message  Cell{
            optional string primitiveString=1;
            optional int64  primitiveLong=2;
            optional int32 primitiveInt=3;
            optional double primitiveDouble=4;
            optional bool primitiveBool=5;
            optional int64 primitiveDate=6;
            optional Row complexValue=7;
            optional Table listValue=8;
  }

}
```

[data.txt](https://github.com/dcodeIO/protobuf.js/files/47304/data.txt)
The hex data is not encoded by protobuf.js but given by an external service.

We are not able to de-serialize the proto binary data (attached).

The error message we are getting when running the decode is following:
_[Error: Illegal wire type for field Message.Field .GenericTable.Cell.primitiveString: 6 (2 expected)]_

**Comment by arpanmukherjee1** [comment]
Request you to provide a workaround for this issue. Thanks

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
