### ISSUE TITLE
Accessors usage in your implementation

### ISSUE THREAD

**Issue by Braingines** [dcodeIO/protobuf.js#373]
It seems that starting from this topic

https://github.com/dcodeIO/ProtoBuf.js/issues/179

Nothing is changed with accessors, right? 

The AoJ and dougrad users clearly said that current accessors implementation is just wrong and violates the ProtoBuf specification in case of setting default values for primitive fields and representing empty optional or repeated primitive fields as their defaults.

So the only motivation to use your current implementation is in not transfering the data scheme with every message, that's it. 

And, at the same time, the main reason why the ProtoBuf was just created (that is the proper way of accessors usage that leads to reducing dramatically the whole data parsing time) is still ignored.

Do you plan to fix this "JS feature" somehow? Do you have any proposals how to fix it or still not? If not, I want to propose you to implement "has" accessor and to fix other accessors in the way they implemented in C++ / Java.

[UPD]:

https://github.com/dcodeIO/protobuf.js/issues/200#issuecomment-98153230

This topic seems to me as a solution to decode message and get non-empty optional and repeated fields

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
