### ISSUE TITLE
Do not publish or remove gtfs-realtime.proto

### ISSUE THREAD

**Issue by superkhau** [dcodeIO/protobuf.js#379]
https://github.com/dcodeIO/protobuf.js/blob/master/tests/gtfs-realtime.proto has the Creative Commons copyright embedded and it's not acceptable use within our organization.

Is possible to not publish or remove the file since it is only used for testing?

**Comment by dcodeIO** [comment]
Well, technically you are not touching / including this file at all. It's there for a test case only and does not provide anything else to the library.

**Comment by superkhau** [comment]
From a legal perspective, we cannot include protobuf.js because of the licensing. However if this file is not included with the repo, then we can use the package. This is why I was asking if it was possible to remove or unpublish that particular file.

**Comment by superkhau** [comment]
@dcodeIO Basically, the Creative Common license in gtfs-realtime.proto is not compatible the Apache license. I've submitted a [PR](https://github.com/dcodeIO/protobuf.js/pull/381) that excludes the tests dir from the published project, which would allow third party vendors to use this project without violating license terms.

**Comment by superkhau** [comment]
@dcodeIO Ping.

Can you please publish the latest version so I can get your changes on NPM?

**Comment by dcodeIO** [comment]
Is published now as 5.0.1

**Comment by superkhau** [comment]
@dcodeIO Thanks! :smile:

**Comment by superkhau** [comment]
@dcodeIO Can you push your git tags? I don't see it at https://github.com/dcodeIO/protobuf.js/releases

**Comment by dcodeIO** [comment]
Thanks for the reminder, pushed now
