### ISSUE TITLE
options parser exception parsing multiple options in same code block

### ISSUE THREAD

**Issue by grier** [dcodeIO/protobuf.js#383]
A proto file with options like:

```
option (toplevel_3.options) = {
  opt1: true,
  opt2: "Support multiple options in the same block"
};
```

Causes exceptions when parsing: 

```
 Parse error at line 5: illegal option name: (toplevel_3.options).,
    Error: Parse error at line 5: illegal option name: (toplevel_3.options).,
```

**Comment by mikhailmikhaylov** [comment]
Is there any chance that this will be resolved soon?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
