### ISSUE TITLE
Negative int32 is decoded as positive number

### ISSUE THREAD

**Issue by naksu** [dcodeIO/protobuf.js#386]
Negative int32 is decoded as positive number.

It seems that the most significant bit is not treated to mean negative. For example, for -1718021840 (encoded by Java) is decoded into 2576945456. Both are 0x99991130 when treated as unsigned int32.

**Comment by naksu** [comment]
Sorry, its actually fixed32 that I'm using. By looking at the language guide, unsigned is the correct behavior for fixed32.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
