### ISSUE TITLE
error occurs with loadProtoFile when ajax status 304

### ISSUE THREAD

**Issue by Jerret321** [dcodeIO/protobuf.js#387]
When I use `loadProtoFile` from 304 cache, builder can not  compile successfully.

When I use `loadJsonFile`, everything is ok. 

But I think this is a bugs.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
