### ISSUE TITLE
Trying collecting data using protobuf. How about browser support ?

### ISSUE THREAD

**Issue by coderfamily** [dcodeIO/protobuf.js#388]
I'm trying collecting data using protobuf for all platform including browser. 
It seems that IE 10+ is needed because xhr2 and typed array.
Is there any solution for this ?

**Comment by wwwsevolod** [comment]
You can encode all of your protobuf bytes into base64, for example

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
