### ISSUE TITLE
repeated int32 not parsing properly

### ISSUE THREAD

**Issue by jhspaybar** [dcodeIO/protobuf.js#390]
The entire context can be seen here https://github.com/grpc/grpc/issues/5174 . @dsymonds from Google says he's going to work on fixing the documentation to make the expected behavior more explicit, but that a repeated int32 field without packed=true specified should still be able to parse as if packed=true were set.

**Comment by murgatroid99** [comment]
From the comments on that issue, it also looks like repeated fields should serialize with packed=true by default when using proto3 semantics.

**Comment by waltsc** [comment]
i just ran into this too, for proto3 it looks like packed=true is the default, and this code needs to be fixed. as a temporary workaround you can just specify packed=true or packed=false on all your repeated primitive fields.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
