### ISSUE TITLE
Typescript code generation

### ISSUE THREAD

**Issue by aliok** [dcodeIO/protobuf.js#391]
It would be really nice to have Typescript code generation out of the box with _pbjs_ tool.

There might be 2 different approaches:
1. Generating TS classes
   - This is pretty much like official Protobufs client generating Java code
2. Generating JS code and TS type definitions
   - _pbjs_ creates JS code (already there) and `.d.ts` files

Number#2 is currently achievable BTW, using multiple tools like this:
- _pbjs_ creates JS code
- _pbjs_ creates JSON definitions
- [_proto2typescript_](https://github.com/SINTEF-9012/Proto2TypeScript) creates `.d.ts` files using those JSON definitions

I had to [modify](https://github.com/aliok/Proto2TypeScript) _proto2typescript_ to make it working BTW.

Related issues : 
- https://github.com/dcodeIO/protobuf.js/issues/196
- https://github.com/dcodeIO/ProtoBuf.js/issues/188

**Comment by DouglasHeriot** [comment]
I would also find this useful. I’m currently down option number 2, and have had to spend time making proto2typescript work how I need it.

**Comment by kalbasit** [comment]
@dcodeIO is this something that you would consider? I think I might be able to contribute a PR as I need it myself as well.

**Comment by paralin** [comment]
I've written something like this already, could possibly wrap it up into the CLI and release it.

**Comment by aliok** [comment]
@dcodeIO any comments?

**Comment by jwueller** [comment]
It would be great to have first-party support for this due to external tools always being slightly out of sync with development.

**Comment by dcodeIO** [comment]
See also: https://github.com/dcodeIO/protobuf.js/issues/485

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
