### ISSUE TITLE
how the protobuf data types  map to the JS  data types

### ISSUE THREAD

**Issue by harter123** [dcodeIO/protobuf.js#392]
["bool","double","float","int32","string","bytes","uint32","int64","uint64","sint32","sint64","fixed32","fixed64","sfixed32","sfixed64"]  these are protobuf base data types, if i want to build  a  probobuf  object of  nodejs ,  how to transform  the  data types. Which data types of  nodejs  should  use   when  dealing with different data types of protobuf.  is anyone can help me?

**Comment by dcodeIO** [comment]
* bool = boolean
* double, float, int32, uint32, sint32, fixed32, sfixed32 = Number
* string = String
* bytes =  [ByteBuffer](https://github.com/dcodeIO/bytebuffer.js) (wraps a node Buffer under node.js and an ArrayBuffer in the browser)
* int64, sint64, fixed64, sfixed64 = [Long](https://github.com/dcodeIO/long.js) (wraps two 32 bit integers)
