### ISSUE TITLE
Referring to options

### ISSUE THREAD

**Issue by mhahn** [dcodeIO/protobuf.js#393]
From the tests, you refer to options explicitly with their strings: https://github.com/dcodeIO/protobuf.js/blob/7df5707614f7739d0a90e4eaa9926c6c6729d8e7/tests/suite.js#L609.

is there a way to get this from the protobuf object itself?

ie if i have:

```
syntax = "proto3";
package services.options;
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
    bool inflation = 50000;
}
```

and compile js protobufs with:
`pbjs src/protobufs/services/options.proto --path=src --target=commonjs --min > js/index.js`

if i use that option on the field, i see it listed as `{ '(services.options.inflation)': true }`, which is awesome. i wanted to see if there was a way to get the `"(services.options.inflation)"` from the object though or do i just need to setup a constant when i want to refer to it?

**Comment by dcodeIO** [comment]
While you can load google/protobuf/descriptor.proto, protobuf.js does not use it. Hence, in your example, you are extending the plain "google.protobuf.FieldOptions" message that is defined in descriptor.proto with an additional field, but this has no effect on any other message.

You can, of course, look up "google.protobuf.FieldOptions" via reflection afterwards (Builder#lookup) and iterate over its fields. Also, there is a hidden property named `$options` on message classes and instances, see: https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Builder/Message.js#L714

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
