### ISSUE TITLE
Builder.isEnum() not work

### ISSUE THREAD

**Issue by kelvinh** [dcodeIO/protobuf.js#394]
Hi,

Thanks for this awesome library, when I was using reflection, the static function `Builder.isEnum()` seems do not work as expected, proto content:

```
enum MessageId {
    HeartbeatReq = 1;
}
```

javascript content:

```
var protobuf = require('protobufjs');
var proto = protobuf.loadProtoFile('test.proto');
var root = proto.build();
var aEnum = protobuf.Builder.isEnum(root.MessageId); // produces false here
```

In my opinion, the `aEnum` should be `true` here, am I doing something wrong, or is it a bug? The protobuf.js version I am using is **5.0.1**, and the content of `root` is:

```
{ MessageId: { HeartbeatReq: 1 } }
```

I read the source code of `Builder.isEnum()`, and found it checks "name" and "value" fields of the parameter, I don't know why, but to help you debug, I checked `root.MessageId["name"]` and `root.MessageId["value"]`, they were both `undefined`.

**Comment by dcodeIO** [comment]
´Builder.isEnum` tests if a JSON definition is an enum. What you are looking for is `root.MessageId instanceof protobuf.Builder.Enum`.

**Comment by kelvinh** [comment]
Oh, I see, thanks for the explanation!
