### ISSUE TITLE
Shouldn't undefined treated same as null?

### ISSUE THREAD

**Issue by aliok** [dcodeIO/protobuf.js#395]
When I build an object:
- when I set value of a string property to null : all good
- when I set value of a string property to undefined : `Uncaught Error: Illegal value for [object Object] of type string: undefined (not a string)`

I cannot really talk for other falsy values. I only needed undefined.

**Comment by JamesMGreene** [comment]
:+1:

**Comment by englercj** [comment]
For required (and defaulted) fields there is a significant difference between "set to null" and "not set". I had assumed that `null` was "set to null" and `undefined` was "not set".

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
