### ISSUE TITLE
pbjs fails to serialize strings that are greater than 127 characters in length

### ISSUE THREAD

**Issue by jeremyong** [dcodeIO/protobuf.js#400]
Internally, I created a test case that succeeds when the encoded string is precisely 127 characters, and instantly fails when a single additional character is added.

String lengths are base 128 encoded as varints like other integers on the wire, and my suspicion is that pbjs is not handling this correctly.

**Comment by jeremyong** [comment]
Some more information: Printing the bytes of the serialized message gives me:
```
00011010 11000010 10000000 00000001
```
The leftmost byte indicates a field number of 00011 (3) which is correct and a wire type of 010 (2) which is also correct for a length delimited field.

The next byte is completely wrong, and I have no idea what it is (11000010).

The third and fourth bytes are a properly encoded varint representing 128 (127 + 1)

**Comment by jeremyong** [comment]
ByteBuffer#writeVString correctly encodes the varint and string. I am now attempting to figure out what is happening prior to that (working theory is it is passed the wrong offset)

**Comment by jeremyong** [comment]
Sorry tracking this down a little further, the `ByteBuffer` produced by encoding the message is actually correct. The problem seems to arise when I convert it to binary

**Comment by jeremyong** [comment]
Closing this issue as I no longer believe this is a PBJS problem. The problem occurred because the binary data was being marshaled in a way that was corrupting the binary. Sorry for the noise.

**Comment by dcodeIO** [comment]
I see. This may also be relevant here, for anyone stumbling upon the issue: https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F

**Comment by jeremyong** [comment]
In my case, it was a little trickier because I was using pbjs with React Native and encoding the messages with `toBinary`. However, data that is sent as a string gets marshalled over to Objective-C (for iOS, Java for Android) via JSON. I believe this was silently corrupting data. My solution was to base64 encode the strings prior to the marshaling step, and reverse the operation on the other side.
