### ISSUE TITLE
Message#decode getting stuck

### ISSUE THREAD

**Issue by apbarrero** [dcodeIO/protobuf.js#401]
According to API docs on Message#decode:

> Throws:
>     If the message cannot be decoded or if required fields are missing. The later still returns the decoded message with missing fields in the `decoded` property on the error.
> Type
>     Error

I found that when a received buffer includes a value for a nested message but a required first level field is missing, the call doesn't return nor does it throw any error.

I tweaked the websocket example to reproduce the issue. You can find the code here: https://github.com/apbarrero/protobuf.js/tree/decodehangup

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
