### ISSUE TITLE
execute proto2js programmatically

### ISSUE THREAD

**Issue by chpio** [dcodeIO/protobuf.js#403]
hi,

i want to run the proto2js in my build script, without using workarounds (eg `exec('proto2js ....')`). Is there an usable API for my purpose?

https://github.com/dcodeIO/protobuf.js/blob/master/examples/protoify/index.js#L9-L14
https://github.com/dcodeIO/protobuf.js/issues/188

**Comment by chpio** [comment]
my *uncool* code right now:
```javascript
gulp.task('build-proto', () =>
	$.exec('./node_modules/.bin/pbjs src/lib/messages.proto > src/generated/messages.json')
);
```

**Comment by dcodeIO** [comment]
The [pbjs command](https://github.com/dcodeIO/protobuf.js/blob/master/bin/pbjs) is just a wrapper around the cli code: https://github.com/dcodeIO/protobuf.js/blob/master/cli/pbjs.js

You can require `cli/pbjs.js` and run the exported `main` function directly.

**Comment by dtracers** [comment]
@chpio What did you final command look like?

**Comment by dtracers** [comment]
What I ened up doing:
using ```grunt-exec```

```
        exec: {
            build_proto: {
                cmd: function() {
                    var inputFiles = [ 'src/**/proto/**/*.proto' ];
                    var protoFiles = grunt.file.expand(inputFiles);
                    var jsFiles = grunt.file.expandMapping(protoFiles, 'target/website/proto', { flatten: true, ext: '.js' });
                    var command = '';
                    for (var i = 0; i < protoFiles.length; i++) {
                        grunt.log.write('cimpiling protofile ' + protoFiles[i]);
                        grunt.log.write('');
                        var jsFile = jsFiles[i].dest;
                        command+= '"./node_modules/.bin/pbjs" ' + protoFiles[i] + ' --source=proto ' +
                            '--target=js --path=src/main/proto > ' + jsFile + ' &';
                    }
                    return command + 'echo "completed compile"';
                }
            }
        },
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
