### ISSUE TITLE
ProtoBuf not decoding byte arrays correctly

### ISSUE THREAD

**Issue by wjacobs214** [dcodeIO/protobuf.js#407]
I have a simple proto

message NLSignature {
    required bytes signedHash = 1;
    required int32 species = 2;
}

I assign a Uint8Array(256) to signedhash
then encode to bytes and decode back to the message
SignedHash is larger than the original
Anyone else seen this?

**Comment by dcodeIO** [comment]
`signedHash` is a [ByteBuffer](https://github.com/dcodeIO/bytebuffer.js/wiki/API) instance, which wraps the exact part of the entire message via its `offset` and `limit` properties.

See: `ByteBuffer#toBuffer` / `ByteBuffer#toArrayBuffer` / `ByteBuffer#compact`

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
