### ISSUE TITLE
Building on Linux fails

### ISSUE THREAD

**Issue by joshkel** [dcodeIO/protobuf.js#408]
If I run `npm run make` on Linux, I get the following error:

```
> protobufjs@5.0.1 jsdoc /home/jkelley/src/protobuf.js
> node node_modules/jsdoc/jsdoc.js -c jsdoc.json

ERROR: Unable to find the source file or directory /home/jkelley/src/protobuf.js/dist/ProtoBuf.js
There are no input files to process.
```

Apparently it's a case sensitivity issue: JSDoc is looking for `dist/ProtoBuf.js`, but the actual filename is `dist/protobuf.js`.

If you're okay with replacing all JSDoc references to `ProtoBuf` with `protobuf`, I can submit a PR.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
