### ISSUE TITLE
Decode object is empty

### ISSUE THREAD

**Issue by guillaume-roy** [dcodeIO/protobuf.js#409]
When I want to decode an object sent from a server, the decoded object is empty.

* .proto file :
```
syntax="proto3";

message Container {
	message TestModel2 {
		string Property1 = 1;
		bool Property2 = 2;
		double Property3 = 3;
	}

	repeated TestModel2 Models = 1;
}
```

* Server code :
```
var container = new Container();

var model = new TestModel2
{
    Property1 = "Test",
    Property2 = true,
    Property3 = 3.14
};

container.Models.Add(model);
```

* Base64 data :
```
ChEKBFRlc3QQARkfhetRuB4JQA==
```

* JS decoding :
```
var ProtoBuf = dcodeIO.ProtoBuf;
var xhr = ProtoBuf.Util.XHR();
xhr.open(
    /* method */ "GET",
    /* file */ "/XXXX/Protobuf/GetProtoData",
    /* async */ true
);
xhr.responseType = "arraybuffer";
xhr.onload = function (evt) {
    var testModelBuilder = ProtoBuf.loadProtoFile(
    	"URL_TO_PROTO_FILE",
        "Container.proto").build("Container");
    var msg = testModelBuilder.decode64(xhr.response); 
    console.log(JSON.stringify(msg, null, 4)); // Correctly decoded
}
xhr.send(null);
```

* Result object in JS console :
```
{
    "Models": []
}
```

* bytebuffer.js v2.0
* protobuf.js v2.0

Thank you !

**Comment by guillaume-roy** [comment]
I would like to specify that, server-side, if I serialize my object and then deserialize it, I retrieve my initial data.

**Comment by englercj** [comment]
Have you tried using the latest version of protobufjs (5.0.1)?

**Comment by guillaume-roy** [comment]
Ok after checking, it's not the version 2. 

I'm using the files in https://github.com/dcodeIO/protobuf.js/tree/master/dist

Where did you find the version number ?

**Comment by guillaume-roy** [comment]
I found how to get the v5.0.1, I switched to it.
My data is still empty client-side.

**Comment by guillaume-roy** [comment]
Finally i solved the problem by myself.

It was the client-side which was in fault.

* In fact the `xhr.response` is JSON format so it was between double quotes `"ChEKBFRlc3QQARkfhetRuB4JQA=="`. I had to `JSON.parse` my response.
* I removed the `xhr.responseType = "arraybuffer"`;

Here is my code now :

```
var ProtoBuf = dcodeIO.ProtoBuf;
var xhr = ProtoBuf.Util.XHR();
xhr.open(
    /* method */ "GET",
    /* file */ "/XXXX/Protobuf/GetProtoData",
    /* async */ true
);
// xhr.responseType = "arraybuffer"; <--- Removed
xhr.onload = function (evt) {
    var testModelBuilder = ProtoBuf.loadProtoFile(
        "URL_TO_PROTO_FILE",
        "Container.proto").build("Container");
    var msg = testModelBuilder.decode64(JSON.parse(xhr.response)); <-- Parse the response in JSON format
    console.log(msg); // Correctly decoded
}
xhr.send(null);
```
