### ISSUE TITLE
Is it really performant against JSON

### ISSUE THREAD

**Issue by YouriT** [dcodeIO/protobuf.js#414]
Hi !

I do understand that protocol buffer is great for send loads of little message by removing the JSON self describing structure. But I ran a quick bench and here are my results:

```
1,000,000 encodes / decodes
protobuf: 23696.981ms
json: 10823.868ms
```

for this given proto:

```
syntax = "proto3";

message Item {
    enum Schema {
        schema1 = 0;
        schema2 = 1;
    }
    required Schema schemaName = 1;
    required string transId = 2;
    required Contents contents = 3;
}

message Contents {
    optional double value = 1;
    optional string date = 2;
    optional string currency = 3;
}
```

So either I mis got something, either there is only a message size advantage.

```
protobuf: 64bytes
json: ~124bytes
```

Thanks for the input :)

**Comment by englercj** [comment]
json is one of the fastest format to seialize to/from in JS. The benefits of protobuf are wire size, strong typing for wire messages, and platform interop.

I would be blown away if this lib serialized faster than native `JSON.parse`.

**Comment by YouriT** [comment]
@englercj well @mafintosh shows it differently on his [implementation of protobuf + benchmark](https://github.com/mafintosh/protocol-buffers#performance).

**Comment by englercj** [comment]
That module seems pretty cool, it generates code at runtime for the encoding/decoding of messages which makes its encoding/decoding super fast. Very clever! This module doesn't do that, it uses a generic algorithm and reflection data so of course it is slower.

I was surprised it was faster than JSON.parse until I saw that it was generating code on creation of a Message type. That makes sense for it to be faster because you are comparing a general purpose algo, with one generated specifically for the data being serialized. Unless you do something wrong, the later should always be faster.

Thanks for the heads up on this module, pretty interesting and clever way of doing runtime generation.

**Comment by englercj** [comment]
Looking into it more, unfortunately it looks like that module has some issues with int encodings and doesn't support 64-bit numbers at all.

With a bit more work/time though that module could be really awesome!

**Comment by YouriT** [comment]
Thought the same when looking at it and when I saw there were some issues I thought that this (dcode) project would be more stable that's how I came across testing dcode/proto but I think I gonna stick with the other one because my only need is to transfer data between 3 node processes on 3 machines so the faster the better and JSON Streams showed to be inefficient sadly.

**Comment by YouriT** [comment]
@englercj happy to have made you discover someone's else project :)

**Comment by dtracers** [comment]
what about the command line utility of this library?

It is supposed to pregenerate javascript files.

**Comment by englercj** [comment]
> what about the command line utility of this library?

> It is supposed to pregenerate javascript files.

They are just files with json representations passed into `.build()` it doesn't pregenerate serialization code specific to that message or anything. It doesn't really generate *any* code.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
