### ISSUE TITLE
is it possible to encode to application/json+protobuf?

### ISSUE THREAD

**Issue by jimmywarting** [dcodeIO/protobuf.js#415]
Is it possible to encode it hybrid like json+protobuf? (where all the keys is represented by its number value)
So that it always becomes an array, something like this:

```
 [[[44,3,"text",1458765064],["foo","bar"],null,"sv"],[720,30]]
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
