### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by Okahyphen** [dcodeIO/protobuf.js#416]
The README states that 

> [bytebuffer.js](https://github.com/dcodeIO/bytebuffer.js) is the only production dependency

but the [`package.json`](https://github.com/dcodeIO/protobuf.js/blob/master/package.json) file is only making use of the `dependencies` field:

```
"dependencies": {
  "ascli": "~1",
  "bytebuffer": "~5",
  "glob": "^5.0.10",
  "yargs": "^3.10.0"
}
```

Wouldn't it be better to move `ascli`, `glob`, and `yargs` to the [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) field, to give more control over what gets installed with `npm install` (`npm install --no-optional`)?

```
"dependencies": {
  "bytebuffer": "~5"
 },
"optionalDependencies": {
  "ascli": "~1",
  "glob": "^5.0.10",
  "yargs": "^3.10.0"
}
```

Thoughts? Would this affect anything internally?

**Comment by dcodeIO** [comment]
These are dependencies for the `pbjs` command line utility, which is a node.js only thing of course. They are not required if you don't use the CLI (which most modules that just `require("protobufjs")` in fact don't), but I am not sure if it'd be good practice to explicitly mark them optional.

What if the CLI utility would have its own package instead, with its own dependencies, including `protobufjs`? Not sure if always making sure both packages are up to date (and compatible), especially with breaking changes, would be so great, though.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
