### ISSUE TITLE
Protobuf builder returns "null" in Node Webkit project

### ISSUE THREAD

**Issue by pjwl33** [dcodeIO/protobuf.js#418]
Whenever I try to create a Protobuf builder, returns `null`.

This is what I am using to create the builder:
`var builder = dcodeIO.Protobuf.loadProtoFile("path_to_file.proto")`

I have ensured that my file path is correct from the html file and I am including the dependencies in order (long.js, ByteBufferAB.js, protobuf.js). Also this same code works in the browser when built as a web app. 

Any insight would be helpful, thank you.

**Comment by dcodeIO** [comment]
This is what's called to retrieve the contents of the file: https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Util.js#L59

Is ProtoBuf.Util.IS_NODE `true` in your case?

**Comment by pjwl33** [comment]
Yes it is: 
![screen shot 2016-04-13 at 11 41 38 am](https://cloud.githubusercontent.com/assets/4692340/14499539/b5ba4928-016c-11e6-9c65-27249df892e5.png)

**Comment by pjwl33** [comment]
Another thing I have noticed is that, since this is a Corodva/PhoneGap project as well as a Node Webkit project, the ProtoBuf object is correctly built in the PhoneGap project but returns `null` **ONLY** in the Node Webkit project version, even with the same code.

Is there a potential issue with NWK's compatibility with ProtoBuf or vice versa? Thank you for your help.
