### ISSUE TITLE
Inefficiency: int32 encoding encodes as int64

### ISSUE THREAD

**Issue by evanw** [dcodeIO/protobuf.js#419]
Test code:

```
var protobufjs = require('protobufjs');
var test = protobufjs.loadProto([
  'package test;',
  'message Test {',
  '  optional int32 x = 1;',
  '}',
].join('\n')).build('test');
console.log(test.Test.encode({x: -1}).toBuffer());
```

When I run this, I get `<Buffer 08 ff ff ff ff ff ff ff ff ff 01>` but I expected `<Buffer 08 ff ff ff ff 0f>` instead because that's what I get when I call `ByteBuffer.writeVarint32(8)` followed by `ByteBuffer.writeVarint32(-1)`.

**Comment by dcodeIO** [comment]
As of [Protocol Buffers / Encoding / Signed Integers](https://developers.google.com/protocol-buffers/docs/encoding#signed-integers):

> As you saw in the previous section, all the protocol buffer types associated with wire type 0 are encoded as varints. However, there is an important difference between the signed int types (sint32 and sint64) and the "standard" int types (int32 and int64) when it comes to encoding negative numbers. If you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer. If you use one of the signed types, the resulting varint uses ZigZag encoding, which is much more efficient.

**Comment by evanw** [comment]
Oh ok, cool. My mistake. That's a strange design choice but it sounds like that's the spec. I guess that means int32 is actually just an alias of int64.
