### ISSUE TITLE
Question: Unclear Documentation

### ISSUE THREAD

**Issue by dtracers** [dcodeIO/protobuf.js#420]
I was a bit unclear about how the reflection api works.  Are there any examples of it in practice

I specifically want to know how to tell if a protobuf message is a Message or a Service or an Enum

**Comment by dcodeIO** [comment]
Basically it is:
```js
var obj = builder.lookup('mypackage.SomeThing');
if (obj instanceof ProtoBuf.Reflect.Message) {
   ...
}
```

**Comment by dtracers** [comment]
Awesome!  Thank you very much.  I actually ended up using the post built
messages so I ended up using the $type

Where it was:

If (obj.$type instance of ProtoBuf.Reflect.Message)

And obj is just the ProtoBuf message that you can use to create message
instances.
