### ISSUE TITLE
Services that import proto files can't be called correctly

### ISSUE THREAD

**Issue by dtracers** [dcodeIO/protobuf.js#425]
This may be user error but I believe I am using the correct procedure:

simple example:

proto1:
```
package proto.package;
message Hi {
 optional string hellomate = 1;
}
```

proto2:
```
package proto.package2;
import "proto1";

service serv {
  rpc sayHi(proto.package.Hi) returns (DoesntMatter);
}
```
Here is the set up code

```
var proto1Builder = DcodeIo.ProtoBuf.protoFromFile('proto1.proto');
var Hi = proto1Builder.build('proto').package.Hi;

var proto2Builder = DcodeIo.ProtoBuf.protoFromFile('proto2.proto');
var serv = proto2Builder.build('proto').package2.serv;
```

Here is the code that causes the problem:

```
// service defined correctly here with its networking stuff

var hiObj = new Hi();
hiObj.hellomate = "STRING HELLO";

hiObj.toArrayBuffer(); // this line works perfectly

servObj.sayHi(hiObj); // This line is broken!
```

This line fails with the error:
```
Error: Illegal value for hellomate value element of type string: object (not a string)
```
It is trying to set the message instance of Hi to the first field in a new instance of Hi.
What I believe is happening is that setting a service with an object from an imported proto that is built independently fails for the reasons shown below:

![capture](https://cloud.githubusercontent.com/assets/1933836/14901604/da779612-0d5b-11e6-9094-722ed3c613a3.PNG)

Basically it checks to see if the argument of the service is of the correct type and if not it creates a new instance of that type.  But because they have different builders the Hi from proto1 is not the same as the Hi from proto2

This causes it to try and create a new instance of the Hi from proto2 passing in the message of Hi from proto1.

![capture](https://cloud.githubusercontent.com/assets/1933836/14901671/4e9c89d0-0d5c-11e6-921a-89fa796016b1.PNG)

The above is showing that values is a message type.

![capture](https://cloud.githubusercontent.com/assets/1933836/14901720/8528b0b4-0d5c-11e6-8d87-8ee05480668f.PNG)

Where it then checks to make sure it is not a message.  But it is in fact a message so it fails this test.  And instead proceeds to use the arguments instead of setting values.

![capture](https://cloud.githubusercontent.com/assets/1933836/14901790/c93a16bc-0d5c-11e6-81e0-c2a9855d2590.PNG)

Of course the first argument is a message Hi which causes the code instead to fail.

Potential solutions:

Solution 1.
Commenting out the line 2405:
```
/* not _another_ Message */ // (typeof values.encode !== 'function' || values instanceof Message) &&
```

Solution 2.
Instead of having the if statmeent:
```
if (!(req instanceof method.resolvedRequestType.clazz))
  req = new method.resolvedRequestType.clazz(req);
```
maybe have it check to see if req is the same message type (if you store the name and other unique identification information about the message)  This will mainly fix the import part of protobuf

Solution 3.
I am being an idiot when I build the proto files and I should instead find a different way to build proto files.

Thanks for reading!

**Comment by dcodeIO** [comment]
In your setup code, you are creating two distinct builder contexts. While you can do that, it's not possible to use the messages from builder A in code using builder B and vice versa. This is because each builder holds its own reflection structure. Instead, do:

```js
var protoBuilder = DcodeIo.ProtoBuf.protoFromFile('proto1.proto');
var Hi = protoBuilder.build('proto').package.Hi;

DcodeIo.ProtoBuf.protoFromFile('proto2.proto', protoBuilder );
var serv = protoBuilder.build('proto').package2.serv;
```

**Comment by dtracers** [comment]
okay cool!

Is the returned builder of the second proto file the exact same object as the context that is passed in?

example:
```
var protoBuilder = DcodeIo.ProtoBuf.protoFromFile('proto1.proto');
var Hi = protoBuilder.build('proto').package.Hi;

var protoBuilder2 = DcodeIo.ProtoBuf.protoFromFile('proto2.proto', protoBuilder );
var serv = protoBuilder.build('proto').package2.serv;
```
are ```protoBuilder``` and ```protoBuilder2``` the exact same object?

**Comment by dcodeIO** [comment]
Yes, they are the same.
