### ISSUE TITLE
I cannot use protobufjs objects over socket io 1.4.5

### ISSUE THREAD

**Issue by kinghadi** [dcodeIO/protobuf.js#426]
**Problem**
I want to use `protobufjs` module with `socket.io 1.4.5`. The problem is when I send my encoded object over socket and it throws an error says that: 

```
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (../node_modules/bytebuffer/dist/bytebuffer-node.js:378:23)
```
**Code**
This piece sends the object: 
```
		client.on('connect', function () {
			// send a login message
			var loginMessage = new C2SMessage({
				"from": "myid",
				"body": "mybody",
				"messageType": C2SMessage.MessageType.LOGIN_MESSAGE,
				"serverMessage": new ServerMessage({
					"salt": "UNKWON",
					"messageId": "time",
					"sessionId": "sessionId",
				})
			});
			var a = loginMessage.encode();
			console.log(a)							;
			client.emit("login", a);

			client.on("login", function (msg){
				if (msg === "FAIL" || msg === "SUCCESS") {
					done();					
				}else{
					throw new Error("login failed");
				};
			});
		});	
```

This is how I decode it: 
```

socket.on("login", function (msg, callback){
      callback = callback || function () {};
      console.log(msg);
      var loginMessage = C2SMessage.decode(msg);
      console.log(loginMessage);
      // console.log("login message: %s", loginMessage);
      socket.emit("login", "FAIL");     
    });
```

This is  a problem with `protobufjs` or `socket io` ?

**Comment by kinghadi** [comment]
Bytes are the same in both sender file and receiver code. I mean the same schema and the same data! 

**Sending object**
```
{ buffer: <Buffer 0a 0b 70 68 6f 6e 65 4e 75 6d 62 65 72 12 00 18 01 22 22 0a 06 55 4e 4b 57 4f 4e 12 0d 31 34 36 32 31 39 35 31 32 31 32 39 35 1a 09 73 65 73 73 69 6f ... >,
  offset: 0,
  markedOffset: -1,
  limit: 53,
  littleEndian: false,
  noAssert: false }
```
**Receiving object**
``` 
{ buffer: <Buffer 0a 0b 70 68 6f 6e 65 4e 75 6d 62 65 72 12 00 18 01 22 22 0a 06 55 4e 4b 57 4f 4e 12 0d 31 34 36 32 31 39 35 31 32 31 32 39 35 1a 09 73 65 73 73 69 6f ... >,
  offset: 0,
  markedOffset: -1,
  limit: 53,
  littleEndian: false,
  noAssert: false }

```

**Comment by dcodeIO** [comment]
```js
            var a = loginMessage.encode();
            console.log(a)                          ;
            client.emit("login", a);
```
There you are sending a ByteBuffer object, which is probably not what you want. A ByteBuffer is just a wrapper and might even be a slice backed by a much larger byte array. Instead, try:

```js
            var a = loginMessage.encode().toBuffer();
            console.log(a)                          ;
            client.emit("login", a);
```

**Comment by kinghadi** [comment]
Yeah that's right :) Thank you :)

**Comment by Edisoni** [comment]
Why?
I use:
<script src="//cdn.rawgit.com/dcodeIO/protobuf.js/6.6.3/dist/protobuf.min.js"></script>
<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>

.encode(...).toBuffer is not a function

**Comment by dcodeIO** [comment]
protobuf.js 6's API differs from that of protobuf.js 5. See the README etc. for more information.

**Comment by Edisoni** [comment]
How to message from client decode?
{ len: 20,
  head: { len: 0, next: { len: 1, next: [Object], val: 10 }, val: 0 },
  tail: { len: 4, val: 30 },
  states: null }

I try
var dataDecoded = ProtoPlayer.decode(new Buffer(data));
but it is error 
![2017-02-18 21 08 00](https://cloud.githubusercontent.com/assets/10086099/23095657/5b3e574e-f61e-11e6-87c9-cffcae192666.png)

**Comment by x1911** [comment]
i have same issue, and where can man find the solution from version 6? a link maybe?

**Comment by dcodeIO** [comment]
`.decode` should be able to determine the type of buffer usually, but if that fails for whatever reason, you can try to wrap the buffer in a reader:

```js
var buffer = ...;

var reader = protobuf.Reader.create(buffer);
var myMessage = SomeMessage.decode(reader);
```

**Comment by x1911** [comment]
thank you very much for your reply, 

now in client can get data, no more null object, it looks like : 
Object {buf: ArrayBuffer, pos: 0, len: 1147}

but after the decode, it still comes the 'illegal buffer' error in client side.

Uncaught Error: illegal buffer
    at Function.create (protobuf.min.js?0.5:8)
    at n._PACK_ItemInit$decode [as decode] (eval at l (protobuf.min.js?0.5:7), <anonymous>:5:12)
    at n.decode (protobuf.min.js?0.5:8)
    at Object.PF.pfDecode (ProtocolBuffers.js:38)
    at n.<anonymous> (socketio.js:249)
    at n.emit (socket.io.min.js?0.5:2)
    at n.onevent (socket.io.min.js?0.5:3)
    at n.onpacket (socket.io.min.js?0.5:3)
    at n.<anonymous> (socket.io.min.js?0.5:3)
    at n.emit (socket.io.min.js?0.5:2)

**Comment by x1911** [comment]
Maybe somewhere can i get the .encode(...).toBuffer function back? so make it easier with socket.io

**Comment by dcodeIO** [comment]
There has been an issue recently that might be related: https://github.com/dcodeIO/protobuf.js/pull/795

**Comment by x1911** [comment]
the version i am using is "protobufjs": "^6.7.3", i stuck here for almost 2 days
have tried base64 encode decode, but would not work.
