### ISSUE TITLE
dcodeIO.ProtoBuf.loadProtoFile callback with empty builder on network timeouts

### ISSUE THREAD

**Issue by gregor** [dcodeIO/protobuf.js#427]
If you call dcodeIO.ProtoBuf.loadProtoFile asynchroneously and the network requests times out, due to the lack of network connectivity for example, the callback will not contain an error but an empty builder instead.

This is caused by the Util.fetch method:

https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Util.js#L86
`if (/* remote */ xhr.status == 200 || /* local */ (xhr.status == 0 && typeof xhr.responseText === 'string'))` 

I do not know the history of the `or` case for local use but this will always return true on an timed out request. The responseText is of type `string` but the `string` is empty. You do not end up in the failure case as you should.

I created a simple PR that should fix this: https://github.com/dcodeIO/protobuf.js/pull/428

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
