### ISSUE TITLE
pbjs: would like to parse option with aggregated syntax

### ISSUE THREAD

**Issue by ibaileyStingray** [dcodeIO/protobuf.js#430]
I Have the following proto:
`import "google/protobuf/descriptor.proto";

enum Error {
    ERROR_1 = 0;
    ERROR_2 = 1;
}
extend google.protobuf.MessageOptions {
  optional Exception throwing = 51234;
}

message Exception {
    repeated Error e = 1;
}

message OptionThrowing {
    option (throwing) = {e: ERROR_1 e: ERROR_2};
    required int32 value = 1;
}`

it work with protobuf-net but with pbjs I have an exception:
protobufjs\cli\pbjs\targets\json.js:136 throw Error("Illegal option type: "+typeof(val));

if I comment the throw in buildOptions pbjs generate a valid json.
`{
    "package": null,
    "messages": [
        {
            "name": "OptionThrowing",
            "options": {
                "(throwing).e": [
                    "ERROR_1",
                    "ERROR_4"
                ]
            },
            "fields": [
                {
                    "rule": "required",
                    "type": "int32",
                    "name": "value",
                    "id": 1
                }
            ]
        },
        {
            "name": "Exception",
            "fields": [
                {
                    "rule": "repeated",
                    "type": "Error",
                    "name": "e",
                    "id": 1
                }
            ]
        }
    ],
    "enums": [
        {
            "name": "Error",
            "values": [
                {
                    "name": "ERROR_1",
                    "id": 0
                },
                {
                    "name": "ERROR_2",
                    "id": 1
                },
                {
                    "name": "ERROR_3",
                    "id": 2
                },
                {
                    "name": "ERROR_4",
                    "id": 3
                }
            ]
        }
    ]
}`

is this exception really necessary or can it be dropped?

thanks for your time

**Comment by w4-sjcho** [comment]
I'm also having the same problem, when there's a repeated field inside an option.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
