### ISSUE TITLE
unclear documentation on pbjs

### ISSUE THREAD

**Issue by dtracers** [dcodeIO/protobuf.js#431]
I am trying to run pbjs as a grunt task and I keep having problems passing in files.  It keeps saying the filename to parse is required but I pass it in.

example that does not work:
but does it the way I want

```
        var protoFiles = grunt.file.expand([ 'src/**/proto/**/*.proto' ]);
        grunt.log.write('Attempting to compile proto files:');
        grunt.log.write(protoFiles);
        for (var i = 0; i < protoFiles.length; i++) {
            grunt.log.write('cimpiling protofile ' + protoFiles[i]);
            grunt.log.write('');
            var options = [ '--source=proto', '--target=js', '--path=src/main/proto' ];
            var files = [ protoFiles[i] ];
            var args = files.concat(options);
            pbjs.main(args);
        }
```

this example compiles but only the first one:

```
        var protoFiles = grunt.file.expand([ 'src/**/proto/**/*.proto' ]);
        grunt.log.write('Attempting to compile proto files:');
        grunt.log.write(protoFiles);
        for (var i = 0; i < protoFiles.length; i++) {
            grunt.log.write('cimpiling protofile ' + protoFiles[i]);
            grunt.log.write('');
            var options = [ '--source=proto', '--target=js', '--path=src/main/proto' ];
            var args = protoFiles.concat(options);
            pbjs.main(args);
        }
```

The only time it worked was when I passed in the entire the entire array then it only build the first one.

There are not any examples on how to use the pbjs besides the documentation which I feel does not apply as well when you are trying to run it from code.  Especially because how the library splits the strings is also not well defined.

To say what I want to do:
I want to build a directory of proto files to js that outputs at a different directory that I specify.

**Comment by dcodeIO** [comment]
The command line parser has changed a while ago. Try `var options = [ '--source', 'proto', '--target', 'js', '--path', 'src/main/proto' ];` etc.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
