### ISSUE TITLE
Error: failed to import google/api/annotations.proto

### ISSUE THREAD

**Issue by prashcr** [dcodeIO/protobuf.js#433]
It seems to be trying to import a local file called `google/api/annotations.proto` rather than enable options
  
Related issue: https://github.com/gengo/grpc-gateway/issues/165

**Comment by c3s4r** [comment]
Did you find a solution for this? I'm having the same issue when trying to create an RGRPC server in node.

**Comment by dcodeIO** [comment]
It might be required to add [google/api/annotations.proto](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto) and its dependencies to your application, if not bundled with grpc already. protobuf.js doesn't bundle it.

**Comment by prashcr** [comment]
Yep, that's what I did.

**Comment by konsumer** [comment]
If it's commented out, it works without error, but also it seems that there is a [mechanism for handling missing but optional files](https://github.com/dcodeIO/protobuf.js/issues/368).

So, basically, we can do this before a grpc parse:

```
protobuf.common(path.resolve('test/google/api/annotations.proto'), {})
```

Since the annotation lib isn't needed by grpc (it parses the options directly.)

**Comment by konsumer** [comment]
But it looks like the version required by gRPC doesn't have `common()`...

```
protobuf.common is not a function
```

**Comment by dcodeIO** [comment]
gRPC is still in the process of updating to protobuf.js v6. If no definitions from annotations.proto are used, actually, you could also just create an empty file at current working directory + `/google/api/annotations.proto`.

**Comment by konsumer** [comment]
would that work for nested structures, or just top-level proto files?

I ended up doing this in with grpc:

```
const getProto = (protoFile) => {
  protobuf.common(`${path.dirname(protoFile)}/google/api/annotations.proto`, {})
  return grpc.load(protoFile)
}
```

Which works ok for single-level RPC service definitions.

**Comment by konsumer** [comment]
Oh wait, that didn't actually work (I had it commented out, still.)

**Comment by konsumer** [comment]
If there was a concept of "include path" like protoc, I could be using my existing protoc include dir, which has this and also the [common types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf). Maybe this is more of an issue for grpc.
