### ISSUE TITLE
Undefined ByteBuffer when requiring bower version of protobufjs via amd modules

### ISSUE THREAD

**Issue by dtracers** [dcodeIO/protobuf.js#439]
I am using a protobuf with requirejs and protobufjs is saying it is not ByteBuffer is undefined on line 52 of the built protobuf.js file

Line 31 is passing in undefined for ByteBuffer and for isCommonJs

It is in face calling line 25 where it calls the define correctly.
And my code does in fact pull up the ByteBufferAB.js because require was complaining with a failed get when it could not find the file.

here is the code I am using that causes this problem:

```
<script src="/bower_components/requirejs/require.js"></script>
    <script>
  require.config({
            baseUrl: "/src",
            paths: {
                "stacktrace-js": "/bower_components/stacktrace-js/dist/stacktrace",
                "long": "/bower_components/long/dist/long",
                "Long": "/bower_components/long/dist/long",
                "bytebuffer": "/bower_components/bytebuffer/dist/ByteBufferAB",
                "ByteBuffer": "/bower_components/bytebuffer/dist/ByteBufferAB",
                "protobufjs": "/bower_components/protobufjs/dist/protobuf",
            }
        });

        require(['protobufjs'], function (protobufjs) {
              console.log(protobufjs);
        });
</script>
```

I am currently using chrome in a single html file

**Comment by dtracers** [comment]
This can be fixed simply by having ByteBuffer define using lower case or have protobuf call using uppercase.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
