### ISSUE TITLE
Deserialise Binary as ArrayBuffer

### ISSUE THREAD

**Issue by MeirionHughes** [dcodeIO/protobuf.js#443]
The whole deserialising of byte fields to ByteBuffer objects is rather inconvenient; Node.js does actually have ArrayBuffer these days. I appreciate it didn't years ago, hence ByteBuffer, but its entirely redundant now.  

There should be an option to simply de-serialise directly to pure ArrayBuffer. As is stands, I'm going to have to "clean up" the deserialised object trees to force this.  

Secondly, there seems to be something wrong with `.toArrayBuffer` in when running in node; it returns a seemingly empty object, but there is data in there somewhere. `toBuffer` works and you get  the data dumped when you output it to console.log.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
