### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by makkesk8** [dcodeIO/protobuf.js#445]
Is there a reason why we are still using try catch ?

**Comment by dcodeIO** [comment]
Are you referring to something specific or are you questioning the use of try/catch in general?

**Comment by makkesk8** [comment]
@dcodeIO Well error handling for protobuf.js mostly :)

**Comment by dcodeIO** [comment]
The way it is implemented is that it throws on synchronous code, and returns an error with the callback on asynchronous code. Most of the library is synchronous, though. Or what are you proposing?

**Comment by makkesk8** [comment]
> @dcodeIO  and returns an error with the callback on asynchronous code.

Could you give an example of this? Checked the docs and there is no mention of any callbacks.

> @dcodeIO Most of the library is synchronous, though.

Yea, Was that made on purpose? and/or can/will it ever become fully async?

**Comment by englercj** [comment]
@makkesk8 What operations are you wanting to be async? Most of the operations here are CPU-bound, what is it that you need to be async?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
