### ISSUE TITLE
schema.ToJavaScript is not a funtion

### ISSUE THREAD

**Issue by mbonnet** [dcodeIO/protobuf.js#446]
when using pbjs commant to generate javascrit files from a .proto file, i'va got a error "schema.ToJavaScript is not a funtion" on cli.js.

**Comment by dcodeIO** [comment]
That's strange. protobuf.js doesn't use the terms [schema](https://github.com/dcodeIO/protobuf.js/search?utf8=%E2%9C%93&q=schema) and [ToJavaScript](https://github.com/dcodeIO/protobuf.js/search?utf8=%E2%9C%93&q=ToJavaScript) at all.

**Comment by mbonnet** [comment]
It is ok, i used the npm of pbjs not the pbjs included in the protobufjs npm. thanks it works fine.

**Comment by emcniece** [comment]
@mbonnet Did you find a solution anywhere? I see that https://github.com/evanw/pbjs/issues is empty.

@dcodeIO this is fine to close on your end.
