### ISSUE TITLE
Support for proto well known types

### ISSUE THREAD

**Issue by tbillington** [dcodeIO/protobuf.js#447]
Is support for [well known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) on the roadmap at all?

**Comment by the-duke** [comment]
Especially support for [Any Type](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any) would be awesome!

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
