### ISSUE TITLE
Long is required?

### ISSUE THREAD

**Issue by jhanssen** [dcodeIO/protobuf.js#448]
Hi, I'm trying to use protobuf.js in an environment where I don't have Long and I get an error saying `TypeError: 'null' is not an object (evaluating 'ProtoBuf.Long.isLong')` and the code does indeed unconditionally call Long.isLong() even though it's previously set to null when Long is not available. Is this intentional? Changing the code in question to

``` javascript
if (ProtoBuf.Long && ProtoBuf.Long.isLong(obj))
```

seems to fix the issue.

Thanks.

**Comment by englercj** [comment]
To be compatible with the protobuf.js spec Long is required, because protobuf supports 64-bit integers.

**Comment by jhanssen** [comment]
I wouldn't really mind if it was required but https://github.com/dcodeIO/ProtoBuf.js/wiki/Long indicates that it's not.

**Comment by englercj** [comment]
Oh I see, maybe this is just a bug then :P

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
