### ISSUE TITLE
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

### ISSUE THREAD

**Issue by kinghadi** [dcodeIO/protobuf.js#450]
Hi, 
I'm trying to load the `.proto` files in the html file. The `.proto` files are beside the my html file. but it throws this error:

**Error**
`Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Code**

``` html
<script>
      var socket = io("http://172.20.16.163:9090");
      var pb = dcodeIO.ProtoBuf;
      var builderC2SMessage = pb.loadProtoFile("./ClientToServerMessage.proto");
      var C2SMessage = builderC2SMessage.build().ClientToServerMessage;
      console.log(C2SMessage);     
</script>
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
