### ISSUE TITLE
Importing multiple .proto from strings causes "Duplicate name in namespace"

### ISSUE THREAD

**Issue by Phrogz** [dcodeIO/protobuf.js#452]
``` js
var builder = ProtoBuf.loadProto(
   'syntax="proto3"; message meas { float value=1; float stdDev=2; }', 
   {file:"shared.proto",root:"main.proto"},
   'shared.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; package API; import "shared.proto"; message nob{ meas width=1; } message nobs{ repeated nob message=1; }',
   builder,
   'objects.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; package API; import "objects.proto"; message APIMessage { nobs nobjects=1; }',
   builder,
   'main.proto');
   // /scripts/protobuf.js:38: Error: Duplicate name in namespace Namespace : meas

```

Am I doing something wrong? Is there a way to import these three protos as strings?

**Comment by Phrogz** [comment]
Invalid? I cannot reproduce this now with the test case above (but still seeing the error message in my real protos). Attempting to pare down and repro again.

**Comment by Phrogz** [comment]
Re-opening; confirmed that the exact code above (updated) is failing exactly in this way.

**Comment by Phrogz** [comment]
Possibly the same as #40?

**Comment by Phrogz** [comment]
Here's slightly simplified code, with `.proto` files that I believe are still valid.

```
var builder = ProtoBuf.loadProto(
   'syntax="proto3"; message meas { float value=1; }', 
   {file:"shared.proto",root:"main.proto"},
   'shared.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; import "shared.proto"; message nob{ meas width=1; }',
   builder,
   'objects.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; import "objects.proto"; message nobs{ repeated nob message=1; }',
   builder,
   'main.proto');
// /scripts/protobuf.js:38: Error: Duplicate name in namespace Namespace : meas
```

**Comment by dcodeIO** [comment]
This is working for me:

```js
var builder = ProtoBuf.loadProto(
   'syntax="proto3"; message meas { float value=1; }',
   // {file:"shared.proto",root:"main.proto"}, <- isn't a builder
   'shared.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; import "shared.proto"; message nob{ meas width=1; }',
   builder,
   'objects.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; import "objects.proto"; message nobs{ repeated nob message=1; }',
   builder,
   'main.proto');
```

**Comment by Phrogz** [comment]
The problem is not as simple as I stated. Still debugging. The problem appears to be that I also have a file named `objects.proto` on disk, with similar content (but importing a DIFFERENT, conflicting file, and the third `loadProto` is importing the `objects.proto` from disk instead of the string that I supplied and named `objects.proto`.

Does that make sense? If not, I can try to clarify further.

**Comment by Phrogz** [comment]
Regarding the commented out code, I was confused by this comment for loadProto:

```
/**
 * Loads a .proto string and returns the Builder.
 * @param {string} proto .proto file contents
 * @param {(ProtoBuf.Builder|string|{root: string, file: string})=} builder Builder to append to. Will create a new one if omitted.
 * @param {(string|{root: string, file: string})=} filename The corresponding file name if known. Must be specified for imports.
 * @return {ProtoBuf.Builder} Builder to create new messages
 * @throws {Error} If the definition cannot be parsed or built
 */
```
I thought that the second (`builder`) param was suggesting that an object should be passed in. Am I misreading the comment, or is it in error?

**Comment by dcodeIO** [comment]
The comment basically tells that the second parameter might be a Builder, a filename string or a filename object, while the third, if provided, only accepts a Builder. Documenting it like this is necessary because the Builder argument (2nd) is omittable and thus the 2nd argument may also be a filename.

**Comment by Phrogz** [comment]
This code works, where I've renamed `objects.proto` to `kobjects.proto` to avoid matching a file name available on disk:

```
var builder = ProtoBuf.loadProto( 'syntax="proto3"; message meas { float value=1; }', 'shared.proto');
ProtoBuf.loadProto( 'syntax="proto3"; import "shared.proto"; message nob{ meas width=1; }', builder, 'kobjects.proto')
ProtoBuf.loadProto( 'syntax="proto3"; import "kobjects.proto"; message nobs{ repeated nob message=1; }', builder, 'main.proto');
```

**Comment by dcodeIO** [comment]
Workaround suggestion:

```js
var builder = ProtoBuf.loadProto(
   'syntax="proto3"; message meas { float value=1; }',
   { file: 'shared.proto', root: 'a' });

ProtoBuf.loadProto(
   'syntax="proto3"; import "shared.proto"; message nob{ meas width=1; }',
   builder,
   'a/objects.proto');

ProtoBuf.loadProto(
   'syntax="proto3"; import "objects.proto"; message nobs{ repeated nob message=1; }',
   builder,
   'a/main.proto');
```

**Comment by Phrogz** [comment]
Oh, is THAT what the `root` is for. :) Nice workaround. Shall I close this bug, or mutate the description to mention that `loadProto` fell back to finding files on disk, or is it PEBCAK because I messed up the root on the first one, so it could not find the proper files?

**Comment by dcodeIO** [comment]
It's all fine, others will probably just search for the error message they got.

**Comment by Phrogz** [comment]
I will close it as user error (and others can still find it). If you feel that it is an error for `loadProto` to look for files on disk, feel free to re-open and mutate, or add your own.
