### ISSUE TITLE
protoc --decode_raw < file equivalent in node.js ?

### ISSUE THREAD

**Issue by y3nd** [dcodeIO/protobuf.js#453]
Hi!

What's the equivalent of doing `protoc --decode_raw < file` with node.js ?

Thanks.

**Comment by hebrew878** [comment]
i do also need this.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
