### ISSUE TITLE
this.reset is not defined on build

### ISSUE THREAD

**Issue by cdaringe** [dcodeIO/protobuf.js#454]
hello:

i'm on a fresh install loading a fresh model.  i do the following steps:

``` js
const builder = ProtoBuf.loadProtoFile(PROTO_PATH)
const srv = new builder.build('SomeModel')
```

the following error occurs: `"this.reset is not a function"`

the error occurs here in the source: https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Builder.js#L557

thanks

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
