### ISSUE TITLE
Encode enums by their `int32` value

### ISSUE THREAD

**Issue by kalbasit** [dcodeIO/protobuf.js#455]
Hello,

I have a Go server running [gRPC](https://github.com/grpc/grpc-go) and also serving [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway). I've defined a [proto](https://github.com/publica-project/protobuf-defs/blob/master/logger/event.proto#L15) with an emum. The generated go code expects an enum to be encoded as `int32`, but protobufjs seems to be encoding them as strings.

I am aware that this could be solved with reflection, however, due to the lack of examples re: reflection, can someone help me out to make it encode as an `int32`?

FYI: My code calls `protoMessage.encodeJSON()` to get the JSON out.

**Comment by kalbasit** [comment]
The following worked, but obviously is a hack, any better way to do it?

```
diff --git a/src/ProtoBuf/Builder/Message.js b/src/ProtoBuf/Builder/Message.js
index 4ba5c40..f4864ce 100644
--- a/src/ProtoBuf/Builder/Message.js
+++ b/src/ProtoBuf/Builder/Message.js
@@ -485,12 +485,6 @@ MessagePrototype.toHex = MessagePrototype.encodeHex;
  */
 function cloneRaw(obj, binaryAsBase64, longsAsStrings, resolvedType) {
     if (obj === null || typeof obj !== 'object') {
-        // Convert enum values to their respective names
-        if (resolvedType && resolvedType instanceof ProtoBuf.Reflect.Enum) {
-            var name = ProtoBuf.Reflect.Enum.getName(resolvedType.object, obj);
-            if (name !== null)
-                return name;
-        }
         // Pass-through string, number, boolean, null...
         return obj;
     }
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
