### ISSUE TITLE
[Help Wanted] How to create a 64 uInt

### ISSUE THREAD

**Issue by didix16** [dcodeIO/protobuf.js#457]
Hi guys. I'm using this amazing library but now I need to send a 64 uLong (fixed64) value. I need to do the follwing:
- Get the bytes of a float number
- Get those bytes and generate a uLong number and set the fixed64 field of the message.

I have to do this function in C# into javascript:

public static ulong FloatAsUlong(double value)
        {
            var bytes = BitConverter.GetBytes(value);
            return BitConverter.ToUInt64(bytes, 0);
        }

Thanks in advance

**Comment by dcodeIO** [comment]
You could use DataView for that. First allocate an ArrayBuffer with a size of 8, then write the float, then read two 32 bit integers. `ProtoBuf.Long` can be used to do the rest.

**Comment by didix16** [comment]
Hw should I code it? I never used the Long in protobuf. Also I have a constant variable with u long number but javascript truncate it. So with the Long method could I set it without problems?

I'm coding an auxiliar function to parse it.

function floatToInt(x){

	var a = new ArrayBuffer(8);
	var d = new DataView(a);
	d.setFloat64(0,x);
        var lo = d.getUint32(0);
        var hi = d.getUint32(4);

       //What should I do here?
}

**Comment by dcodeIO** [comment]
`var myulong = ProtoBuf.Long.fromBits(lo, hi, true);`

**Comment by didix16** [comment]
Ok. I supose when protobujs sends the message, it sends correctly, the 8 bytes. I'm gonna test it and I'll feddback to you here. Thanks :)

**Comment by didix16** [comment]
Mmm it seems it does not work. I'm trying to comunicate with an RPC server. It response must contain an api_url value with content but I got it empty and I'm thinking its why my Request is wrong because the C# project is working perfectly (I'm porting a project in C# to javascript nodejs).

I don't know what I'm doing wrong, Is there any method to debug the whole byte buffer that will be send?

I'm using request library to send the protobuf data. This is the method:

this.setServer = function(){

		var RequestType = protoModels.AllEnum.RequestMethod;

		var serverRequest = requestBuilder.getInitialRequestByCustomRequestTypes({
			authToken: this.accessToken,
			authType: this.authType,
			lat: this.currentLat,
			lng: this.currentLng,
			altitude: this.currentAltitude,
			customRequests: [
				RequestType.GET_PLAYER, RequestType.GET_HATCHED_OBJECTS, RequestType.GET_INVENTORY,
                RequestType.CHECK_AWARDED_BADGES, RequestType.DOWNLOAD_SETTINGS
			]
		});

		request({
			url: config.rpcUrl,
			body:serverRequest.toBuffer(),
			method: 'POST',
			responseType: "arraybuffer",
			encoding: null,
			headers: {
				"User-Agent": "Niantic App",
				"Connection": "keep-alive",
				"Accept": "*/*",
				"Content-Type": "application/x-www-form-urlencoded"
			}
		},function(err,incomingMsg,body){

			if(err){
				console.log(DEBUG_MSG_PREFIX+"setServer: RPC First Request Error");
			}else{
				console.log(DEBUG_MSG_PREFIX+"setServer: Response OK =>",body);
			}


			var resp = protoModels.Response.decode(body);
			var eResp = JSON.parse(resp.encodeJSON());

			if(eResp.auth == null) throw new Error(DEBUG_MSG_PREFIX+"setServer: The RPC Server don't authenticate us...")
			that._unknownAuth = resp.get('auth');
			that._apiUrl = resp.get('api_url');

			console.log("APIURL=>",that._apiUrl);
			
		});


	};

And this is my requestBuilder methods:

getInitialRequest: function(options){

		def = {
			authToken: '',
			authType: 0,
			lat: 0.0,
			lng: 0.0,
			altitude: 10.0,
			customRequests: [] //Request.RequestMethod
		};
		extend(def,options);

		console.log("INITIAL_R",def);
		var req = new protoModels.Request({
			altitude: floatToInt(def.altitude),
			auth: new protoModels.Request.AuthInfo({
				provider: def.authType === 0 ? "google" : "ptc",
				token: new protoModels.Request.AuthInfo.JWT({
					contents: def.authToken,
					unknown13: 14
				})
			}),
			latitude: floatToInt(def.lat),
			longitude: floatToInt(def.lng),
			//rpc_id: 1469378659230941192,
			rpc_id: ProtoBuf.Long.fromBits(0x000000008, 0x1464481B, true), //<== 1469378659230941192
			unknown1: 2,
			unknown12: 989,
			requests: def.customRequests
		});

		return req;

	},

	getInitialRequestByCustomRequestTypes: function(options){

		var requestArray = [];

		//Call getInitialRequest
		def = {
			authToken: '',
			authType: 0,
			lat: 0.0,
			lng: 0.0,
			altitude: 10.0,
			customRequests: [] //Request.RequestMethod
		};
		extend(def,options);

		for(var i = 0;i< def.customRequests.length;i++){

			requestArray.push(new protoModels.Request.Requests({type: def.customRequests[i]}));
		}

		def.customRequests = requestArray;

		return this.getInitialRequest(def);
	}

};


function floatToInt(x){

	var a = new ArrayBuffer(8);
	var d = new DataView(a);
	d.setFloat64(0,x);

	var lo = d.getUint32(0);
    var hi = d.getUint32(4);

	return ProtoBuf.Long.fromBits(lo, hi, true);
}

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
