### ISSUE TITLE
toBuffer() not working? Node.js

### ISSUE THREAD

**Issue by UAVova** [dcodeIO/protobuf.js#458]
My app code looks like:

**main.js**

```
const express = require('express');
const app = express();
const ProtoBuf = require("protobufjs");
let builder = ProtoBuf.loadProtoFile("protos/player.proto")
let Main = builder.build("Main")
let Player = Main.PlayerInfo

app.get('/test1', function (req, res) {
  let plr = new Player("name", "123")
  let enc = plr.encode()
  res.send(`Message is: ${enc}`); // Response 'Message is: ByteBufferNB(offset=0,markedOffset=-1,limit=11,capacity=16)'

});
app.get('/test2', function (req, res) {
  let plr = new Player("name", "123")
  let enc = plr.encode()
  res.send(`Message is: ${enc.toBuffer()}`); // Response 'Message is: name123'

});
app.get('/test3', function (req, res) {
  let plr = new Player("name", "123")
  let enc = plr.encode()
  res.send(`Message is: ${plr.toBuffer()}`); // Response 'Message is: name123'

});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

**player.proto**

```
syntax = "proto3";

package Main;

message PlayerInfo {
  required string username = 1;
  required string password = 2; 
}
```

When i visit those pages, i get responses like:

```
/test1 - Message is: ByteBufferNB(offset=0,markedOffset=-1,limit=11,capacity=16)
/test2 - Message is: name123
/test3 - Message is: name123
```

As you see, data is not even encoded\buffer style. But why? Am i doing something wrong?

**Comment by englercj** [comment]
You are outputting the buffer as a string, which outputs the contents not the object. Instead do this:

```js
const buffer = plr.toBuffer();

console.log(Buffer.isBuffer(buffer));
console.log(buffer);
```

You should get `true` and the buffer object.

**Comment by UAVova** [comment]
@englercj Thank you! Do you know if it is possible transfer buffer data using redis.publish? I've established connection between 3 node instances, which is made by using redis channels.

**Comment by englercj** [comment]
Sure, it is dependant upon you redis client. A lot of the only pub/sub strings, so you will need to serialize/deserialize somehow. Either via a binary string or base64 or w/e.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
