### ISSUE TITLE
Enable passing importRoot in the CLI

### ISSUE THREAD

**Issue by splintor** [dcodeIO/protobuf.js#460]
I'm currently trying to use the pbjs CLI
I have:

> FolderA
>      -- a.proto
> 
> FolderB
>      -- b.proto

And **a.proto** has:
`import "FolderB/b.proto";`

The pbjs CLI fails with 

> "failed to import '...\FolderA\FolderB/b,proto' in '...\FolderA\a.proto': file not found"

.
I would like to be able to pass the importRoot in the command line, so the import will look for imports in the correct location.

**Comment by splintor** [comment]
One bypass is to build a dummy file at the root level, and make it include the file(s) I want to build:

**import-all.proto**:
`import "FolderA/a.proto";`

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
