### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by luciusli** [dcodeIO/protobuf.js#466]
I have already converted all my .proto files into one single .json without any imports. However, protobuf.js relies on `fs` and `path` module which are not available on react native. It would be nice if these dependencies are moved to another package.

**Comment by IjzerenHein** [comment]
How do you convert your proto files to a single .json file? Did you do it manually or did you manage to do that in an automated way?

Also, I'm using protobuf with react-native as well, I'm not seeing any errors with the fs and path modules.

**Comment by luciusli** [comment]
Automated. It's fine on Android but not on iOS.

**Comment by IjzerenHein** [comment]
Awesome! Would you mind sharing how you did the automation, scripts etc..?

Hmm, thats weird, I tested on iOS (and only iOS so far) last Friday and it worked just fine (no `fs/path` errors. I'll be doing more integration today, see how that goes. I'm using the 5.0.1 version from NPM.

cheers

**Comment by luciusli** [comment]
I just used the included pbjs cli and file watcher

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
