### ISSUE TITLE
Streaming RPCs

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#468]
GRPC adds the following syntax:

```
service MyService {
  rpc StreamSomething(stream MyRequest) returns (stream MyResponse);
}
```

As far as I can tell the ProtobufJS RPC wrapper doesn't support this right now. Can this be done? 

This works in GRPC with an object which adds a "Send" function, and a channel for receiving messages (basically a buffered stream).

A few interesting things:

 - An error will close the stream. This means a callback would be needed for close, with an optional error param.
 - Server-to-client, client-to-server, or bidirectional streams are possible.

If it's supported in protobufJS to do something like this, I can write another library that does websocket transport of RPC calls.

**Comment by paralin** [comment]
GRPC-node itself has streaming calls, by the way.

**Comment by paralin** [comment]
https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/Builder.js#L279

It expects `request_stream` or `response_stream` in the JSON. But this is not set in the `pbjs` exporter. Making a PR to fix this now.

**Comment by paralin** [comment]
This actually is only partially fixed by the PR, we still need an API surface for streaming RPCs

**Comment by gabrielgrant** [comment]
To confirm: even with #470 , am I correct there's still no API support for streaming calls, right?

**Comment by paralin** [comment]
These days we support AsyncIterable and Observable streams in matrixserver
