### ISSUE TITLE
pbjs: proto3 syntax not declared anywhere in JSON output

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#469]
Throughout protobuf.js there are checks if the syntax is proto2 or proto3, but it seems that pbjs generating JSON representations of proto3 does not have anything mentioning proto3 in it.

Is this correct? I'm getting some errors now regarding serializing a object, it expects it to be a string for some reason.

**Comment by paralin** [comment]
I think the issue is that the JSON representation, when generating over multiple proto files at once, the "package" at the top is null, and there is no "syntax" field as there is no top level proto file.

**Comment by aybmab** [comment]
Hey @paralin, did you ever get around this?

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
