### ISSUE TITLE
proto3 default values

### ISSUE THREAD

**Issue by rosek86** [dcodeIO/protobuf.js#471]
Hi,

I have a very simple message as the one below. That message is compiled to json using pbjs. I try to set mode field to 0, encode and then decode the message. When the message is decoded mode field no longer have 0 value but it is set to null.

Looking on the documentation for proto3, the default value for number should be decoded as 0 number:
https://developers.google.com/protocol-buffers/docs/proto3#default

Please let me know if I can provide more details about my problem.

Many thanks,
Krzysztof 

```
syntax = "proto3";

package Package;

message Data {
  uint32 mode = 1;
}
```

**Comment by paralin** [comment]
This is probably because `pbjs` does not seem to include the proto3 syntax in some cases.

**Comment by paralin** [comment]
#380

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
