### ISSUE TITLE
Decoding Redis value

### ISSUE THREAD

**Issue by mariepascale** [dcodeIO/protobuf.js#472]
I am trying to get a value in Redis which has been encoded in C# using protobuf. I have the .proto file. I need to access this value in a node app. I am able to get this value from Redis using a key in the node app. I can decode the value from Redis using protobufjs but, when I console log the data some of the data contains something like this \n�\u0001. Is the it corrupt? Is it encrypted? How do I fix this?

**Comment by goeldeepika3** [comment]
:hankey:

**Comment by dcodeIO** [comment]
Is your data, somewhere on its path, converted to a string and back?

https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
