### ISSUE TITLE
toRaw method without resolvedType

### ISSUE THREAD

**Issue by yagop** [dcodeIO/protobuf.js#473]
¿Its possible to convert a message to raw without converting the resolvedType?

https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L541
https://github.com/dcodeIO/protobuf.js/blob/5.0.1/src/ProtoBuf/Builder/Message.js#L526

Regards

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
