### ISSUE TITLE
Would a 'protojs' target format be a welcome addition to pbjs?

### ISSUE THREAD

**Issue by jonathon-love** [dcodeIO/protobuf.js#477]
hi,

i notice that the pbjs output for a js target begins:

```
module.exports = require("protobufjs").newBuilder({})['import']({
```

and then contains all the JSON. i was wondering about implementing a `protojs` version, where it might contain:

```
module.exports = require("protobufjs").loadProto("  <contents the .proto file  >   ");
```

this would be an alternative to the js representation which would not have the issue #471, and would presumably require very little effort to implement.

would such a contribution be welcome? or am i better off saving my time?

with thanks

**Comment by paralin** [comment]
I don't see why you would do this? Why not just preparse the proto lang if you can do compilation before runtime?

**Comment by jonathon-love** [comment]
compilation before runtime (i.e. using `pbjs`) does not produce code which conforms to the proto3 spec. see #471 for more details.

where as loading from a .proto file does.

**Comment by paralin** [comment]
@jonathon-love that's a bug, and should be fixed.

**Comment by jonathon-love** [comment]
in an ideal universe, yes. but it doesn't look like it's getting fixed any time soon.

my suggestion seems like a good middle-ground between not fixing the bug, and the bug not being fixed :)

**Comment by paralin** [comment]
it makes no sense though. the pbjs tool here is doing absolutely nothing-

**Comment by jonathon-love** [comment]
for me the questions is "does this fix things for people?", not "is the tool working hard enough?"

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
