### ISSUE TITLE
Message.encodeJSON output is incompatible with Message.decodeJSON

### ISSUE THREAD

**Issue by gmatroskin** [dcodeIO/protobuf.js#478]
In an express app I am building, I tried to create an encoding agnostic endpoint that can accept a protobuf represented as JSON if given `application/json` as content type - the primary goal being easier testing in dev.

My plan was to use `encodeJSON/decodeJSON` to accomplish this, but I found that the two functions appear incompatible due to `encodeJSON` including the _virtual_ `oneof` fields, and `decodeJSON` failing to recognize them.  Not sure if I am missing something 

Assuming this is indeed an issue, I feel like the right way to solve this may be to exclude the virtual fields from `encodeJSON` output, but that will probably be a breaking change for most people, so perhaps making the parser ignore them (possibly having verified they are correctly set) is a good compromise...

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
