### ISSUE TITLE
No way to tell namespace vs message in json

### ISSUE THREAD

**Issue by englercj** [dcodeIO/protobuf.js#479]
In the JSON output messages and namespaces look exactly the same. This is a problem when I am trying to generate code because I don't know if the object is a message or a namespace. Different code is generated depending on which it is.

Can we add an "isNamespace" field or something here: https://github.com/dcodeIO/protobuf.js/blob/master/cli/pbjs/targets/json.js#L61

That would let us know if what we are parsing is a message or just a namespace.

Thanks!

**Comment by dcodeIO** [comment]
Actually I believe that all namespaces should be messages anyway, with the only difference being that a message has fields and thus encodes something while namespaces simply encode, well, nothing. I am currently working something out in this regard locally, drastically reducing the amount of code required to make this work.

Stuff like:

``` js
    this.create(["google", "protobuf"])
       .add(new Message("Any")
           .add(new Field("type_url", 1, "string"))
           .add(new Field("value", 2, "bytes")
        )
    );
```

Or 

```json
{
  "nested": {
    "google": {
      "nested": {
        "protobuf": {
          "options": {
            "go_package": "descriptor",
            "java_package": "com.google.protobuf",
            "java_outer_classname": "DescriptorProtos",
            "csharp_namespace": "Google.Protobuf.Reflection",
            "objc_class_prefix": "GPB",
            "optimize_for": "SPEED"
          },
          "nested": {
            "FileDescriptorSet": {
              "fields": {
                "file": {
                  "rule": "repeated",
                  "type": "FileDescriptorProto",
                  "id": 1
                }
              }
            },
            "FileDescriptorProto": {
              "fields": {
                "name": {
                  "type": "string",
                  "id": 1
                },
                "package": {
                  "type": "string",
                  "id": 2
                },
                "dependency": {
                  "rule": "repeated",
                  "type": "string",
                  "id": 3
                },
                "public_dependency": {
                  "rule": "repeated",
                  "type": "int32",
                  "id": 10
                },
...
```

P.S. It is currently built with pixify 🍰

**Comment by englercj** [comment]
Sounds good, I understand that packages and messages are similar in the encoding world; but when using the json output to generate code I need to know the distinction. Simply checking if there are fields or not is insufficient because a message may have no fields.

For example this proto:

```protobuf
package my.namespace;

message Something {}
```

Would ouput json like:

```json
{
    "package": "my.namespace",
    "messages": [
        {
            "name": "Something",
            "fields": []
        }
    ]
}
```

Which is great, code-gen would work perfectly. I can output TypeScript code like:

```typescript
module my.namespace {
    class Something() {}
}
```

But say I have two files, and the second look like this:

```protobuf
package my.namespace.other;

message SomethingElse {}
```

Those together would generate json like:

```json
{
    "package": "my.namespace",
    "messages": [
        {
            "name": "Something",
            "fields": []
        },
        {
            "name": "other",
            "fields": [],
            "messages": [
                {
                    "name": "SomethingElse",
                    "fields": []
                }
            ]
        }
    ]
}
```

Now the `other` spackage looks just like a message, so I would generate something like this:

```typescript
module my.namespace {
    class Something() {}

    class other() {}
    module other {
        class SomethingElse() {}
    }
}
```

I can work around this based on limitations in my project but I would *have* to generate that `class other()` because it looks like a message, when in fact it isn't one and you should not be able to make an instance of it. But I have no way to know that. Its less of a mater of what is needed for encoding, and more of wanting enough metadata for the json output to be more useful that just encoding.

**Comment by dcodeIO** [comment]
Alright. Hope you'll like the below more, though, when it's time:

```js
module.exports = RuntimeMessage;

/**
 * Runtime message base class ready to be extended by generated code.
 * 
 * It is important that this class is not used directly so that its
 * fields are declared on the prototype of a runtime message and not
 * on the runtime message itself.
 * 
 * @constructor
 * @param {!Message} type Reflected message
 * @abstract
 */
function RuntimeMessage(type) {

    /**
     * Reference to the reflected message.
     * @type {!Message}
     */
    this.$type = type;
}

var RuntimeMessagePrototype = RuntimeMessage.prototype;

/**
 * Returns a string representation of this runtime message.
 * @returns {string}
 */
RuntimeMessagePrototype.toString = function() {
    return this.$type.name;
}
```

**Comment by englercj** [comment]
Sounds awesome :)

Looking forward to it!
