### ISSUE TITLE
API Docs page is broken

### ISSUE THREAD

**Issue by iamtheddrman** [dcodeIO/protobuf.js#480]
From the GitHub page, the "API Docs" link redirects to http://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/ProtoBuf.js/master/docs/ProtoBuf.html and then shows "No definition found for Table headers".

Tested with Chrome 53 and Firefox 48 on Windows 7.

**Comment by dcodeIO** [comment]
Seems to be working again. Can you confirm? Probably an issue on the htmlpreview side of things.

**Comment by iamtheddrman** [comment]
It was working when you commented up until the switchover for the v6 branches, and now it appears to be broken again. I can see the v6 documentation from the main readme.md, but not from the link on the ProtoBuf5 branch (https://github.com/dcodeIO/protobuf.js/tree/ProtoBuf5). I get the same error from the same link: http://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/protobuf.js/master/docs/ProtoBuf.html

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by iamtheddrman** [comment]
I've reviewed the release notes and caveats for v6.0.0 and it seems heavily focused on proto3 rules/semantics. My company isn't switching to proto3 any time soon (we have many required fields in our messaging schemas), so switching to v6.0.0 would be a lot of code changes for no benefit.

Would it be possible to put the v5 documentation in the new format and select which version of the API to look at? Many libraries do this (lodash, Angular, etc). I can open a new issue if you'd like to track that separately. For now, I can get by with viewing the local build of the docs.

**Comment by dcodeIO** [comment]
It's still available but a few links (on the wiki etc.) need to be updated: http://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/ProtoBuf.js/ProtoBuf5/docs/index.html

**Comment by iamtheddrman** [comment]
Great. Thanks!
