### ISSUE TITLE
ArrayBuffer vs ArrayBufferView

### ISSUE THREAD

**Issue by arbesfeld** [dcodeIO/protobuf.js#481]
I am calling this in Safari:

```
const req  = new XMLHTTPRequest();
...
req.send(protobuf.toArrayBuffer());
```

and seeing this warning:

```
ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead.
```

Are there any known workarounds?

**Comment by dcodeIO** [comment]
Try:

```js
req.send(new Uint8Array(protobuf.toArrayBuffer()));
```

**Comment by arbesfeld** [comment]
Thanks @dcodeIO! That seems to work on Safari/Chrome but I'm getting this error on Firefox:

`NS_ERROR_CANNOT_CONVERT_DATA:`

I'll report back to see if any of the other constructors work.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
