### ISSUE TITLE
Sub-namespaces in protobuf.js json builder

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#482]
It's possible to have sub-namespaces with the pbjs json output. The builder incorrectly loads them as Messages. It would be good to instead label these as `className == Namespace`.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
