### ISSUE TITLE
inherits mutiple Message to one?

### ISSUE THREAD

**Issue by xingyuzhe** [dcodeIO/protobuf.js#486]
I have 2 .proto files named a.proto and b.proto. I want to get a new Messsage contains Fields from both of a.proto and b.proto. I've read the documents and issures, but have not found a solution yet. I notice that there's a static method named inherits on top level in documents, but there is not In fact. I'm i missed something?

**Comment by dcodeIO** [comment]
It seems that you are using the development branch, which is still heavily in flux. If you are not just toying with this, you should probably use [the current stable version](https://github.com/dcodeIO/protobuf.js/tree/ProtoBuf5) for now.

**Comment by xingyuzhe** [comment]
I just use `import protobuf from protobufjs` , it's version is 5.0.1.  It should be the current stable version.

**Comment by xingyuzhe** [comment]
@dcodeIO  I've found the inherits  code in branch master,  so there may be some problem with the npm package

**Comment by dcodeIO** [comment]
I see. Yes, you are currently using the stable version, just reading the development docs.
