### ISSUE TITLE
Receiving error HS: ACCEPT missing often when trying to connect

### ISSUE THREAD

**Issue by sjames1958gm** [dcodeIO/protobuf.js#487]
Using the test client as a guide (building client code into my app) I am trying to connect to 
wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize
For most attempts I am receiving error HS: ACCEPT missing
Sometimes I get a completed connection.
Any clues as to why?

**Comment by dcodeIO** [comment]
Could be an issue on the transport layer, or related to: https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F if there are string conversions happening that may corrupt the data you send.

**Comment by sjames1958gm** [comment]
Sorry - posted this to the wrong project - too many tabs open.
