### ISSUE TITLE
Proto to JSON

### ISSUE THREAD

**Issue by eltoro** [dcodeIO/protobuf.js#488]
Other than using pbjs, Is there an easy way to parse a protocol buffer object into a JSON format like:

```
{
  package: '',
  services: [ ],
  messages: []
}
```

I'm using protobuf.js 5 through grpc.load(). Right now I'm parsing it manually.

**Comment by dcodeIO** [comment]
You could manually spin up an instance of [ProtoBuf.Parser](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/DotProto/Parser.js).

**Comment by eltoro** [comment]
Thanks, that worked. Is there a way to turn off the shell formatting stuff?
