### ISSUE TITLE
Error decoding message using map field when value is a message

### ISSUE THREAD

**Issue by delapavap** [dcodeIO/protobuf.js#492]
I'm having some problems trying to decode a message that uses a Map field.

```
message SignPartition {

    option (test_message).extends = "AbstractParametrizedAttributeTile";
    repeated SegmentAnchor segment_anchors = 1 [(test_field).pool = "signs" ];
    map<string, AnchorReferences> signs = 2 [(test_field).in_pool = "signs" ];
    repeated SpeedLimitAttribute speed_attrs = 10;
    repeated SignMetadata metadata = 11;  

    message AnchorReferences {
       repeated uint32 anchor_references = 1;
       string timestamp = 2;
    }
}
```
the error that I get is the following:

Illegal wire type for field Message.Field SignPartition.AnchorReferences.anchor_references: 2 (0 expected)

I tried using a map<string,string> and It worked, so I think the problem is when the value is a message instead of a simple type.

I forgot to mention that i'm using the stable version of protobuf.js.

Thanks

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
