### ISSUE TITLE
Cannot know is repeated field empty or not set at all

### ISSUE THREAD

**Issue by teemupiiroinenwirepas** [dcodeIO/protobuf.js#493]
This is more like a question. How I can know is decoded message's repeated field just empty, or has it been set at all?

In both cases I get an empty array. I would think that in the case where it is not set at all, the value would be null or undefined.

**Comment by dcodeIO** [comment]
There is currently no way to know that

**Comment by teemupiiroinenwirepas** [comment]
Thanks for the information. Is this something that can be checked in the future with v6.0?

**Comment by dcodeIO** [comment]
With v6, default values are on the prototype. For all basic types it is therefore possible to check if the value is present on the wire using `myMessage.hasOwnProperty('myField')` for example.

**Comment by teemupiiroinenwirepas** [comment]
Ok, thanks
