### ISSUE TITLE
Failed to get the ProtoBuf object in browser environment with the latest update

### ISSUE THREAD

**Issue by tibetty** [dcodeIO/protobuf.js#494]
I introduce protobufjs library & its dependencies with below lines in a html:
```
<script src="https://cdn.rawgit.com/dcodeIO/long.js/master/dist/long.min.js"></script>
<script src="https://cdn.rawgit.com/dcodeIO/bytebuffer.js/master/dist/bytebuffer.min.js"></script>
<script src="https://cdn.rawgit.com/dcodeIO/protobuf.js/master/dist/protobuf.min.js"></script>
```

And use below statement to get ProtoBuf object:
let protobuf = dcodeIO.ProtoBuf;

It used to work pretty well, but recently (maybe after the latest release of the protobufjs version) I encountered failures with undefined value in protobuf variable.  When I try to log out dcodeIO object, I can only see 2 available fields: ByteBuffer & Long, and ProtoBuf get lost.  I highly suspect it's an compatibility issue caused by the latest update.  How to get ProtoBuf object in this version?  What's the new API?  

Thanks in advance!

**Comment by dcodeIO** [comment]
The master branch now hosts the development version of protobuf.js 6. Try replacing protobuf.min.js with:

```
<script src="https://cdn.rawgit.com/dcodeIO/protobuf.js/ProtoBuf5/dist/protobuf.min.js"></script>
```

**Comment by tibetty** [comment]
Many thanks for the prompt response! My issue was solved - it turned out that it's not a good practice to use the most updated release in a real world web app, :).  Thank you again, @dcodeIO !
