### ISSUE TITLE
Don't resolve Enums to strings?

### ISSUE THREAD

**Issue by f5io** [dcodeIO/protobuf.js#506]
Is there a way to not have protobuf.js resolve enums to strings? I'd like them to resolve to their uint32 values if possible.

**Comment by dcodeIO** [comment]
Which version are you using?

**Comment by f5io** [comment]
Currently using ^5.0.0 as defined by the `grpc` node lib. I'm guessing thats probably a problem :/

**Comment by dcodeIO** [comment]
Hard to tell without knowing which part of the API you are using.

There are reflected enums for example that allow converting between string and number values. Also, enums are represented by their numeric ids on message instances, but these are converted to strings when using `Message#toRaw`.

**Comment by f5io** [comment]
yes, looks like this is the culprit, https://github.com/grpc/grpc/blob/master/src/node/src/common.js#L69

**Comment by paralin** [comment]
This happens in grpc-node as well.

**Comment by f5io** [comment]
Gonna close this, this is an issue with grpc lib. Thanks for the awesome work on protobuf.js :)
