### ISSUE TITLE
How to instantiate Service?

### ISSUE THREAD

**Issue by pronebird** [dcodeIO/protobuf.js#507]
Hi,

I am following the example at https://github.com/dcodeIO/protobuf.js/wiki/Services and creating my RPC.

Everything seems fine but I cannot create a new instance of Service. it says:

> Service is not a constructor

```js
  var Service = root.lookup('MailService');
  var RequestType = root.lookup('RequestType');
  var ResponseType = root.lookup('ResponseType');

  function rpcHandler(method, req, callback) {
    var request = RequestType.decode(data);
    var response = new ResponseType();

    if(method === '.MailService.addMailbox') {
      // add mailbox
    } else if(method === '.MailService.removeMailbox') {
     // remove mailbox
    }

    callback(response.toBuffer());
  }

  var srv = new Service(rpcHandler); // CRASH
```

**Comment by dcodeIO** [comment]
The documentation refers to protobuf.js 5.

Using protobuf.js 6, services are instances of the [service class here](https://github.com/dcodeIO/protobuf.js/blob/master/src/service.js). You can look them up, but there is not a lot of functionality within. You can, however, get the resolved request and response types of the respective methods.

**Comment by dcodeIO** [comment]
This commit adds the following API:

```js
var MyService = root.lookup("MyService");

// Implement the RPC channel:
function rpc(method, requestData, callback) {
  // send requestData (binary) over the network
  ...
  // then call the callback with error, if any, and responseData (binary)
  callback(null, responseData);
}

// Create a runtime service:
var service = MyService.create(rpc, /* requestDelimited? */ true, /* responseDelimited? */ true);

// Call its methods:
service.MyMethod({ awesomeField: "awesomeText" }, function(err, responseMessage) {
   ...
});
```

**Comment by dcodeIO** [comment]
Feel free to reopen if there are still any issues or if you have a suggestion on how this should be implemented.

**Comment by pronebird** [comment]
@dcodeIO thanks Daniel! Works like a charm! 

One quick question, maybe I found a bug...: 

So in RPC I do this:

```js
  function rpc(method, requestData, callback) {
    var request = RequestType.decode(requestData); // CRASH in ReaderPrototype.skip on throw indexOutOfRange(this);
```

Trying to debug:
```js
requestData.toString()
"\u0000"
```

I know it's silly that my messages are empty at the moment, but I guess it shouldn't crash anyway:

```
message RequestType {}
message ResponseType {}

service MailService {
  rpc addMailbox(RequestType) returns (ResponseType);
  rpc removeMailbox(RequestType) returns (ResponseType);
}
```

**Comment by dcodeIO** [comment]
So, your messages are length delimited, right? Did you specify that to Service.create?

```js
var myService = MyService.create(/* your rpc implementation */ rpc, /* requestDelimited? */ true, /* responseDelimited? */ true);
```

**Comment by pronebird** [comment]
Well I am not sure whether message without any fields is delimited or not. But if I create RPC with `MailService.create(rpc, false, false)` then it works fine.

**Comment by dcodeIO** [comment]
Above you mentioned that, in one of your messages, there was a single zero byte:

```
$ requestData.toString()
"\u0000"
```

That's why I assumed that it is a length-delimited empty message.

**Comment by pronebird** [comment]
Yeah strange, that's how I call the method:

```js
service.addMailbox(RequestType.create(), function (err, res) {
    console.log(err);
});
```

Not sure where 0-byte comes from. RequestType as is without any fields.

**Comment by dcodeIO** [comment]
Strange. in fact. The code encoding to a buffer is here: https://github.com/dcodeIO/protobuf.js/blob/master/src/service.js#L159

If shouldn't generate the zero byte, except if there is something true-ish specified for `requestDelimited`.

**Comment by pronebird** [comment]
This is the source code if it helps ( bare bones)

```js
#!/usr/bin/env node

var ProtoBuf = require("protobufjs");

ProtoBuf.load('mailservice.proto', function (err, root) {
  var MailService = root.lookup('MailService');
  var RequestType = root.lookup('RequestType');
  var ResponseType = root.lookup('ResponseType');

  function rpc(method, requestData, callback) {
    var request = RequestType.decode(requestData);

    if(method.fullName === '.MailService.addMailbox') {
      // add mailbox
      var response = ResponseType.create();
      callback(null, response);
    } else if(method.fullName === '.MailService.removeMailbox') {
      // remove mailbox
      var response = ResponseType.create();
      callback(null, response);
    } else {
      throw new Error('Not implemented.');
    }
  }

  var service = MailService.create(rpc, true, false);
  service.addMailbox(RequestType.create(), function (err, res) {
    console.log(err);
  });
});
```

mailservice.proto:

```proto
syntax="proto3";

message Mailbox {
  required string name = 1;
  repeated Mail messages = 2;
}

message Mail {
  string subject = 1;
  string body = 2;
}

message RequestType {}
message ResponseType {}

service MailService {
  rpc addMailbox(RequestType) returns (ResponseType);
  rpc removeMailbox(RequestType) returns (ResponseType);
}
```

**Comment by pronebird** [comment]
Hey, quick question:

so with Protobuf.js I can create RPC server in Node.js and that's pretty clear, however, how do I define an RPC client? Do I have to funnel data to remote RPC and pass back results somehow? I use ZeroMQ as transport. As I understand there is no serialization protocol for that?

**Comment by dcodeIO** [comment]
The is an example [in the README](https://github.com/dcodeIO/protobuf.js#using-services).

There is also a streaming rpc example [here](https://github.com/dcodeIO/protobuf.js/blob/master/examples/streaming-rpc.js).

**Comment by pronebird** [comment]
@dcodeIO thanks. I figured that it works on network level so it was easy to wire up everything!
