### ISSUE TITLE
CLI not usable under Unix

### ISSUE THREAD

**Issue by vanthome** [dcodeIO/protobuf.js#511]
The line endings of the `bin/pbjs.js` are CRLF while they should be LF.
It leads to an error message _/usr/bin/env: „node\r“: ...._ when you invoke the CLI.
This is for example discussed here: https://github.com/nwjs/nw-builder/issues/75.

**Comment by vanthome** [comment]
That's weird, the code is correctly formatted with LF but all code published on NPM is not.
I suspect that you checked out on windows and then published with CRLF.
There is also a discussion here about this:
https://github.com/npm/npm/issues/2097
To fix it, you need to increment the version and publish it again.

**Comment by gaccob** [comment]
I got the same problem now,  expecting this bug to be fixed :)

**Comment by dcodeIO** [comment]
Noooo that bug again. Fixed.
