### ISSUE TITLE
Missing protobuf.js documentations

### ISSUE THREAD

**Issue by bennyn** [dcodeIO/protobuf.js#516]
Google indexes 2 pages ("Getting-started" & "Installation") which are now gone from the [protobuf.js wiki](https://github.com/dcodeIO/protobuf.js/wiki):

![unbenannt](https://cloud.githubusercontent.com/assets/469989/20867370/1561e45a-ba43-11e6-82b7-277992f51e32.PNG)

Can you please bring them back or redirect those pages? I am also missing the documentation about the **pbjs** tool. 😢

**Comment by dcodeIO** [comment]
I have integrated the missing wiki pages into the README of v5. Publishing this with prior to next release of v6, so that npm keeps showing the latest README.

**Comment by dcodeIO** [comment]
README is now updated: https://github.com/dcodeIO/protobuf.js/tree/ProtoBuf5

**Comment by bennyn** [comment]
Thanks, @dcodeIO! 🎉
