### ISSUE TITLE
Cannot convert proto files to js format using pbjs

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#522]
I am trying to convert .proto file to javascript target but I am getting below error :
My protobufjs version is:
protobuf.js v6.0.2 cli

```
$ pbjs cat.proto -target=js > cat_pb.js
module.js:474
    throw err;
    ^
Error: Cannot find module '/restore/test/js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.exports.main (/usr/lib64/node_modules/protobufjs/cli/pbjs.js:64:18)
    at Object.<anonymous> (/usr/lib64/node_modules/protobufjs/bin/pbjs:4:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

My proto file is below :

```
syntax = "proto3";
package demo;
message Cat {
   required string name = 1;
   required     int32 age = 2;
	message Parent {
		required     string name = 1;
	        required     string email = 2;
			}
	repeated Parent parents =4;
}
```
Please suggest.

**Comment by dcodeIO** [comment]
protobuf.js 6's `pbjs` does not have a js target. It has `proto2`, `proto3`, `json` and `static`. A `classes` target similar to `js` of protobuf.js 5 is planned but would benefit a lot from generation multiple files (one for each class, but currently pbjs generates a single file only).

**Comment by Arun-KumarH** [comment]
So which versions of `pbjs` currently support the target js / commonjs ?
When is the expected planned release for `pbjs` support for prtobuf.js 6's version ?

**Comment by dcodeIO** [comment]
The `js` target you are looking for is currently available with protobuf.js 5. Technically, it is not much different from what is described [here](https://github.com/dcodeIO/protobuf.js#command-line) for protobuf.js 6, which uses the `json` target and loads its output through `Root.fromJSON`.

The `js` target of protobuf.js 5 basically just loads the `json` output in a CommonJS wrapper.

I'd recommend that you use protobuf.js 6 with the `json` target and just wrap this up as:

````js
module.exports = protobuf.Root.fromJSON(%INSERT_GENERATED_JSON_HERE%);
```

**Comment by dcodeIO** [comment]
You can use `json-module` now, which is basically what `js` was before. Use the `--wrap` argument in case you'd like to have a custom CommonJS-only wrapper.

**Comment by Arun-KumarH** [comment]
Does `js` here mean `json-module` for java script. I was looking for java script file which would be generated from `pbjs` some thing like `protoc --proto_path=. --js_out=import_style=commonjs,binary:. test.proto` - so a file similar to test_pb.js file which would be generated by protoc but using pbjs on cli, is that not possible using `pbjs` ?

**Comment by dcodeIO** [comment]
For static code, use the `static-module` target. This is still somewhat experimental, though, so let me know of any issues.
