### ISSUE TITLE
Streaming RPCs / GRPC Compatibility

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#529]
We need to add a API surface for streaming RPCs.

Have a look at how GRPC node does it: http://www.grpc.io/docs/quickstart/node.html

I would recommend mirroring that exactly and then attempting to convert grpc-node to use the protobuf.js pattern.

**Comment by dcodeIO** [comment]
Once implemented through [Service.create](https://github.com/dcodeIO/protobuf.js/blob/master/src/service.js#L159) with a RPC implementation, the API actually looks quite similar:

```js
var Greeter = root.lookup("Greeter");
var greeter = Greeter.create(myRpcImpl);

// Now you can use (rename the method to begin with a lower case letter here?)
greeter.SayHello({ name: "you" }, function(err, res) {
  ...
});
```

The RPC implementation can be quite everything that takes a request and asynchronously returns a response.

**Comment by paralin** [comment]
Yes, but it needs to be able to take a stream of request or response
messages (not sure if you're just comparing the current implementation or
saying it doesn't need changing)

**Comment by dcodeIO** [comment]
I refer to the API described at http://www.grpc.io/docs/quickstart/node.html - which doesn't seem to cover streams explicitly - but I assumed it is also the API for streaming buffers, which in this case should be possible to be implemented with a rpcImpl. I might just be missing something.

**Comment by paralin** [comment]
Try this one: http://www.grpc.io/docs/tutorials/basic/node.html

**Comment by dcodeIO** [comment]
Hmm, stream classes. I'd rather try to avoid these as this potentially adds a lot of usually-unused code to the library. I'll probably try to use the current rpcImpl stuff first to implement streaming RPC. Requirements: Multiple requests, common callback, right?

**Comment by paralin** [comment]
Yes, as well as a number of events (end, error, data, status, meta)

**Comment by dcodeIO** [comment]
What about...

* data: `callback(null, someMessage)`
* error: `callback(someError)`
* end: `callback(null, null)`

And to signal end, also sending a `null` message.

**Comment by paralin** [comment]
How would you send multiple messages from the client side? Is this really
better than the grpc way?

**Comment by dcodeIO** [comment]
From an API perspective, using stream classes will most likely always look and feel better. The alternative I am proposing would simply not require dedicated stream classes at all.

Let me prepare an example.

**Comment by dcodeIO** [comment]
[Example](https://github.com/dcodeIO/protobuf.js/blob/master/scripts/rpc-test.js)

**Comment by paralin** [comment]
@dcodeIO see https://github.com/grpc/grpc/issues/8991 and https://github.com/grpc/grpc/pull/9004

**Comment by dcodeIO** [comment]
Seems `loadSync` will be a thing pretty soon :)

**Comment by paralin** [comment]
I'm sitting here converting every single one of their tests to use async `load`...

Would be great if there was `loadSync`, haha.

Running into one issue right now @dcodeIO. How do we `load` with an alternate root dir? Before we could pass an object into `load` to do this.

**Comment by dcodeIO** [comment]
There is no such option anymore, but there is:

```js
/**
 * Resolves the path of an imported file, relative to the importing origin.
 * This method exists so you can override it with your own logic in case your imports are scattered over multiple directories.
 * @function
 * @param {string} origin The file name of the importing file
 * @param {string} target The file name being imported
 * @returns {string} Resolved path to `target`
 */
RootPrototype.resolvePath = util.resolvePath;
```

**Comment by paralin** [comment]
@dcodeIO This is a bit clumsy with the grpc single-function `load`... I guess if people want a different root they will have to build a protobuf.js Root first and then pass it to `loadObject` in GRPC

**Comment by dcodeIO** [comment]
What if protobuf.js would support something like...

```js
protobuf.load("file.proto;../otherdir", ...);
```

Using everything after `;` as the root?

**Comment by paralin** [comment]
@dcodeIO I solved it like this: https://github.com/grpc/grpc/pull/9004/commits/6c077665a2ebf373e5e8afdffa19cb5bd86a60b2#diff-06d976047eb70c6a503cf5b260e71feeR215

That solution is a bit clunky but I guess it could work.

I think the most urgent thing to fix is `loadSync` since grpc downstream doesn't seem to like loading async (breaks their API too much).

I could put my current solution into a `loadAsync` function in grpc.

**Comment by paralin** [comment]
OK, I guess I'm blocked here until `loadSync` is done. Other than that GRPC should be easy to finish upgrading.

**Comment by dcodeIO** [comment]
There it is. Didn't really test it yet.

**Comment by paralin** [comment]
Neat, will implement and get back to you.

**Comment by dcodeIO** [comment]
Note: I just changed util.resolvePath to be util.path.resolve. Iirc, you are using this explicitly where overriding Root#resolvePath (which keeps its name).

**Comment by dcodeIO** [comment]
On npm now!

**Comment by dcodeIO** [comment]
Closing this issue for now. Feel free to reopen it if necessary!
