### ISSUE TITLE
TypeScript: Cannot find type definition file for 'node' and 'long'

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#530]
Get error even use `tsd install node long` when compile.

> node_modules/protobufjs/types/protobuf.js.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/protobufjs/types/protobuf.js.d.ts(2,1): error TS2688: Cannot find type definition file for 'long'.

**Comment by twoeo** [comment]
Works well if remove this from protobuf.js.d.ts
> /// <reference types="node" />
/// <reference types="long" />

And `tsd install node long`.

Or remove node_modules/protobufjs/types, and `tsd install protobufjs node`

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/protobuf.js/pull/527#issuecomment-265608946

Seems that the ideal way depends on the environment. Are you aware of any documented standard on how referencing definition dependencies is supposed to be done?

**Comment by paralin** [comment]
Easy solution.

In a post-build step, delete the two `/// <reference types` lines. This doesn't actually cause any problems anywhere.

We do similar in other projects with `es6-promise` references.

**Comment by dcodeIO** [comment]
The `/// reference` lines aren't generated anymore, which should fix the problem.
