### ISSUE TITLE
Question: Issue after removing newBuilder function in pbjs 6.0.2

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#533]
I migrated from 5.0.1 to 6.0.2 and I get newBuilder is not a function.

TypeError: ProtoBuf.newBuilder is not a function

 const builder = ProtoBuf.newBuilder({convertFieldsToCamelCase: true,});
 ProtoBuf.loadProto(file, builder, {file: fileName,root});

Is newBuilder  function not supported in version6 ?

**Comment by dcodeIO** [comment]
Builder functionality has been integrated into reflection.

See: [Changes in protobuf.js 6](https://github.com/dcodeIO/protobuf.js/wiki/Changes-in-protobuf.js-6.0)

The new API is described in more detail [within the README](https://github.com/dcodeIO/protobuf.js).

**Comment by Arun-KumarH** [comment]
I am still having issues loading grpc objects.
Below is the source code and I get an error when loading grpc objects `grpc.loadObject(this.$pbRoot.ns)`:

```
TypeError: Cannot read property 'className' of undefined
at Object.loadObject (node_modules/grpc/src/node/index.js:65:12)
```

build protobuf:
```
function buildProtobuf(files, root, logger) {
  const protoBufRoot = new ProtoBuf.Root();
  _.forEach(files, (fileName, key) => {
    const ok = protoBufRoot.files[fileName];
    if (ok) {
      return;
    }
    const file = fs.readFileSync(root + fileName, 'utf8');
    ProtoBuf.load(file, protoBufRoot, {
      file: fileName,
      root
    });
  });
  return protoBufRoot;
}
```
loading grpc object and creating service:
```
this.$pbRoot = buildProtobuf(protos, protoRoot, logger);
this.$proto = grpc.loadObject(this.$pbRoot.ns);
this.$service = _.get(this.$proto, this.$config.service);
```
Is this an issue or am I doing something wrong here ?

**Comment by dcodeIO** [comment]
Afaik the currentl grpc is still using protobuf 5, hence you need protobuf 5 for working with it.

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen if that wasn't the issue.
