### ISSUE TITLE
6.0.2/6.1.0 release tracking

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#537]
Hey @dcodeIO sorry to make an issue about this, but whenever you spin 6.0.2 or 6.1.0 please give me a ping here / close this issue so I can fix this: https://github.com/paralin/grpc/blob/refactor-protobufjs-6/package.json#L37

**Comment by dcodeIO** [comment]
I am ready so far to release 6.1.0 on npm. Are the features you required all in and working?

**Comment by paralin** [comment]
I think so. The tests that are failing now on grpc are related to interop, and I have no idea if it's something protobuf.js is causing or something else internal. It could be because of the transition from underscore -> camel case in the Node bindings to grpc-c. Waiting to hear back from them.

For my other projects I've internally hopped to Protobuf.JS 6 and am using tarball links right now until you publish. I'm doing a lot of Typescript typings generation / transpiliation internally (to graphql too, actually) so I'll be sure to report any other issues to you. For now, looks good!

**Comment by dcodeIO** [comment]
Alright, it's up!

**Comment by paralin** [comment]
Looks good! Thanks!
