### ISSUE TITLE
node.js protobufjs decode issue with import proto

### ISSUE THREAD

**Issue by supersuraccoon** [dcodeIO/protobuf.js#543]
I am using protobuf.js v6.1.0  in node.js.

Here is my proto files:

socket.proto:

```
package com.xxx.socket;
import "game.proto";

message CMsgBase
{
    required CMsgHead msghead           = 1;
    optional bytes msgbody              = 2;
}

message CMsgHead
{
    required int32 msgtype                = 1;
    required int32 msgcode                = 2;
}

message SC_USER_REGISTER
{
    required game.RoleObject roleInfo=1;
}
```

And game.proto:

```
package com.xxx.game;

message RoleObject
{
    //......
}
```

And here is how I load the proto:

```
socketProto = rf.readFileSync("socket.proto");
socketRoot = protobuf.parse(socketProto);

gameProto = rf.readFileSync("game.proto");
gameRoot = protobuf.parse(gameProto);
```

and everything works fine until I try to decode a message from the server :

```
var SCMsgBody = socketRoot.root.lookup("com.xxx.socket.SC_USER_REGISTER");
var msgbody = SCMsgBody.decode(message.msgbody);
```
The error is :

`Error: unresolvable field type: game.RoleObject`

It seems like the two proto files is not loaded intp one root.

I know how to do it when use the protobuf.js in the browser:

```
var ProtoBuf = dcodeIO.ProtoBuf;
var xappBuilder = ProtoBuf.newBuilder();
ProtoBuf.loadProtoFile("game.proto", null, xappBuilder);
ProtoBuf.loadProtoFile("socket.proto", null, xappBuilder);
xxx = xappBuilder.build("com.xxx");
```

I just do not know how to do this in node.js with protobufjs.

Any advice will be appreciated, thanks :)

**Comment by dcodeIO** [comment]
You don't really have to call the parser yourself (you could use `protobuf.loadSync` instead on node which automatically resolved the import for you):

```js
var socketRoot = protobuf.loadSync("socket.proto");
```

Of course, you can also use the parser directly, as you did, but you have to provide the common root to any subsequent calls of `protobuf.parse`:

```js
socketProto = rf.readFileSync("socket.proto");
socketRoot = protobuf.parse(socketProto);

gameProto = rf.readFileSync("game.proto");
protobuf.parse(gameProto, socketRoot);

// use the common socketRoot
```

**Comment by supersuraccoon** [comment]
@dcodeIO 

Thanks for your quick reply :)

I tried `protobuf.loadSync` know all the related proto are loaded successfully.

But, I am having another weird issue when decoding a SC_USER_REGISTER message:

```
node_modules/protobufjs/src/reader.js:470
            throw Error("invalid wire type: " + wireType);
            ^

Error: invalid wire type: 6
    at Error (native)
    at BufferReader.ReaderPrototype.skipType (node_modules/protobufjs/src/reader.js:470:19)
    at Type._com_xxx_game_ItemObject$decode [as decode] (eval at eof (node_modules/@protobufjs/codegen/index.js:96:25), <anonymous>:31:7)
    at Type.decode_setup [as decode] (node_modules/protobufjs/src/type.js:363:7)
    at Type._com_xxx_game_RoleObject$decode [as decode] (eval at eof (node_modules/@protobufjs/codegen/index.js:96:25), <anonymous>:77:45)
    at Type.decode_setup [as decode] (node_modules/protobufjs/src/type.js:363:7)
    at Type._com_xxx_socket_SC_Login$decode [as decode] (eval at eof (node_modules/@protobufjs/codegen/index.js:96:25), <anonymous>:11:28)
    at Type.decode_setup [as decode] (node_modules/protobufjs/src/type.js:363:7)
    at Object.protobuffer.decode (protobuffer.js:151:27)
    at Socket.<anonymous> (server.js:61:15)
```

I have a python script using the same proto files as in node.js and the python script can decode the buffers from the server (SC_Login) successfully and I have checked that the buffers received in node.js are the same in python script.

Here is the proto of SC_Login:

```
socket.proto
message SC_Login
{
	required game.RoleObject roleInfo=1;
}

game.proto
message ItemObject 
{
    required int32 a = 1;
    required int32 b = 2;
    optional int32 c = 3;
    repeated string d = 4;
	repeated string e = 5;
	optional bool f = 6;
}

message RoleObject
{
    required string a = 1
    // ...... 
    repeated ItemObject b = 20;
}
```


BTW,  I tried to decode another message that has few fileds (no import game proto data) :

```
message SC_CREATE
{
	required string a=1;
	required string b=2;
}
```

And this time it works fine in node.js.


Can you give me some advice on this issue? Thanks :)

**Comment by dcodeIO** [comment]
> I have a python script using the same proto files as in node.js and the python script can decode the buffers from the server (SC_Login) successfully and I have checked that the buffers received in node.js are the same in python script.

Can you provide an example buffer that produces `Error: invalid wire type: 6` in node but node in python?

**Comment by dcodeIO** [comment]
Does it still fail with current master?

**Comment by dcodeIO** [comment]
Closing this issue for now. Feel free to reopen it if necessary!
