### ISSUE TITLE
TypeScript: strongly typed lookup function

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#544]
I'm finding myself doing this a lot:

```js
(<any>tree.lookup('mynamespace.MyMessage')).encode...
```

The reason is that `lookup` returns a `ReflectionObject` which I cannot directly cast to any of its children (I can cast a Type -> ReflectionObject but not the other way around). 

I'm proposing doing something like:

```js
tree.lookupService('mynamespace.MyService'); // ok -> ProtoBuf.Service
tree.lookupType('mynamespace.MyService'); // throws -> MyService is not a Type
```

Strongly typed with exceptions if you attempt to lookup the wrong type (or just return null)

**Comment by dcodeIO** [comment]
Hmm, the following is passing in the test file:

```ts
protobuf.Class.create(root.lookup("Hello") as protobuf.Type, Hello);
```

https://github.com/dcodeIO/protobuf.js/blob/master/types/test.ts#L20

**Comment by paralin** [comment]
It's possible, but messy. And not particularly safe (in the case that it isn't in fact a Type)

**Comment by bb** [comment]
The changeset 01365ba helps specifically for Type and Service, but if I understand @paralin correctly, he was looking for a type declaration like
```typescript
lookup<T>(path: (string|string[]), parentAlreadyChecked?: boolean): T extends (ReflectionObject|Type);
```
(didn't check that, just trying to generalize the type definition right here in the comment editor)

This would enable him writing
```typescript
tree.lookup<MyMessage>('mynamespace.MyMessage').encode...
```

**Comment by paralin** [comment]
Actually @bb that's not what I meant, however what you have posted is quite nice and I'd love it if that was in place.

**Comment by dcodeIO** [comment]
I'd favor any solution that doesn't require additional code (like it is now with `lookupType` etc.), and just works on a definition basis only.

**Comment by xujihui1985** [comment]
Hi @dcodeIO, I tested the following on node v6.9.1, and seems nodejs doesn't happy with that https://github.com/dcodeIO/protobuf.js/blob/master/types/test.ts#L20

it throws error `TypeError: Cannot assign to read only property 'prototype' of function` on 
https://github.com/dcodeIO/protobuf.js/blob/master/src/class.js#L44 ,  because property prototype on constructor is not writeable while the clazz is an Class

**Comment by dcodeIO** [comment]
Try `"typescript": "^2.2.0-dev.20161214",`

**Comment by dcodeIO** [comment]
`lookupType` and `lookupService` are now generated programmatically, which makes me feel a lot better about this. Considering this issue fixed for now.
