### ISSUE TITLE
src/verify.js syntax error

### ISSUE THREAD

**Issue by boljen** [dcodeIO/protobuf.js#546]
There's a missing "gen" function call that causes a syntax error;

See https://github.com/dcodeIO/protobuf.js/blob/master/src/verify.js#L214

The one below that probably also fails

**Comment by dcodeIO** [comment]
Oh my, seems I am getting sloppy. Thanks for pointing this out!

**Comment by boljen** [comment]
You're welcome, thank you for your great work on this project!
