### ISSUE TITLE
Forcing long from Browserify

### ISSUE THREAD

**Issue by elsehow** [dcodeIO/protobuf.js#548]
Hi there

Thanks for this excellent package.

I've been working on moving OpenWhisperSystem's [signal-protocol-javascript](https://github.com/WhisperSystems/libsignal-protocol-javascript) into the JS module ecosystem, so it can be installed via npm.

Regarding this point,

> If you need a proper way to work with 64 bit values (uint64, int64 etc.), you can install long.js alongside this library. All 64 bit numbers will then be returned as a Long instance instead of a possibly unsafe JavaScript number (see).

I was wondering if there is any way to force using `Long`s from the caller side, when I `require('protobufjs')`? Or do I need to concatenate the two files together (potentially making my own build)?

**Comment by dcodeIO** [comment]
When you `require("protobufjs")` on node, long should always be available. It is marked as an optional package because it effectively is, but as long is on npm, it is always available on node.

**Comment by elsehow** [comment]
Thanks for the reply. For some reason, I was getting an issue where concatenating Long, ByteArray, and Protobuf.js into a single file, then requiring that and calling `dcodeIO.ProtoBuf.loadProto` worked, but `require('protobufjs').loadProto` did not. (This is protobuf 5.0.1). Any ideas why that may be happening?

**Comment by dcodeIO** [comment]
Did you use the asynchronous version of `loadProto`?

**Comment by elsehow** [comment]
It doesn't look like it. It's being called like this,

```js
return dcodeIO.loadProto(/*...*/).build('textsecure');
```

You can see [the original usage here](https://github.com/WhisperSystems/libsignal-protocol-javascript/blob/master/src/protobufs.js#L8).

**Comment by dcodeIO** [comment]
Hmm, still not quite sure what's happening there.

* When concatenating the files, make sure to do it in this exact order: long, bytebuffer, then protobuf so that the dependency chain is properly set up.
* When looking at your code, it also appears to me that using a json file (generated through `pbjs`) together with `loadJson` would be ideal. It's unlikely that this fixes your issue, though.

**Comment by elsehow** [comment]
Thanks for your reply.

I am indeed concatinating the files in just that order:

```
      components: {
        src: [
          'node_modules/long/dist/long.js',
          'node_modules/bytebuffer/dist/ByteBufferAB.js',
          'node_modules/protobufjs/dist/protobuf.js'
        ],
        dest: 'build/dcodeIO.js'
````

Here's an example from [this file](https://github.com/elsehow/signal-protocol/blob/ada861df64cd02f7c7b5c1cbebdfab38181e4938/src/protobufs.js). With the concatinated libs, this snippet works:

``javascript
  var dcodeIO = require('../build/dcodeIO.js');
  function loadProtoBufs(filename) {
    return dcodeIO.loadProto(Internal.protoText['protos/' + filename]).build('textsecure');
  }
  var protocolMessages = loadProtoBufs('WhisperTextProtocol.proto');
```
But I can break stuff by doing this:

```javascript
  var protobufjs = require('protobufjs');
  function loadProtoBufs(filename) {
      return protobufjs.loadProto(Internal.protoText['protos/' + filename]).build('textsecure');
  }
  var protocolMessages = loadProtoBufs('WhisperTextProtocol.proto');
```

Here's an error I see in the tests:
```
1) SessionCipher Standard Signal Protocol Test Vectors as Alice send prekey message A:
     TypeError: Illegal buffer
      at new module.exports.ByteBuffer.wrap (node_modules/bytebuffer/dist/ByteBufferNB.js:353:23)
      at Object.toString (src/helpers.js:14:10)
      at src/SessionCipher.js:106:69
```

**Comment by dcodeIO** [comment]
Are you maybe mixing ByteBufferAB and ByteBufferNB in your tests somehow? You could also try to assert what ByteBuffer.wrap is called with in this exact situation.

**Comment by elsehow** [comment]
> You could also try to assert what ByteBuffer.wrap is called with in this exact situation.

In both cases, I find `ByteBuffer.wrap` is called on 

```sh
bb: undefined
buffer:ArrayBuffer
(32 bytes)
encoding:undefined
littleEndian:undefined
noAssert:undefined
```

> Are you maybe mixing ByteBufferAB and ByteBufferNB in your tests somehow?

I see ByteBufferNB in the error stacktrace. But, I do not understand why the same tests work when I rely on the concatenated version (with ByteBufferAB). Do these packages have different APIs? And/or, is there a way to force the imported bytebuffer.js to use ByteBufferAB?

Thanks for your help on this issue.

**Comment by dcodeIO** [comment]
```
bb: undefined
buffer:ArrayBuffer
(32 bytes)
encoding:undefined
littleEndian:undefined
noAssert:undefined
```

So, `ByteBuffer.wrap` Is called with an object made from these keys and values? If so, then this looks like a custom object that is neither from protobuf nor bytebuffer. More precisely, the following properties are uncommon and I have no idea where these come from:

```
bb: undefined
encoding:undefined
```

Everything else could be from a ByteBuffer instance, but in this combination it doesn't make a lot of sense to me as there should be additional properties like `offset` if it were a ByteBuffer instance.

Am I misinterpreting your example?

**Comment by elsehow** [comment]
This is good to know. I am still trying to figure out what's going on in the WhisperSystems codebase with these protocol buffers. Let me do a little digging and come back to this when I have more of a clue.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
