### ISSUE TITLE
Synchronous loader #enchancement

### ISSUE THREAD

**Issue by pronebird** [dcodeIO/protobuf.js#549]
It would be great to have a synchronous loader. My code looks like madness with this callback that wraps entire server implementation. Linear flows look and feel better. In most cases .proto files are loaded once on startup so nobody really benefits from asynchronous logic which eventually after reading tiny file runs parsing on main thread anyway.

ps: i can imagine it would hard to change existing logic... maybe we can add promise? I could combine promise with ESNext's await/async and it would do it. so far i just use event emitter.

**Comment by jeffgrossmann** [comment]
FYI,   loadSync API has already been added.  See

http://dcode.io/protobuf.js/Root.html#loadSync

**Comment by pronebird** [comment]
@jeffgrossmann wow I must have overlooked this! Thanks!
