### ISSUE TITLE
Any good way to generate TypeScript definition for static .js files from pbjs ?

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#550]
See that protobuf.js generate .d.ts via jsdoc, it is useful for dynamic use case.
While for static code generate, any good way to generate this ?

**Comment by dcodeIO** [comment]
This is planned and will probably be available soon. In the meantime you can look at how protobuf.js generates the .d.ts and apply that to the statically generated files.

**Comment by dcodeIO** [comment]
Give it a try! (use `--name` instead of `-n` for now)

**Comment by jeffgrossmann** [comment]
First, thanks for adding this feature.    I installed the latest version to test out pbts and it works if the *.proto files do NOT include a package statement.    With a package statement, the generated d.ts only contains single var with the package name.   See attached proto files and generated output in the zip.
[pbts_example.zip](https://github.com/dcodeIO/protobuf.js/files/649320/pbts_example.zip)

nopackage.proto:  Does not have a package and generates the correct nopackage.d.ts
simple.proto:   Has a package statement and generates an incomplete simple.d.ts

Test steps
1) run pbjs to generate js from proto
2) run pbts to generate d.ts from js

Thanks much.

**Comment by dcodeIO** [comment]
Does this fix it?

**Comment by jeffgrossmann** [comment]
Yes, the generated d.ts looks good.   I need to test with some typescript code to verify the types but visual inspection is a "pass".

Thanks again.

**Comment by twoeo** [comment]
### Must use absolute path ?

**This get error**
``pbjs -n test test.js``
> ERROR: Unable to find the source file or directory C:\Users\longsheng\AppData\Roaming\npm\node_modules\protobufjs\test.js


**and this works**
``pbjs -n test E:\xxx\xxx\xxx\test.js``

**Comment by osechet** [comment]
Nested classes are not generated properly. In typescript definition, nested classes must be added to a module whose name is the same as the parent class:
```
message A {
  message B {
  }
}
```
should give:
```
class A {
}
module A {
  class B {
  }
}
```

**Comment by dcodeIO** [comment]
@twoeo: Did you mean `pbts`?

**Comment by dcodeIO** [comment]
@osechet: That doesn't appear correct to me.

**Comment by osechet** [comment]
@dcodeIO The concept of nested class does not exist in Typescript. The only way to make something equivalent is the way I described. You can find a lot of resources on Internet that explains it, i.e:
http://stackoverflow.com/questions/13495107/any-way-to-declare-a-nest-class-structure-in-typescript
https://blog.oio.de/2014/03/21/inner-classes-typescript/

But I think it's a problem with tsd-jsdoc. I remember running into a similar problem last time I used it.

**Comment by dcodeIO** [comment]
Can you provide me with an example output that fails?

**Comment by dcodeIO** [comment]
@twoeo: This commit should fix the absolute path issue you described. Also make sure that the tsd-jsdoc dependency is updated to current master (there has been an issue with piped output).

**Comment by dcodeIO** [comment]
I've restructured tsd-jsdoc and incorporated our changes, which is now [part of this repository](https://github.com/dcodeIO/protobuf.js/tree/master/lib/tsd-jsdoc). There are a few more comments on what the different functions actually do making the code relatively easy to understand. Hence, it's now possible to process issues and PRs.

**Comment by dcodeIO** [comment]
As tsd-jsdoc puts inner classes into modules now and all other issues mentioned seem to be resolved, I am closing this for now. Feel free to create new issues or PRs referencing lib/jsdoc directly.
