### ISSUE TITLE
Not works well with Webpack (AMD package name wrong ?)

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#554]
When using with webpack (generate static code), it always compiled error:
> ERROR in ../realtimeServer/src/proto/RealtimeServerProto.js
Module not found: Error: Cannot resolve module 'protobuf' in E:\Codes\ChartMaker\realtimeServer\src\proto
 @ ../realtimeServer/src/proto/RealtimeServerProto.js 4:8-37

This problem can be resolved by modify the line 4 in generated .js file:
```js
define(["protobuf"], factory);
```

modify to 
```js
define(["protobufjs"], factory);
```

**Comment by dcodeIO** [comment]
The AMD module name is `protobuf`. If you do not require AMD, try with the current master version and use `--wrap commonjs` with pbjs. If you require AMD only, consider using `--wrap amd` and a require config to point `protobuf` accordingly.

**Comment by twoeo** [comment]
with ``--wrap commonjs``
But occur error at runtime.
> TypeError: Cannot set property 'default' of undefined

At last of the js file:
``$protobuf.roots["default"] = $root;``
Seems `$protobuf.roots` is undefined

**Comment by twoeo** [comment]
AMD package name is different with npm package name.
Not sure if it is unfriendly to other package tools except `Webpack`

**Comment by dcodeIO** [comment]
The protobuf.roots feature has just been added. Are you using 6.1.1?
