### ISSUE TITLE
React Native: undefined is not a function (evaluating 'Namespace.extend(Type)')

### ISSUE THREAD

**Issue by vanekt** [dcodeIO/protobuf.js#560]
protobuf.js version: <6.1.0>

### How to reproduce ###

Just import protobuf.js in ReactNative:

```js
import Protobuf from 'protobufjs'
```

After rebuild the app it shows:
```
undefined is not a function (evaluating 'Namespace.extend(Type)')

<unknown>
type.js:8

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

<unknown>
namespace.js:9

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

<unknown>
root.js:4

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

<unknown>
parse.js:5

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

<unknown>
index.js:78

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

<unknown>
index.android.js:4

loadModuleImplementation
require.js:170

guardedLoadModule
require.js:122

_require
require.js:106

global code
require-0.js:1
```

**Comment by dcodeIO** [comment]
[Relevant line](https://github.com/dcodeIO/protobuf.js/blob/master/src/type.js#L10)

Unfortunately, I have practically no experience with React Native, so I have to guess:

1. The sources make heavy use of cyclic require calls, which might be causing errors in non-node environments
2. This might be an issue with the [extend](https://github.com/dcodeIO/protobuf.js/blob/master/src/object.js#L97) implementation

One possible workaround could be to use a prebuilt bundle from [dist/](https://github.com/dcodeIO/protobuf.js/tree/master/dist). These are made for browser environments, though and do not really support require / import.

If you have additional information or an idea, let me know!

**Comment by dcodeIO** [comment]
This now moved the extend implementation around which might or might not help with your issue, depending on what exactly is failing where. Please give it a try.

If this doesn't resolve your issue, yet, a more general approach could still be examined.

**Comment by vanekt** [comment]
Unfortunately this does not solve the problem

**Comment by dcodeIO** [comment]
Please try again. If it raises another error now, please paste it here.

**Comment by vanekt** [comment]
It works! Great, thank you!

**Comment by dcodeIO** [comment]
Feel free to reopen if necessary!

**Comment by develand** [comment]
Can anyone confirm if this works with react-native?

**Comment by vanekt** [comment]
The 6.5.0 version works fine with React Native
