### ISSUE TITLE
Have an option to use snake_case for message properties

### ISSUE THREAD

**Issue by vgoloviznin** [dcodeIO/protobuf.js#564]
protobuf.js version: 6.1.1

I'm running pbjs utility to generate JSON for my proto files, but the issue is that it generates camelCase property names  (proto files have snake_case). 

Is there already some configuration for this (found a broken link to wiki article) or is it possible to include one?

**Comment by dcodeIO** [comment]
Currently, v6 always converts to camel case for simplicity. Google's JS implementation also does this.

Do you have a specific use case where this fails or snake_case is absolutely required?

**Comment by vgoloviznin** [comment]
Can't say that I have a hard requirement for snake_case :) 
We have all documentation for communication between services where all field names are in snake case, so it's just easier to blindly follow the documentation (or reading the proto file) without thinking about camel case conversion

**Comment by dcodeIO** [comment]
pbjs now supports the option `--keep-case` that skips the camel case conversion. I haven't tested this for edge cases in detail, yet, so let me know if there are any issues.

**Comment by vgoloviznin** [comment]
@dcodeIO cool! When will it get released on npm?

**Comment by dcodeIO** [comment]
Maybe tonight as 6.2.1 if there are no more pending issues.

**Comment by vgoloviznin** [comment]
Awesome, thanks for the quick fix! 

I will check during the weekend for our definition

**Comment by dcodeIO** [comment]
It's on npm now!

**Comment by thirstyfish** [comment]
Hi!
Apologies if it's a silly question, I'm just familiarising myself with your library, but haven't found an answer to this in the docs, this issue is as close as I got.
I have the same problem as the OP, but I'm not using the CLI to generate a json file.
Is there an equivalent option that can be set in the proto file or elsewhere that will have the same effect (leave the snake case intact) in case I'd like to load the raw proto file directly with protobuf.load()?
Thanks!

**Comment by dcodeIO** [comment]
Yes: [Root#load](http://dcode.io/protobuf.js/Root.html#load3)

```js
var root = new protobuf.Root();
root.load(..., { keepCase: true }).then(...);
```

**Comment by thirstyfish** [comment]
Great, thanks for your help!

**Comment by samkeke** [comment]
Thank you help,

I finally found the answer

**Comment by rahulverma** [comment]
Is there a way to --keep-case for static modules. Its a big problem when using typescript.
