### ISSUE TITLE
Default value for bytes field?

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#566]
Can we add an option to `asJSON` for `bytes` to force the bytes fields to consistently come out as Node Buffers?

The issue is that the GRPC code expects buffers but sometimes gets `[]` due to the `defaults` option.

**Comment by dcodeIO** [comment]
Yes, sir. Going to add { bytes: Buffer }

**Comment by dcodeIO** [comment]
Give it a try!

**Comment by dcodeIO** [comment]
Closing this issue for now. Feel free to reopen it if necessary!

**Comment by dcodeIO** [comment]
FYI: 6.5.0 does not have `bytes: Buffer` anymore, which I further explain [here](https://github.com/dcodeIO/protobuf.js/issues/620#issuecomment-272071912) while making an assumption. Do you know why exactly this is required in gRPC?
