### ISSUE TITLE
strings aren't correctly decoded in the browser

### ISSUE THREAD

**Issue by jonathon-love** [dcodeIO/protobuf.js#567]
Hi,

I'm not completely sure what you're goals are wrt browser support, but `static_module`s created by `npmjs` don't work correctly in the browser (and probably other code paths are affected too).

here you use the `toString([encoding[, start[, end]]])` method of `utf8buffer`:

https://github.com/dcodeIO/protobuf.js/blob/master/src/reader.js#L520

although this works in node, browsers don't support those additional arguments:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/toString

and so you end up with a string like "50,34,23,78" rather than, say "fred"

thanks, and keep up the good work!

**Comment by dcodeIO** [comment]
In the browser, `BufferReader` shouldn't be used at all. [Writer](https://github.com/dcodeIO/protobuf.js/blob/master/src/reader.js#L372) is for browsers.

I assume you are using browserify with [buffer](https://github.com/feross/buffer), right?

**Comment by jonathon-love** [comment]
ah yes, i was using a utf8array rather than a buffer! sorry!
