### ISSUE TITLE
Non deterministic code gen

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#573]
protobuf.js version: 6.2.1

Run` pbjs -p <path-to-protobuf> -t json -o something.json `
Output is not deterministic on every run.
Please ensure that the tree traversal and code generated is in a sorted and determinstic fashion. 

This creates huge diffs on every checkin. This was not the case in v5.

I am upgrading a 50K line client side code base  with over 100 protos from 5 to 6.

**Comment by dcodeIO** [comment]
Unfortunately, I don't know where this could come from. Do you know if this affects specific parts / features of the generated output more than others?

**Comment by r-tock** [comment]
I cannot discern where this is stemming from. I would think that a sorting would solve this issue.

**Comment by dcodeIO** [comment]
Had an idea: pbjs is using async `load`, which most likely results in fields being loaded in different order for large code bases. Replacing that with `loadSync` should prevent it.

**Comment by r-tock** [comment]
👍 Let me know when the fix is pushed. I will try it.

**Comment by paralin** [comment]
@dcodeIO just add a --sync flag or something

**Comment by dcodeIO** [comment]
Let me know if this fixes it!

**Comment by r-tock** [comment]
Verified to be fixed
