### ISSUE TITLE
Enum Strings are no longer supported

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#575]
In V5 the ctor would either support string value or int value of an enum. in 6.2.1 string value is not supported when parsing from JSON. Would love to get that functionality back

```proto
message MyMessage {
 enum Type {
   CAT = 0;
   DOG = 1;
 }
 optional Type type = 1;
}
```

```js
MyMessage.create({ type: 'DOG' });
```
does not work.

**Comment by dcodeIO** [comment]
I see that there are valid uses for this. This would, however, affect performance in that it adds additional assertions to the constructor that are potentially (especially internally) unnecessary.

What about adding something like `MyMessage.fromJSON` that supports a set of options for these cases instead?

**Comment by r-tock** [comment]
`MyMessage.from(obj)` sound good as an interface.

However, I would like to avoid that unless the performance regresses significantly. I am looking at the large code base and any place where we will make things optional will create opportunities for error.

**Comment by dcodeIO** [comment]
For context: [This is what it currently does](https://github.com/dcodeIO/protobuf.js/blob/master/src/message.js#L15), which is as minimal as possible. With enum strings, however, we'd have to check if 1. a key references a field, 2. field type is enum, 3. the value is a string and 4. whether there is a valid value for that string. For every field.

**Comment by r-tock** [comment]
yeah bummer, MyMessage.from with options would be the way to go.

**Comment by dcodeIO** [comment]
Message/Type.from is now in, give it a try!

**Comment by r-tock** [comment]
Perfect! tested on an example, works great. Haven't been able to start migration due to missing protos https://github.com/dcodeIO/protobuf.js/issues/576

**Comment by dcodeIO** [comment]
Closing this for now. Feel free to reopen the issue if there are any issues!
