### ISSUE TITLE
Simplify imports for enums.

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#576]
protobuf.js version:  6.2.1

Enums are a common thing used across our code. in v5. I would be able to do things like

```js
import { MyMessage } from 'protos';
if (something === MyMessage.Type.CAT) {
   // Do something.
}
```

The same thing now is

```js
import root from 'protos';
const MyMessage = root.lookup('MyMessage');
const Type = MyMessage.lookup('Type');

if (something === Type.values.CAT) {
}
```

I like the lookup pattern for messages, I understands its pros. But for enums its very clunky when you have values in between.

Can enums live in its own shadow hierarchy? which makes it easy to do something like.

```js
import { MyMessage: { Type } } from 'enums'; 

if (something === Type.CAT) {
   // Do something.
}
```

**Comment by dcodeIO** [comment]
The reason that there aren't any magically created object trees anymore basically is that there is no way to make this work the same with typed dialects like TypeScript, which require proper types on everything.

What do think about adding

```
/**
 * Gets the values of the nested enum with the specified name.
 * @param {string} name Nested enum name
 * @returns {Object.<string,number>} Enum values
 */
NamespacePrototype.getEnum = function getEnum(name) {
    if (this.nested && this.nested[name] instanceof Enum)
        return this.nested[name].values;
    throw Error("no such enum");
};
```

so you can do the following (if Type is a direct child of MyMessage):

```js
if (something === MyMessage.getEnum("Type").CAT) {
}
```

**Comment by r-tock** [comment]
Thanks that's better.
However, still I don't like that dynamic interface is it doesn't throw error during import. Explicit import checking is something we have gotten used to and I would love if there was some way of keeping that...

**Comment by dcodeIO** [comment]
These methods throw: `lookupType`, `lookupService`, `lookupEnum` and `getEnum`
These don't: `lookup`, `get`

**Comment by r-tock** [comment]
¯\_(ツ)_/¯ Still a runtime check. I am thinking if there is something I can add so that the whole thing barfs during babel bundling.

**Comment by paralin** [comment]
Interesting idea to use static checking for this somehow, I like the idea

**Comment by r-tock** [comment]
This idea is very raw: I feel like there is a middle ground between the current static-module (3.2MB in our case) and json-module (56KB)

I think you can create exports within json-module by not just export $root but the entire hierarchy as symbols. For all Types, Services and Enums.

I mean it is easy for me to do the following, Therefore I believe we can do something like that in the generated json-module itself whereby we can make these import statements work.
```js
import * as protobuf from 'protobufjs';

const root = protobuf.Root.fromJSON(require('core/dist/core.json'));
  		  
 const protos = {	
  ...root.lookup('tocktix.messages').nested
  };
  		  
  module.exports = protos;	
```js
 Lock conversation

**Comment by paralin** [comment]
So why not just generate Typescript definitions for the static code, and actually generate + execute the static code at runtime?

By that I mean, generate a strongly typed TypeScript tree for the expected output of protobuf.Root.fromJSON. Then don't actually compile that to code. Just use `fromJSON` at runtime.

**Comment by r-tock** [comment]
@paralin Could you mock a example for me. I would like to see what that looks like. I am trying to convert a large react codebase from v5-v6. I am also trying to automate this conversion, examples help me visuale the refactor.

**Comment by paralin** [comment]
This would have to be a few steps, I think.

Given a proto:

```proto
message MyMessage {
  string my_string = 1;
}
```

Step 1 is to generate typescript interfaces for these:

```
interface IMyMessage {
  myString?: string;
}
```

Then step 2 is to allow `Type` to take a `Type<T>`:

`let myMessage: Type<IMyMessage>;`

The T would be used for the return type of `asJSON`, as the argument type for `create`, `validate`, `encode`, etc.

Next, generate a tree:

```js
{
  MyNamespace: {
     MyMessage: <Type<IMyMessage>>root.nested.MyNamespace.nested.MyMessage,
  },
}
```

Then usage would be:

```
generatedTree.MyNamespace.MyMessage.encode({myString: "test"})
```

The `myString` literal would be TypeScript validated, as the argument type would be of `IMyMessage`.

**Comment by r-tock** [comment]
Yes! The generated tree portion. This is exactly what I had in my mind, which I started the conversation when I said shadow hierarchy. The trouble we have right now is nesting them together, so we will have to create such trees independently for Types, Services and Enums.  And we can do that in JS too... Doesn't have to be just typescript.

**Comment by dcodeIO** [comment]
Well, it's theoretically possible to expose everything uppercased on the reflection objects so that a .d.ts from a static module could be used with reflection. `encode`, `decode` are the same anyway, but generated static classes would need `create` and `$type` in addition to that to make it work the same.

**Comment by r-tock** [comment]
❤️ I strongly support that theoretical possibility and would encourage to be made a reality. A clean API goes a long way; this is one of the last remaining kinks with v6.

**Comment by dcodeIO** [comment]
Give it a shot! Might still be missing something.

**Comment by paralin** [comment]
Damn, you're quick.

**Comment by r-tock** [comment]
It looks like the generated json is missing that type entirely.
```
field.js:251 Uncaught Error: unresolvable field type: BusinessOnboarding
    at Field.resolve (field.js:251)
    at Type.resolveAll (type.js:263)
    at Namespace.resolveAll (namespace.js:323)
    at Namespace.resolveAll (namespace.js:323)
    at Root.resolveAll (namespace.js:323)
    at Object.eval (protos.js:15)
    at Object.eval (protos.js:21)
    at eval (protos.js:22)
    at Object.<anonymous> (index.js:7048)
    at __webpack_require__ (index.js:556)
```
I am getting this error calling resolveAll(). I

**Comment by r-tock** [comment]
```bash
robinanil 21:14:10 :~/work/core$ cat src/main/model/proto/*.proto |grep "message BusinessOnboarding"
message BusinessOnboarding {

robinanil 21:14:34 :~/work/core$ ./node_modules/protobufjs/bin/pbjs src/main/model/proto/*.proto -s proto -t json -w commonjs -p src/main/model/proto/*.proto -p node_modules/protobufjs/ -o dist/core.json
robinanil 21:14:37 :~/work/core$ cat dist/core.json |grep "BusinessOnboarding: {"
```

**Comment by r-tock** [comment]
This does not happen at v6.2.1  Just at head. -t static fails too

./node_modules/protobufjs/bin/pbjs src/main/model/proto/*.proto -s proto -t static -w commonjs -p src/main/model/proto/*.proto -p node_modules/protobufjs/ -o dist/core.json

**Comment by dcodeIO** [comment]
That's probably because v6.2.1 didn't call `resolveAll()`, hence missing definitions caused an error only if used directly or if a type using one needed to be resolved. Hence I'd assume that the definition wasn't in the JSON with v6.2.1, too.

**Comment by r-tock** [comment]
Yes, Let me need additional information for figuring out a fix

**Comment by Rranran** [comment]
The .proto file is

_syntax = "proto3";
message person {
     string name=1;
     int32 id=2;
     string email=3;
    enum PhoneType {
        MOBILE=0;
        HOME=1;
        WORK=2;
    }
    message PhoneNumber {
         string number=1;
         PhoneType type=2 [default=HOME];
    }
    repeated PhoneNumber phone=4;
}_
how to init it? especially the enum type

**Comment by dcodeIO** [comment]
I don't know if this issue actually requires a fix. If I understood you correctly, there are missing definitions, which should, to my understanding, cause an error.

**Comment by Rranran** [comment]
Your means if a enum type is included in the .proto file, we can't serialize it use protobufjs now ?

**Comment by dcodeIO** [comment]
@Rranran: Sorry, forgot to mention r-tock. My reply was directed to him.

Regarding your question: I am not quite sure what your issue is. You can just look up the enum and access its values:

```js
root.lookup("person.PhoneType").values
```

Or create a PhoneNumber from JSON and enum strings using `Type#from`:

```js
var PhoneNumber = root.lookup("PhoneNumber");
PhoneNumber.from({
  number: "01234",
  type: "WORK"
});
```

Or you could rename "person" to "Person" to benefit from what we talked about above.

**Comment by r-tock** [comment]
@dcodeIO the missing definition is caused by the pbjs compiler. All the Protos are in the valid path. See my grep command. The compiler is the one that is skipping those definitions

**Comment by Rranran** [comment]
@dcodeIO 
According to your code, I  solved my problem.  Thanks a lot

**Comment by r-tock** [comment]
Reopening this, there is one more case needs to be handled. which are Enums nested in a namespace not within a message, needs to be resolved into the namespace

**Comment by dcodeIO** [comment]
Erm, are those missing on top of the namespace after `resolveAll()`?

**Comment by r-tock** [comment]
They are present in a different form. Where to access the values I need to do Type.values.CAT instead of Type.CAT

**Comment by dcodeIO** [comment]
Hmm, that's strange. This is what happens there: https://github.com/dcodeIO/protobuf.js/blob/master/src/namespace.js#L297

**Comment by r-tock** [comment]
Ha found it. I was exposting this
```json
root.resolveAll().lookup('tocktix.messages').nested            
```
instead of
```json
root.resolveAll().lookup('tocktix.messages')            
```

**Comment by MaheshSasidharan** [comment]
If anyone wants [solution](https://github.com/dcodeIO/protobuf.js/issues/349#issuecomment-466587934) to what @Rranran
