### ISSUE TITLE
Uncaught ReferenceError: Reader is not defined

### ISSUE THREAD

**Issue by osechet** [dcodeIO/protobuf.js#580]
protobuf.js version: master

From the rev 1fcfdfe21c1b321d975a8a96d133a452c9a9c0d8, I get the error: `Uncaught ReferenceError: Reader is not defined`, on `protobufjs/runtime/index.js` ([line 14](https://github.com/dcodeIO/protobuf.js/blob/1fcfdfe21c1b321d975a8a96d133a452c9a9c0d8/runtime/index.js#L14)).

It isn't blocking the application execution.

**Comment by dcodeIO** [comment]
Fixed in master!
