### ISSUE TITLE
Bug: `.encode` doesn't work properly on nested oneof members.

### ISSUE THREAD

**Issue by kfir-drivenets** [dcodeIO/protobuf.js#583]
protobuf.js version: 6.2.1

Encoding message that includes nested oneof elements results in an empty buffer.

Using the following protobuf as an example:
```protobuf
syntax='proto2';					
message A {								
	required int32 b = 1;			
}														
														
message B {									
	required int32 c = 1;			
}														
														
message C {									
	oneof child {						
		A a = 1;							
		B b = 2;								
	}													
} 

message D {  
    oneof child {
        C c = 1; 
        B b = 2; 
    }
}
```

And the relevant js
```js
var D = root.lookup("D");
var d_message = D.create({
	c: {
  		a: {
    			b: 10
   		}
	}
});
console.log(d_message);
buffer = D.encode(d_message).finish();
console.log(buffer.length, buffer);
```

The resulting buffer will be empty.

In this version however it does work
```js
var C = root.lookup("C");
var D = root.lookup("D");
var c_message = C.create({
  a: {
    b: 10
  }
});
var d_message = D.create({});
d_message.c = c_message;
console.log(d_message);
buffer = D.encode(d_message).finish();
console.log(buffer.length, buffer);
```

The following jsfiddle snippet shows the error, printed to console
https://jsfiddle.net/ju7h93rr/

The followign jsfiddle snippet shows a modified version in which it works as expected
https://jsfiddle.net/2tvqLtLo/

**Comment by dcodeIO** [comment]
Here, you are creating a runtime message for D, but using a plain object for C. Plain objects do not have virtual oneof properties so the encoder cannot efficiently know which field is present:
```js
var d_message = D.create({
	c: {
  		a: {
    			b: 10
   		}
	}
});
```

This should work:

```js
var d_message = D.create({
	c: {
  		a: {
    			b: 10
   		},
                child: "a"
	}
});
```

Or this:

```js
var d_message = D.create({
  c: C.create({
    a: {
      b: 10
    }
  }
});
```

**Comment by kfir-drivenets** [comment]
I just tested your version of the code and it seems to work just fine. :+1:
Is there a documentation page that explains this behavior?
Also I think that some error should be raised if this case is detected and not just to return an empty buffer..

**Comment by dcodeIO** [comment]
The empty buffer you see there might be related to https://github.com/dcodeIO/protobuf.js/issues/581 - or does this also happen with master?

**Comment by dcodeIO** [comment]
Also, with master, it should be possible to use `Message.from` with (mixed) JSON data like in your case:

```js
var d_message = D.from({
  c: {
    a: {
      b: 10
    }
  }
});
```
Related: https://github.com/dcodeIO/protobuf.js/issues/575

**Comment by kfir-drivenets** [comment]
Checked on `v6.3.0` tag and it seems to work.
Thanks :+1:
