### ISSUE TITLE
Exception when encoding empty message

### ISSUE THREAD

**Issue by kfir-drivenets** [dcodeIO/protobuf.js#584]
protobuf.js version: 6.2.1

When trying to encode empty messages an exception is raised.

```js
protoString = "  		\
syntax='proto2';		\
message A {			\
}"; 
root = protobuf.parse(protoString).root;
var A = root.lookup("A");
var a_message = A.create();
console.log("a_message", a_message);
var buffer = A.encode(a_message).finish();
```

```
Uncaught TypeError: Method get TypedArray.prototype.subarray called on incompatible receiver null
    at subarray (native)
    at Function.pool_alloc [as alloc] (https://cdn.rawgit.com/dcodeIO/protobuf.js/6.2.1/dist/protobuf.js:704:25)
    at Writer.finish (https://cdn.rawgit.com/dcodeIO/protobuf.js/6.2.1/dist/protobuf.js:6698:33)
```

jsfiddle snippet https://jsfiddle.net/mv0gjn0e/

Also note that there isn't a way to set an empty field.
The following link shows how this is achieved via the python binding for protobuf.
http://stackoverflow.com/questions/29643295/how-to-set-a-protobuf-field-which-is-an-empty-message-in-python

This seems to be related to https://github.com/dcodeIO/ProtoBuf.js/issues/87

**Comment by dcodeIO** [comment]
This has been fixed in https://github.com/dcodeIO/protobuf.js/pull/570 but it's not yet on npm.
