### ISSUE TITLE
Migrating from 5.0.1 To 6.3.0

### ISSUE THREAD

**Issue by mj-mehdizadeh** [dcodeIO/protobuf.js#586]
I want to migrate from 5.0.1 To 6.3.0 , but I have an issue , There is no getter and setter in decoded object . why?
```
TypeError: protobuf.getName is not a function
```

```
TypeError: protobuf.getPassword is not a function
```
Decoded object contain both ```name``` and ```password```

How can I have getter and setter?

**Comment by dcodeIO** [comment]
There are no getters and setters with v6. Just set the properties instead.

**Comment by mj-mehdizadeh** [comment]
The problem is m I my project I use getter and setter 1000+ times , How can I migrate to version 6.3.0??

**Comment by dcodeIO** [comment]
You could implement [custom classes](https://github.com/dcodeIO/protobuf.js#using-custom-classes) that have the respective get and set functions. If your protobuf definitions are rather huge, this process wouldn't be convenient though.

**Comment by r-tock** [comment]
@mj-mehdizadeh We have a similar problem. But we decided as a team to rip off the bandage and convert all call sites. A simple regex will match all `\.[gs]et[A-Z].*\(` and then we go through it one by one and convert. there are of course false positives but we end up checking all those call sites anyways.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
