### ISSUE TITLE
pbts: output is cutted to 200kb when processing large js-file

### ISSUE THREAD

**Issue by halex2005** [dcodeIO/protobuf.js#587]
protobuf.js version: 6.3.0

I have 70 proto-files in my project and I have generated static module with pbjs successfully: 

```
node_modules/protobufjs/bin/pbjs -p ./proto -o protoclasses.js -t static-module ./proto/**/*.proto
```

Then I'd like to produce typescript definitions for module:

```
node_modules/protobufjs/bin/pbts -o protoclasses.d.ts protoclasses.js
```

The `pbts` exits successfully, but resulting `protoclasses.d.ts` is broken - it's content is cutted to 200kb.

In the sources, `pbts` starts child process `jsdoc` and puts it's stdout to resulting file. NodeJS will cut stdout because of default buffer capacity is 200 kb.

I found [this answer on stackoverflow](http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process#answer-23429654) useful to workaround this bug.

If I've add maxBuffer option with high value, output will not be cutted:

```js
    var child = child_process.exec("node \"" + basedir + "/node_modules/jsdoc/jsdoc.js\" -c \"" + basedir + "/jsdoc.types.json\" -q \"module=" + encodeURIComponent(moduleName) + "\" " + files.map(function(file) { return '"' + file + '"'; }).join(' '), {
        cwd: process.cwd(),
        argv0: "node",
        stdio: "pipe",
        maxBuffer: 1024*1024*1024
    });
```

Will you fix this?
Which is reasonable value in your opinion?
In my case the resulting `protoclasses.d.ts` has 1.1mb size, it is sad that I cannot remove jsdoc comments in generated typescript definitions.

Cheers, halex2005.

**Comment by dcodeIO** [comment]
Limit has been adjusted to 16mb and there is also a `--no-comments` option for pbts now.

**Comment by r-tock** [comment]
@dcodeIO This seems to have fixed https://github.com/dcodeIO/protobuf.js/issues/576

**Comment by halex2005** [comment]
Thanks, `--no-comments` helps very much, 245 kb vs 2.5 mb :+1:
