### ISSUE TITLE
Exception encoding nulled long

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#590]
When encoding a long field set to null (which is typical of a JSON object), instead of the field being ignored the code throws an exception. I don't see a reason not to support the old behavior. Null or undefined override on a nulled field should ignore it from being encoded on the byte stream.

```
util.longNe = function longNe(val, lo, hi) {
    if (typeof val === "object") // Long-like, null is invalid and throws
        return val.low !== lo || val.high !== hi;
    var bits = util.LongBits.from(val);
    return bits.lo !== lo || bits.hi !== hi;
};

```

**Comment by r-tock** [comment]
This is a general comment about nulled fields in general. not just long.

**Comment by dcodeIO** [comment]
There is no particularly important reason not to support ´null`. I just skipped it to save the additional assertion, i.e. here

```js
("if(%s!==undefined&&util.longNe(%s,%d,%d))", ref, ref, field.defaultValue.low, field.defaultValue.high);
```

but I am also OK with supporting this again.

**Comment by r-tock** [comment]
Thank you!  This is the last remaining issue(so far) in our migration from 5 to 6. Its coming along nicely.

**Comment by dcodeIO** [comment]
I've added this for long fields especially now because any other objects would be messages, which already default to `null` which is checked.
