### ISSUE TITLE
Anyway to force deocde fixed64/uint64 as string ?

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#591]
Notice that now it's decoded as `long` Object.
Anyway to force it to be as `string` ?
Sometimes `string` is more useful.

For example, when a `uint64` is used as id, `string` is more convenient to compare and use.

**Comment by dcodeIO** [comment]
`Long` objects implement `toString([radix=10])` for this purpose ([see](https://github.com/dcodeIO/long.js#api)).

Note that you could also just compare any Long object using `==` instead of `===` to a string **but** this performs the conversion for each such comparison.

**Comment by twoeo** [comment]
Of course long.js is useful.

But actually, `Long` is JSON-unfriendly.

Say I have a service that get some message from a grpc service, and return a json to browser.
If `fixed64` and `uint64` is `Long`, it is not convenient to transform everyone to string.

Especially at some cases when protobuf message need to convert to JSON, and transport to browser...
And they are not used for calculate

**Comment by dcodeIO** [comment]
You know that there is `Message#asJSON`, which supports `{ longs: String }` as an option, right?

The reason why longs aren't just strings by default is that every conversion from bits to strings and vice-versa has a cost, and you really don't want this to happen implicitly all the time.

**Comment by twoeo** [comment]
Thanks, `asJSON` really solve this perfectly.

Sorry for that I really don't know this before, maybe it's because never find this function in generated static js files.

Maybe consider to include `asJSON` in generated js ?

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/protobuf.js/issues/588

**Comment by dcodeIO** [comment]
Closing this for now as 6.4.0, which is now released, should solve the issue. Feel free to reopen the issue if necessary.
