### ISSUE TITLE
Type definition error (TypeScript) when enable strictNullChecks

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#592]
***tsconfig.json***
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": true,
        "moduleResolution": "node",
        "strictNullChecks": true
    }
}
```

when compiled, it will error:
> ERROR in E:\Codes\ChartMaker\frontend\node_modules\protobufjs\types\protobuf.js.d.ts
(1284,11): error TS2417: Class static side 'typeof Root' incorrectly extends base class static side 'typeof Namespace'.
  Types of property 'fromJSON' are incompatible.
    Type '(json: any, root?: Root | undefined) => Root' is not assignable to type '(name: string, json: Object) => Namespace'.
      Types of parameters 'root' and 'json' are incompatible.
        Type 'Object' is not assignable to type 'Root | undefined'.
          The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
            Type 'Object' is not assignable to type 'Root'.
              The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
                Property 'deferred' is missing in type 'Object'.
webpack: bundle is now VALID.

**Solution**

protobuf.js.d.ts, Line 1313 change to :

```ts
static fromJSON(json: any, root: Root): Root;
```

or 

protobuf.js.d.ts, Line 754 change to :

```ts
static fromJSON(name: string, json?: Object): Namespace;
```

**Comment by dcodeIO** [comment]
I am not exactly sure if this fixes the issue, so please let me know.

I actually believe that not being able to override static methods like that with TypeScript is wrong. There should be a way to force it because it sometimes makes sense.

**Comment by twoeo** [comment]
> I actually believe that not being able to override static methods like that with TypeScript is wrong.

Agree, and finally I solve this by add a declaration in my custom.d.ts:
```ts
declare module 'protobufjs';
```

I always use static-module js file, so above makes `protobufjs` as `any` to ignore this error.
