### ISSUE TITLE
Unresolvable field type for nested fields.

### ISSUE THREAD

**Issue by ashubham** [dcodeIO/protobuf.js#595]
protobuf.js version: 6.3.1

In prior versions of protobufjs (4.0/5.0) this used to compile fine, and also with the google proto compiler. But when trying to generate a static module or using the json I get the following error for some fields in my `.proto`. All of these fields are actually nested fields like the one below:

```js
import "net/trace/trace.proto"
package net.rpc;

message RpcDebugInfo {
  extend TraceEvent {
    optional RpcDebugInfo trace = 1008;
  }
  optional int64 size = 1;
}
```
This is the error:
```
Error: Unresolvable field type: RpcDebugInfo
```

**Comment by dcodeIO** [comment]
Is it correct to assume that the full names of the messages in question are `net.trace.TraceEvent` and `net.rpc.RpcDebugInfo`?

If so, does the same happen if you change `extend TraceEvent` to `extend trace.TraceEvent`?

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by ufenegga** [comment]
Looks like  changing extend TraceEvent to extend trace.TraceEvent solve the issue..

**Comment by dcodeIO** [comment]
Afaik this is also the indented behavior.

With `TraceEvent`, look up is:
* `TraceEvent`  in `net.rpc`? no, search parent
* `TraceEvent` in `net`? no, search parent
* TraceEvent in *root*? no, throw

With `trace.TraceEvent`, it is:
* `trace` in `net.rpc`? no, search parent
* `trace` in `net` yes, search child
* `TraceEvent` in `net.trace`? yes, return `TraceEvent`
