### ISSUE TITLE
add imports to generated .d.ts file

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#596]
protobuf.js version: 6.3.1

Using the pbts tool and WebStorm doesn't like the generated .d.ts file unless I manually add the following lines at the top of the file

import {Writer} from 'protobufjs';
import {Reader} from 'protobufjs';

**Comment by jeffgrossmann** [comment]
Is it issue with WebStorm of the typescript compiler?

**Comment by ehallander9591** [comment]
It would seem that any external package references in the generated .d.ts file would need some sort of reference. Webstorm complains, because tsc complains.

**Comment by vanishs** [comment]
Also need to add 'Method'.

**Comment by dcodeIO** [comment]
Closing this for now as 6.4.0, which is now released, should solve the issue. Feel free to reopen the issue if necessary.
