### ISSUE TITLE
When defaults=false, arrays are initialized as null

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#597]
V5 behavior has been that arrays are always initialized. Can we get the same behavior back via an JSONConversionOption. We don't want non-arrays to be initialized to defaults, but there are several places where arrays need to be initialized to []

#MigrationPains

**Comment by dcodeIO** [comment]
Not exactly sure that there should be an option to handle just array defaults while excluding everything else. I feel like this is too much of a special case.

**Comment by r-tock** [comment]
I understand the feel of special case. But because of v5 there are several places where this is done and even at our scale of code size it's a nightmare.

For arrays in every language other than protobufjs arrays are never null. Which makes the null representation here stick out as a exception. And this is independent of proto2/3

**Comment by dcodeIO** [comment]
So, the array field values are explicitly set to `null` instead of being just `undefined`? That would indeed be a bug.

**Comment by r-tock** [comment]
I mean set to null instead of default initialized []

**Comment by dcodeIO** [comment]
Can you provide additional information or an example?

**Comment by r-tock** [comment]
Let's say a parsed proto object looks like

Message MyProto {
 optional int32 some_int = 1;
 repeated int32 some_array = 2;
 repeated int32 other_array = 3;
}

Let's say it parsed a datastream and looked like this.
 {someArray:[0, 1] }
obj.otherArray will be []

 But on converting to JSON
 We get {someArray:[0, 1] }
However when I enable defaults, I get {someInt :0, someArray:[0,1], otherArray: [] } this is fine as this is a proto3 behavior
But former is not. When converting to JSON without defaults prroto2 usually gives you default initialized array and you expect { someArray:[0,1], otherArray: [] }

**Comment by r-tock** [comment]
👍

**Comment by r-tock** [comment]
Reopening to address https://github.com/dcodeIO/protobuf.js/commit/40074bb69c3ca4fcefe09d4cfe01f3a86844a7e8#comments

**Comment by r-tock** [comment]
@dcodeIO Hope you get a chance to address this again, last remaining blocker for us.

**Comment by dcodeIO** [comment]
Have you tried again [with master](https://github.com/dcodeIO/protobuf.js/blob/master/src/converter.js#L57), lately?

**Comment by dcodeIO** [comment]
Closing this for now as 6.4.0, which is now released, should solve the issue. Feel free to reopen the issue if necessary.
