### ISSUE TITLE
Typings: micro-modules need types!

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#599]
Typings files need to be included for your micro-modules, like `@protobufjs/base64`

**Comment by dcodeIO** [comment]
Do you get any error or are you using the modules directly?

**Comment by dcodeIO** [comment]
I copy-pasted these now but didn't verify whether this is working without additional modifications.

**Comment by dcodeIO** [comment]
Updated to mirror, what I hope to be improvements, from https://github.com/dcodeIO/protobuf.js/commit/a7d23240a278aac0bf01767b6096d692c09ae1ce

**Comment by paralin** [comment]
Yeah, you need index.d.ts for each module. I was using them directly. Furthermore I've had a lot of issues with having the typings in the typings subdirectory instead of next to index.js as index.d.ts so I'm glad you've made that change.

**Comment by dcodeIO** [comment]
Closing this for now as 6.4.0, which is now released, should solve the issue. Feel free to reopen the issue if necessary.
