### ISSUE TITLE
Error when directly decoding Uint8Array

### ISSUE THREAD

**Issue by osechet** [dcodeIO/protobuf.js#605]
protobuf.js version: 6.3.1

Here is my proto message:
```proto
message Response {
    fixed32 id = 1;
    bytes data = 2;
    string error = 3;
}
```

When I directly decode the data sent from my server as a `Uint8Array`, for example:
```ts
let data = Uint8Array.from([26, 5, 69, 114, 114, 111, 114]);
let foo = Response.decode(data);
```

I get the following error:
```
TypeError: this.buf.utf8Slice is not a function
    at BufferReader.read_string_buffer [as string]
    at Function.decode
```

If I pass a `Reader` to the `decode` function, it works:
```ts
let data = Uint8Array.from([26, 5, 69, 114, 114, 111, 114]);
let foo = Response.decode(new Reader(data));
```

**Comment by dcodeIO** [comment]
Why would you use Uint8Array.from over Buffer.from on node?

**Comment by osechet** [comment]
@dcodeIO This was just for the example. In my application, I'm not creating the data array, I get it from a c++ server and I receive it as a `Uint8Array`.

**Comment by dcodeIO** [comment]
Alright, just note that passing an Uint8Array uses the browser reader now which doesn't benefit from node's buffer binding for strings and so on.
