### ISSUE TITLE
Enums should default to first defined value not the one with tag = 0

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#613]
On the client side I am encoding

```json
{
   operation: 'AND',
   valueSet: [{
      dimension: 'DIMENSION_1',
      value: [2]
   }]
}
```

On the server (in java) I am receiving

```json
{
    valueSet: {
      value: [605]
    }
}
```
Here is the proto used. Stripped down for simplicity

```proto
message Filter {
  enum Operation {
    AND = 0;
  }

  optional Operation operation = 1;
  repeated ValueSet value_set = 2;
  repeated Filter filter = 5;
}

enum Dimension {
   DIMENSION_1 = 0;
}

message ValueSet {
  optional Dimension dimension = 1;
  repeated int64 value = 2;
}
```

**Comment by r-tock** [comment]
On the client side converting to buffer and parsing the buffer back yields the correct json (1st one). Since the server side is using Google's protobuf library, I suspect protobufJS to be having the bug, but we could be wrong.

**Comment by dcodeIO** [comment]
Buffer:

```
08	id 1, wireType 0
00	value 0
12	id 2, wireType 2
04	length 4
08	id 1, wireType 0
00	value 0
10	id 2, wireType 0
02	value 2
```

**Comment by r-tock** [comment]
ha. it turns out the enum is a bit weird. number 18 is defined at the top and on the server side it is being defaulted to as the parsed object does not seem to have the enum set.

```proto
enum Dimension {
   DIMENSION_18 = 18;
   DIMENSION_1 = 0;
}
````

**Comment by dcodeIO** [comment]
I see. Optional enums with default values are not encoded on the wire, so this seems to be the underlying issue.

**Comment by r-tock** [comment]
Hmm yeah, in this case there is no `[default = DIMENSION_1]` specified. Could be a quirk in the format.

**Comment by dcodeIO** [comment]
From Google's developer guide:

> For enums, the default value is the first defined enum value, which must be 0.

https://developers.google.com/protocol-buffers/docs/proto3#default

Seems that the official implementation just takes the first defined, while protobuf.js uses 0.

**Comment by r-tock** [comment]
The enum issue I fixed on the server side, but yes you should use the first defined as the default in js as well. The int64 wire type issue is red-herring, that seems to be a bug in our code which was sending wrong data. I will rename the bug
