### ISSUE TITLE
Can we get enum implementations similar to the typescript compiled code ?

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#617]
protobuf.js version: <6.3.1>

Enhancement Request

For example an enum defined as 
```protobuf
enum View {
	VIEW_UNSPECIFIED = 0,
	VIEW_BLUE = 1,
	VIEW_RED = 2,
	VIEW_WHITE = 3
}
````
will generate javascript that is:
```js
var View;
(function (View) {
    View[View["VIEW_UNSPECIFIED"] = 0] = "VIEW_UNSPECIFIED";
    View[View["VIEW_BLUE"] = 1] = "VIEW_BLUE";
    View[View["VIEW_RED"] = 2] = "VIEW_RED";
    View[View["VIEW_WHITE"] = 3] = "VIEW_WHITE";
})(View || (View = {}));
```
which allows View[0] to be "VIEW_UNSPECIFIED" and View["VIEW_UNSPECIFIED"] to  be 0. 

Pretty sure, that a proto definition of
```protobuf
enum View {
	VIEW_UNSPECIFIED = 0;
	VIEW_BLUE = 1;
	VIEW_RED = 2;
	VIEW_WHITE = 3;
}
```
could be implemented as
```js
View = {
      VIEW_UNSPECIFIED: 0,
      VIEW_BLUE: 1,
      VIEW_RED: 2,
      VIEW_WHITE: 3,
      "0": "VIEW_UNSPECIFIED",
      "1": "VIEW_BLUE",
      "2": "VIEW_RED",
      "3": "VIEW_WHITE"
};
```
I am currently referencing the static module generated javascript, and such an addition would allow a generic function to easily map rest values of both the numeric and string versions of the enumeration to a number value in those generated classes whose property is an enum. ie number.

Thanks

**Comment by dcodeIO** [comment]
This has been implemented in 6.4.0. pbts generates proper "enum" types there.

**Comment by ehallander9591** [comment]
FYI, I wrote this up before I actually tried my generic function against what you were already generating, and it works fine as is. :)

Would there be any value to listing the enums in the .d.ts file?

**Comment by dcodeIO** [comment]
> Would there be any value to listing the enums in the .d.ts file?

What do you mean? pbts currently generates [something like this](https://github.com/dcodeIO/protobuf.js/blob/master/tests/data/test.d.ts#L20).

**Comment by ehallander9591** [comment]
Having trouble verifying that because pulling the latest gives me runtime errors

     [exec] C:\Users\eric_hallander\git\MPXSCore\node_modules\protobufjs\cli\pbjs.js:115
     [exec]         if (glob.hasMagic(files[i])) {
     [exec]                  ^
     [exec] TypeError: glob.hasMagic is not a function
     [exec]     at Object.exports.main (C:\Users\eric_hallander\git\MPXSCore\node_modules\protobufjs\cli\pbjs.js:115:18)
     [exec]     at Object.<anonymous> (C:\Users\eric_hallander\git\MPXSCore\node_modules\protobufjs\bin\pbjs:4:16)
     [exec]     at Module._compile (module.js:570:32)
     [exec]     at Object.Module._extensions..js (module.js:579:10)
     [exec]     at Module.load (module.js:487:32)
     [exec]     at tryModuleLoad (module.js:446:12)
     [exec]     at Function.Module._load (module.js:438:3)
     [exec]     at Module.runMain (module.js:604:10)
     [exec]     at run (bootstrap_node.js:394:7)
     [exec]     at startup (bootstrap_node.js:149:9)
     [exec] Result: 1

**Comment by ehallander9591** [comment]
However I did see the enums on a colleague's generation of the code using 6.4.0. I have 6.4.2 downloaded, and can't run anything.

**Comment by ehallander9591** [comment]
Final comment,

I guess because of the change in the lazy loading to only load the non devDependencies needed at runtime, I needed to run npm install from both the local node_modules/protobufjs and the global protobufjs to get the missing libraries loaded.

FYI - For local it was glob, and for global it was jsdoc
