### ISSUE TITLE
protobufjs - backbone

### ISSUE THREAD

**Issue by frediana** [dcodeIO/protobuf.js#619]
Hello,

First of all, congratulation for your lib, it's very well done. Simple and efficient, I like it.

Not sure this is the best place to discuss it, but I would talk about an idea/project I have. Not sure yet if worth it, but maybe you can help me decide.

I would like to use protobufjs to dynamically generate Backbone Model/Collection (http://backbonejs.org/)

In my previous company, we were using a protocol buffer like (with more feature like Classes, Unions, statics and more stuff) , and I successfully done the lib that generates Backbone stuff from it. Now, I thought this would be great to create a similar open source project but based on the real protocol buffer spec.

At this time we were generating .json definition from .proto, and load them into the browser in a very similar way you do. Then I made a jquery-like lib to quickly request everything a need for each Struct (fields, optional ,field type etc...). I was then building Backbone Model on the Fly, including defaults, attributes, sync method, model validation etc...

Instead, now I think, I could just use protobufjs, to build these the same way. I could maybe go further, and allow static code generation maybe.

What do you think?

Any feedback would be more than welcome!

Thanks a lot, Adrien.

**Comment by dcodeIO** [comment]
Using reflection, you should be able to generate pretty much everything you can think of. This is how [pbjs does it](https://github.com/dcodeIO/protobuf.js/blob/master/cli/targets/static.js). You could, of course, also use a hybrid approach by generating code with pbjs first and then extending the generated classes with custom functionality. This also works with reflection based classes as [explained here](https://github.com/dcodeIO/protobuf.js#using-custom-classes).

If you have any further questions, feel free to ask!

**Comment by frediana** [comment]
I'm currently bootstrapping the project here: https://github.com/fairway-digital/pbjs-backbone

Since I will probably heavily use protobufjs I may have some questions soon:)

Thanks a lot
