### ISSUE TITLE
Seeing a bunch more weirdness in asJSON

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#620]
This is converted with
```json
{ fieldsOnly: true, longs: Number, enums: String, defaults: false, arrays: true }
```

Array entry 0 is missing color, secondary state and orderings.
<img width="1440" alt="screen shot 2017-01-04 at 2 24 49 pm" src="https://cloud.githubusercontent.com/assets/11711723/21658156/05dc3fac-d28b-11e6-9853-285fd1cc76ae.png">

Array entry 1 is missing all the fields.
<img width="1437" alt="screen shot 2017-01-04 at 2 25 03 pm" src="https://cloud.githubusercontent.com/assets/11711723/21658153/04fbcf4e-d28b-11e6-90d0-5fb36fb72432.png">

I also have a case where enum is not converted to String.

**Comment by yoni-tock** [comment]
It also looks like the enum value 0 isn't being converted to a string, but anything greater than zero is being converted. For example, before `toJSON` index 0 has icon 0 and index 1 has icon 3 but after `toJSON` index 0 has icon 0 and index 1 has icon "TRANSFER".

<img width="1435" alt="screen shot 2017-01-04 at 2 46 53 pm" src="https://cloud.githubusercontent.com/assets/11616747/21658544/ad874a34-d28c-11e6-9c3b-be6375ebec86.png">

**Comment by r-tock** [comment]
Also including https://github.com/dcodeIO/protobuf.js/issues/616 There needs to be a better differentiation between 0 and unset.

**Comment by dcodeIO** [comment]
This is probably due to asJSON removing any default values when `{ defaults: true }` isn't set. Hrm.

**Comment by r-tock** [comment]
Thank you! Once this is done, we will be in a really amazing pace, can't wait to get all the big performance improvements with this release. 

All these are painful because these are breaking changes and we have a large code base with hundreds of messages.

**Comment by dcodeIO** [comment]
May I ask what's the exact format of the json data you are using? Does it somewhat correspond to the official [proto3 json mapping](https://developers.google.com/protocol-buffers/docs/proto3#json)?

The reason why I'm asking is that I'd like to start with the official JSON mapping and then build onto that, ideally eliminating as many of the options as possible.

**Comment by r-tock** [comment]
Yes, official mapping will work with few options for exceptions. 
 we use number for long,(which we can change over in a different pass) and add defaults for arrays(which again is too daunting for this pass). 
The mappings don't specify extensions which we use heavily. I would love to keep the current format for that where key is the type. 
We can't remove default values if present because that is a proto2 thing and that will be a severe breakage. The only rule we care is that specified values need to be present in JSON form

**Comment by r-tock** [comment]
@dcodeIO just checking to see if you have made some progress on this.

**Comment by dcodeIO** [comment]
Not yet, unfortunately. I really want 6.4.X to become stable enough now, before going for a 6.5.X with new converters.

**Comment by dcodeIO** [comment]
Additional notes:
* `asJSON` is now `toObject` to mimic official protobuf APIs. This is available both statically (with an additional `message` parameter) and on instances.
* There is now `toJSON` on message instances (utilized by `JSON.stringify`) that uses default options to be somewhat compatible to official json conversion
* Currently, there is no more `bytes: Buffer` option. I know this is important to gRPC, but I'd rather like to drop it than to keep this around forever
* There is no more `fieldsOnly: true|false` option
* There is now `objects: true` that does for maps what `arrays: true` does for repeated fields
* There are no more conversion options for object -> message conversion because unnecessary

Also worth mentioning: This generates somewhat longish code now, but it is 10+ times faster than what we had before iirc.

**Comment by r-tock** [comment]
Sweet! Let me try it

**Comment by r-tock** [comment]
from is throwing an error. I have a proto which has a message as a nested field 

message MyProto { optional MyNestedProto proto = 1 }
where MyNestedProto has a long id in it.

MyProto.from({}) is crashing, its trying to parse MyNestedProto

**Comment by r-tock** [comment]
still throwing...

**Comment by dcodeIO** [comment]
This is working for me:

```js
var root = protobuf.Root.fromJSON({
    nested: {
        MyProto: {
            fields: {
                proto: {
                    type: "MyNestedProto",
                    id: 1
                }
            }
        },
        MyNestedProto: {
            fields: {
                aLong: {
                    type: "uint64",
                    id: 1
                }
            }
        }
    }
}).resolveAll();

var myProto = root.MyProto.from({});
console.log(myProto);
```

What's the difference?

**Comment by r-tock** [comment]
Hmm. I don't know... 
I am seeing this

<img width="597" alt="screen shot 2017-01-11 at 11 25 51 pm" src="https://cloud.githubusercontent.com/assets/11711723/21878090/5e395322-d855-11e6-99fb-42391d50f193.png">

**Comment by r-tock** [comment]
Fixed it. Looks like a version skew. I am working off git+https://... in package.json It does not really work on branches. 
All good, All our tests are passing!

**Comment by r-tock** [comment]
I have gone through several features so far in my giant protobuf conversion branch and I have yet to find anything obviously broken with the entire slew of apps we have.

I will have more eyes during code-review and QA. I will post if there are more issues. 

Closing the bug. please push 6.5.0 when you get a chance, we would prefer not to build production assets directly from git master.
