### ISSUE TITLE
pbts cannot find jsdoc

### ISSUE THREAD

**Issue by cyluss** [dcodeIO/protobuf.js#622]
protobuf.js version:  6.4.3
OS: windows 10 x64

`pbts` fails to run, because it cannot find jsdoc module. Maybe affected by #618?

repro step
-----------

1. `greeter.proto` is [Greeter example](https://github.com/dcodeIO/protobuf.js#using-services).

2. Run `node_modules\.bin\pbjs --target static-module --wrap commonjs greeter.proto >greeter.js`. This step installs CLI dependency and __runs as expected__.

3. Run `node_modules\.bin\pbts greeter.js > greeter.d.ts`, fails to run.

error output
--------------
```
PS C:\Users\kang\Downloads\test> node_modules\.bin\pbts greeter.js > greeter.d.ts
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\kang\Downloads\test\node_modules\protobufjs\node_modules\jsdoc\jsdoc.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
C:\Users\kang\Downloads\test\node_modules\protobufjs\cli\pbts.js:123
                    throw err;
                    ^

Error: code 1
    at Error (native)
    at ChildProcess.<anonymous> (C:\Users\kang\Downloads\test\node_modules\protobufjs\cli\pbts.js:119:27)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by cyluss** [comment]
There is no `node_module` directory under `node_modules/protobufjs`, while it exists under `node_modules/protobufjs/cli`.

**Comment by dcodeIO** [comment]
On first run of `node_modules\.bin\pbjs` it should be installing all required CLI dependencies, which are:
```
installing CLI dependencies: chalk@^1.1.3, glob@^7.1.1, jsdoc@^3.4.2, minimist@^1.2.0, tmp@0.0.31, uglify-js@^2.7.5
```
These are installed to `node_modules\protobufjs\cli\node_modules` to make sure that not all dev dependencies from the protobufjs package are installed (npm does this, unfortunately, when not having node_modules specifically for the cli).

When running `node_modules\.bin\pbts` afterwards, it should be able to find the dependencies in `cli\node_modules`, but it obviously can't for some reason. Any ideas?

**Comment by dcodeIO** [comment]
Found it, hardcoded [here](https://github.com/dcodeIO/protobuf.js/blob/master/cli/pbts.js#L100).

**Comment by cyluss** [comment]
https://github.com/dcodeIO/protobuf.js/blob/6.4.3/cli/pbts.js#L98

basedir should be `__dirname`. Fixed and ran again, gives another error.

```
Cannot parse the config file C:\Users\kang\Downloads\test\node_modules\protobufjs\cli/jsdoc.types.json: Error: ENOENT: no such file or directory
```

Where is `jsdoc.types.json`? Is it in protobuf.js or in jsdoc?

**Comment by dcodeIO** [comment]
Yeah, because the config is still in the old basedir. This required another lookup just for jsdoc.

**Comment by dcodeIO** [comment]
The latter does the same, just a bit simpler.

**Comment by dcodeIO** [comment]
On npm now as 6.4.4, thanks!
