### ISSUE TITLE
how can I use encode in static-module

### ISSUE THREAD

**Issue by yejinjian** [dcodeIO/protobuf.js#623]
I Hav change my 'proto' file to a commonjs file.

so how can I use use encode/decode whith this js file？ 

I saw the code in "protobufjs/runtime", it did not include root.js

**Comment by dcodeIO** [comment]
Have you tried 6.4.4? There has been a fix for static json modules mistakenly requiring "protobufjs/runtime" instead of "protobufjs" recently.

**Comment by yejinjian** [comment]
I got it.  But I have a question:  why didn't include "protobuf.Root"  into   "protobufjs/runtime"

**Comment by dcodeIO** [comment]
You can read about the runtime [here](https://github.com/dcodeIO/protobuf.js#descriptors-vs-static-modules) and [here](https://github.com/dcodeIO/protobuf.js/tree/master/dist/runtime).

Basically, the runtime is a minimal subset of protobuf.js that has just enough functionality to work with statically generated code (the ´static` and `static-module` targets). `Root`, for instance, is a reflection object, but static code does not have any reflection capabilities hence it is excluded from the minimal runtime.

**Comment by yejinjian** [comment]
any  example with "static modules" use?

**Comment by yejinjian** [comment]
I got it, I want to write a pb-loader for webpack which suport 'static-module'.
I find I should use 
``` javascript
{
  create: true,
  encode: true,
  decode: true,
  verify: true,
  convert: true,
  delimited: true,
  beautify: true,
  comments: true,
}
```
I used to find 'encode/decode' in the code of "protobufjs/runtime" everywhere.   thanks!

**Comment by cyluss** [comment]
Alright, so you need to [run `pbjs` programmatically](https://github.com/dcodeIO/ProtoBuf.js/#using-pbjs-and-pbts-programmatically). Note that all your options is [already set as default](https://github.com/dcodeIO/protobuf.js/blob/6.4.4/cli/pbjs.js#L35).

Any other questions? If not, please close your issues.

**Comment by yejinjian** [comment]
thank you!
