### ISSUE TITLE
compile error in ionic2

### ISSUE THREAD

**Issue by jagannathTL** [dcodeIO/protobuf.js#626]
protobuf.js version: <6.4.5>

It should compile with out any errors.

  ```
console.log('Hello ProtoService Provider');
    protobuf.load("../assets/awesome.proto", function(err, root) {
    if (err) throw err;
 
    // Obtain a message type 
    var message = root.lookup("awesome");
 
   console.log(message);
});
```

```
1:52:28]  lint finished in 6.63 s
[11:52:33]  Error: Error at /Users/zaggu/Documents/ionic/bookapp/node_modules/protobufjs/index.d.ts:1346:25
[11:52:33]  Cannot find name 'Buffer'.
[11:52:33]  ngc failed
[11:52:33]  ionic-app-script task: "build"
[11:52:33]  Error: Error

```

**Comment by ralscha** [comment]
Just ran into the same problem with Ionic 2.
First step to solve that problem is installing the type definitions for node
```
npm install @types/node --save-dev
```

This solved the problem on Linux (nodejs 6.9.4) but did not on Windows. 
I tested it with nodejs 6.9.4 and 7.4.0.

To finally solve the problem on Windows I had to add a ```reference``` line to the 
<project_home>node_modules\protobufjs\index.d.ts
file. 

```
/// <reference types="node" />
export as namespace protobuf;
.......
```

I have no idea why Linux and Windows behave differently. 

I found the idea with the reference line in the node-uuid definition file. 
This definition references Buffer too.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-uuid/index.d.ts

**Comment by dcodeIO** [comment]
Reference lines were in place initially, but didn't work well. Another thing is that the library can be used under node.js as well as in the browser, making the node reference rather opt-in. It shouldn't error out without those references, though, if you do not use any node specific features on your own, in which case you'd require the reference anyway.

**Comment by ralscha** [comment]
My app contains this protobuf code
```
  constructor(private readonly http: Http) {
    protobuf.load("assets/Earthquake.proto", (err, root) => {
      if (err) {
        throw err;
      }
      this.Earthquakes = root.lookup("Earthquakes");
    });
  }
```
and a bit later this
```
const message = this.Earthquakes.decode(new Uint8Array(response.arrayBuffer()));
```

I agree, Ionics build system should not complain about the missing Buffer, unfortunately it does. 
And it will not build the app without installing the node type definition file and adding the reference (on Windows).

**Comment by ralscha** [comment]
If somebody wants to investigate this further. Here is a simple way to reproduce the error.

Install ionic and create a new app
```
npm install ionic -g
ionic start myapp blank --v2
```
add 
```
import * as protobuf from "protobufjs";
```
to ```<project_home>/src/pages/home/home.ts``` and then start the build
```
npm run build
```

**Comment by zixia** [comment]
I ran into this issue today in my ubuntu 17.10.

```
node_modules/grpc/index.d.ts(2,55): error TS7016: Could not find a declaration file for module 'protobufjs'. '/home/zixia/chatie/grpc/node_modules/protobufjs/dist/protobuf.js' implicitly has an 'any' type.
  Try `npm install @types/protobufjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'protobufjs';`
```

I had already installed the `@types/protobufjs` but this error still exists.
