### ISSUE TITLE
Create release of Protobuf5 branch

### ISSUE THREAD

**Issue by BeyondDefinition** [dcodeIO/protobuf.js#627]
protobuf.js version: HEAD of Protobuf5 branch

Could you please create a release of the Protobuf5 branch, since development in this branch has been reduced. Commit https://github.com/dcodeIO/protobuf.js/commit/f2661c32e44cdc975e3baabe0667cc648717f58f adds an important feature for me, now I have to reference github instead of an npm package.

**Comment by dcodeIO** [comment]
Now on npm as 5.0.2. Really hope this doesn't break something. Feel free to reopen if necessary!

**Comment by gabrielgrant** [comment]
According to [a comment on #468](https://github.com/dcodeIO/protobuf.js/issues/468#issuecomment-245373126), that change doesn't fully enable streaming RPC calls. @BeyondDefinition have you found a way to use streaming calls with the v5 branch?
