### ISSUE TITLE
'repeated' fields are readonly?

### ISSUE THREAD

**Issue by wgreenberg** [dcodeIO/protobuf.js#630]
protobuf.js version: 6.4.5
node version: 4.4.3

Apologies if this is me simply using protobuf.js incorrectly, but after upgrading from 4.x I noticed that I can no longer alter a repeated field at runtime using `Array.push`:

```js
const Protobuf = require('protobufjs');
const fs = require('fs');

const protobufRoot = Protobuf.parse('message Foo { repeated string bar = 1; }').root;
const protobufObjects = protobufRoot.nested;

let h = protobufObjects.Foo.create();
h.bar.push('foo');
```

This yields the following error:

```
h.bar.push('foo');
      ^

TypeError: Can't add property 0, object is not extensible
    at Object.<anonymous>
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by dcodeIO** [comment]
This is a quirk of having default values on prototypes. If you just modify an array or objects on the prototype, you modify this exact instance of the object and thus modify the default value of all messages that extend this prototype. Hence, objects on the prototype are frozen through `Object.freeze`.

Instead, you should assign a new array, which sets it on the actual instance of the message.

```js
h.bar = ["foo"];
```

Internally, protobuf.js accounts for this by either checking for `=== protobuf.util.emptyArray` respectively simply following the pattern `if (!h.bar.length) h.bar = [];`.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by wgreenberg** [comment]
@dcodeIO sounds good. Your comments on this and #631 addressed my issues well enough, thanks!
