### ISSUE TITLE
Is this a bug about loadSync?

### ISSUE THREAD

**Issue by codingmiao** [dcodeIO/protobuf.js#632]
When I use "loadSync" method to construct a Root object,the attribute "nested" is undefined:
`var root1 = protobuf.loadSync("feature.proto");
//root1 : {options: undefined, name: "", parent: null, resolved: false, nested: undefined…}`

So will not be able to execute the following code "var arrBuilder = root.lookup("pojo.FeatureArrPb")"

But when I use load method,it's correct:
`protobuf.load("feature.proto", function (err, root) {
        if (err) throw err;
        console.log(root);
    });`
`//root : {options: undefined, name: "", parent: null, resolved: false, nested: Object…}`

this is feature.proto file ：

> syntax = "proto3";
package pojo;
message ShapePb{
	fixed32 sdoGtype = 1;
	repeated fixed32 sdoElemInfo = 2;
	repeated double sdoOrdinates = 3;
}
message FeaturePb{
	string devId = 1;
	ShapePb shape = 2;
	string classId = 3;
	fixed32 vlevelCode = 4;
	string name = 5;
}
message FeatureArrPb{
	repeated FeaturePb list = 1;
}

**Comment by dcodeIO** [comment]
Are you using `.loadSync` in the browser? Might be a bug otherwise.

**Comment by codingmiao** [comment]
Sorry, I didn't notice that it's node.js only,and I will try to use other ways to realize synchronously load.Thanks!
