### ISSUE TITLE
How to retrive bytebuffer from protobuf message

### ISSUE THREAD

**Issue by rameshpasunoori** [dcodeIO/protobuf.js#634]
Hi All
I am trying to send protobuf message from javascript based client application to Java based server application using web sockets.

How to get the bytebuffer from protobuf message in javascript and send over network, again create the message in javaside.

Please provide is there any sample application.

Thanks
Ramesh

**Comment by dcodeIO** [comment]
Which version of the library are you using? (There is a reason for the issue template)

**Comment by rameshpasunoori** [comment]
Protobuf version 6.4.4
Exact issue is need to generate bytebuffer from protobuf message.
Send over the network using websockets.
Regenrate the message in java server using message.parsefrom function.

With older version of protobuf released in 2013.
Able to get bytebuffer using
message.encode method it,s returning bytebuffer directly.

Latest version encode method returning writer.

**Comment by dcodeIO** [comment]
v6 does not use bytebuffer.js anymore. Instead, calling `Writer#finish()` returns a Buffer / Uint8Array directly.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
