### ISSUE TITLE
Encoding: Longs default value of 0 is not being set on the wire

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#639]
protobuf.js version: master

Is this intended? If the field is set java proto2 library does not ignore defaults and sets it on the byte stream

**Comment by r-tock** [comment]
In general anything set (either on the object or present in the json from which it is parsed) should be on the wire.

**Comment by dcodeIO** [comment]
I always assumed that such default values would ideally be excluded on the wire for efficiency. Do you know if this is an official implementation detail or if it just happens that the Java lib does it this way?

**Comment by r-tock** [comment]
I guess it is official implementation detail based on both C++ and Java libraries (~8 years of exp now). I don't know about the other libraries.

**Comment by r-tock** [comment]
With proto3 I presume you can make the argument that default values should be excluded. But I have definitely been used to the behavior of value being set in the proto2 world.

**Comment by r-tock** [comment]
Could you help get a release out with a fix for this issue. This is the last remaining issue with migrating our code-base.

**Comment by dcodeIO** [comment]
Sorry, have been busy fixing jsPerf today. On top of that, a fix for this would break a lot of stuff, as the entire default values on prototypes model is involved.

**Comment by dcodeIO** [comment]
I've now tested an implementation that uses `Object.keys` to determine which values are present. Unfortunately, that's 33% slower than what we have now.

**Comment by dcodeIO** [comment]
Now testing an implementation using `hasOwnProperty`. This does in fact seem to drop by just a bit with all the default value checks removed. Investigating.

**Comment by dcodeIO** [comment]
As a side-product, generated toObject implementations are super fast now using `hasOwnPropery` instead of `Object.keys`.

**Comment by r-tock** [comment]
Works great! Now I need a new release and I push our new converted code base to QA!

**Comment by dcodeIO** [comment]
Released on npm. Feel free to reopen if there are any issues!

**Comment by r-tock** [comment]
@dcodeIO I am seeing more related issues. nulled/undefined string fields are being sent as empty strings. across the wire

**Comment by dcodeIO** [comment]
Reference: https://github.com/dcodeIO/protobuf.js/blob/master/src/encoder.js#L88

Might be the case for required fields, yeah. Should throw on `.verify` though.

**Comment by r-tock** [comment]
These are not required fields, lets continue conversation here https://github.com/dcodeIO/protobuf.js/issues/652
