### ISSUE TITLE
Enhanced Documentation?

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#640]
protobuf.js version: <6.4.2>

Enhancement Request.

Was checking out https://github.com/estan/protoc-gen-doc and looking at the results, and thought that maybe pbjs could add the comments from a .proto file to it's own generated comments

Cheers

```js
/**
 * The type of change the published type represents
 */
enum ChangeType {
	CHG_UNKNOWN = 0;    /// An Unknown ChangeType condition
	CHG_UPSERT = 1;     /// Updated or Insert / Added
	CHG_DELETED = 2;    /// Deleted
}

could produce

                /**
                 * ChangeType enum.
                 * The type of change the published type represents
                 * @name ChangeType
                 * @memberof com.eoir.mpxs
                 * @enum {number}
                 * @property {number} CHG_UNKNOWN=0 An Unknown ChangeType condition
                 * @property {number} CHG_UPSERT=1 Updated or Insert / Added
                 * @property {number} CHG_DELETED=2 Deleted
                 */

or something like that.


```

```
<please paste the stack trace of the error if applicable>
```

**Comment by ehallander9591** [comment]
Then running jsdoc against the staticModule would product more complete and better documentation than what the plugin tool is producing.

**Comment by dcodeIO** [comment]
I really like the idea. Currently, the parser just ignores comments, though. Will look through it eventually.

**Comment by dcodeIO** [comment]
There is probably more to do here. For reference, this is the test case:
* [comments.proto](https://github.com/dcodeIO/protobuf.js/blob/master/tests/data/comments.proto) input
* [comments.js](https://github.com/dcodeIO/protobuf.js/blob/master/tests/data/comments.js) output

**Comment by dcodeIO** [comment]
While looking at the output of other test files, I realized that parsing all types of comments leads to a lot of nonsense for older protos, like using just commented out lines as field descriptions and stuff like that. Therefore, I decided to limit comment parsing to actual `/**` comment blocks for compatibility.

**Comment by dcodeIO** [comment]
And now also this:

```protobuf
/**
 * The type of change the published type represents
 */
enum ChangeType {
	CHG_UNKNOWN = 0; /// An Unknown ChangeType condition
	CHG_UPSERT = 1;  /// Updated or Insert / Added
	CHG_DELETED = 2; /// Deleted
}
```

**Comment by ehallander9591** [comment]
That looks pretty damn good sir.

Double Thanks
