### ISSUE TITLE
Encode JS /Decode server problem

### ISSUE THREAD

**Issue by pantonis** [dcodeIO/protobuf.js#643]
protobuf.js version: 5.0.1

<please describe the expected and actual behavior>
I am encoding an object and getting the following data:
8,1,18,6,67,104,97,114,105,115,0,0,0,0,0,0

On the server (protobuf-net) I am trying to deserialize this and I get error. If I remove the six extra 0s at the end of the payload it deserializes successfully. Why the library adds these extra 0s and is there any way to avoid them?

```js
<please provide a code snippet for reproduction>
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Seems to be exactly 16 bytes. Are you correctly using the ByteBuffer instance returned by `encode`? [This is why I ask](https://github.com/dcodeIO/bytebuffer.js/blob/master/src/bytebuffer.js#L133).

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by pantonis** [comment]
Hi, Sorry for the delayed response.

The problem I had is that the protobuf-net does not accept the extra 0s at the end which are unecessary. By using the Compact function of the ByteBuffer it solved my problem.

Thanks
