### ISSUE TITLE
Microsoft Edge ReaderPrototype.bytes returns whole buffer

### ISSUE THREAD

**Issue by zodern** [dcodeIO/protobuf.js#645]
protobuf.js version: 6.4.0

At [reader.js line 430](https://github.com/dcodeIO/protobuf.js/blob/master/src/reader.js#L430), it returns the whole buffer in Microsoft edge. In other web browsers it correctly slices the buffer. I am using Microsoft Edge 39.14986.1000.0 Microsoft EdgeHTML 15.14986. 

This happened anytime I decoded a message with a string.

Changing it to this fixed it:
```
this._slice.call(new Uint8Array(this.buf), 4, 80)
```

**Comment by dcodeIO** [comment]
Can you find out of what type `this.buf` is in your case - without your fix applied? Is it an Uint8Array?

**Comment by zodern** [comment]
It is Uint8Array

**Comment by dcodeIO** [comment]
Tested this in "Microsoft Edge 38.14393.0.0":

```js
var MyArray = Uint8Array;

var o = {};
o._slice = MyArray.prototype.subarray || MyArray.prototype.slice;
o.buf = new MyArray([1,2,3]);
o.bytes = function(start, end) {
    return o._slice.call(this.buf, start, end);
};

var sl = o.bytes(1, 2);
console.log("len=" + sl.length + ", val=[" + Array.prototype.slice.call(sl) + "]");
```

Outputs `len=1, vals=[2]` as it should.

**Comment by dcodeIO** [comment]
Closing this for now as I've added explicit test cases for this meanwhile which do not show any issues when running the tests in Edge on SauceLabs. Feel free to reopen the issue if you have any further details!
