### ISSUE TITLE
Encode + decode corrupts endianness in 5.0.1

### ISSUE THREAD

**Issue by joshkel** [dcodeIO/protobuf.js#647]
protobuf.js version: 5.0.1

If protobuf.js 5.0.1 is used to encode a message then immediately decodes that same message, then the message is incorrectly decoded as big endian, causing floating point and fixed-width integer fields to be corrupted.

I realize that protobuf.js 5.x has been superseded, but I thought it would help to at least have a record of the issue.

```js
var protobuf = require('protobufjs');
var builder = protobuf.loadProto('package awesomepackage; message AwesomeMessage { required float awesome_field = 1; }');
var AwesomeMessage = builder.build('awesomepackage.AwesomeMessage');
var message = new AwesomeMessage(1.1);
var buffer = message.encode();
console.log(message.$type.decode(buffer));
// writes -428967904
```

Manually setting the buffer to be little endian (by calling `buffer.LE()`) before calling `decode` fixes the problem.

**Comment by dcodeIO** [comment]
Shouldn't happen if you use `AwesomeMessage.decode` instead of the reflected type ([see](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/Builder/Message.js#L585)):

```js
var message = new AwesomeMessage(1.1);
var buffer = message.encode();
console.log(AwesomeMessage.decode(buffer));
```

**Comment by joshkel** [comment]
I had noticed that `AwesomeMessage.decode` works and should have mentioned that. I was using reflection as an attempt at a generic "clone" utility, [as discussed here](https://github.com/dcodeIO/protobuf.js/issues/315#issuecomment-135520905). Thank you for clarifying v5's reflection's limitations.
