### ISSUE TITLE
Internals change breaks pre-generated file

### ISSUE THREAD

**Issue by jkrems** [dcodeIO/protobuf.js#649]
protobuf.js version: `protobufjs@6.5.0`

The following code has been generated by a previous version (I think `6.4.5`):

```js
                        RecordSet.from = function from(source, options) {
                            return this.convert(source, $protobuf.converters.message, options);
                        };
```

Running with the latest version of protobufjs, I get the following error:

```
Uncaught TypeError: Cannot read property 'message' of undefined
```

**Comment by jkrems** [comment]
Looking at the changelog - should we be pinning to a specific version of the runtime or at least to a specific minor?

**Comment by dcodeIO** [comment]
Static code is still somewhat in flux due to being an entirely new feature. Hence, compatibility between minor version updates (i.e. 6.4 to 6.5) can't really be guaranteed. In such a case I'd recommend to depend on `"protobuf.js": "~6.5.0"` (or likewise) for now, which only accepts patch updates.

**Comment by jkrems** [comment]
Cool, thanks. We'll investigate moving code generation to startup and for now we'll narrow it down to `~6.5.0`.

**Comment by dcodeIO** [comment]
Also going to think about semver-compatible versioning again with the next breaking change. If you see a protobuf.js v7 in the near future, you'll know.
