### ISSUE TITLE
Problems with rpc calls in promise and class based Javascript

### ISSUE THREAD

**Issue by drObig** [dcodeIO/protobuf.js#650]
protobuf.js version: 6.5.0

I am not shure if it is the rigth place for this question but I am trying to do a rpc call to a Server with class and promise based Javascript (ES6) and the new protobuf.js Version.
It worked properly with Version 5.x but there I did it without promises and classes.

```js
var rpcCaller;
var rpcChannel;

export class Test {
	constructor( address ){
		this.address = address || '127.0.0.1:8000';
		rpcChannel = axios.create({
			baseURL: "http://" + this.address,
			responseType: "arraybuffer"
		});

		ProtoBuf.load("data/Service.proto")
			.then( ( root ) => {
				let TestServerService = root.lookup("service.TestServerService");
				rpcCaller = TestServerService.create( this.callMethod, /* requestDelimited? */ false, /* responseDelimited? */ false);
			});
	}
		
	callMethod( method, request, callback ){
		rpcChannel.request({
			url: "/" + method.parent.name + "/" + method.name
		}).then( (response) => {
			let msg = method.resolvedResponseType.decode(response.data, response.data.byteLength);
			
			//The Message is an empty Object of the right Type
			console.log("Decoded message ", msg);
			
			return callback(null, msg);
		});
	}
	
	getData(){
		return new Promise( ( resolve, reject ) => {
			rpcCaller.getData( {}, ( error, response ) => {
				if( error )
					return reject();

				return resolve( response );
			});
		});
	}
}
```
The function "getData()" is called after loading the index.html and the request works fine.

So, why is the "msg" in the callMethod function always empty? The response.data is the encoded Protobuf message, which i can see in the development tools of the browser (chrome).

Maybe I am wrong using the decode function of Protobuf.

A snippet of my Service.proto:

```
import "Common.proto"

package service;

message VoidIn
{}

message PathAliasesOut
{
	optional int32 errorCode = 1;
	repeated common.PathAlias pathAliases = 2;
}

service TestServerService
{
	rpc getData (VoidIn) returns (PathAliasesOut);
}
```

**Comment by dcodeIO** [comment]
Within `callMethod`, the callback expects raw responseData instead of a decoded message. but I remember that passing an already decoded message worked in v5.

**Comment by dcodeIO** [comment]
Tackled in https://github.com/dcodeIO/protobuf.js/commit/27b16351f3286468e539c2ab382de4b52667cf5e

Now also accepts an already decoded runtime message. Feel free to reopen if there are any issues!
