### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#651]
protobuf.js version: <6.5.2>

So, I "mused" about how to package my generated static module and generated .d.ts and said I packaged them both so I could find them in node_modules and node_modules/@types so I could write

```
import {namespace} from "myModule";
```

and then have code that used this as

```
let x:namespace.inner1.inner2.innerType = namespace.inner1.inner2.innerType.create({});
```

That was fine, however I didn't really need to put my .d.ts in @types, I could have simply packaged it with my generated .js file directly, and my IDE would have been fine with that.

HOWEVER, now because I have these inner namespaces which help the java, and c++ side of our protocol buffers, they seem cumbersome to some of us to use.

If I change my generated .d.ts to export everything as in

```
export namespace one {
     export namespace two {
          export namespace three {
               export class MyClasss {
               }

              export enum MyEnum {
                  VAL = 0,
                  ...
              }
        }
    }
}
```

then I can have an intermediate convenience file that imports and exports like rollup.ts

```
import {one} from "path-to-.d.ts";
import MyClass = one.two.three.MyClass;
import MyEnum = one.two.three.MyEnum;

export {MyClass, MyEnum}
```

and then finally I can write the following
```js
import * as rollup from "rollup";
let x:rollup.MyClass = rollup.MyClass.create({});
let y:rollup.MyEnum = rollup.MyEnum.VAL;
```

which my work colleague likes, or I could write 

```js
import {MyClass, MyEnum} from "rollup";
let x:MyClass = MyClass.create({});
let y:MyEnum = MyEnum.VAL;
```
which I like better.

```
<please paste the stack trace of the error if applicable>
```

So the take away from this ramble, is can we add "export" to all the inner definitions? or at the very least add an option to add inner exports?

**Comment by dcodeIO** [comment]
I don't quite undestand why your intermediate file shouldn't be working already. What I noticed, though, is that you are importing a `.d.ts` file, which doesn't seem right to me considering that it is just a definition and not a TypeScript source file.

Usually, you have both the `.js` file generated from `pbjs` and the `.d.ts` file generated from `pbts` stored next to each other, like `generated.js` and `generated.d.ts`, and then import it like `import * as root from "./rollup.js";` (notice that it is the `.js` file), which should also properly lookup its type definition. From there on, your intermediate file should already work, like so:

```ts
/// <reference path="./generated.d.ts" />
import * as root from "./generated.js";
export var A = root.My.Long.Path;
export var B = root.My.Other.Long.Path;
```

The leading reference path comment is actually optional if the lookup mechanism built into your IDE isn't able to resolve the definitions automatically.

**Comment by ehallander9591** [comment]
Firstly, I said path to .d.ts but meant path to where both .d.ts and .js files existed. The IDE finds the .d.ts file, and the runtime finds the .js implementations for those definitions.

The problem I saw with 

```
import * as root from "./generated.js";
export var A = root.My.Long.Path;
export var B = root.My.Other.Long.Path;

function(a:A) {
      console.log(a.toJSON());
}
```
would be fine for the definition a:A, but wasn't fine when I tried to access the methods or properties behind A.

**Comment by ehallander9591** [comment]
Apologies, I regenerated my files, and my rollup file still looks fine with no red squigglies.

I withdraw my request.

The takeaway

```
import {exported namespace in generated file} from "path to generated files"

import Class1=ns1.ns2.ns3.Class1;

let instance:Class1 = Class1.create({});
console.log(instance.toJSON());

```

seems to work just fine. I just didn't experiment enough. I got side tracked by this documentation in the Typescript handbook
```
namespace Shapes {
    export namespace Polygons {
        export class Triangle { }
        export class Square { }
    }
}

import polygons = Shapes.Polygons;
let sq = new polygons.Square(); // Same as 'new Shapes.Polygons.Square()'
```

Cheers
