### ISSUE TITLE
Do something better for calling Proto.from with a proto instead of a JSON. Currently all unset fields get expanded

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#652]
protobuf.js version: 6.5.2

This is causing failures for us on the server side as the has*() semantics are now broken.

**Comment by dcodeIO** [comment]
Reference: https://github.com/dcodeIO/protobuf.js/blob/master/src/converter.js#L128

**Comment by r-tock** [comment]
trying to construct a test case, simple test with a proto with one field passes. So it must be something deeper

**Comment by r-tock** [comment]
Gah!!! Found it. Somewhere in our code we are passing protoObj into a MyProto.from(protoObj) instead of JSON. the from happily takes in the proto, expands all the null fields. 🤦‍♂️

Can you help identify such bad call site and throw a console.warn or fatal error or something. Or maybe do something smarter

**Comment by dcodeIO** [comment]
Should now just return the runtime message. That sufficient? 👂

**Comment by r-tock** [comment]
haha! yes! that is good. A minor release would be great!

**Comment by dcodeIO** [comment]
On npm as 6.5.3!
