### ISSUE TITLE
Improve mobile browser performance

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#653]
protobuf.js version: 6.5.3

Currently on mobile browsers, the performance lags significantly. Opening an issue to aid investigation

Here are live sites using this library. You can use these sites to profile. Heritage loads in 1.1s on MacBook pro while it takes several seconds to load on my Nexus 6

https://theheritage.tocktix.com
https://theaviary.tocktix.com
https://next.tocktix.com
https://alinea.tocktix.com

**Comment by dcodeIO** [comment]
For reference: 5-6 seconds on a OnePlus One on first load, about 2 second on subsequent loads.

**Comment by r-tock** [comment]
Yes.

**Comment by r-tock** [comment]
There is also server latency of the calendar call, you will have to ignore the rare uncached hits there.

**Comment by dcodeIO** [comment]
One thing that comes to my mind is that the used definitions' code is generated on the fly, once. This might or might not result in an initial performance hit that could be less heavy with static code.

**Comment by dcodeIO** [comment]
A bit of profiling (red marks calls most likely protobuf.js related):

![](http://i.imgur.com/7UockZd.jpg)

**Comment by r-tock** [comment]
Our static definitions are 3.2mb uncompressed m that will add a huge
performance hit on asset size.

**Comment by dcodeIO** [comment]
Yup, the timeline view reveals that `bundle.js`, which seems to be a file of 2.17mb minified js (~344kb gzipped), takes super long to parse.

The red frame shows raw network download time (for my connection) and where bundle.js is parsed in red. The blue frame marks where I'd expect protobuf.js to actually execute:

![](http://i.imgur.com/iAFtfGU.jpg)

**Comment by r-tock** [comment]
You know what would be great? To compute transitive closure of the protos we use during build process based on import statements. Thus pruning away excess proto fat. Then static bundle maybe useful. Protobufs were a server side thing so no one really cares about pruning code size. This is a web perf motivated optimization.

Maybe too much effort for not enough benefit

**Comment by r-tock** [comment]
Yes it loads and does a resolveAll

**Comment by dcodeIO** [comment]
> You know what would be great? To compute transitive closure of the protos we use during build process based on import statements. Thus pruning away excess proto fat.

Maybe some mechanism to determine which reflection objects have actually been used. Not exactly sure if that should be in core, but it could certainly be patched into the prototypes of reflection objects or maybe into generated (en/de)code.

**Comment by dcodeIO** [comment]
Now we have a starting point, at least.

**Comment by r-tock** [comment]
Will check. I was doing some basic measurements. using performance.now(), confirms what you saw

On nexus 6 chrome 55 for one of the sites.
The Root.fromJSON takes 900ms and 200ms for resolveAll().

On nexus 6 chrome 56 beta
The Root.fromJSON takes 660ms and 166ms for resolveAll().

Secondly decode of the calendar data takes ~250-300ms on either
toObject of proto to json takes ~20ms on either.

**Comment by dcodeIO** [comment]
One thing that comes to my mind is that the required call to `resolveAll()` to populate additional properties for runtime compatibility could be relieved by moving this to add/remove, effectively resulting in a situation where only actually used reflection objects have to be resolved.

Do you know how much of the durations above are from `resolveAll()` alone?

**Comment by r-tock** [comment]
200 and 166ms

**Comment by dcodeIO** [comment]
Hmm, ok, would improve it by a bit maybe, but not by much. Todo: Benchmark on reflection stuff.

**Comment by dcodeIO** [comment]
With this now in place, it should also be possible to use `ReflectionObject#resolved` as an indicator.

**Comment by r-tock** [comment]
Update: Our dependency graph is so huge that the result of pruning would not yield more than 5% of data shaving.

Few more interesting things I discovered.

I ran the protobuf benchmark https://jsperf.com/protobufjs-robin
on Safari 10.0.2 and Safari Technical Preview 21 and Chrome 55.

Note this only performs the encode, decode tests.

On Safari 10.0.2 the encoding is ~427K/s and decoding is 681K/s
Page load (median of 10 runs) is ~800ms

On Safari 10.2.0 (Technical preview 21) the encoding is ~173K/s and decoding is 251K/s
Page load (median of 10 runs) is ~550ms (2x better than chrome)

On Chrome 55 the encoding is ~620K/s and decoding is 782K/s
Page load (median of 10 runs) is ~1000ms

Even though Chrome was better are raw encoding decoding tests, I have a few hypothesis, let me know if any of these sound plausible.

1) I suspect the new improvements in GC in Safari is helping page load quite a lot in general https://webkit.org/blog/7122/introducing-riptide-webkits-retreating-wavefront-concurrent-garbage-collector/

2) GC is probably reducing the Root.fromJSON() performance for such large bundle as ours

3) Safari may just be switching from interpreter to JIT compiled mode much more quickly and may be aggressively caching them. Chrome interpreter might be running protobufjs slowly while in crankshaft mode Chrome blows Safari out of the water.

4) Safari may in general be better at network http performance on a mac.

5) Benchmarks may need more work, maybe run then on node with crankshaft disabled and capture the performance with larger protobuf bundle, maybe useful to write a protobuf generator which fills fields with random data, that way we can point to any proto bundle and let the benchmark use those protos.

6) Maybe figure out a better test setup for node on Arm. 

 JS Performance is hard.

**Comment by dcodeIO** [comment]
This performance pass includes quite a lot of micro-optimizations like inlining Array#forEach and similar, using cached vars instead of getters where possible, and so on. Slightly reduces the number of total ticks in a simple test case.

**Comment by r-tock** [comment]
that gave a small boost for Chrome (~5%) and big boost in performance for safari technical preview 21  encoding  ~554K/s and decoding is 683K/s

**Comment by dcodeIO** [comment]
Interesting that this affected encoding/decoding speed at all as there haven't been any changes to generated code. Was meant for parsing / setup speed.

One more thing that could be done is disabling any assertions when loading pre-asserted modules through `.fromJSON`, but I haven't looked through the potential of such an optimization yet.

Do you have updated timings on page load speed (especially regarding "Evaluate Script (bunde.js:1)" above)?

**Comment by r-tock** [comment]
I dont have it yet. Locally whatever measurements I make will not like production with production data and I need a protobufjs release to take it all the way till production :|

**Comment by dcodeIO** [comment]
Hmm, there are still some possible tweaks to investigate. Could really need a rather large real world JSON definition for local profiling.

**Comment by r-tock** [comment]
@dcodeIO I can send you our large definition via email if you are willing to sign an NDA? and that you never push it any public repo.

**Comment by r-tock** [comment]
Actually I realized that is kind of stupid thing, our bundles are in JS anyways. Let me send over the protos

**Comment by dcodeIO** [comment]
So, are you using static code in your bundles / not a JSON module?

**Comment by r-tock** [comment]
we are using a JSON file, importing that then calling resolveAll() before re-exporting.

**Comment by dcodeIO** [comment]
I see, then I am still optimizing at the right spots. Currently using tests/test.proto for fromJSON profiling, that's already a lot better than bench.proto.

**Comment by r-tock** [comment]
```
import { Root } from 'protobufjs';
const root = Root.fromJSON(require('core/dist/core.json'));

const protos = {
  ...root.resolveAll().lookup('tocktix.messages')
};

module.exports = protos;
```

@dcodeIO If we can somehow find a middle ground between fully expanded static classes (which is too big 5MB for these files) and a file containing a bunch of exports for each type that is resolved on import. Webpack is smart enough to resolve them based on demand. Just throwing it out there.

**Comment by dcodeIO** [comment]
> If we can somehow find a middle ground between fully expanded static classes (which is too big 5MB for these files) and a file containing a bunch of exports for each type that is resolved on import. Webpack is smart enough to resolve them based on demand. Just throwing it out there.

Hmm, ideally there'd be a way to split messages, services, enums etc. over multiple files to make this possible. As a starting point, the last commit introduces that the root name specified through pbjs's `--root` parameter is reused, so that multiple files can define their types on the same shared root instance more easily.

**Comment by dcodeIO** [comment]
With this now in place it still looks like a lot of work to implement proper splitting. A good approach could be to build some sort of abstract bundler for the CLI that takes operations to perform like defining sub-namespaces, setting options, adding (sub-)types and importing types where required - and then reuse that, cutting through the operations, to generate actual JSON and static modules.

**Comment by r-tock** [comment]
@dcodeIO can you cut a release. I will try upgrading and report back improvements

**Comment by r-tock** [comment]
On nexus 6 chrome 56 beta
The Root.fromJSON takes ~550ms and resolveAll() takes ~120ms But there is huge variance specially when measuring with remote debugging.

**Comment by dcodeIO** [comment]
Just finished the last minor improvements, on npm now as 6.6.0.

**Comment by r-tock** [comment]
Latest optimized build with latest release of protobufjs

On nexus 6 chrome 56 beta
The Root.fromJSON takes ~318ms and resolveAll() takes ~87ms. And it's much more consistent in performance.

Btw, on a iPhone 7 (tested today on a friends phone), the load time is ridiculously fast, almost blink speed I guess its all due to hardware. I will try to get more scientific measurements tomorrow.

**Comment by r-tock** [comment]
These will be live tomorrow, I will update the thread when the release happens.

**Comment by r-tock** [comment]
New release is live. The same links will now be serving the latest protobufjs library

**Comment by dcodeIO** [comment]
Timeline alone looks pretty much identical to before, hmm.

**Comment by dcodeIO** [comment]
Maybe of interest: pbjs now has an experimental `--sparse` option that excludes anything not directly or indirectly referenced from within the main .proto files (those directly specified on the command line).

**Comment by r-tock** [comment]
Update:
There is a way to do CPU throttling in the timeline view to replicate low powered smart phones. It looks like the majority time is not fromJSON when I do that.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently (and seems to be solved). Feel free to reopen it if necessary!
