### ISSUE TITLE
Make a stable mid-to-long term version.

### ISSUE THREAD

**Issue by madroneropaulo** [dcodeIO/protobuf.js#659]
So, I know this is open source and we all really appreciate the big effort put on this package, but it would be handy to define a stable version. Some kind of "Long Term Support" version, whose API can be used and patches updated without the fear of breaking all the code that depends on it. Any project that relies on this package automatically becomes hard to maintain, because some nice-to-have fixes are made alongside with API changes on later versions, so if the project is using v6.0.0 and needs some fix made on a later version, it becomes mandatory to update API and refactor stuff that in most cases work "just fine".

**Comment by dcodeIO** [comment]
You are right, ideally there'd be some sort of long term support. I can't provide it, unfortunately.

For what it's worth, there is a [changelog](https://github.com/dcodeIO/protobuf.js/blob/master/CHANGELOG.md) file for v6.

Additionally, as of today, most of breaking API changes should be completed. I use to do this early where necessary to reach a stable API asap. In the near future, the library will go to maintenance mode again for a longer period - at least that's how it usually goes.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
