### ISSUE TITLE
Issue after migrationg to pbjs 6.0.2

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#662]
Old reference - https://github.com/dcodeIO/protobuf.js/issues/533

We migrated from 5.0.1 to 6.0.2 and we are having issue loading grpc objects.
(we are using the latest version 1.1.0-pre1 of grpc).

Below is the source code and I get an error when loading grpc objects.
(The builder object does not contain 'ns').

```
grpc.loadObject(this.$builder.ns):

TypeError: Cannot read property 'className' of undefined
at Object.loadObject (node_modules/grpc/src/node/index.js:65:12)
```

Our build protobuf function:
```
function buildProtobuf(files, root, logger) {
  const builder = new ProtoBuf.Root();
  _.forEach(files, (fileName, key) => {
    const ok = builder.files[fileName];
    if (ok) {
      return;
    }
    const file = fs.readFileSync(root + fileName, 'utf8');
    ProtoBuf.load(file, builder, {
      file: fileName,
      root
    });
  });
  return builder;
}
```

loading grpc object and creating service:

```
this.$builder = buildProtobuf(protos, protoRoot, logger);
this.$proto = grpc.loadObject(this.$builder.ns);
this.$service = _.get(this.$proto, this.$config.service);
```

**Comment by dcodeIO** [comment]
6.0.2 is quite old-ish already. Also, in v6, there is no builder anymore. And no ´ns`.

**Comment by Arun-KumarH** [comment]
Its just the variable name is builder (instead of root) I am using ProtoBuf.Root() as in above code snippet and not ProtoBuf.newBuilder() function. 
Tried using 6.6.1v and its the same.
If there is no 'ns' should we just provide the root object ?
We get "Error: ENOENT: no such file or directory" when we just provide the builder/root object.

**Comment by dcodeIO** [comment]
```js
    const file = fs.readFileSync(root + fileName, 'utf8');
    ProtoBuf.load(file, builder, {
      file: fileName,
      root
    });
```
Hmm, you are loading the file's source there. The correct way to do this would be:
```js
    ProtoBuf.load(root + fileName, builder, function(err, root) {
       // callback is called once loaded
    });
```
Or, you could use the parser directly when loading the source is actually what you want:
```js
    const file = fs.readFileSync(root + fileName, 'utf8');
    ProtoBuf.parse.filename = fileName;
    ProtoBuf.parse(file, builder);
    // builder now has the definitions
```

**Comment by Arun-KumarH** [comment]
I have below type script code for encoding the protobuf message dynamically.

The 'MessageClass' below is of type 'any' and it does not show auto code completion in VS code editor.

I have included the type definition file for the test.proto file generated using pbts from cli.
Also after decoding the messge its type is 'any' and does not show auto completion when trying to get the original contents back.

Could you please let me know what am I missing below so that auto completion works for type script?

```
/// <reference path="../../../../definitions/test.d.ts" />

....
  /**
   * Encode the given message object using protobufjs (pbjs).
   *
   * @param  {string} eventName
   * @param  {Object} msg
   * @param  {string} protoFilePath
   * @param  {string} messageObject
   * @return {Object} buffer
   */
  * encodeObject(eventName: string, msg: Object, protoFilePath: string,
      messageObject: string): any {
    const protoRoot = yield protobuf.load(protoFilePath).then((root) => {
      return root;
    }).catch((err) => {
      this.logger.error('error creating protoRoot for pbjs');
      throw err;
    });
    const root = protoRoot;
    const MessageClass = root.lookupType(messageObject);

    const convertedMessage = MessageClass.create(msg);

    const buffer = MessageClass.encode(convertedMessage).finish();
    return buffer;
  }
```
