### ISSUE TITLE
Guarantee that BufferReader#buf is a Buffer

### ISSUE THREAD

**Issue by seishun** [dcodeIO/protobuf.js#668]
I'm in the process of updating my encoder/decoder generator to match the API of protobuf.js 6.x (currently it mimics protobuf.js 4.x, you can see it [here](https://github.com/seishun/node-steam-resources/blob/1403939a12ba467a4b82c8ccbc279bbcdad43588/README.md#structs)). The generated `decode` methods will take an object with properties `buf` and `pos`. `buf` will have to be a Buffer since the decoder will take advantage of Buffer's methods.

I also want to be able to pass the same data type to both my own `decode` and protobuf.js's `decode`. The latter accepts BufferReader, but the documentation for BufferReader says its `buf` is a Uint8Array, not Buffer, so it would be technically incompatible with my `decode`. But it's clear from the source code that it's actually a Buffer.

Can you update the documentation to state that BufferReader#buf is a Buffer and not just Uint8Array?

**Comment by dcodeIO** [comment]
The `Uint8Array` reference is used to simplify TypeScript usage (no need to have @types/node respectively making it unnecessary to override every single reader/writer function that is inherited from the Uint8Array reader/writer), which is based on modern node version's `Buffer` inheriting from `UintArray` anyway.

Would it be enough if documentation would cover this textually, without changing the actual type to `Buffer`?

**Comment by seishun** [comment]
I'm not sure how that would look like, but sure, as long as the documentation makes it clear that it's a Buffer I'd be okay with that.

Could you clarify why overriding all the functions would be necessary though?

**Comment by dcodeIO** [comment]
> Could you clarify why overriding all the functions would be necessary though?

Sorry, not all functions, just the ones referencing `Uint8Array`. Because documentation.

**Comment by seishun** [comment]
So just `bytes()`?

**Comment by dcodeIO** [comment]
That and `#buf` for `BufferReader`.

`#bytes`, `#finish` and `#buf` for `BufferWriter` - and maybe all the `Op` stuff.

**Comment by seishun** [comment]
Seems reasonable to me, although I'm not sure what you mean by `Op` stuff.

I think it would be particularly useful to note that BufferWriter#finish returns a Buffer since that seems to be its primary difference from Writer.

Also BufferWriter#bytes doesn't need any doc change since it does actually accept Uint8Array, not only Buffer.

**Comment by dcodeIO** [comment]
Updated, let me know if that solves your issue!

**Comment by seishun** [comment]
Yes, thanks for the quick response!
