### ISSUE TITLE
Issue decoding after migrating from 4.x to 6.6.3

### ISSUE THREAD

**Issue by johnnyreilly** [dcodeIO/protobuf.js#670]
protobuf.js version: `6.6.3`

Hey it's me again 😉 

I've just attempted an upgrade from v4 to v6.  With v4 I was generating js files like so:

```
pbjs ./proto/bcl.proto ./proto/MonitoringClientMessage.proto ./proto/MonitoringServerMessage.proto --target commonjs > ./proto/proto.js
```

With v6 I'm doing it like so: (I've also attempted with commonjs as well)

```
pbjs --target static-module --wrap es6 --out ./proto/proto6.js ./proto/bcl.proto ./proto/MonitoringClientMessage.proto ./proto/MonitoringServerMessage.proto
pbts --out ./proto/proto6.d.ts ./proto/proto6.js'
```

However, decoding always fails for me.  Specifically, when I debug `Reader.prototype.uint32` always produces 0:

```js
/**
 * Reads a varint as an unsigned 32 bit value.
 * @function
 * @returns {number} Value read
 */
Reader.prototype.uint32 = (function read_uint32_setup() {
    var value = 4294967295; // optimizer type-hint, tends to deopt otherwise (?!)
    return function read_uint32() {
        value = (         this.buf[this.pos] & 127       ) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) <<  7) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) << 14) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) << 21) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] &  15) << 28) >>> 0; if (this.buf[this.pos++] < 128) return value;

        /* istanbul ignore next */
        if ((this.pos += 5) > this.len) {
            this.pos = this.len;
            throw indexOutOfRange(this, 10);
        }
        return value;
    };
})();
```

It's rather strange and so I wanted to report in case I'm doing anything dozy... If there's any ideas I'd greatly appreciate them!

**Comment by dcodeIO** [comment]
Do you have an example buffer at hand?

**Comment by johnnyreilly** [comment]
Yup - I'll share one shortly
________________________________

**Comment by johnnyreilly** [comment]
Actually there's nothing that I'm allowed to share.... Frustrating.  I'll see if I can get a repro with one of the examples and share that.

**Comment by dcodeIO** [comment]
There is also a little howto on [how to reverse engineer a buffer by hand](https://github.com/dcodeIO/protobuf.js/wiki/How-to-reverse-engineer-a-buffer-by-hand) in order to spot the underlying issue.

**Comment by johnnyreilly** [comment]
Thanks I'll take a look!

**Comment by johnnyreilly** [comment]
I'm not at a keyboard and so can't test but I just noticed the presence of a `--keep-case` option. I'm relying on the original (not camel) case for my app and I haven't used it in my new generation. Is that something worth checking out? I can't see it listed in breaking changes since v4 so perhaps not?

**Comment by dcodeIO** [comment]
ParseOptions, goes there: https://github.com/dcodeIO/protobuf.js/blob/master/src/root.js#L70

**Comment by johnnyreilly** [comment]
So worth trying? Has the camelCase thing only be around since v6 then?

**Comment by dcodeIO** [comment]
v5 had an option. v6 uses camel case by default, which can still be overridden with `{ keepCase: true }`.

**Comment by johnnyreilly** [comment]
And `--keep-case` if using `pbjs` presumably? Great I'll give it a try in the morning. Thanks!

**Comment by johnnyreilly** [comment]
Nope `--keep-case` wasn't the issue

**Comment by johnnyreilly** [comment]
OK - it seems likely that the problem lies with `ArrayBuffer`.  My project is using `ArrayBuffer` from the babel polyfill - and it seems there might be some issues with that:

https://github.com/babel/babel/issues/5140

Namely I can't actually read from the `ArrayBuffer` and it doesn't have the API you would expect.  (It lacks  a `length` property for instance)

**Comment by dcodeIO** [comment]
Yeah, using Uint8Array in the browser / Buffer under node.js is correct. ArrayBuffer alone does not provide slices, indexed access etc. across modern to ancient environments.

**Comment by johnnyreilly** [comment]
Thanks for the clarification - I'd missed that

**Comment by johnnyreilly** [comment]
Is it worth mentioning somewhere in the docs that users might need this approach if they are consuming `ArrayBuffer`s?

**Comment by dcodeIO** [comment]
The API documentation always refers to `Uint8Array` respectively `Buffer`. It's not mentioned in the README, though, hmm.

**Comment by johnnyreilly** [comment]
I was actually more thinking about the `decode` side of things; a user may be handed an `ArrayBuffer` via a websocket without realising that they need to `Uint8Array`-ify things before they can decode.

**Comment by dcodeIO** [comment]
Yeah, added that to the first example in README.

**Comment by johnnyreilly** [comment]
Oh I saw - my point was more that people may not realise that they have an `ArrayBuffer` on their hands that they need to transform.  I didn't and I'd say it's not obvious..

**Comment by johnnyreilly** [comment]
Actually it's covered here: https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F 

I wonder if this section merits promotion to the readme? Or a link off to it perhaps?

**Comment by johnnyreilly** [comment]
Closing as all my issues are resolved; thanks for your help @dcodeIO!
