### ISSUE TITLE
Incorrect plain object encoding with oneof

### ISSUE THREAD

**Issue by ilyaluk** [dcodeIO/protobuf.js#672]
protobuf.js version: 6.6.3

Plain object is not encoded correctly. But explicitly setting property works.

```
syntax = "proto3";
package test;

message Test {
    oneof TestOneOf {
        string msg = 1;
    }
}
```

```js
 protobuf.load('/test.proto', function(err, root) {
   var test = root.lookup('test.Test');
   console.log(test.encode({msg:'123'}).finish()); // []
   var tmp = test.create();
   tmp.msg = '123';
   console.log(test.encode(tmp).finish()); // [10, 3, 49, 50, 51]
 });
```

**Comment by dcodeIO** [comment]
It makes a difference whether you are encoding a plain object or a runtime message. When encoding plain objects, it's necessary to set the virtual oneof field's property to the set field's name manually, like so:

```js
 console.log(test.encode({msg:'123', TestOneOf: 'msg'}).finish());
```

This is because plain objects do not have any virtual properties on their own.

**Comment by ilyaluk** [comment]
Thanks for explanation.
