### ISSUE TITLE
Please add a config variable to turn on and off "packed" mode for protocol buffer fields

### ISSUE THREAD

**Issue by serkangunes** [dcodeIO/protobuf.js#673]
protobuf.js version: 6.6.3

Please add a config variable to turn on and off "packed" mode for protocol buffer fields.

Every single proto field is considered as packed if [packed=false] option is not present in .proto file

**Comment by dcodeIO** [comment]
Have you tried setting the syntax to proto2 explicitly?

```proto
syntax = "proto2";

message Foo {
   repeated uint32 bar = 1;
}
```

**Comment by serkangunes** [comment]
Proto files are shared between projects so we can't change them. I thought ProtoBuf version 3 has packed=false by default for backward compatibility.

**Comment by dcodeIO** [comment]
From [Language Guide (proto3) / Specifying Field Rules](https://developers.google.com/protocol-buffers/docs/proto3#specifying-field-rules)

> In proto3, repeated fields of scalar numeric types use packed encoding by default.

**Comment by serkangunes** [comment]
Oh my bad. I have solved this by generating single proto file using pbjs proto2 option which automatically added the syntax line at the top. Closing it.

**Comment by serkangunes** [comment]
Even with the syntax = "proto2" it still packs the repeated enum fields.

`syntax = "proto2";

package test;

import "TestMessageFlag.proto";

option java_outer_classname = "TestMessageProto";

message TestMessage {
  repeated test.TestMessageFlag flags = 1;
}
`
`syntax = "proto2";

package test;

enum TestMessageFlag {
  FLAG_1 = 1;
  FLAG_2 = 2;
  FLAG_3 = 3;
  FLAG_4 = 4;
  FLAG_5 = 5;
} 
`
`var protobuf = require("protobufjs");

var proto = require('./TestProtoModule');

protobuf.load("proto/TestMessage.proto", function(err, root) {
    if (err) throw err;

    protobuf.load("proto/TestMessageFlag.proto", function(err2, root2) {
      if (err2) throw err2;

      var TestMessageFlag = root2.lookup("test.TestMessageFlag");
      var TestMessage = root.lookup("test.TestMessage");

      // Create a new message
      var message = TestMessage.create({ flags: [
        TestMessageFlag.values.FLAG_4,
        TestMessageFlag.values.FLAG_2,
        TestMessageFlag.values.FLAG_3,
        TestMessageFlag.values.FLAG_1
      ] });

      // Encode a message
      var buffer = TestMessage.encode(message).finish();
      console.log(buffer)
    });
});`

Run the code and it outputs: "<Buffer 0a 04 04 02 03 01>"

Now change the field to be unpacked with an option.

`
syntax = "proto2";

package test;

import "TestMessageFlag.proto";

option java_outer_classname = "TestMessageProto";

message TestMessage {
  repeated test.TestMessageFlag flags = 1 [packed = false];
}
`

Now run the same code and it outputs: <Buffer 08 04 08 02 08 03 08 01>
Which is the correct value for unpacked repeated field.

syntax = "proto2" should by default use unpacked without the need for options.
