### ISSUE TITLE
Nested Messages change (and invalidate) JSON structure by adding message labels as keys

### ISSUE THREAD

**Issue by trakout** [dcodeIO/protobuf.js#674]
protobuf.js version: 6.6.3

Very new to Protobuf here, so I'm not sure if this is somehow intentional behaviour or a bug.
Basically I am attempting to encode nested JSON, with one key containing an array of objects, and the other key containing another more simple object.

The proto file works as expected, with one caveat -- the message name in the .proto file gets encoded along with the data. For example:

Data before encode:
```js
{ paginationTokens: 
   { query: 'test',
     youtubePageToken: 'CBQQAA',
     vimeoPageToken: '/videos?page=2&per_page=20&query=test&sort=relevant',
     dailymotionPageToken: '2',
     twitchPageToken: 'https://api.twitch.tv/kraken/search/streams?limit=20&offset=20&q=test' 
   },
  items: 
   [ { id: '99bVMixpCJg',
       uniqHash: '99bVMixpCJg',
       source: 'youtube',
       title: 'title',
       description: 'description Test',
       thumbnail: 'test.jpg' } 
   ] 
}
```

Data after encode/decode:
```js
{ paginationTokens: 
   Pagination: { query: 'test',
     youtubePageToken: 'CBQQAA',
     vimeoPageToken: '/videos?page=2&per_page=20&query=test&sort=relevant',
     dailymotionPageToken: '2',
     twitchPageToken: 'https://api.twitch.tv/kraken/search/streams?limit=20&offset=20&q=test' 
   },
  items: 
   [ Item: { id: '99bVMixpCJg',
       uniqHash: '99bVMixpCJg',
       source: 'youtube',
       title: 'title',
       description: 'description Test',
       thumbnail: 'test.jpg' } 
   ] 
}
```

Note the additions of the Pagination & Item 'keys'. 

Here's the .proto file:
```js
message SearchresMessage {
  message Item {
    string id = 1;
    string uniqHash = 2;
    string source = 3;
    string title = 4;
    string description = 5;
    string thumbnail = 6;
    optional string sprite = 7;
  }
  message Pagination {
    string query = 1;
    string youtubePageToken = 2;
    string vimeoPageToken = 3;
    string dailymotionPageToken = 4;
    string twitchPageToken = 5;
  }
  Item items = 1;
  Pagination paginationTokens = 2;
}
```

**Comment by dcodeIO** [comment]
When `items` is an array, it should probably be marked repeated:

```proto
  repeated Item items = 1;
```

Besides that the .proto file looks ok to me and it's hard to tell where the additional keys come from. I'd even say that this is impossible to produce with protobuf.js based on your .proto file - can you provide a snippet of your JS code?

**Comment by trakout** [comment]
@dcodeIO oops, correct -- I am in fact using repeated for that field (thanks!).

My code is as follows:

```js
protobuf.load('./proto/search.proto', function(err, root) {
  if (err) throw err;

  var testMessage = root.lookup('searchpackage.SearchresMessage');
  var created = testMessage.create(message); // message == unencoded JSON
  var encoded = testMessage.encode(created).finish();

  var decoded = testMessage.decode(encoded);
  console.log(decoded)
});
```

**Comment by dcodeIO** [comment]
`console.log(decoded)` doesn't actually output JSON and I assume that's where the presumed keys come from. For example, it prepends the class name to structures.

Try this:

```js
console.log(JSON.stringify(decoded, null, 2))
```

Note that there is also `testMessage.toObject(conversionOptions)` if you'd like to have a plain JSON object first, with conversion options providing support to convert enums, longs etc. and similar to other data types than what is used internally, i.e. strings.

**Comment by trakout** [comment]
@dcodeIO .stringify() is the answer, thanks very much! Closing this ticket.
