### ISSUE TITLE
Question: use CLI to generate static js files 

### ISSUE THREAD

**Issue by satrughan** [dcodeIO/protobuf.js#675]
Hi I have a folder containing a large number of .proto files that I want to use to generate the static JS files. Anyway I can use the CLI to do this?

**Comment by schwiet** [comment]
This is what pbjs is for; look at the documentation on the readme page: https://github.com/dcodeIO/protobuf.js#command-line

**Comment by satrughan** [comment]
Hi Schwiet, thanks for replying.  

Sorry my bad, I wasn't clear with my question.

Given that we have the pbjs cli to generate the static files via the command line, does the CLI have commands that support:

- Generating the static files if i provide a folder and say I want to compile every file in there.
- For each input I would like an output with a similar name, like how google's js protobuf compiler has a `one_output_file_per_input_file` option. e.g. message.proto ---> message.pb.js.

For both of the above, to make it work, I am currently looping through all the files in there and running the commands individually per proto file. I wanted to know if there was a cleaner way to do it through the CLI commands.

**Comment by dcodeIO** [comment]
It is not yet possible to produce multiple output files (still TODO) - pbjs is always emitting one large file. What you can do already is using a glob expression on the command line to bundle multiple files to a single output file, though.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary - or, better, to create a new one with a feature request for multiple file output.

**Comment by accedo-robcc** [comment]
Hi @dcodeIO. I'm unclear on how can I provide a glob expression to pbjs. Could you provide an example of this? My goal is to tell the CLI to bundle all .proto files in a folder and generate a single bundle file.
