### ISSUE TITLE
Reader modify the pos when throw indexOutofRange() exception in uint32()

### ISSUE THREAD

**Issue by dreamershl** [dcodeIO/protobuf.js#680]
protobuf.js version: 6.6.3

Reader will throw the indexOutOfRange() exception if the underlying buffer doesn't have enough bytes for the reading. But the function uint32() will modify the "this.pos" first before throwing the exception while others will just keep the current value. Ideally the current properties should be kept when throw the exception, so the caller function will be able to resume the operation after adjust the buffer. 

```js
Reader.prototype.uint32 = (function read_uint32_setup() {
...
 /* istanbul ignore next */
        if ((this.pos += 5) > this.len) {
            this.pos = this.len;
            throw indexOutOfRange(this, 10);
        }
        return value;
...
```

```js
Reader.prototype.fixed32 = function read_fixed32() {

    /* istanbul ignore next */
    if (this.pos + 4 > this.len)
        throw indexOutOfRange(this, 4);

    return readFixed32(this.buf, this.pos += 4);
};
```

**Comment by dcodeIO** [comment]
This is done to prevent the additional operation / temp var. Shouldn't be much of an issue because a corrupted buffer remains a corrupted buffer - but you can of course remember `pos` yourself.
