### ISSUE TITLE
path.normalize cannot handle paths with more than two ".."

### ISSUE THREAD

**Issue by linluxiang** [dcodeIO/protobuf.js#688]
protobuf.js version: latest

<please describe the expected and actual behavior>
The function path.normalize will remove all "../..". When it meets a path like "../../folder", it will return "folder". This behavior is totally incorrect.

Here is the the source code where it removes the double "..". [https://github.com/dcodeIO/protobuf.js/blob/master/lib/path/index.js#L35](url)
```js
        if (parts[i] === "..") {
            if (i > 0)
                parts.splice(--i, 2);
            else if (absolute)
                parts.splice(i, 1);
            else
                ++i
```

```js
<please provide a code snippet for reproduction>
pbjs ../../folder.proto
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
This should be fixed within v6.6.4. Feel free to reopen if there are still any issues!
