### ISSUE TITLE
`toObject` with large long type is returning a wrong value

### ISSUE THREAD

**Issue by yoni-tock** [dcodeIO/protobuf.js#690]
protobuf.js version: 6.6.3

Calling `.toObject` with the `Number` option for `longs` is returning a value that's incorrect, at least for very large `Longs` (in our case, an epoch). Strangely, the result is different than calling `toNumber` on the specific field. Calling `proto.toObject({ longs: Number })` is resulting in a different value than `proto.longValue.toNumber()`.

The relevant shape of the object is:

```js
const proto = {
  innerProto: {
    timestampMs: {
      low: -2114947712,
      high: 346,
      unsigned: true,
    },
  },
};

// Calling toObject we get the following
const converted = proto.toObject({ longs: Number });
console.log(converted.innerProto.timestampMs); // 1483943736704
// vesus...
console.log(proto.innerProto.timestampMs.toNumber()); // 1488238704000
```

**Comment by r-tock** [comment]
@dcodeIO Please prioritize this, we have a customer escalation due to this.

**Comment by dcodeIO** [comment]
Please let me know if this solves your issue!

**Comment by r-tock** [comment]
@dcodeIO Yes could you also push a new minor release. Thanks again for the fast fix.

**Comment by yoni-tock** [comment]
@dcodeIO Thanks so much! This resolved the issue we were seeing.

**Comment by dcodeIO** [comment]
Now on npm!

**Comment by raojs** [comment]
Repair very timely, very grateful.
