### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by emilioriosvz** [dcodeIO/protobuf.js#691]
protobuf.js version: 6.6.3

I'm trying to decrypt a message give to me from a router vía pubsub 0mq queue. 
The fabricant provide the schema.proto and with your library I'm available to load the schema correctly, but when I attempt to decrypt the message I got this: 

`index out of range: 90 + 10 > 90`

This is my snippet of code:

```js
protobuf.load(path.join(__dirname, 'schema.proto'), function(err, root) {
    if (err) throw err;
    var schema = root.lookup('ce.nbapi.presence'); // here I have the schema correctly
    console.log('Topic: ', topic.toString());
    
    console.log('Message:', message);
    try {
      // Decode an Uint8Array (browser) or Buffer (node) to a message
      var m = schema.decode(message);
      console.log(m);
    } catch (error) {
      console.log(error);
    }
}
```

I'm new to protobuffers, what that does mean??

**Comment by dcodeIO** [comment]
`index out of range: 90 + 10 > 90` means that the library tried to read 10 more bytes according to the protobuf wire format, but the buffer didn't contain these bytes (probably corrupted or a schema mismatch).

There is an example on how to reverse engineer a buffer: https://github.com/dcodeIO/protobuf.js/wiki/How-to-reverse-engineer-a-buffer-by-hand

**Comment by emilioriosvz** [comment]
I spend the morning on this and I think I'm close.
This is a string after decrypt: 

```{apName: '*\u0006\u0000\f)"�x�\u001f?\n\b\n\u0006�\u001fr���\u0010\u0000\u001a\u00147����L��\u000fYwDe������"\u0011f0:5c:19:cb:9f:ae*\b\n\u0006�\\\u00199��' }```

This should to be a MAC address, so I guess that this is a format problem.
There is a custom type in my `.proto` that is an object and if I have a format problem and because that fails when the library try to decrypt it.

Maybe I have to parse my `Uint8Array` before passing it to protobuf? 
Have you ever had a similar problem?

Thanks!!

**Comment by dcodeIO** [comment]
Looks like the buffer is interpreted differently than specified by the schema. There are a couple of possible reasons:
* The schema doesn't match the data
* The buffer has been corrupted somewhere on its way ([see also](https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F))
* The data has additional, custom, non-protobuf bytes in it

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by krforgit** [comment]
I am new to buffers,
I am trying to decode my message which I am getting from a console application
where I am sending message form the following C# Snippet
		foreach (ConnectionContext clientContext in clientContexts)
				{
					try
					{
                        var asyncResult = clientContext.ConnectionSocket.BeginSend(message, 0, message.Length, SocketFlags.None, null, null);
                        asyncResult.AsyncWaitHandle.WaitOne(10000);
                        if(!asyncResult.IsCompleted)
                        {
                            Console.WriteLine("Error writing data: ASyncResult not completed!");
                        }
					}
					catch (Exception e)
					{
						Console.WriteLine(String.Format("Error sending message to {0}: {1} Stack Trace: {2}", 
							clientID.ToString(), e.Message, e.StackTrace));
						success = false;
					}
				}
			}
			return success;



I am facing the index out of range exception
 index out of range: 90 + 10 > 90 
when I am subscribing that message through this JS snipppet
![capture](https://user-images.githubusercontent.com/31538061/29968059-ee081dfa-8ee7-11e7-92cc-17f8d55c8c26.PNG)
.
I do not understand why the exception thrown is there any one which same situation and succceded

**Comment by adhil-bit** [comment]
Response message parsing error: index out of range: 3 + 10 > 3
getting error while passing a count as integer

**Comment by bookkilled** [comment]
axios调用和fetch调用的时候axios需要特殊处理下，fetch可以直接成功的，截图代码我做了区分：

<img width="958" height="638" alt="Image" src="https://github.com/user-attachments/assets/b9d8886e-5da1-4dfe-964f-7f23e8b86e47" />
