### ISSUE TITLE
sfixed64 are smaller by a factor of 2

### ISSUE THREAD

**Issue by tomergg** [dcodeIO/protobuf.js#692]
protobuf.js version: v6.6.4

When deserializing sfixed64 values, the `Long` object returned contains data that is smaller by a factor of 2.
I've compared v5.0.2 results with v6.6.4. 
* Identical base 64 input
* output of `Long` values is different by a factor of 2

v6.6.4
```js
const pbEntity = pbRoot.lookup(schema);
const buffer = Buffer.from(base64Data, 'base64');
const entity = pbEntity.decode(buffer).toObject({ bytes: String, enums: String, arrays: true });
```

v5.0.2
```js
const entity = protoBufBuilder.build(schema).decode(base64Data).toRaw(true);
```

When I removed the `zzDecode` call, I got correct results:
```js
function read_sfixed64_long() {
    return readFixed64.call(this).toLong();
}
```
instead of:
```js
function read_sfixed64_long() {
    return readFixed64.call(this).zzDecode().toLong();
}
```

I think that the implementation might need to be identical to `fixed64`.
If needed, I can write some code to repro the problem in isolation.

**Comment by tomergg** [comment]
Thank you for the quick fix.
If I may ask, when are you planning on releasing v6.6.5 to npm?

**Comment by dcodeIO** [comment]
Now on npm!

**Comment by tomergg** [comment]
@dcodeIO, thank you!
