### ISSUE TITLE
Protobuf with Angular 2.0 + asp.net core(webpack) and Typescript

### ISSUE THREAD

**Issue by seanishok01** [dcodeIO/protobuf.js#694]
protobuf.js version: "protobufjs": "^6.6.4",

i am new to protobufjs and planning to implement the protobufjs in Angular 2 project.
I have installed the protobufjs using the "npm install protobufjs --save" inside the Angular 2 project(VS2015).

i have the service below, which sends the request to WebAPI 2.0 service and get the response in protobuf format

getStudentNames(): Observable<Response> {
        var headers = new Headers();
        headers.append('Content-Type', 'application/x-protobuf');
        return this.http.get('/api/students', { headers });
    }
Get the sample response as below,
↵*Ram"(0↵&Gopal"

how to decode the response to below model object
//student.model.ts
export class Student
{
name:string;
rollno: number;
}
Please help me by providing some samples with descriptive steps for Get/POST/PUT/Delete request in Angular 2 and typescript.

Any help are really appreciated.

**Comment by dcodeIO** [comment]
Unfortunately, there hasn't been an answer to this question, yet. Maybe try posting it [on StackOverflow](http://stackoverflow.com/search?tab=newest&q=protobuf.js) instead.

**Comment by kundan36** [comment]
Hello,

I am facing same issue,
is there any solution with the given query.
please let me know
