### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by wesleytodd** [dcodeIO/protobuf.js#696]
As far as I can tell there are no docs on error handling for this package.  Are errors thrown when using `decode`/`encode`? Is there an emitter I can bind to?  Maybe I just missed them while looking around?

I would be happy to write up something for the readme, or wherever you prefer.  But I think as a noob with this package I would like guidance from the maintainers before I do :)

**Comment by dcodeIO** [comment]
`decode` throws if the buffer cannot be decoded. Starting with 6.7.0, it will also throw if the argument is not a valid buffer ([see](https://github.com/dcodeIO/protobuf.js/issues/695)).

`encode` does not verify messages on its own. it just tries to encode whatever is specified, which might, for entirely bogus data, result in a runtime error being thrown somewhere down the road.

for explicit verification of runtime messages, there is `verify` instead, which can be used where necessary. having separate methods for encoding and verification avoids performing possibly redundant assertions when encoding. for example, sometimes a developer already knows that a payload is valid, thus it would be unnecessary to verify it (again) implicitly.

Hope this helps!

**Comment by wesleytodd** [comment]
That does help, thanks!  Would you be opposed to me taking this explanation and adding it to the readme?  Or is there a better place to document this so others don't have to dig?

**Comment by dcodeIO** [comment]
I've now added respective documentation to the initial README example. Decoders now also throw if required fields are missing so that `verify` does not have to be called after `decode`, which it isn't meant for (would introduce new redundant assertions otherwise).

Related: https://github.com/dcodeIO/protobuf.js/issues/695

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
