### ISSUE TITLE
version: 3.8.2 - dependency of bytebuffer does not have correct case for AMD and commonJS

### ISSUE THREAD

**Issue by zeachco** [dcodeIO/protobuf.js#698]
protobuf.js version: 3.8.2

it should work on a file system that is case-sensitive. it fails with webpack since it consume both ADM and commonJS at the same time
```js

    /* CommonJS */ if (typeof require === 'function' && typeof module === 'object' && module && typeof exports === 'object' && exports)
        module['exports'] = init(require("bytebuffer"));
    /* AMD */ else if (typeof define === 'function' && define["amd"])
        define(["ByteBuffer"], init); // <-- this should be "bytebuffer"
    /* Global */ ...
```

**Comment by dcodeIO** [comment]
v3.8.2 is super outdated. Current latest is 6.6.5.

**Comment by zeachco** [comment]
Thanks for the information, I tried latest 4, 6 and 5.0.2 without success. I'll investigate why but so far, I get `Unrecognized source format: file.name.proto` when trying other versions.

I also suspect your Travis integration is broken on node 0.08 for reasons unrelated to my pr https://github.com/dcodeIO/protobuf.js/pull/699
I work with a much recent version of node so I could include in my PR a travis target for it as well.

Let me know if you think it's possible to introduce a 3.8.3 for example. otherwise i might end up using my fork instead.

**Comment by dcodeIO** [comment]
> Let me know if you think it's possible to introduce a 3.8.3 for example. otherwise i might end up using my fork instead.

Well, I'd recommend upgrading to 6.X for a lot of reasons, but if you can't do that, using your fork is probably the way to go. Unfortunately, I don't have the motivation to support 3.X. For what it's worth and iirc, the earlier versions until v5 have a largely common codebase, means that 5.0.2 should be the most up to date version of what you are using. v6, on the other hand, is a complete rewrite.

Btw.: I am pretty sure that v3 depends on a version of bytebuffer.js that still used the camelcased naming convertion (edit: looked this up, it uses [bytebuffer 3.5](https://github.com/dcodeIO/bytebuffer.js/tree/ByteBuffer3)). There is a chance that you are using a much newer version of bytebuffer.js, which isn't compatible with protobuf.js v3 at all, if you have naming issues.

**Comment by zeachco** [comment]
@dcodeIO about bytebuffer, you are right, there the `"Long"` dependencies that should resolve to `'long'` so far I fixed them locally, just wanted to update both libraries to make it official. For some reasons, I can't upgrade (the app is too large and scattered) so I'll just use an internal version, thanks for the heads up about other versions.

**Comment by dcodeIO** [comment]
The same goes for `Long`. I am pretty sure that v3 depends on a long.js version that still used upper case naming.

**Comment by dcodeIO** [comment]
Closing this issue for now. Feel free to reopen it if necessary!
