### ISSUE TITLE
How to produce error when required field is missing in given json? 

### ISSUE THREAD

**Issue by d21d3q** [dcodeIO/protobuf.js#702]
protobuf.js version: 6.6.5

`protobufjs` is automatically filling required fields with zeros/nulls.
I am implementing kind of grpc client over serial connection as node-red node, so that as input I am given some message to encode ant path. From path I can obtain method and message type, so that I would expect from `protobufjs` to be able to verify if given json message is valid - contains required fields. Previously I've been playing with [protobuf node](https://github.com/DynamicDevices/node-red-contrib-plugins/tree/master/protobuf) which was using some older version of `protobufjs` and it was producing errors if field was missing.  

Here is how I going from json given by user to buffer:
```js

var jsonMsgWithMissingFields = {/* some fields, but no required */ };

var ProtoBuf = require("protobufjs");
var root = ProtoBuf.loadSync('/path/to/proto/file');
if (root == null){ /* error - unable to load proto file  */ } 

var messageTemplate = root.lookup('nameOfMessage');
if (messageTemplate == null){ /* error - unable to find messager */ } 

var message = messageTemplate.create(jsonMsgWithMissingFields);
/* I would like to know here that required fields haven't been provided,
some error thrown. Instead ot that I am having required fields automatically
filled with zeros (or nulls) */
var verified = messageTemplate.verify(message);
if (verified != null){/* error */}

var buf = messageTemplate.encode(message).finish();
/*send buffer */
```

**Comment by dcodeIO** [comment]
What happens if you `verify` `jsonMsgWithMissingFields` explicitly instead of the created message?

**Comment by d21d3q** [comment]
Then it works as expected. 
I think that documentation could say more about those functions, or maybe there could be some official tutorial for beginners to make easier diving into protobufjs?

**Comment by dcodeIO** [comment]
Meanwhile, I've updated the documentation with specific usage instructions, so I am closing this issue for now. Feel free to reopen if necessary.
