### ISSUE TITLE
get message types from service definition

### ISSUE THREAD

**Issue by zzo** [dcodeIO/protobuf.js#708]
protobuf.js version: 5

Can I get the message type from the Service definition somehow?  I'm trying to dynamically respond to all rpcs and would like to get the types of the 'request' and 'response' message dynamically.

I DO have the built protobuf from:
const api = protobuf.build(namespace);

but now in the code that handles the rpc I would like to determine the message types of the request and response from the Service itself.

I print the Service definition in my rpc handler it looks like this:
```js
{ [Function: Service]
  AddScenario: [Function],
  RemoveScenario: [Function],
  RemoveAllScenarios: [Function],
  ResetState: [Function],
  GetCurrentState: [Function] }
```
I know the name of the rpc itself (say 'AddScenario') but from just this structure I need to know that the 'request' message type is 'AddScenarioRequest' and the response message type is 'AddScenarioResponse' (which are in the built protobuf).
I need to know these types so I can properly decode and encode the binary message appropriately.
Is there some way to query the rpc methods to get the names of their respective 'request' and 'response' objects?

thanks!!  and hope that made sense..

**Comment by dcodeIO** [comment]
For reference:
- [Runtime service you are working with](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/Builder/Service.js) (has a `.$type` property to obtain the reflected type)
- [Reflected service](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/Reflect/Service.js)
- [Reflected service method](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/Reflect/Service/RPCMethod.js)

```js
var method = MyService.$type.getChild("AddScenario");
// method.resolvedRequestType
// method.resolvedResponseType
```

**Comment by zzo** [comment]
spectacular perfect thanks!!!
