### ISSUE TITLE
Encoder-only code still contains writer import

### ISSUE THREAD

**Issue by joscha** [dcodeIO/protobuf.js#712]
protobuf.js version: 6.6.5

When using the CLI with these options:
```bash
pbjs \
    --target=static-module \
    --wrap commonjs \
    --no-create \
    --no-encode \
    --no-verify \
    --no-convert \
    --no-delimited \
    --out decoder.js \
    ./my.proto
```
I expect to end up with a file that only contains references to anything that is needed to decode messages, however the file ends up having an unused reference to `$protobuf.Writer`:
```js
// Common aliases
var $Reader = $protobuf.Reader, $Writer = $protobuf.Writer, $util = $protobuf.util;
```
I searched a bit in the code and could not actually find the place where it calculates the needed dependencies. If you point me in the right direction I am happy to contribute a fix.

**Comment by dcodeIO** [comment]
Should be fixed in master. Feel free to reopen if there are any remaining issues!

**Comment by joscha** [comment]
Thanks!
