### ISSUE TITLE
Blank line between message comments and message caused an offset in the property/element comments

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#713]
protobuf.js version: <6.6.5>

I had gotten used to using the generated jsdocs for my protobuf objects, and then came across an generation error that I just couldn't see the forest through the trees for a long time. The comment on a particular attribute, which alphabetically was the first attribute in the object documentation, had the default comment, when I was pretty sure the source .proto file had a /// comment. Long story short, it turned out that the message /** ... */ comment had a blank line after it, and what that did was offset all the attribute comments by 1 as show in this simple example.

```proto
syntax = "proto3";

package issue;

/**
 * Message Comment
 */

message SomeMessage {
    string field1 = 1; /// This is Field 1
   string field2 = 2; /// This is Field 2

   string cField1 = 3; /// Should be the second field
   string alphabeticallyFirstField = 4; /// Comment for alphabeticallyFirstField 
}
```

```generated
        /**
         * SomeMessage field1.
         * @type {string}
         */
        SomeMessage.prototype.field1 = "";

        /**
         * This is Field 1
         * @type {string}
         */
        SomeMessage.prototype.field2 = "";

        /**
         * SomeMessage cField1.
         * @type {string}
         */
        SomeMessage.prototype.cField1 = "";

        /**
         * Should be the second field
         * @type {string}
         */
        SomeMessage.prototype.alphabeticallyFirstField = "";

```

```
<please paste the stack trace of the error if applicable>
```

Cheers

**Comment by dcodeIO** [comment]
Should be fixed in master. Feel free to reopen if there are any remaining issues!

**Comment by ehallander9591** [comment]
Thank you kindly sir
