### ISSUE TITLE
Support Google Closure Compiler (Refactor to remove stringified reference to types)

### ISSUE THREAD

**Issue by joscha** [dcodeIO/protobuf.js#715]
protobuf.js version: 6.6.5 (but also on master)

When generating code, there is this piece:

```js
        const $types = {
            3: "xyz.MyEnum"
        }; $lazyTypes.push($types);
```

which is then resolved later in `util.lazyResolve`. I am trying to use protobuf.js in the [Things Network Console](https://www.thethingsnetwork.org/docs/network/console/) which allows you to specify a payload function to decode incoming data from a byte buffer. This code is run within [otto](https://github.com/robertkrimen/otto), so I am trying to get a statically generated decoder as small as possible. With Uglify I get to 22KB for a decode/fromObject/toObject combo (17.4 for decode-only). However, the Google Closure Compiler is far better at getting this even smaller with advanced optimizations (about 12KB). One problem with that, however, is that it renames symbols quite rigidly, so `xyz.MyEnum` would be renamed and when the lazy loader tries to find it, it won't be there any more.
There are a couple of possible solutions I can see for this. We could either define the types as callbacks, e.g.

```js
        const $types = {
            3: () => xyz.MyEnum
        }; $lazyTypes.push($types);
```

or we can define them with array notation:
```
xyz["MyEnum"]= (function() {...}
```

to prevent them from being modified. Is there a reason why on a static build these are lazily evaluated at all?

**Comment by dcodeIO** [comment]
> Is there a reason why on a static build these are lazily evaluated at all?

The `$root` object is assembled linearly in static code, hence a type reference from message 1, which is declared first, to message 2 might not yet be there (`undefined` or a TypeError if even the parent namespace isn't there yet).

> We could either define the types as callbacks

I really like this approach, going to implement.

**Comment by dcodeIO** [comment]
This commit removes the need for lazy types entirely. Let me know if there are any issues.

**Comment by joscha** [comment]
:tada: @dcodeIO - will check it out later and let you know! Thank you very much!

**Comment by joscha** [comment]
works a charm @dcodeIO, just tried with 8401a47d030214a54b5ee30426ebc7a9d9c3773d - thank you so much, any chance we can get a new version released?
