### ISSUE TITLE
Which JS types are valid in fromObject, create, and encode?

### ISSUE THREAD

**Issue by seishun** [dcodeIO/protobuf.js#719]
For instance, in which cases am I allowed to specify enum values as strings rather than numbers?

```proto
syntax = "proto3";

message DeviceReadings {
  enum Foo {
    ONE = 0;
    TWO = 1;
  } 

  Foo foo = 1;
}
```

When I use a string in `encode` it seems to fall back to the default value:

```js
> DeviceReadings.decode(DeviceReadings.encode({foo: 'TWO'}).finish())
DeviceReadings { foo: 0 }
```

But if I go through `fromObject` first then it works:

```js
> DeviceReadings.decode(DeviceReadings.encode(DeviceReadings.fromObject({foo: 'TWO'})).finish())
DeviceReadings { foo: 1 }
```

But with `create` it works the same as `encode` alone:

```js
> DeviceReadings.decode(DeviceReadings.encode(DeviceReadings.create({foo: 'TWO'})).finish())
DeviceReadings { foo: 0 }
```

Is all that documented somewhere?

**Comment by dcodeIO** [comment]
There is a new **Usage** section in the README that tries to explain the differences. Basically, `.create` and `.encode` expect a valid object, while `.fromObject` performs conversion to proper internal types.

**Comment by seishun** [comment]
That's great, but it would be even greater if it also described what is considered "valid" and what kind of conversions `fromObject` can do.

**Comment by dcodeIO** [comment]
Using this issue to create some documentation to copy to the README eventually.

---

**What is a valid message?**

A valid message basically is an object exclusively using JS types for its fields that are understood by the [Writer](https://github.com/dcodeIO/protobuf.js/blob/master/src/writer.js).

| Type   | JS Type
|--------|----------
| int32, uint32, sint32 | Number (32 bit integer)
| float, double | Number (32 bit  integer)
| fixed32, sfixed32 | Number (32 bit integer)
| int64, uint64, sint64 | Number (53 bit integer) or Long instance (64 bit)
| bool | Boolean
| string | String
| bytes | Array.\<Number> or a base64 encoded string

| Modifier | JS Type
|-----------|---------
| repeated | Array.\<T>
| map | Object.\<string,T>

**Comment by dcodeIO** [comment]
Is this approximately what you have been looking for?

**Comment by seishun** [comment]
Looks good, but it doesn't mention that enum can be a string in the "naive conversion".

I think it should also be mentioned which conversion is performed by `encode`.

Also IMO if you list Buffer objects as `Buffer`, then people might think that `String` means a String object (rather than a string value).

**Comment by dcodeIO** [comment]
Added enums in the meantime. String is both String objects and string values.

**Comment by seishun** [comment]
Looks great, thank you!

**Comment by seishun** [comment]
Another thing. According to my experiments, if there's a `oneof` field, you must set the virtual property to the name of the set field, otherwise it's not serialized. If that's correct, then that should also be mentioned.

**Comment by dcodeIO** [comment]
This has changed lately to encode whatever is present.

Related: https://github.com/dcodeIO/protobuf.js/issues/710

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
