### ISSUE TITLE
Generated Static enums

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#720]
protobuf.js version: <6.6.5>

What happened to the reverse entries for the generated enums in the static code? I liked that feature.

By reverse I mean, the generated code used to look like

```js
            values[valuesById[0] = "NOT_SPECIFIED"] = 0;
            values[valuesById[102] = "GET_MISSION"] = 102;
```

and now looks like

```js
            values["NOT_SPECIFIED"] = 0;
            values["GET_MISSION"] = 102;
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
It should still emit that, except if it is an aliased key.

Reference: https://github.com/dcodeIO/protobuf.js/blob/master/cli/targets/static.js#L612

Isn't this working?

**Comment by ehallander9591** [comment]
Hmmm. What would I have done to trigger the aliased key?

**Comment by ehallander9591** [comment]
Thank you

**Comment by ehallander9591** [comment]
Back to my normal..

**Comment by joscha** [comment]
I think this might be related to #727
