### ISSUE TITLE
Getting >>> interface Units$Properties in .d.ts files now

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#721]
protobuf.js version: <latest from master>

I pulled the latest to get the enum fix you took care of today, and this showed up in my .d.ts files.

I reverted back and it would seem the generated .d.ts had class definitions, and now they are all interface definitions and all interface definitions contain '$Properties' appended to the interface

```js
        /**
         * Properties of an Units.
         * @typedef mpxs.model.Units$Properties
         * @type Object
         * @property {Array.<mpxs.model.Unit>} [unit] Units unit.
         * @property {number} [planTimeOffset] Units planTimeOffset.
         */
        interface Units$Properties {
            unit?: mpxs.model.Unit[];
            planTimeOffset?: number;
        }

```

```Old
        /**
         * Constructs a new Units.
         * @exports mpxs.model.Units
         * @constructor
         * @param {Object} [properties] Properties to set
         */
        class Units {

and all the class details
}
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
This is discussed here: https://github.com/dcodeIO/protobuf.js/issues/717

**Comment by ehallander9591** [comment]
I suspect there is still work going on in the issue and that was what my colleague was talking about when he asked me if I had been following the talk about the typescript changes. I will check back and try to monitor what is going on.
