### ISSUE TITLE
optional fields return zero value (empty string) instead of null

### ISSUE THREAD

**Issue by tamird** [dcodeIO/protobuf.js#728]
Given the [definition](https://github.com/cockroachdb/cockroach/blob/aa22f21/pkg/build/info.proto):
```protobuf
syntax = "proto2";
package cockroach.build;
option go_package = "build";

import "gogoproto/gogo.proto";

// Info describes build information for this CockroachDB binary.
message Info {
  optional string go_version = 1 [(gogoproto.nullable) = false];
  optional string tag = 2 [(gogoproto.nullable) = false];
  optional string time = 3 [(gogoproto.nullable) = false];
  optional string revision = 4 [(gogoproto.nullable) = false];
  optional string cgo_compiler = 5 [(gogoproto.nullable) = false];
  optional string platform = 6 [(gogoproto.nullable) = false];
  optional string distribution = 7 [(gogoproto.nullable) = false];
  optional string type = 8 [(gogoproto.nullable) = false];

  // dependencies exists to allow tests that run against old clusters
  // to unmarshal JSON containing this field. The tag is unimportant,
  // but the field name must remain unchanged.
  //
  // alternatively, we could set jsonpb.Unmarshaler.AllowUnknownFields
  // to true in httputil.doJSONRequest, but that comes at the expense
  // of run-time type checking, which is nice to have.
  optional string dependencies = 10000;
}

```

The generated message behaves incorrectly:
```javascript
$ node
> var protos = require('./src/js/protos');
undefined
> r = new protos.cockroach.build.Info()
Info {}
> r.go_version
''
```

This should return null, not empty string. Note that in protobuf 3 it should return empty string, since primitives are non-nullable in protobuf 3.

The typescript definitions are also incorrect with respect to the nullability of these attributes.

**Comment by dcodeIO** [comment]
If not set, it returns the default value of the field and the default value of an unset string field is an empty string as of the official spec. More precisely, the value you see there comes from `protos.cockroach.build.Info.prototype.go_version`

**Comment by tamird** [comment]
The spec says that you should be able to distinguish between an empty value
and an unset value.

**Comment by dcodeIO** [comment]
You can by using `r.hasOwnProperty("go_version")`

**Comment by tamird** [comment]
Yikes, that's an unfortunate API. Still, the type definitions should
reflect that the value is non-null.

**Comment by dcodeIO** [comment]
The type definition just says it is `string`. You can still manually set fields to `null` or `undefined` (which is checked by `r != null`).

I know that the API isn't perfect, but I don't see another way in JS (without introducing something not really performant like hidden properties and such).

**Comment by tamird** [comment]
Why can't you make unset properties return null?

**Comment by dcodeIO** [comment]
Using `null` for everything was something frequently discussed in v5. This ultimately lead to the behavior we have today.

**Comment by tamird** [comment]
Can you link to some of those discussions?

**Comment by dcodeIO** [comment]
https://github.com/dcodeIO/protobuf.js/pull/380 for example

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by vjpr** [comment]
I had some tough time with this.

Assume the protobuf def `message` is something like:

```
{
  a: {
    foo: Number,
    bar: Number,
  }
}
```

```
const message = MyMessage.decodeDelimited(bytes)
const messageJson =  MyMessage.toObject(message)

// {foo: 1}
console.log(message.a)

// {foo: 1}
console.log(messageJson.a)

// 0
console.log(message.a.bar)

// undefined
console.log(messageJson.a.bar)
```

If you forget to use `toObject` you get a very different result.

**Comment by FanAs** [comment]
Hello, I don't know if it's a good solution, but I changed this behaviour by adding one-liner to our project:
```js
import { Field } from 'protobufjs';
Object.defineProperty(Field.prototype, 'typeDefault', { get: () => null, set: () => null });
```

It works just like I want now.
