### ISSUE TITLE
Incorrect docs for pbjs.main()

### ISSUE THREAD

**Issue by dandean** [dcodeIO/protobuf.js#734]
protobuf.js version: `protobuf.js v6.6.5 CLI for JavaScript`

The **CLI** API documentation states that [`output` is passed to the callback](https://github.com/dcodeIO/protobuf.js/tree/master/cli#api):

```js
pbjs.main([ "--target", "json-module", "path/to/myproto.proto" ], function(err, output) {
    if (err)
        throw err;
    // do something with output
});
```

The documentation is incorrect: an `output` argument is not passed to the callback function.

## Reproduce:

**My code:**

```js
var files = [...protos...];
pbjs.main(['--target', 'static-module'].concat(files), (error, output) => {
  if (error) {
    console.error(`Error building schemas: ${error.message}`);
    process.exit();
  }
  console.log(output);
});
```

## Output

```js
// expected output, followed by:
undefined
```

It's printing `undefined` at the end because `pbjs.main()` writes to `stdout`, it does not pass output to the callback, as documented.

## The fix

The fix on my end is to remove `console.log(output)`. The fix in protobufjs is to update the documentation to remove the `output` argument on the callback and note that it prints directly to `stdout`.

**Comment by dcodeIO** [comment]
See: https://github.com/dcodeIO/protobuf.js/commit/16adff0c7b67c69a2133b6aac375365c5f2bdbf7

Is this still a thing in master?

**Comment by dandean** [comment]
That fixes it! 🙌
