### ISSUE TITLE
How to convert base64 string to Message (protobuf.js v6)

### ISSUE THREAD

**Issue by sulliwane** [dcodeIO/protobuf.js#735]
version: protobufjs@6.6.5

grpc-gateway (not open sourced by google yet) is sending a base64 string encoded protobuf message to me (fetch() request). I'd like to convert this **base64_string** to the protobuf message.

Here is my attempt, but with no luck:
```js
const base64_string = "my_base64_string";
const Message = root.lookup("package.Message");
var message = Message.decode(base64_string);
```
I also tried converting the **base64** string to **Uint8array**:
```js
const base64_string = "my_base64_string";
const buffer = Uint8Array.from(atob(base64_string), c => c.charCodeAt(0))
const Message = root.lookup("package.Message");
var message = Message.decode(buffer);
```
But I get scrumbled characters in the wrong field.

**v5** had ```decode64()```, how to do that with **v6**?

Many thanks!

note: I'm getting the base64 string by doing:
```js
fetch().then(response => response.text()).then(base64 => { ... })
```

**Comment by dcodeIO** [comment]
> But I get scrumbled characters in the wrong field.

You might be experiencing [The "Unicode Problem"](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem). [See also](https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F).

> v5 had decode64(), how to do that with v6?

There is no such method anymore, but a [base64 library is included](https://github.com/dcodeIO/protobuf.js/tree/master/lib/base64). It's available as `protobuf.util.base64`.

```js
var util =  protobuf.util,
    base64 = util.base64;

var string = "...";
var buffer = util.newBuffer(base64.length(string));
base64.decode(string, buffer, 0);
// use buffer
```

**Comment by sulliwane** [comment]
Ok, so I was doing it correctly I suppose, cause I'm still getting scrambled code:
![screenshot from 2017-03-29 11-22-11](https://cloud.githubusercontent.com/assets/1733686/24437142/0c3da29a-1472-11e7-9004-4e01dd32416c.png)

This is probably my base64 string which is not why I expect it to be (it is generated by google grpc-nginx-gateway, soon to be [opensourced](https://github.com/grpc/grpc-web). So I will ask over there).

**Comment by sulliwane** [comment]
Still trying to figure out how to decode the response：
```js
import protobuf from 'protobufjs';
protobuf.load("package.proto")
.then(function(root) {
  const MessageReq = root.lookup("package.MessageReq");
  const messageReq = MessageReq.create({ symbols: ['IF1609'] })

  fetch('http://myhost:port/package.Service/Method', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-protobuf',
      'X-Accept-Content-Transfer-Encoding': 'base64',
      'X-Accept-Response-Streaming': 'true'
    },
    body: MessageReq.encode(messageReq).finish(),
  })
  .then(response => response.text())
  .then(base64_string => {
    // Is that the proper way to convert the base64 string to a TypedArray?
    const buffer = Uint8Array.from(atob(base64_string), c => c.charCodeAt(0))

    const MessageRes = root.lookup("package.MessageRes");
    var messageRes = MessageRes.decode(buffer);

    console.log('messageRes', messageRes) // not OK, scrambled code
  })
});
```
Here is the base64 string response:
```
Cl4KXAoGSUYxNjA5OgVDRkZFWFoT5rKq5rexMzAw5oyH5pWwMTYwOWmamZmZmZnZP7kBmpmZmZmZyT/CAQExygECSUbZAZqZmZmZmdk/iAKsApECAAAAAADGy0CoAucHEgQSAk9L
```
My goal is to write a fetch transport ([rpcImpl method like described here](https://github.com/dcodeIO/protobuf.js#using-services)) compatible with the the specs of [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md).

**Comment by dcodeIO** [comment]
```js
var base64_string = "Cl4KXAoGSUYxNjA5OgVDRkZFWFoT5rKq5rexMzAw5oyH5pWwMTYwOWmamZmZmZnZP7kBmpmZmZmZyT";
var buffer = Uint8Array.from(atob(base64_string), c => c.charCodeAt(0));
console.log(Array.prototype.toString.call(buffer));

// 10,94,10,92,10,6,73,70,49,54,48,57,58,5,67,70,70,69,88,90,19,230,178,170,230,183,177,51,48,48,230,140,135,230,149,176,49,54,48,57,105,154,153,153,153,153,153,217,63,185,1,154,153,153,153,153,153,201
```

```
10	id 1, wireType 2 (A.a)
94	length = 94
10	id 1, wireType 2 (B.b)
92	length = 92
10	id 1, wireType 2 (C.c)
6	length = 6
73 70 49 54 48 57 = "IF1609"
...
```

To me it looks that, if you get the following taken from your comment above, your .proto definition is invalid / not describing your data:

![screenshot from 2017-03-29 11-22-11](https://cloud.githubusercontent.com/assets/1733686/24437142/0c3da29a-1472-11e7-9004-4e01dd32416c.png)

Structure is something like...

```protobuf
message A {
  B a = 1;
  message B {
    C b = 1;
    message C {
      string c = 1;
    }
  }
}
```

**Comment by sulliwane** [comment]
this is basically my proto definition:
```proto
service myService {
  rpc GetInstruments(MessageReq) returns (MessageRes) {}
}
message MessageReq {
  repeated string symbols = 1; // ex: ['IH1609'']
}
message MessageRes {
  repeated Instrument instruments = 1;
}
message Instrument {
  string instrumentid = 1;
}
```
I think my proto definition is correct as it's working for my other grpc clients (node, python).
thank you for your reply!

**Comment by dcodeIO** [comment]
All I can tell is, from your code, that you are decoding a `MessageRes` that contains a single field with id 1 of repeated `Instrument`s. Regarding the buffer you are decoding, this corresponds to:

```
10	id 1, wireType 2 (A.a)
94	length = 94
```

So the buffer starts with some field with id 1 that has a value of 94 bytes length, which is then interpreted as an `Instrument`. An `Instrument` contains a string field with id 1, which corresponds to:

```
10	id 1, wireType 2 (B.b)
92	length = 92
```

These 92 bytes are interpreted as a string (Instrument#instrumentid), but actually aren't a string but another level of nested messages:

```
10	id 1, wireType 2 (C.c)
6	length = 6
73 70 49 54 48 57 = "IF1609"
```

Hence, when decoding, your instrumentid starts with two scrambled bytes, then the string IF1609 and then more scrambled bytes - because these bytes are something different than what you are decoding.

The decoding step works because nested messages and strings use the same wire type (2, ldelim) and hence look the same on the wire.

**Comment by sulliwane** [comment]
Many thanks. I will try this tomorrow.

Notes:
Here is what the JS object looks like once decoded on the grpc-node client: 
```js
[{ instrumentid: 'IF1709', otherprops: 'string' }]
```
There is maybe some extra informations added by grpc-web. Here is an implementation of grpc-web for reference: https://github.com/improbable-eng/grpc-web/tree/master/ts/src/transports

**Comment by sulliwane** [comment]
it works! :1st_place_medal: 

So will ask what is the purpose of the first 2 bytes. I'll update here when I understand more clearly the grpc-web specs.

Many thanks for your help!

**Comment by dcodeIO** [comment]
Alright, feel free to reopen if necessary!

**Comment by metled** [comment]
@sulliwane  maybe the first 2 bytes is the "Length-Prefixed-Message" of [gPRC](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)

**Comment by Nasratullahsarabi** [comment]
How can I add the Enable Base64 encoding in Body of my Protman?

![Image](https://github.com/user-attachments/assets/2b7dd2b2-20bc-405e-8a0d-ba04d05e7bde)
