### ISSUE TITLE
Typescript definitions not valid

### ISSUE THREAD

**Issue by CageFox** [dcodeIO/protobuf.js#737]
protobuf.js version: 6.7.0

1. Install typescript@next locally or globally:

npm i -g typescript@next

2. Create empty dir for project, inside make one typescript file:
import.ts:

import * as protobuf from "protobufjs";
console.log("a");

3. Install protobufjs in above project directory:

npm install protobufjs

4. Compile:
tsc test.ts 

Expected behaviour: compile success

Current behaviour: numerous typescript errors:

node_modules/protobufjs/index.d.ts(419,13): error TS2300: Duplicate identifier 'LoadCallback'.
node_modules/protobufjs/index.d.ts(425,6): error TS2300: Duplicate identifier 'LoadCallback'.
node_modules/protobufjs/index.d.ts(1103,13): error TS2300: Duplicate identifier 'ParserResult'.
node_modules/protobufjs/index.d.ts(1111,6): error TS2300: Duplicate identifier 'ParserResult'.
node_modules/protobufjs/index.d.ts(1115,13): error TS2300: Duplicate identifier 'ParseOptions'.
node_modules/protobufjs/index.d.ts(1119,6): error TS2300: Duplicate identifier 'ParseOptions'.
node_modules/protobufjs/index.d.ts(1520,40): error TS2694: Namespace '"C:/a/node_modules/protobufjs/index".rpc.rpc' has no exported member 'Service'.
node_modules/protobufjs/index.d.ts(1526,13): error TS2300: Duplicate identifier 'RPCImpl'.
node_modules/protobufjs/index.d.ts(1541,6): error TS2300: Duplicate identifier 'RPCImpl'.
node_modules/protobufjs/index.d.ts(1545,13): error TS2300: Duplicate identifier 'RPCImplCallback'.
node_modules/protobufjs/index.d.ts(1551,6): error TS2300: Duplicate identifier 'RPCImplCallback'.
node_modules/protobufjs/index.d.ts(1610,33): error TS2300: Duplicate identifier 'TokenizerHandle'.
node_modules/protobufjs/index.d.ts(1618,6): error TS2300: Duplicate identifier 'TokenizerHandle'.
node_modules/protobufjs/index.d.ts(1821,13): error TS2300: Duplicate identifier 'ConversionOptions'.
node_modules/protobufjs/index.d.ts(1836,11): error TS2300: Duplicate identifier 'ConversionOptions'.
node_modules/protobufjs/index.d.ts(2013,13): error TS2300: Duplicate identifier 'Long'.
...

Way to fix: rebuild protobufjs file index.d.ts by pbts but with added option --no-comments

Reason: Typescript using JSDoc data to build types info, but with JSDoc comments typescript use same types twice:

/**
 * A node-style callback as used by {@link load} and {@link Root#load}.
 * @typedef LoadCallback
 * @type {function}
 * @param {?Error} error Error, if any, otherwise `null`
 * @param {Root} [root] Root, if there hasn't been an error
 * @returns {undefined}
 */
type LoadCallback = (error: Error, root?: Root) => void;

**Comment by dcodeIO** [comment]
Imho, TypeScript shouldn't use JSDoc data from d.ts files at all, because these cannot even contain JavaScript technically. Not sure that this is a protobuf.js problem in the first place.

Of course we can fix this for now by excluding just `@typedef` comments. Iirc these do not result in any sort of IntelliSense documentation anyway.

**Comment by CageFox** [comment]
Typescript is rather new and very swiftly evolving project, but right now use of protobufjs in typescript projects lead to above problem

Personally I agree with you and see no reason typescript using JSDoc data from d.ts, but that's current situation.

I also see no reason to keep JSDoc data in d.ts files, as JSDoc and d.ts both define type data

Will you fix the problem?

**Comment by dcodeIO** [comment]
> I also see no reason to keep JSDoc data in d.ts files

The idea here is to provide textual IntelliSense documentation right from the .d.ts file, even when using a .min.js file.

> Will you fix the problem?

Sure.

**Comment by hnfmr** [comment]
We are having the same issue, `tsc` complains about `Long` in the generated typings...
We locked `protobufjs` to `6.6.5` for now...

**Comment by dcodeIO** [comment]
When not using long.js typings, just reference the stub somewhere in your project:

```js
/// <reference path="./node_modules/protobufjs/stub-long.d.ts" />
```

See: [Usage with TypeScript](https://github.com/dcodeIO/protobuf.js#usage-with-typescript)

**Comment by dcodeIO** [comment]
6.7.3 includes typings for long and node again.

For reference, see these issues: https://github.com/dcodeIO/protobuf.js/issues/711 https://github.com/dcodeIO/protobuf.js/issues/753

So, this should be sorted in your favor now. Feel free to reopen if it is not!
