### ISSUE TITLE
Small bytes field causes protobuf corruption and code leak

### ISSUE THREAD

**Issue by fathyb** [dcodeIO/protobuf.js#738]
protobuf.js version: 6.6.5

When encoding a protobuf message which has a `bytes` filled with small amount of data (something like 400kB) the resulting buffer become corrupt and JavaScript source code is leaked (it seems random which file get leaked). It doesn't happen past a certain size.

Take this case for exemple (see the repro repo in the bottom) : 
```proto
message TestMessage {
    optional bytes data = 1;
}
```

```js
var fs = require('fs')
var TestMessage = require('./message').TestMessage

var message = TestMessage.fromObject({
    data: fs.readFileSync('image-10.png')
})

fs.writeFileSync('image-10.pb', Buffer.from(TestMessage.encode(message).finish().buffer))

message = TestMessage.fromObject({
    data: fs.readFileSync('image-512.png')
})

fs.writeFileSync('image-512.pb', Buffer.from(TestMessage.encode(message).finish().buffer))
```

`image-512.pb` is correct and only contains the image content, `image-10.pb` is corrupted and contains this kind of code : 
```js
"use strict";
module.exports = BufferWriter;

// extends Writer
var Writer = require("./writer");
(BufferWriter.prototype = Object.create(Writer.prototype)).constructor = BufferWriter;

var util = require("./util/minimal");

var Buffer = util.Buffer;

/**
 * Constructs a new buffer writer instance.
 * @classdesc Wire format writer using node buffers.
 * @extends Writer
 * @constructor
 */
function BufferWriter() {
    Writer.call(this);
}

/**
 * Allocates a buffer of the specified size.
 * @param {number} size Buffer size
 * @returns {Buffer} Buffer
 */
BufferWriter.alloc = function alloc_buffer(size) {
    return (BufferWriter.alloc = util._Buffer_allocUnsafe)(size);
};

var writeBytesBuffer = Buffer && Buffer.prototype instanceof Uint8Array && Buffer.prototype.set.name === "set"
    ? function writeBytesBuffer_set(val, buf, pos) {
        buf.set(val, pos); // faster than copy (requires node >= 4 where Buffers extend Uint8Array and set is properly inherited)
                           // also works for plain array values
    }
    /* istanbul ignore next */
    : function writeBytesBuffer_copy(val, buf, pos) {
        if (val.copy) // Buffer values
            val.copy(buf, pos, 0, val.length);
        else for (var i = 0; i < val.length;) // plain array values
            buf[pos++] = val[i++];
    };

/**
 * @override
 */
BufferWriter.prototype.bytes = function write_bytes_buffer(value) {
    if (util.isString(value))
        value = util._Buffer_from(value, "base64");
    var len = value.length >>> 0;
    this.uint32(len);
    if (len)
        this.push(writeBytesBuffer, len, value);
    return this;
};

function writeStringBuffer(val, buf, pos) {
    if (val.length < 40) // plain js is faster for short strings (probably due to redundant assertions)
        util.utf8.write(val, buf, pos);
    else
        buf.utf8Write(val, pos);
}

/**
 * @override
 */
BufferWriter.prototype.string = function write_string_buffer(value) {
    var len = Buffer.byteLength(value);
    this.uint32(len);
    if (len)
        this.push(writeStringBuffer, len, value);
    return this;
};


/**
 * Finishes the write operation.
 * @name BufferWriter#finish
 * @function
 * @returns {Buffer} Finished buffer
 */

```

On our production servers the code from [`source-map/quick-sort`](https://github.com/mozilla/source-map/blob/master/lib/quick-sort.js) is leaked for the same image (maybe with few bytes changed cause of EXIF).

I made a reproduction repository which contains everything to reproduce the bug. Steps to reproduce : 
1. `git clone https://github.com/fathyb/protobufjs-empty-arrays`
2. `npm install`
3. `npm run build`
5. `node test`
6. open `image-10.pb` and `image-512.pb` to see the difference and the code leaked

**Comment by dcodeIO** [comment]
Under node.js, buffers are slices on a much larger buffer pool (something like 8kb) for improved allocation performance. Hence, your issue seems to originate here:

```js
fs.writeFileSync('image-10.pb', Buffer.from(TestMessage.encode(message).finish().buffer))
```

Using `.buffer` is writing out the entire backing buffer of an otherwise smaller buffer slice. Removing `.buffer` should resolve your issue.

**Comment by fathyb** [comment]
Thank you so much for the clear and quick answer (as always), you saved my week-end!

I was using `.buffer` because of TypeScript complaining that `Buffer.from` doesn't takes `ArrayBufferView`.

I close the issue as it is not related to `protobufjs`.

**Comment by dcodeIO** [comment]
The TypeScript error you see there is because `.encode(...)` returns a `protobuf.Writer`, which is actually a `protobuf.BufferWriter` (subclass) under node.js. `Writer#finish()` returns an `Uint8Array` while `BufferWriter#finish()` returns a `Buffer` (which is also an `Uint8Array` when using recent versions of node). A cast should solve this.

**Comment by fathyb** [comment]
If it returns a `Buffer`I think I could even get rid of `Buffer.from` in the first place

**Comment by dcodeIO** [comment]
> If it returns a BufferI think I could even get rid of Buffer.from in the first place

Yeah. Just note that this is node.js-only functionality. Browsers don't use `BufferWriter`.
