### ISSUE TITLE
Dynamically attach an extension before decoding

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#739]
protobuf.js version: 6.6.5

I am not sure if this is possible, so this could either be a feature request or question. I am finally getting around to improving the JS page load and trying to split the messages into multiple bundles.

We have some messages which are extensions

For example Lets say BaseMessage is the part of lib.json bundle describes the extension range.
```proto
message BaseMessage {
  extensions 100 to max;
}

Now MyMessage is in another file core.json
message MyMessage {
   extend BaseMessage {
    optional MyMessage extension = 101;
  }
}

message Payload {
   message BaseMessage message;
}
```

So far I have:

```javascript
const lib = Root.fromJSON(require('lib.json'));
const extensions = Root.fromJSON(require('extensions.json'));
const protos = {
   ...lib.resolveAll().lookup('mynamespace'),
   ...extensions.resolveAll().lookup('mynamespace')
};

let buffer = // Contains a valid buffer from server side containing a BaseMessage with extension
const reader = Reader.create(buffer);   
const msg = protos.BaseMessage.decode(reader);
// msg.message is not present
```

What is the right way to merge two json's objects before resolving()
addJSON created a weird empty key "" under nested under root.

**Comment by r-tock** [comment]
Ok. so if I do 
const extensions = root.addJSON(require('extensions.json').nested);

it proceeds, However I see google namespace is being included in both twice hence the addJSON seems to be failing. When I try to delete that from the bundle and ignore that, The addJSON fails because BaseMessage is declared in both. 

Is it possible to add an option to pbjs cli to skip includes, because that seem to be working...

**Comment by r-tock** [comment]
Alternately,  In java world you can create an ExtensionRegistry register the extension before calling parse() method. I would love an equivalent method here as well.

**Comment by dcodeIO** [comment]
Splitting up definitions (or other target files) currently requires manual work. While using a single `Root` instance with `Root#addJSON` is the correct approach, JSON definitions are still bundles that include all referenced types. Hence it is necessary to remove duplicate definitions before loading.

Related: https://github.com/dcodeIO/protobuf.js/issues/722

> Alternately, In java world you can create an ExtensionRegistry register the extension before calling parse() method. I would love an equivalent mechanism here as well.

Sounds like this could be done with reflection.

**Comment by r-tock** [comment]
FWIW, this is what I ended up with

First create a lib.js file

```javascript
import { Root, util, configure } from 'protobufjs';
const Long = require('long');
util.Long = Long;
configure();

const root = Root.fromJSON(require('core/dist/lib.json'));
const resolvedRoot = root.resolveAll();
export default resolvedRoot;
```

Then create bundles, resolveAll() them and re-export. Seems to be working well. Unless I am overlooking something.

In this case calendar.js looks like

```javascript
import lib from 'shared/utils/lib';
import { Root } from 'protobufjs';

const calendarRoot = Root.fromJSON(require('core/dist/calendar.json'));
lib.nested.tocktix.add(calendarRoot.nested.tocktix.nested.proto);
const resolvedRoot = lib.resolveAll();
const protos = {
  ...resolvedRoot.lookup('tocktix.proto.calendar'),
};
module.exports = protos;
```

**Comment by r-tock** [comment]
I think the ExtensionRegistry approach may be the more clean approach

https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/ExtensionRegistry

**Comment by dcodeIO** [comment]
> I think the ExtensionRegistry approach may be the more clean approach

I see that there are valid reasons for its existence, but adding something like this would come at the price of code size (probably dead code in most scenarios) and general complexity of the library. I'd prefer to tackle the underlying redundancy in target files first through adding a way to generate multiple output files that require/import each other properly.

Regarding your solution:

```js
const calendarRoot = Root.fromJSON(require('core/dist/calendar.json'));
lib.nested.tocktix.add(calendarRoot.nested.tocktix.nested.proto);
```

While this apparently works (reflection isn't much more than a JSON descriptor converted to reflection objects while not resolved), it is not really meant to be done this way. You are basically moving reflection objects between roots, which will most likely corrupt the root instances in some way if something is already resolved.

Instead, you could just load the relevant raw JSON descriptor through `.addJSON`:

```js
const calendarJson = require('core/dist/calendar.json');
lib.define("tocktix.protos.calendar").addJSON(calendarJson.nested.tocktix.nested.proto.nested.calendar);
```

Or better, preprocess calendarJson to remove unnecessary levels of nesting, so you can do:

```js
lib.define("tocktix.protos.calendar").addJSON(require('core/dist/calendar.json'));
```

That's pretty much the manual step I mentioned before.

**Comment by r-tock** [comment]
I see, I switched over to your suggestion. For now the overhead of things to prune is quite negligible that I probably should wait for the long term solution -- converting proto files into individual JS files

**Comment by dcodeIO** [comment]
When looking at this issue again I feel that ExtensionRegistry is not a thing I'd spend time on anytime soon. I'll close it for now with a *wontfix*, no offense intended. Maybe another time - or through a PR.
