### ISSUE TITLE
TS Typings: Class properties should be of type Message, not Message$Properties

### ISSUE THREAD

**Issue by obto** [dcodeIO/protobuf.js#746]
```
message FooMessage {
  bool my_bool = 1;
  repeated BarMessage bars = 2;
}

message BarMessage {
  string my_string = 1;
}
```

Right now FooMessage.bars is of type BarMessage$Properties[] which has the unfortunate side-effect of `FooMessage.bars[0].my_string` being of type `string|undefined` when it should be of type `string`.

1. Would changing the typings from `Message$Properties` to just `Message` be an acceptable fix? OR
2. Should we duplicate the `Message$Properties` interface and create two versions? One with optional props and one without optional props?

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/protobuf.js/issues/741

There is a new command line option `--force-message` in master now that does exactly this.

**Comment by obto** [comment]
Works great. Thanks
