### ISSUE TITLE
Cannot find name 'object' is my tsc error for index.d.ts

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#747]
protobuf.js version: <6.7.0>

I pulled the latest update, and after adapting to the documented changes concerning the $Properties, I ran through tsc, and the following errors came up for protobufjs/index.d.ts

Error:(2173, 24) TS2304:Cannot find name 'object'.

which resolved to 

```js
    /**
     * An immutable empty object.
     * @type {Object}
     * @const
     */
    const emptyObject: **object;**

```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Seems that `object` requires TypeScript >= 2.2

See: https://github.com/Microsoft/TypeScript/issues/14647

**Comment by ehallander9591** [comment]
And I am 2.1.4

**Comment by ehallander9591** [comment]
Upgraded to 2.2.1 all is well.

Thanks
