### ISSUE TITLE
Non-optional fields causing TypeScript errors

### ISSUE THREAD

**Issue by paralin** [dcodeIO/protobuf.js#749]
protobuf.js version: 6.7.1

I'm passing the output of pbjs json conversion to loadJson, this works fine, but there's a new typing error in the latest update:

```
Argument of type '{ "nested": { "google": { "nested": { "api": { "options": { "java_multiple_files": boolean; "java...' is not assignable to parameter of type 'NamespaceDescriptor'.
  Types of property 'nested' are incompatible.
    Type '{ "google": { "nested": { "api": { "options": { "java_multiple_files": boolean; "java_outer_class...' is not assignable to type '{ [k: string]: EnumDescriptor | ExtensionFieldDescriptor | ExtensionMapFieldDescriptor | TypeDesc...'.
      Property '"google"' is incompatible with index signature.
        Type '{ "nested": { "api": { "options": { "java_multiple_files": boolean; "java_outer_classname": strin...' is not assignable to type 'EnumDescriptor | ExtensionFieldDescriptor | ExtensionMapFieldDescriptor | TypeDescriptor | Servic...'.
          Type '{ "nested": { "api": { "options": { "java_multiple_files": boolean; "java_outer_classname": strin...' is not assignable to type 'ServiceDescriptor'.
            Property 'methods' is missing in type '{ "nested": { "api": { "options": { "java_multiple_files": boolean; "java_outer_classname": strin...'
```

The issue is that the "methods" field is not optional. Could you please set that field to optional in the typings?

Thanks!

**Comment by dcodeIO** [comment]
`methods` is actually required, it [marks an object to be a service](https://github.com/dcodeIO/protobuf.js/blob/master/src/service.js#L28). Without it, `fromJSON` doesn't know what kind of object it is handling.

If you generated the respective JSON descriptor somehow, there might be something wrong in generation instead.

**Comment by paralin** [comment]
Right, but it's not required on *every* single thing, right? You can treat it not being there as null. If I just ignore the typing error protobufjs works correctly anyway right now.

**Comment by dcodeIO** [comment]
Yeah, without a marker, addJSON [falls back to treat the object as a namespace](https://github.com/dcodeIO/protobuf.js/blob/master/src/namespace.js#L145). Inner namespaces aren't really intended, though, but could be added [somewhere around here](https://github.com/dcodeIO/protobuf.js/blob/master/src/namespace.js#L103).

**Comment by paralin** [comment]
I nest namespaces in my code, quite a bit actually. It seems to work just fine! Is this just a typings issue, or does something need to be changed in ProtobufJS to support that pattern? Assuming the fallback is actually working as intended and I'm not abusing some kind of bug.

**Comment by dcodeIO** [comment]
More of a typings issue because of empty objects.

> Issue here is that nested is optional on NamespaceDescriptor because it's abstract, effectively making the type accept empty objects.

**Comment by dcodeIO** [comment]
Currently trying to fix this, but as soon as I add a sixth type to `@type {EnumDescriptor|TypeDescriptor|ServiceDescriptor|ExtensionFieldDescriptor|ExtensionMapFieldDescriptor}` my VSCode hangs with 100% cpu. Well, that's new.

**Comment by paralin** [comment]
My `tslint` did the same thing for the longest time, that's probably your issue. I think it has some unchecked infinite recursion if you use recursive structures in your code.

The issue is with only one of the checkers - the "unused variable" checker. But you're not even using tslint, I think. Your vscode might be using it internally. You could try turning off that checker in a little tslint.json file and see if it fixes it.

**Comment by dcodeIO** [comment]
Actually had a tslint plugin installed but the issue remains after uninstalling it. That's amazing...

**Comment by paralin** [comment]
eslint?

**Comment by paralin** [comment]
Here's the non-angular2 one with the unused variable checker disabled:

```
{
  "rules": {
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "curly": true,
    "eofline": true,
    "forin": true,
    "indent": [
      true,
      "spaces"
    ],
    "label-position": true,
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-inferrable-types": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": false,
    "no-use-before-declare": false,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "single"
    ],
    "radix": true,
    "semicolon": [
      "always"
    ],
    "triple-equals": [
      true,
      "allow-null-check"
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "variable-name": false,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ]
  }
}
```

**Comment by dcodeIO** [comment]
![](http://i.imgur.com/T1v8D02.jpg)

https://github.com/Microsoft/vscode-textmate

**Comment by dcodeIO** [comment]
Well, I introduced a new otherwise useless type `AnyExtensionFieldDescriptor` covering two types which makes it a total of 5 again in `AnyNestedDescriptor`. Problem solved.

**Comment by dcodeIO** [comment]
Should be working with 6.7.3. Feel free to reopen if it's not!
