### ISSUE TITLE
Uncaught Error: status 404  at XMLHttpRequest.fetchOnReadyStateChange

### ISSUE THREAD

**Issue by someValue** [dcodeIO/protobuf.js#750]
protobuf.js version: <6.7.1>
 
my code:

	var protoDefine = `
	            package ccc; 
	            message UserInfo 
	            { 
	                optional int32     id = 1;  
	                optional string    name = 2;  
	                optional int32     age = 3;  
	            }
	            `;
    var builder = protobuf.load(protoDefine, function(err, root) {
        if (err)
            throw err;
	
        var Product = root.lookup('ccc.UserInfo');
	
        var data = {
            id: 1,
            name: 'name',
            age: 18
        };
	
        var msgBuffer = Product.encode(data).finish();
    });

**Comment by dcodeIO** [comment]
`protobuf.load` doesn't load strings, it expects a file name to a .proto file. To load a .proto source, use `protobuf.parse`:

```js
var proto = `
            package ccc; 
            message UserInfo 
            { 
                optional int32     id = 1;  
                optional string    name = 2;  
                optional int32     age = 3;  
            }
            `;

var root = protobuf.parse(proto).root;
...
```

**Comment by AnaitBI** [comment]
any updates in this issue?
