### ISSUE TITLE
loadSync in the browser

### ISSUE THREAD

**Issue by arbesfeld** [dcodeIO/protobuf.js#751]
protobuf.js version: ^6.0.0

This is a feature request: is there a way to achieve synchronous loading in the browser version of `protobufjs`?

**Comment by dcodeIO** [comment]
While synchronous XHRs are possible, this lead to various issues ([1](https://github.com/dcodeIO/protobuf.js/issues/233), [2](https://github.com/dcodeIO/protobuf.js/issues/149)) in the past. That's why it isn't supported anymore. Would you mind to describe your exact use case?

**Comment by arbesfeld** [comment]
Ah - I think I misunderstood the docs. I was able to do to this to achieve sync loading in the browser:

```
import ProtoBuf from 'protobufjs/light';
ProtoBuf.Root.fromJSON(protoDefinition)
```
