### ISSUE TITLE
ArrayBuffer is neutered and could not be cloned

### ISSUE THREAD

**Issue by arbesfeld** [dcodeIO/protobuf.js#752]
protobuf.js version: ^6.0.0

I'm using protobufjs in a worker thread, and getting a strange error the second time that I try to transfer the generated `ArrayBuffer`:

```
const message = Protobuf.encode({ foo: 'bar' }).finish().buffer;
postMessage({ message }, [message]);

const message2 = Protobuf.encode({ foo: 'bar' }).finish().buffer;
postMessage({ message2 }, [message2]);
```

The error is 
``` 
DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An ArrayBuffer is neutered and could not be cloned.
```

**Comment by dcodeIO** [comment]
First of all, `Protobuf.encode({ foo: 'bar' }).finish().buffer` gets the entire backing buffer. not the slice you are actually interested in.

In general, protobuf.js uses an 8kb pool under the hood to reduce allocation overhead. In order to transfer a buffer, I'd recommend copying it first.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
