### ISSUE TITLE
Precision lost when decode long field in browser

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#758]
protobuf.js version: <please fill in>
6.7.3

### Reproduction code

**test.proto**
```protobuf
syntax = "proto3";

package TestProto;

message Test {
    fixed64 value = 1;
}
```

**generate scripts:**
```bash
pbjs -t static-module -w commonjs -o Test.js test.proto
npm i protobufjs
```

**index.js**
```js
const TestProto = require('./Test').TestProto;
const Long = require('long');
var buf = TestProto.Test.encode({value: Long.fromString("6221929103415579899")}).finish();
var dec = TestProto.Test.decode(buf);
console.log(buf);
console.log(dec.value.toString());
```

**webpack.config.js**
```js
module.exports = {
    entry: {
        app: './index.js'
    },
    output: {
        filename: 'bundle.js',
    }
}
```

### Result
**Run in node: (works well)**
> <Buffer 09 fb 14 c0 ea 8d bb 58 56>
6221929103415579899

**Run in browser: (wrong result)**
> Uint8Array(9) [9, 251, 20, 192, 234, 141, 187, 88, 86]
6221929103415580000

Notice "9899" at tail was lost!

**Comment by dcodeIO** [comment]
Is `dec.value` a `number` or a `Long`? This usually happens when long.js is not installed / [not properly recognized](https://github.com/dcodeIO/protobuf.js#browserify-integration).

**Comment by dcodeIO** [comment]
Then long.js isn't present in your browser build and unsafe numbers are used ([see long.js](https://github.com/dcodeIO/long.js) for more information on why precision loss is happening). Try assigning Long explicitly as shown above. More information on why this is happening is available [here](https://github.com/dcodeIO/protobuf.js#browserify-integration).

**Comment by twoeo** [comment]
Okay.
`6.5.3` works well.

**Comment by dcodeIO** [comment]
That's strange. Basically, long.js is [loaded automatically](https://github.com/dcodeIO/protobuf.js/blob/master/lib/inquire/index.js#L10) when a global `require` function is present, that has not been renamed, and the long module is available somewhere in the project.

**Comment by twoeo** [comment]
@dcodeIO
In 6.7.3 , it will ok if modify generated js like this:

```js
var $protobuf = require("protobufjs/minimal");

//add this
var Long = require('long');
$protobuf.util.Long = Long;
$protobuf.configure();
```

**Comment by dcodeIO** [comment]
You can do this in any other file as well, it's just important to do it once in your project.
