### ISSUE TITLE
treat Number as string when message.toJSON() after managing converting int64(Long) into Number 

### ISSUE THREAD

**Issue by joel-duqiong** [dcodeIO/protobuf.js#763]
protobuf.js version: "_nodeVersion": "6.9.1"

treat Number as string when message.toJSON() after managing converting Long into Number 

```js
function fixInt64(obj) {
    if(!obj)return;
    if(obj.hasOwnProperty('length')&&obj.length>0){
        for (var key in obj) {
            if (typeof obj[key] === 'object') {
                fixInt64(obj[key]);
            }
            if (obj[key] instanceof Long) {
                obj[key] = obj[key].toNumber();
            }
        }
    }else if (obj.$type) {
        for (var key in obj.$type.fields) {
            if (typeof obj[key] === 'object') {
                fixInt64(obj[key]);
            }
            if (obj[key] instanceof Long) {
                obj[key] = obj[key].toNumber();
            }
        }
    }
    return obj;
}

message = Message[_url].response.decode(new Buffer(data));
fixInt64(message);
message.toJSON()
```

**Comment by joel-duqiong** [comment]
![message](https://cloud.githubusercontent.com/assets/13653416/25140312/703be5a6-2492-11e7-938d-1d7e3583935b.png)

**Comment by joel-duqiong** [comment]
{"resultCode":"1000","resultMsg":"操作成功","traceNo":"18542301","tools":[{**"startTime":"1492061992000",**"forward":{"url":"yqbnative://app.1qianbao.com/pullbomb/index","id":"e5d365a0a36f4da980a2f48c57a74462","type":"native-link","name":"拉霸"},"id":"da0ddb09047a4504b7d1c051c851484e","type":"1021","toolName":"拉霸","image":{"id":"6f0e31a21a9c43448bca4394bc32ffc2","imgSrc":"v5/images/laba_coin1492062015212.png"},**"endTime":"0","sort":"1492062038393"**}]}

**Comment by joel-duqiong** [comment]
please help,thanks a lot in advance

**Comment by dcodeIO** [comment]
> protobuf.js version: "_nodeVersion": "6.9.1"

Looks like a node.js version. What's the version of protobuf.js you are using?

> treat Number as string when message.toJSON() after managing converting Long into Number

Is it correct to assume that the issue is that longs are not properly converted to strings but instead to numbers, by `Message#toJSON()`?

**Comment by joel-duqiong** [comment]
@dcodeIO "version": "6.7.3"

**Comment by joel-duqiong** [comment]
if not converting Long into Number,call Message#toJSON() and the result is the same (not correct)

**Comment by joel-duqiong** [comment]
blow is the part Message when managing converting Long into Number  
QueryServiceListResponse {
  tools: 
   [ CmsToolBean {
       id: 'da0ddb09047a4504b7d1c051c851484e',
       toolName: '拉霸',
       startTime: 1492061992000,
       endTime: 0,
       sort: 1492062038393,
       type: '1021',
       image: [Object],
       forward: [Object] },


but call Message#toJSON() or JSON.stringify ,and the result is below 
 {"resultCode":"1000","resultMsg":"操作成功","traceNo":"18542301","tools":[{"startTime":"1492061992000","forward":{"url":"yqbnative://app.1qianbao.com/pullbomb/index","id":"e5d365a0a36f4da980a2f48c57a74462","type":"native-link","name":"拉霸"},"id":"da0ddb09047a4504b7d1c051c851484e","type":"1021","toolName":"拉霸","image":{"id":"6f0e31a21a9c43448bca4394bc32ffc2","imgSrc":"v5/images/laba_coin1492062015212.png"},"endTime":"0","sort":"1492062038393"}]}

**Comment by joel-duqiong** [comment]
at last ,it's resolved!
after managing converting int64(Long) into Number,call Message#toObject() ,and then JSON.stringify with the object
