### ISSUE TITLE
Very minor jsdocs detail

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#765]
protobuf.js version: <6.7.3>

I noticed that after running jsdoc against the generated static code there is a generated link called "[ Top Level ]" which looks to launch a global.html page in the doc source directory, which doesn't get generated. 

I found that if I add the following to the generated static code I at least get a page generated. It isn't the best page, and I did play around with it a little bit to see if I could have a better suggestion, but nothing I tried was any better. That said, a relatively useless page is better than a page-not-found error

```js
/**
 * @global
 * @namespace
 */
var $root = $protobuf.roots["default"] || ($protobuf.roots["default"] = {});
```
Technically the @namespace didn't add anything, but I left it in. 

Cheers

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Is it correct to assume that you are using [this template](https://github.com/dcodeIO/jaguarjs-jsdoc)?

**Comment by ehallander9591** [comment]
That would appear to be the case.

...browsing...

**Comment by dcodeIO** [comment]
The original version of the template might be better suited for your use case. My forked version is, well, merely a monkey-patched version with specific protobuf.js things, like "top level".

**Comment by ehallander9591** [comment]
I may just ignore it for now. So far, no one from the folks I deliver to has brought it up. When I get some time I will give what you say a try.

Thanks
