### ISSUE TITLE
Incorrect RPCImplCallback type declaration

### ISSUE THREAD

**Issue by rossenassenov** [dcodeIO/protobuf.js#767]
protobuf.js version: 6.7.1

The current type declaration for RPCImplCallback leads to compile errors in TypeScript in strictNullChecks mode:
 
type RPCImplCallback = (error: Error, response?: Uint8Array) => void;

the "error" param should be optional:

type RPCImplCallback = (error?: Error, response?: Uint8Array) => void;

I opened a PR: https://github.com/dcodeIO/protobuf.js/pull/766

**Comment by dcodeIO** [comment]
Should be fixed in https://github.com/dcodeIO/protobuf.js/commit/23f4b990375efcac2c144592cf4ca558722dcf2d
