### ISSUE TITLE
Question: loading multiple proto files with multiples imports in each proto file

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#769]
Hello,

ProtoBuf version: 6.7.3

I am trying to build a protobuf object which later needs to be used for grpc.load function.
One of the proto files has import which contains proto file in different sub directory.

The below function does not seem to be resolving the path for import file and I get:
Error: no such type
      at Service.lookupType (node_modules/protobufjs/src/namespace.js:354:15)
      at Method.resolve (node_modules/protobufjs/src/method.js:138:45)

Am I missing something below ?

Params:
files - subdirectory path + filename
protoroot - main directory

```
function buildProtobuf(files, protoroot, logger) {
    // build protobuf
    let protoFilePath;
    const root = new ProtoBuf.Root();
    _.forEach(files, (fileName, key) => {
        const ok = root.files[fileName];
        if (ok) {
            return;
        }
        
        protoFilePath = protoroot + fileName;
        root.resolvePath = function(origin, target) {
        return protoFilePath;
        };

        root.loadSync(protoFilePath);
    });
    return root;
}
```

**Comment by dcodeIO** [comment]
Usage there is:

```js
const root = new protobuf.Root();
root.resolvePath = function(origin, target) {
  // origin is the path of the importing file
  // target is the imported path
  ... determine absolute path and return it ...
}
root.loadSync(files);
```

No need to call loadSync multiple times or to replace resolvePath per file.

**Comment by Arun-KumarH** [comment]
Seems to be an issue on grpc.loadObject() when the proto file references other proto files, closing this for now.
