### ISSUE TITLE
Why generated TypeScript definitions service method return type didn't contain Promise type?

### ISSUE THREAD

**Issue by laysdra7265** [dcodeIO/protobuf.js#770]
protobuf.js version: latest in master

<please describe the expected and actual behavior>
protofile:

```
service ClientService {
    rpc Search (result) returns (result)
    {
        option (local_method_id) = 1;
    }
    rpc echo (answer) returns (answer)
    {
        option (local_method_id) = 2;
    }
}
```
expected:
```
public echo(request: com.Protocol.Ianswer, callback?: ClientService_echo_Callback): void|Promise<com.Protocol.answer>;
```

actual 
```js
public echo(request: com.Protocol.Ianswer, callback: ClientService_echo_Callback): void;
```

**Comment by dcodeIO** [comment]
Seems JSDoc has stopped documenting because, well, I didn't add enough bullshit annotations and workarounds with undocumented side effects to the generated code's comments. Did that now.

**Comment by laysdra7265** [comment]
still not work ;(
It looks like jsdoc's problem?
look here
![image](https://cloud.githubusercontent.com/assets/10185394/25282515/4b143654-26e3-11e7-96d2-bb2c09f5c70d.png)

The memberof property not same cause second definitions for promise use it never be find by 'getChildrenOf()'
value should be 'com.Protocol.ClientService' not 'ClientService'
maybe can fix by add @memberof tag

**Comment by laysdra7265** [comment]
I fix the problem by replace the code:
'''js
 pushComment([
            method.comment || "Calls " + method.name + ".",
            "@function " + escapeName(service.name) + "#" + lcName,
            "@param {" + exportName(method.resolvedRequestType, !config.forceMessage) + "} request " + method.resolvedRequestType.name + " message or plain object",
            "@returns {Promise<" + exportName(method.resolvedResponseType) + ">} Promise",
            "@variation 2"
        ]);
'''
reaplace 'escapeName(service.name)' to 'escapeName(service.toString().split(' ')[1].substr(1))'
I'll make a pull request later.
