### ISSUE TITLE
How can I send my message in the browser?

### ISSUE THREAD

**Issue by gz65555** [dcodeIO/protobuf.js#778]
`MyMessage.encode(myMessage).finish()` is a Uint8Array. 

Should I use `uint8Array.buffer.slice(0, uint8Array.length)` to convert it to ArrayBuffer before sent it?

**Comment by dcodeIO** [comment]
If the API you use expects an ArrayBuffer, yes, but it's:

```js
var arrayBuffer = uint8Array.buffer.slice(uint8Array.byteOffset, uint8Array.byteOffset + uint8Array.length)
```
