### ISSUE TITLE
pbts: doesn't generate typings for Enums

### ISSUE THREAD

**Issue by SmaugTheGreat** [dcodeIO/protobuf.js#780]
protobuf.js version: 6.7.3

Using pbts doesn't actually generate typings for Enums. Accessing those requires an ugly construct such as `(<any>proto).ESomeEnum`

```
enum ESomeEnum {
	someValue = 0;
	someOtherValue = 1;
}
```

**Comment by dcodeIO** [comment]
This should be fixed in master. Actually, a lot of the typings stuff has changed (to the better) in 6.8.0.

**Comment by dcodeIO** [comment]
Feel free to reopen if this is still an issue!
