### ISSUE TITLE
Exclude docs from npm package?

### ISSUE THREAD

**Issue by dandv** [dcodeIO/protobuf.js#782]
Installing the module brings along the docs directory:

![image](https://cloud.githubusercontent.com/assets/33569/25688000/db828704-302f-11e7-90d1-4ee65d7452d0.png)

**Comment by dcodeIO** [comment]
protobuf.js 4.1.3 is super outdated.

[see also](https://github.com/dcodeIO/protobuf.js/blob/master/.npmignore#L7).
