### ISSUE TITLE
Load from URL

### ISSUE THREAD

**Issue by dakom** [dcodeIO/protobuf.js#783]
calling `protobuf.load("http://localhost:4000/file.proto");`

Appends the url onto the current server url, i.e. if my dev server is `http://localhost:3000` it is trying to load `http://localhost:3000/localhost:4000/file.proto`

**Comment by dakom** [comment]
Nevermind, I see that using a custom Root and overriding resolvePath fixes this. e.g.:

```let root:protobuf.Root = new protobuf.Root();
            root.resolvePath = (origin, target) => {
                return target;
            }

            protobuf.load(Path.GetConfigPath("config.proto"), root, function() {
                console.log(root.lookupType("game.Options"));
            });```

**Comment by pchandna24** [comment]
Hey @dakom  I am facing the same issue, instead of fetching the file on a different file server, I need to pass in a local system path. It works fine on a normal script but when I try do the same in my electron app. It adds the http://localhost:1212 in the beginning, can you help?

**Comment by pchandna24** [comment]
@joakimkonig Yes I did, I used the fs module to read the proto file as a string and then used protobufjs parse function to parse the string.
