### ISSUE TITLE
Namespace protobuf has no exported member Writer

### ISSUE THREAD

**Issue by omzmarlon** [dcodeIO/protobuf.js#788]
protobuf.js version: <6.7.3>

<please describe the expected and actual behavior>
ran pbjs and then pbts to generate typescript code, as instructed on http://dcode.io/protobuf.js/
Everything works until tsc compiler complains: namespace protobuf has no exported member Writer

For every piece of code that needs the Writer, compiler complains
```js
public static encode(message: com.managementapp.transfers.TokenDTO$Properties, writer?: $protobuf.Writer): $protobuf.Writer;
```

No stack trace. Just the compilation error

**Comment by omzmarlon** [comment]
It seems many other members are not found:
ConversionOptions, Reader

**Comment by dcodeIO** [comment]
Are you using `-t static`?

**Comment by omzmarlon** [comment]
I have used both -t static and -t static-modules.
Both have the same issue.
I'm actually using protobufjs for an Angular2 application, I have npm installed protobufjs and @types/protobufjs

**Comment by dcodeIO** [comment]
Might be because `@types/protobufjs` are v5 typings. v6 ships its own typings and doesn't use the `@types` namespace.

**Comment by omzmarlon** [comment]
So I should downgrade protobufjs to v5?

**Comment by dcodeIO** [comment]
You should not use `@types/protobufjs` with v6. Just use `index.d.ts` from protobuf.js 6 instead.

**Comment by omzmarlon** [comment]
Followed your instructions, everything worked!
Thanks a lot!!
