### ISSUE TITLE
Extension in multiple Files

### ISSUE THREAD

**Issue by mmolero** [dcodeIO/protobuf.js#791]
Hi All

I'm using protobuf.js version: 6.7.3 and I would like to know how to deal with extensions in protobujs when these are implemented in different protos files. 

I'm able to handle in C++ but I don't know how to deal with this in JS. 

----

For example:

**file1.proto**

```

syntax = "proto2";

option optimize_for = LITE_RUNTIME;

package message.one;

message MessageOne
{
   optional  int32  id = 1;
   extensions 2 to 1000;
}
```

**file2.proto**

```
syntax = "proto2";

option optimize_for = LITE_RUNTIME;

package message.two;

extend message.one.MessageOne
{
  optional CustomType payload = 2;
} 
```

If anyone knows how to proceed, it would be great!!!!
thanks in advance!!!

cheers

**Comment by dcodeIO** [comment]
Doesn't this work if you just load both files at once?

```js
protobuf.load([ "file1.proto", "file2.proto" ], ...
```

**Comment by mmolero** [comment]
Indeed I am using the bundle approach so that I only need to import a file.json generated using the CLI compiler pbjs. I am able to create the object however when I want to encode it, it does not work.

**Comment by dcodeIO** [comment]
And MessageOne has two fields `id` and `.payload` (note the leading dot referencing the fully qualified name)? Can you paste a snippet?

**Comment by mmolero** [comment]
Thanks, it was that!!
