### ISSUE TITLE
Passing from ByteBuffer to BufferWriter/BufferReader

### ISSUE THREAD

**Issue by Pomarom** [dcodeIO/protobuf.js#792]
protobuf.js version: 6.7.3

I'm currenlty migrating from protobuf.js 5.x to 6.x.
With the previous version, i used ByteBuffer to convert my inputs into specific typed datas : 

```js
// Create the ByteBuffer for String
new ByteBuffer(null, true).writeString(string);
...
// Read the ByteBuffer value
buffer.readString(buffer.limit - buffer.offset, ByteBuffer.METRICS_BYTES)
```
I'm understood that protobuf.js version < 6.x no longer use ByteBuffer, but should be used with the following : 

```js
// Create the BufferWriter for String
new BufferWriter().string(string).finish()
...
// Read the buffer value 
new BufferReader(buffer).string();
```
However, i used to use ByteBuffer with types such as ```js writeInt8(), writeUint8(), writeInt16(), writeUint16() ```

How can i use such type in ```js BufferWriter/BufferReader``` (not present in the API documentation) ?

Thanks in advance !
P.

**Comment by dcodeIO** [comment]
The reader/writer interface of protobuf.js 6 includes methods necessary to work with the protobuf wire format only. If you need these, you can just continue using ByteBuffer:

```js
var bb = ByteBuffer.wrap(MyMessage.encode(someObject).finish());
...
```

**Comment by Pomarom** [comment]
Okay, i guess i'll stick with ByteBuffer then.
Thanks !
