### ISSUE TITLE
decodeDelimited: TypeError: Cannot set property 'buf' of undefined

### ISSUE THREAD

**Issue by milgner** [dcodeIO/protobuf.js#794]
protobuf.js version: 6.7.3

`.proto` file encoded as an ES6 module.

Expected: `decodeDelimited(buffer)` returns a Message.

```
let message = MyMessage.decodeDelimited(buffer);
```

Instead it raises an error:
```
TypeError: Cannot set property 'buf' of undefined
    at Reader (node_modules/protobufjs/src/reader.js:28:14)
    at Function.decodeDelimited (my_message.js:192:56)
```

**Comment by masonk** [comment]
Wrap your buf in a Reader. If you have an `ArrayBuffer`, slap a `Uint8Array` over it too.
```
const reader = new protobuf.Reader(new Uint8Array(msg.data));
let pb = MyMessage.decodeDelimited(reader);
```

**Comment by milgner** [comment]
Thanks a lot, that helped! I only write Javascript every now and then but since that works, I guess the generated code must be missing a `new` before `$Reader`:

```javascript
    function decodeDelimited(reader) {
            if (!(reader instanceof $Reader))
                reader = $Reader(reader);
```

I'll see whether I can't locate the generator code in question and submit a PR...
