### ISSUE TITLE
using snake_case JSON as payload?

### ISSUE THREAD

**Issue by Rohithzr** [dcodeIO/protobuf.js#796]
protobuf.js version: 6.7.3

Using the following protobuf file

```protobuf
package dabster;
syntax = "proto3";

message ManyData {
    required bool success = 1;
    required string message = 2;
    required string type_type = 3;
    required string action = 4;
    required string id = 5;
    enum Corpus {
        UNIVERSAL = 0;
        WEB = 1;
        IMAGES = 2;
        LOCAL = 3;
        NEWS = 4;
        PRODUCTS = 5;
        VIDEO = 6;
    }
    Corpus corpus = 6;
}
```
and following json
```json
{
    "success": true,
    "message": "",
    "type_type": "connect",
    "action": "getUserConnections",
    "id": "null",
    "corpus": 0
}
```
as a payload below
```js
var errMsg = ManyData.verify(payload);
    if (errMsg)
        throw Error(errMsg);
```
should work just fine, instead it throws the following error
```sh
client.js:55
        throw Error(errMsg);
        ^

Error: typeType: string expected
    at Error (native)
    at /Users/rohithazra/Work/os/teade/example/client.js:55:15
    at finish (/Users/rohithazra/Work/os/teade/example/node_modules/protobufjs/src/root.js:94:9)
    at process (/Users/rohithazra/Work/os/teade/example/node_modules/protobufjs/src/root.js:122:13)
    at /Users/rohithazra/Work/os/teade/example/node_modules/protobufjs/src/root.js:181:17
    at fetchReadFileCallback (/Users/rohithazra/Work/os/teade/example/node_modules/protobufjs/node_modules/@protobufjs/fetch/index.js:51:19)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

now I see a `--keep-case      Keeps field casing instead of converting to camel case.` option that should in theory work, but i I feel clueless as to how to use it in Node.JS itself.

also I can make it work correctly (it seems) by changing the default to true at the following line
https://github.com/dcodeIO/protobuf.js/blob/master/src/parse.js#L5

but I am unaware as to why this is being done and does it cause an issue.

**Comment by dcodeIO** [comment]
Keep case is a parse time option:

```js
protobuf.Root.load("someFile.proto", { keepCase: true }, ...);
```

**Comment by Rohithzr** [comment]
@dcodeIO nice, it should be somewhere in the documentation though?

**Comment by dcodeIO** [comment]
[It is](http://dcode.io/protobuf.js/global.html#ParseOptions), but it's quite hard to spot because options are only accepted by `Root#load` and not by `protobuf.load`, which is merely a convenience function to get started quickly.
