### ISSUE TITLE
ES6 Static code import `protobufjs` isntead of `protobufjs/minimal`

### ISSUE THREAD

**Issue by kalitine** [dcodeIO/protobuf.js#798]
protobuf.js version: 6.7.3

**Actual behavior**

When generating static code with `es6` wrapping like so:
```shell
$pbjs -w es6 -t static-module message.proto > message.js
```

The `message.js` script imports `protobufjs`:
```js
import * as $protobuf from "protobufjs";
```

**Expected behavior**
The `message.js` script should import `protobufjs/minimal`, isn't it?

**Comment by dcodeIO** [comment]
Yeah, is hard coded [here](https://github.com/dcodeIO/protobuf.js/blob/master/cli/wrappers/es6.js#L1) but should be more like [here](https://github.com/dcodeIO/protobuf.js/blob/master/cli/wrappers/commonjs.js#L3).

**Comment by kalitine** [comment]
Ok, thanks. I'll send pull request, once back from vacation.
