### ISSUE TITLE
Bitshift in encoder

### ISSUE THREAD

**Issue by thomas-jeepe** [dcodeIO/protobuf.js#802]
Hello, this is just a question about your code.

In [your code for generating the encoder](https://github.com/dcodeIO/protobuf.js/blob/3f8b74ba6726567eaf68c4d447c120f75eac042f/src/encoder.js#L92), you use the bit shift operators to get the tag. I understand the left shift and OR gate to construct the tag with the last 3 bits being the wire type. The zero-filling bit shift to the right, however, confuses me. I don't quite see the purpose in shifting with no change. Normally this is done to convert a int to a uint, but I don't think that is possible with the code you have.

If you could tell me why you do it, that would be great.

**Comment by dcodeIO** [comment]
`>>> 0` casts the value to an unsigned 32-bit integer (it's the opposite of `| 0`, which casts to a signed 32-bit integer), so it just makes sure that the value doesn't wrap around to something negative.

**Comment by thomas-jeepe** [comment]
Thanks!
