### ISSUE TITLE
Filling bytes field from NodeJS with Buffer from Jimp image results in TypeError: Illegal Buffer

### ISSUE THREAD

**Issue by bvobart** [dcodeIO/protobuf.js#814]
protobuf.js version: inherited as a dependency through [grpc](https://www.npmjs.com/package/grpc)

For my bachelor project, I'm currently developing a NodeJS webserver that is supposed to communicate with a Python GRPC API server (which does some deep learning image analysis). I have a .proto file defining the following Request:
```protobuf
message Request {
	bytes image = 1; //Binary representation of the image to be analysed.
	FileType image_format = 2; //Image format (JPG / PNG)
	float scale = 3; //Size of a single pixel in meters.
}
```
I have created a factory method that creates a Request and fills it. This method reads an image and converts it to a binary buffer using [Jimp's getBuffer method](https://www.npmjs.com/package/jimp#writing-to-buffers) as follows:
```js
    createRequest: function (imageLoc, scale) {
        var promise = new Promise((resolve, reject) => {
            var request = new protoApi.bep.Request();
            
            Jimp.read(imageLoc).then(function (image) {
                request.image_format = getImageFormat(image.getMIME());
                image.getBuffer(image.getMIME(), function (err, data) {
                    if (err) throw err;
                    else {
                        request.image = data;
                        console.log("Resolving createRequest: ", request.image instanceof Buffer);
                        resolve(request);
                    }
                });
            }).catch(function (err) {
                console.error("PutIn: Error while reading image at: ", imageLoc);
                console.error(err);
                reject(err);
            });
        });

        return promise;
    }
```

Jimp tells me that the `data` object passed into `getBuffer`s callback is a Buffer, which I decided to confirm by checking whether `request.image` is now indeed also an instance of Buffer, which returns true. The Promise returned by this method is used as follows:

```js
RequestFactory.createRequest(imageLoc).then(function (request) {
	console.log("Request created.");
	api.analyseImage(request, function(err, result) {
		if (err) reject(err);
		else {
			console.log("PutIn: Got reply: ", result);
			ctx.body = `AnalyseImage method returned: ${JSON.stringify(result)}`;
			resolve(result);
		}
	});
}).catch(function (err) {
	console.error("Some error while creating request: ", err)
});
```

The problem occurs when the analyseImage method is called. I cannot copy the console output for some reason, but I've typed the important parts here:

```
Resolving createRequest: true
Request created.

Some error while creating request: TypeError: Illegal Buffer
    at Function.module.exports.ByteBuffer.wrap (/src/node_modules/bytebuffer/dist/bytebuffer-node.js:378:23)
    at Element.Protobuf.Reflect.ElementPrototype.verifyValue (/src/node_modules/protobufjs/dist/protobuf.js:1886:39)
    ....
    at Client.makeUnaryRequest [as analyseImage] (/src/node_modules/grpc/src/node/src/client.js:395:19)
    at /src/app.js:81:8
```

`app.js:81:8` refers to the call to `api.analyseImage(...)`. I have scoured the internet, tried to wrap `data` in a ByteBuffer before setting it to `request.image` (which completes without throwing an error) seeing as this is what Protobuf.js uses internally, but it keeps throwing the same exception for the same reason at the same location. 

I'm at wits end, what could be the problem here?

**Comment by dcodeIO** [comment]
For reference, the error seems to be thrown [here](https://github.com/dcodeIO/bytebuffer.js/blob/master/dist/bytebuffer-node.js#L346), suggesting that a `buffer` provided to `ByteBuffer.wrap` is either `null` or not of type `object`.

Following your typed stack trace, that's called [here](https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/src/ProtoBuf/Reflect/Element.js#L188). The `"base64"` parameter there is just provided in case it is a string.

Have you tried monkey-patching the respective dist files at these places to pinpoint what's the exact object (type) there?

**Comment by bvobart** [comment]
Thanks for your quick reply! The system runs in Docker containers, so I'm not really sure how I would go about monkey-patching those dist files, but I will see what I can do, perhaps by adding an operation to my Dockerfile which replaces `bytebuffer-node.js` with a locally modified one?

In the mean time, I've been trying a couple of things. First off I've tried testing whether `request.image` is `null` or not of type `object` at `resolve(request)` with `console.log("Resolving createRequest: ", request.image);`, which prints as expected:
```
Resolving createRequest:  <Buffer ff d8 ff e0 00 10 4a 46 blablablabla ... >
```
This would suggest that the `buffer` provided to `ByteBuffer.wrap` is of type `object` and not `null`. Then I realised that the operation `request.image = data` is probably done by reference and therefore it could possibly be so that the actual value of `data` is garbage collected before `ByteBuffer.wrap` is called, even though this would be rather quick for garbage collection. Therefore I tried to replace this operation with:
```
request.image = Buffer.alloc(data.byteLength);
data.copy(request.image);
```
Yet it still gave the same error as before...

**Comment by bvobart** [comment]
Woohoo, I've been able to fix my problem! The problem was the way I created the Request object: apparently the gRPC library cannot handle a Request object in the form `new protoApi.bep.Request()`, but only as a JSON object, as shown here:
```
var request = {image: data, image_format: imageFormat, scale: scaleRef};
```

Thanks for your help, and sorry to have been bothering you with this question as it seems the solution was not related to a problem in your Protobuf.js library, but rather to a problem in the gRPC library.
