### ISSUE TITLE
Should Message.encode error out when passed a non-object?

### ISSUE THREAD

**Issue by fiibbb** [dcodeIO/protobuf.js#815]
protobuf.js version: 6.1.1

Expected behavior:
`Message.encode` should error out when passed a non-object type

Actual behavior:
`Message.encode` does not error out when passed a non-object type

```js
> var proto = require('protobufjs')
undefined
> var idl = 'syntax = \"proto3\"; package test; message String { string value = 1; }'
undefined
> var protoRoot = new proto.Root()
undefined
> proto.parse(idl, protoRoot)
{ package: 'test',
  imports: undefined,
  weakImports: undefined,
  syntax: 'proto3',
  root:
   Root {
     options: undefined,
     name: '',
     parent: null,
     resolved: false,
     comment: null,
     filename: null,
     nested: { test: [Object] },
     _nestedArray: null,
     deferred: [],
     files: [] } }
> var stringMessage = protoRoot.lookup('test.String')
undefined
> stringMessage.encode({value:"hi"})
BufferWriter {
  len: 4,
  head:
   Op {
     fn: [Function: noop],
     len: 0,
     next: Op { len: 1, next: [Object], val: 10 },
     val: 0 },
  tail:
   Op {
     fn: [Function: writeStringBuffer],
     len: 2,
     next: undefined,
     val: 'hi' },
  states: null }
> stringMessage.encode("hi")
BufferWriter {
  len: 0,
  head: Op { fn: [Function: noop], len: 0, next: undefined, val: 0 },
  tail: Op { fn: [Function: noop], len: 0, next: undefined, val: 0 },
  states: null }
> %
```

As shown above, `Message.encode` simply returns a zero-length buffer when asked to encode a string `hi`. I'm wondering if this is intentional. Under what condition would passing a non-object to `encode` be useful? I personally find it a bit annoying to debug. Would like to hear about thoughts from the protobufjs team.

**Comment by dcodeIO** [comment]
This is a result from trying to reduce redundant assertions.

See also: https://github.com/dcodeIO/protobuf.js#toolset

Usual flow there should be to pre-check arguments on the application side or use `.verify`.
