### ISSUE TITLE
Chrome: DevTools failed to parse SourceMap: http://localhost:8383/0/js/vendors/protobuf.js/protobuf.js.map

### ISSUE THREAD

**Issue by woigl** [dcodeIO/protobuf.js#816]
protobuf.js version: 6.7.2

<please describe the expected and actual behavior>

**index.html**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="../js/vendors/protobuf.js/protobuf.js"></script>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>
```
**Google Chrome Alert:**
```
DevTools failed to parse SourceMap: http://localhost:8383/0/js/vendors/protobuf.js/protobuf.js.map
```
![screen shot 2017-05-31 at 21 56 29](https://cloud.githubusercontent.com/assets/17859431/26646290/11adf4bc-464c-11e7-99d7-81b2b57c285b.png)

What can I do to resolve this error? Is there something wrong with the map file in the version mentioned above?

Thanks in advance,
Stefan

**Comment by dcodeIO** [comment]
Hmm, not sure. Depends on what's wrong. I assume you double checked that the source map file actually exists, right?
