### ISSUE TITLE
Generated class definitions don't implement their corresponding interfaces

### ISSUE THREAD

**Issue by Alexendoo** [dcodeIO/protobuf.js#824]
protobuf.js version: 5f2f177682dcec21ec167dea587f601632036b8e

```proto
syntax = "proto3";

package people;

message Person {
  string name = 1;
}
```

Produces (some fields omitted)

```ts
import * as $protobuf from "protobufjs";

/** Namespace people. */
export namespace people {

    /** Properties of a Person. */
    interface IPerson {

        /** Person name */
        name?: string;
    }

    /** Represents a Person. */
    class Person {

        /**
         * Constructs a new Person.
         * @param [properties] Properties to set
         */
        constructor(properties?: people.IPerson);

        /** Person name. */
        public name: string;

        /* ... */
    }
}

```

Expected class definition:

```ts
class Person implements IPerson { /* ... */ }
```

**Comment by dcodeIO** [comment]
In this context, `IPerson` is the definition of a JSON object that can be supplied to the constructor of `Person`. It's not really an interface the class implements.

**Comment by Alexendoo** [comment]
It is, however Person *does* implement IPerson by way of having all the properties available, adding the explicit implements keyword would mean you can pass a Person to Person.encode() without having to resort to using type assertions:

```ts
const writer = Person.encode(Person)
```

instead of

```ts
const writer = Person.encode(Person as IPerson)
```

which does not provide type safety, as you can use `as` on any type

Alternatively, the signature of encode could be changed to 

```ts
public static encode(message: messages.ISigned | message.Signed, writer?: $protobuf.Writer): $protobuf.Writer;
```

**Comment by dcodeIO** [comment]
Hmm, I didn't have any issues with providing a Person to encode yet, because it still satisfies the interface, even if it doesn't explicitly implement it. The difference there is that, on the interface most properties are optional, while on the class these are on the prototype and thus always present.

**Comment by Alexendoo** [comment]
Ah my apologies I was looking at the wrong thing for the issue, it's that messages with `oneof`s aren't compatible with their interfaces (dupe of #808)
