### ISSUE TITLE
Question regarding parse method.

### ISSUE THREAD

**Issue by michax** [dcodeIO/protobuf.js#825]
protobuf.js version: 6.7.3

I was in need of parsing proto schemes stored as strings. However currently only exposed public method for parsing proto is load/loadSync method, which only accepts files or fetch requests. 

After reading protobuf implementation I've stumbled upon parse method, which works quite nicely. However I'm not sure if this method is currently intended to be 'public'. 

Why I care? Because I'm worried this method could be easily moved to different place in next versions.

So, ideally, could we make this method public and document it? I think it's pretty useful to be able to parse  proto from string, which allows for creating self sufficient web services, that provide client with proto schema during handshake.

What do you think?

**Comment by dcodeIO** [comment]
This method is intended to be public and also [documented](http://dcode.io/protobuf.js/global.html#parse).

**Comment by michax** [comment]
Great! Thanks. I've missed because it's not returned when you use search on api page.
And for example load/loadSync was.

**Comment by gilly3** [comment]
That documentation links gives a 404.

**Comment by gilly3** [comment]
[Found it](https://protobufjs.github.io/protobuf.js/global.html#parse2).

It looks like none of the global members turn up when searching the documentation.
