### ISSUE TITLE
Generated TypeScript message definition not compatible with message$Properties definition

### ISSUE THREAD

**Issue by bhouser** [dcodeIO/protobuf.js#826]
protobuf.js version: 6.7.3
Protobuf version: 3

<please describe the expected and actual behavior>
Generated TypeScript message definition not compatible with message$Properties definition.  It's not possible to (for example) pass a Token object as a parameter to Token.encode(token), since the types are incompatible.

Protobuf definition
```proto
message Token {
    google.protobuf.Any message = 1;
}
```

Generated Typescript definitions
```ts
type Token$Properties = {
    message?: google.protobuf.Any$Properties;
};

class Token {
    constructor(properties?: core.Token$Properties);
    public message: (google.protobuf.Any$Properties|null);
    public static encode(message: core.Token$Properties, writer?: $protobuf.Writer): $protobuf.Writer;
    public static encodeDelimited(message: core.Token$Properties, writer?: $protobuf.Writer): $protobuf.Writer;
    public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number): core.Token;
    public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): core.Token;
    public static verify(message: { [k: string]: any }): string;
}
```

Typescript error:
```
Error:(42, 37) TS2345:Argument of type 'Token' is not assignable to parameter of type 'Token$Properties'.
  Types of property 'message' are incompatible.
    Type 'Any$Properties | null' is not assignable to type 'Any$Properties | undefined'.
      Type 'null' is not assignable to type 'Any$Properties | undefined'.
```

I'm pretty sure it should be possible to assign an object of Type `Token` to an object of type `Token$Properties`.  This is however impossible, since `public message: (google.protobuf.Any$Properties|null);` is incompatible with `message?: google.protobuf.Any$Properties;`.  An optional field does not accept types which could be null.

I believe this is the same issue as described here:
https://github.com/dcodeIO/protobuf.js/issues/808

**Comment by bhouser** [comment]
I'm using protobufjs 6.7.3

**Comment by bhouser** [comment]
I forgot to mention: I have the TypeScript compiler flag `strictNullChecks` activated.  I encountered the issue after activating `strictNullChecks` in my project.  Without that flag, this problem disappears, since `null` can be assigned to any type.

**Comment by bhouser** [comment]
This is great.  Any prediction as to when this will land in an npm release?

**Comment by dcodeIO** [comment]
It's on npm as 6.8.0

**Comment by bhouser** [comment]
You're right, it is in 6.8.0.  I was under the impression that 6.8.0 was final before I posted this issue.  Terribly sorry about overlooking that!  Thanks!

**Comment by dcodeIO** [comment]
No worries, you're welcome! :)

**Comment by Alexendoo** [comment]
The types are still incompatible, example:

```
ERROR in ./src/registration.ts
(25,37): error TS2345: Argument of type 'Link' is not assignable to parameter of type 'ILink'.
  Types of property 'newDevice' are incompatible.
    Type 'INewDevice | null | undefined' is not assignable to type 'INewDevice | undefined'.
      Type 'null' is not assignable to type 'INewDevice | undefined'.
```

It's because of the presence of `null` rather than the lack of `undefined`

**Comment by bhouser** [comment]
I was about to re-file the bug but you beat me to it ;)

The change you made doesn't solve the problem I posted, but the Types are more accurate: the constructor for a given message can leave fields `undefined`, which is now reflected in the types.

But yes, the presence of `null` in the class prevents assignment to a variable with the interface type.
