### ISSUE TITLE
[TypeScript] Invalid codegen if message name starts with Object

### ISSUE THREAD

**Issue by mkosieradzki** [dcodeIO/protobuf.js#842]
protobuf.js version: 6.8.0

When message name starts with Object in every place where this type is returned lowercase version of message name is injected causing errors.

## Repro
Minimal proto file
```
syntax = "proto3";

message ObjectAsd {
}
```

Run following command: `pbjs my.proto -t static-module -w commonjs -es6 -o my.js && pbts my.js -o my.d.ts`

Output my.d.ts file will contain:
```js
public static create(properties?: IObjectAsd): objectAsd;
```
but should contain
```js
public static create(properties?: IObjectAsd): ObjectAsd;
```

**Comment by AndiDog** [comment]
I have the same problem and it was pretty easy to figure out the problem: https://github.com/dcodeIO/protobuf.js/blob/952c7d1b478cc7c6de82475a17a1387992e8651f/cli/lib/tsd-jsdoc/publish.js#L298

With context:

```
    // Convert plain Object back to just object
    name = name.replace(/\b(Object(?!\.))/g, function($0, $1) {
        return $1.toLowerCase();
    });
```

should probably read

```
    name = name.replace(/\b(Object\b(?!\.))/g, function($0, $1) {
```
