### ISSUE TITLE
In-Browser floats encode as zeros

### ISSUE THREAD

**Issue by lhartmann** [dcodeIO/protobuf.js#848]
System
======

protobuf.js version: 6.8.0
Firefox version: 53.0.3 64-bit
Chromium browser: 59.0.3071.104 
OS: Fedora 25, 64-bit

Expected Behaviour
=====

For this message:
```
message Robot_Command{
	required uint32	id = 1;			//! ID que define de qual robô é a comando
	required float left_vel = 2;	//! Velocidade da roda esquerda
	required float right_vel = 3;	//! Velocidade da roda direita
}
```
Running
```
var buff = encodeDelimited({left:vel: +0.2, right_vel:-0.2}).finish();
```
`buff` is supposed to be `Uint8Array [ 12, 8, 0, 21, 205, 204, 76, 62, 29, 205, 204, 76, 190 ]`

Actual behaviour
=====
`buff` is incorrectly set to `Uint8Array [ 12, 8, 0, 21, 0, 0, 0, 0, 29, 0, 0, 0, 0 ]`

**The bytes where the floats should be are all zero.**

Workaround
====
```
function writeFloatAt(buff, pos, val) {
	var f_tmp = new Float32Array(1);
	f_tmp[0] = val;
	
	var b_tmp = new Uint8Array(f_tmp.buffer);
	buff.set(b_tmp, pos);
}

var buff = encodeDelimited(...);
writeFloatAt(buff, 4, payload.left_vel);
writeFloatAt(buff, 9, payload.right_vel);
```

**Comment by dcodeIO** [comment]
This might be because you are using underscore case field names, but by default the library expects camel case.

```js
var buff = encodeDelimited({leftVel: +0.2, rightVel:-0.2}).finish();
```

**Comment by lhartmann** [comment]
Oh my! The library does variable name translation by default! That's completely unexpected.
Really cool feature, but having it enabled by default seems a bad choice! Several conflicts could arise:

`file.proto` => `file.js`
`left_vel` => `leftVel`
`leftVel` => `leftVel`
`Robot_Command` => `Robot_Command`

`Robot_Command` is a message type, not sure why it was kept unchanged.

Got it working with camelCase, though. Thanks.
