### ISSUE TITLE
field name with '_' in .proto file is not recognized when encoding and decoding

### ISSUE THREAD

**Issue by hunter1085** [dcodeIO/protobuf.js#854]
protobuf.js version: <please fill in>
6.8.0
<please describe the expected and actual behavior>
field name with '_' in .proto file is not recognized when encoding and decoding
```js
<please provide a code snippet for reproduction>
```
for example, lm.message.proto is as following:
package lm; 
syntax = "proto3";
message helloworld 
{ 
   required int32     id = 1;  // ID 
   required string    my_str = 2;  // str 
   optional int32     opt = 3;  //optional field 
}

writer.js is as following:

var protobuf = require("protobufjs");
var fs = require('fs');

protobuf.load("lm.message.proto", function(err, root) {
    if (err)
        throw err;

    var helloworld = root.lookupType("lm.helloworld");

    var payload = { id: 10,my_str: "helloworld" };

    var errMsg = helloworld.verify(payload);
    if (errMsg)
        throw Error(errMsg);

    // Create a new message
    var message = helloworld.create(payload); // or use .fromObject if conversion is necessary

    // Encode a message to an Uint8Array (browser) or Buffer (node)
    var buffer = helloworld.encode(message).finish();
    //console.log('buffer=',buffer.toString());
    fs.writeFile('./test.log', buffer, function(err) {
	    if(!err) {
	        console.log('done!');
	    }
	});

});

when run at helloworld.verify() ,it corrupt, protobuf.js assume the field should be "myStr"
```
<please paste the stack trace of the error if applicable>
```
hzh@hzh-VBox:~/node_test/rpc_test$ node writer.js 
/home/hzh/node_test/rpc_test/writer.js:14
        throw Error(errMsg);
        ^

Error: myStr: string expected
    at /home/hzh/node_test/rpc_test/writer.js:14:15
    at finish (/home/hzh/node_test/rpc_test/node_modules/protobufjs/src/root.js:95:9)
    at process (/home/hzh/node_test/rpc_test/node_modules/protobufjs/src/root.js:123:13)
    at /home/hzh/node_test/rpc_test/node_modules/protobufjs/src/root.js:182:17
    at fetchReadFileCallback (/home/hzh/node_test/rpc_test/node_modules/@protobufjs/fetch/index.js:51:19)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

**Comment by dcodeIO** [comment]
Might be helpful: https://github.com/dcodeIO/protobuf.js/issues/796
