### ISSUE TITLE
The change of "json-module"

### ISSUE THREAD

**Issue by yejinjian** [dcodeIO/protobuf.js#856]
[the change commit](https://github.com/dcodeIO/protobuf.js/commit/4eac28c7d3acefb0af7b82c62cf8d19bf3e7d37b)

why "json-module" default use " protobuf/minimal "?
"protobuf/minimal" did not have function "Root()"

**Comment by dcodeIO** [comment]
Related: https://github.com/dcodeIO/protobuf.js/issues/860
