### ISSUE TITLE
Alert user before leaving the page if page is touched. 

### ISSUE THREAD

**Issue by Paniraj2010** [dcodeIO/protobuf.js#868]
protobuf.js version: <please fill in>

<We have requirement where we have to alert user if page is touched, if use select different menu application should show alert with Yes or No if user continue to proceed then only redirect should occur else it should fall back to the same page. We have tried with ngOnDestroy but, application is redirecting to next page without showing Alert>

```js
<   ngOnDestroy()
    {        
        this.touched = this.eventForm.touched;
        if (this.touched)
            this.display = true;
    }>
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Doesn't seem to have any relation to protobuf.js. Maybe [ask here](https://stackoverflow.com/questions/tagged/angular).
