### ISSUE TITLE
Illegal buffer

### ISSUE THREAD

**Issue by loul42** [dcodeIO/protobuf.js#869]
Hi!

First, thank you for protobuf.js !

I just spent 3 hours trying to reverse engineer a buffer, (I read your how to and some other issues) but no success ...

Maybe you can guide me.

So via websocket I receive an arraybuffer : 
message.data : 
<Buffer 6a 02 20 0c 22 17 0a 15 08 8a 95 99 04 10 88 b0 c3 cb 05 1d cd 44 26 45 25 ba 6c 5f 3d>

When trying to decrypt it : 

```
protobuf.load("shop.proto", function(err, root) {
            if (err)
                throw err;
            var ShopUpdate= root.lookupType("ShopMarket.ShopUpdate");

            var message1 =  ShopUpdate.decode(message.data);
        });
```
Last line provoke this error : 

_C:\Project\node_modules\protobufjs\src\reader.js:47
        throw Error("illegal buffer");
        ^
Error: illegal buffer
    at Error (native)
    at create_typed_array (C:\Project\node_modules\protobufjs\src\reader.js:47:15)
    at create_buffer (C:\Project\node_modules\protobufjs\src\reader.js:69:19)_

I don't see why the decode part is not working. If you can help!

Thanks

**Comment by loul42** [comment]
Also the version encrypting the message is protobuf 5.01

The version I am using to decode is 6.8.1, could that be an issue ?

Thank you

**Comment by dcodeIO** [comment]
What type of object is message.data? If it is just an ArrayBuffer, try to wrap it in an Uint8Array before decoding.

**Comment by loul42** [comment]
Well... It was easy it's working !!
 Even if I don't understand why, thank you !!

**Comment by ryanerwin** [comment]
This was a very strange issues... Not sure why this isn't clearly included in the usage examples.
Casting my input variable from whatever is the browser's default type, explicitly to `Uint8Array` did work for me.

```javascript
                $.get("/rest/request/", function(data) {
                    var uint8data = Uint8Array.from(data)
                    var MyType = requestQueue.root.lookupType("my.type")
                    var decoded = MyType.decode(uint8data)
                });
```
