### ISSUE TITLE
Why would I use this repo instead of the JS outputted by the protobuf compiler when using `—js-out`?

### ISSUE THREAD

**Issue by jppgks** [dcodeIO/protobuf.js#889]
Just a question for clarification: Why would I use this repo instead of the JS outputted by the protobuf compiler when using `—js-out`?

**Comment by PavelBogatyrev** [comment]
protobufjs has Typescript support and may other options - like wrapper (commonjs, es6...) etc

**Comment by jppgks** [comment]
@PavelBogatyrev Thanks for your answer. Does it use protoc at its core and extend from its output? Or is it a complete rewrite?

**Comment by PavelBogatyrev** [comment]
@jppgks , welcome, 
no, it doesnt need protoc, it relies on proto syntax only

**Comment by jppgks** [comment]
I see. I’m surprised it is faster (according to the benchmark results) than the protoc generated JS.
