### ISSUE TITLE
Can the function "load" pass a File as a param

### ISSUE THREAD

**Issue by zD98** [dcodeIO/protobuf.js#892]
protobuf.js version: <please fill in>

<please describe the expected and actual behavior>

```js
<please provide a code snippet for reproduction>
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
If you are looking for a way to load a proto string, take a look at `protobuf.parse`. It returns a Root instance from a proto string.

**Comment by zD98** [comment]
Thx.
I want to load a protobuf `File` object. For example, I received a file from uploading, and I want to verify this proto file. 
Now I can only to load file at `protobuf.load( file.path )`，this is ok. But will it be better to load file with the `File` Object ?

**Comment by zD98** [comment]
I think my issue is not important. So I close it.
