### ISSUE TITLE
Using generated static javascript file with  uint64

### ISSUE THREAD

**Issue by ibreathebsb** [dcodeIO/protobuf.js#919]
protobuf.js version: 6.8.0

Hi, I'm using protobufjs in my project .
I use `pbjs` cli to generate a `.js` file from my `.proto` file, but I see that in my `.proto` file ,there are many keys defined as `uint64`. Do I have to include `long.js`  if i want to use static javascript file with `uint64` generated from `.proto` file?  sorry for my broken english...

**Comment by dcodeIO** [comment]
See: https://github.com/dcodeIO/protobuf.js#compatibility, paragraph "If a proper way to work with 64 bit values (uint64, int64 etc.) is required".

The library returns possibly unsafe numbers when long.js is not present, which is ok-ish if all your values are guaranteed to be smaller than 2^53-1.

**Comment by ibreathebsb** [comment]
how to include `long.js`?
I'm using `pbjs` to generate my static codec file, and the  npm scripts
in my`package.json` is like:
```json
"scripts": {
    "codec": "pbjs -t static-module ./src/proto/RM.XChat.proto -o ./src/codec/message.js"
  },
```
`RM.XChat.proto` file contains `uint64 ` fileds,  when I run `npm run codec`,It will generate a `message.js`  codec file.
