### ISSUE TITLE
Aggregate option syntax not supported

### ISSUE THREAD

**Issue by boolking** [dcodeIO/protobuf.js#95]
According official protobuf documentation, options can be written in aggregate syntax, so repeated field in option's message can be supported:

``` protobuf
import "google/protobuf/descriptor.proto";

message FooOption {
  optional int32 opt1 = 1;
  optional string opt2 = 2;
}

message FooOptions {
  repeated FooOption options = 1;
}

extend google.protobuf.FieldOptions {
  optional FooOptions foo_options = 1234;
}

// usage:
message Bar {
  // alternative aggregate syntax (uses TextFormat):
  optional int32 b = 2 
  [(foo_options) = {options { opt1: 1234 opt2: "baz" } options { opt1: 4321 opt2: "foo" }} ];
}
```

Official protobuf parser implemented text format parser and use it in aggregate option syntax parsing.

**Comment by w4-sjcho** [comment]
Hi,

Is there any progress in this? The aggregate syntax is also described here, at the bottom of the custom options section:
https://developers.google.com/protocol-buffers/docs/proto#customoptions

**Comment by callmehiphop** [comment]
/bump

has any progress has been made on this?

**Comment by dcodeIO** [comment]
Just thought I could do it and gave it a try, but I then realized that this is one of the edges where the initial custom design bites back. The internal workings of ProtoBuf.js do not rely on any descriptors to be present and thus it just parses any options "as is". In this exact case however, there is no way to know whether an option is repeated or something. It can probably be done, though, but that old code gives me headaches.

**Comment by dcodeIO** [comment]
Works now:

```protobuf
optional string desc3 = 4 [(foo_options) = { opt1: 123 opt2: "baz" }];
```

Parses now, but exposes just the last array-option element:

```protobuf
optional string desc4 = 5 [(foo_options) = {options { opt1: 1234 opt2: "baz" } options { opt1: 4321 opt2: "foo" }} ];
```

**Comment by dcodeIO** [comment]
The later now also works, but as it doesn't know what exactly is repeated, it just converts duplicate options to arrays. The result is:

```json
{
  "(foo_options).options.opt1": [1234, 4321],
  "(foo_options).options.opt2": ["baz", "foo"]
}
```

**Comment by callmehiphop** [comment]
awesome! :+1:

**Comment by AmandaCameron** [comment]
This doesn't seem to work with options defined in imported files, not under Proto3 at least. I can whip up a sample tomorrow if you'd like, just thought I'd comment now. :)

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
