### ISSUE TITLE
the import problem

### ISSUE THREAD

**Issue by ycllz** [dcodeIO/protobuf.js#954]
i create file "template.proto", this file import "templateVO.proto" file, and i load the file "template.proto", but throw excception : throw Error("unresolvable field type: " + this.type + " in " + scope); . how can i do? and i donot want to copy the file "templateVO.proto" content into "templateVO.proto". thank u so much!

the "templateVO.proto" file content:
//template
import "templateVO.proto";
package template;
syntax = "proto3";

message user_login{
	required int32 userId = 1;
	required string userName = 2;
	repeated int32 ids = 3;
	required DataTempVO vo = 4;
}

the "templateVO.proto" file content:
//template
package proto;
syntax = "proto3";

message DataTempVO {
	optional string key=1;
	optional string value=2;
}

if i want to load ".proto" files, and the ".proto" files be encrypt, how can i do? can i use the file content, a string , to create a message ?

**Comment by dcodeIO** [comment]
> can i use the file content, a string , to create a message ?

Sure:

```js
var root = new protobuf.Root();
protobuf.parse(sourceString, root);
```

The above parses a .proto source to the `root` instance. If the file has imports, you might also want to examine its result:

```js
var result = protobuf.parse(sourceString, root);
if (result.imports) {
  result.imports.forEach(file => {
    protobuf.parse(getSourceOf(file), root);
  });
}
```

As always, it might be better to bundle your .proto files to a .json bunddle beforehand using the `pbjs` CLI, instead of crafting custom loading code using the above functionality.

**Comment by ycllz** [comment]
thank you, it works.
