### ISSUE TITLE
npm package for 6.8.1 no longer has dist directory.

### ISSUE THREAD

**Issue by jrburke** [dcodeIO/protobuf.js#955]
protobuf.js version: 6.8.1

The npm package for version 6.8.0 would get installed on disk with a dist/ directory in it that had the browser builds of protobuf.js. However, 6.8.1 no longer has the dist/ directory.

Is this by design or is it an `npm publish` error?

**Comment by dcodeIO** [comment]
This is due to fixing #781 in https://github.com/dcodeIO/protobuf.js/commit/a8376b57fb0a858adff9dc8a1d1b5372eff9d85c including just the relevant files for npm usage.  Do you need the dist files in there?

**Comment by jrburke** [comment]
I can appreciate wanting to remove extra files from the npm package, like tests. For the dist/ files, that gets into what you want to support for the npm package in relation to front end/browser usage.

It is becoming more common for front end projects to use npm to manage their dependencies, and we were definitely using it that way for an ember project. I can see two pathways if you wanted to support npm packaging for front end protobufjs files:

1) Keep the dist/ directory in the main protobufjs npm package.
2) A separate npm package that only has the dists/ files in it for front end use.

I vote for 1) to keep it easy on publishing, but I am happy to use either. 

Alternatively, if you do not think there should be an npm package for the built, front end protobufjs files, suggestions on how I might get versioned files I can download into my project is appreciated. Referencing it at runtime on the CDN is not an option for me because it is bundled with other modules for deployment.

**Comment by dcodeIO** [comment]
Ok, 6.8.2 has the dist files again.

**Comment by jrburke** [comment]
Thank you very much! Confirmed that it works for my use case.
