### ISSUE TITLE
Issue regarding underscores.

### ISSUE THREAD

**Issue by maxkunes** [dcodeIO/protobuf.js#959]
protobuf.js version: 6.8.3 (? downloaded from npm yesterday)

When the variable in this case "int32 id_number = 1;" has an underscore, protobuf.js is not able to set it when used like this. Basically by changing the variable id_number to idnumber in both the proto and javascript file, everything works as expected. Is this some sort of expected behavior I'm not understanding, or is this a bug?
```js
var staticRadarMessage = root.lookupType("radarpackage.MsgRadar");

var idMsg = staticRadarMessage.create( 
 {
    msgType:1,
    sendIdMessage: { id_number:55}
});

```

In this code, the proto field id_number will not be set.
If I were to console.log the object idMsg, it would result in this 

> MsgRadar { msgType: 1, sendIdMessage: { id_number: 55 } }

If I were to verify, serialize the data to a buffer and then decode that buffer, the result when console.log would be this

> MsgRadar { msgType: 1, sendIdMessage: MsgSendId {} }

When making the necessary modifications 

> Basically by changing the variable id_number to idnumber in both the proto and javascript file, everything works as expected.

Those same console results from before result as one would expect

> MsgRadar { msgType: 1, sendIdMessage: { idnumber: 55 } }

> MsgRadar { msgType: 1, sendIdMessage: MsgSendId { idnumber: 55 } }

**Both versions "verify" correctly **

Relevant .proto definitions

```js
syntax = "proto3";
package radarpackage;

message MsgRadar {
     MessageType msgType = 1;
     MsgSendId sendIdMessage = 2;
}

message MsgSendId {
    int32 id_number = 1;
}

```

**Comment by dcodeIO** [comment]
By default, field names are converted to camel case notation. `id_number` becomes `idNumber`. This behavior can be overridden [here](https://github.com/dcodeIO/protobuf.js/blob/master/src/root.js#L75) by providing the option `keepCase: true` ([see](https://github.com/dcodeIO/protobuf.js/blob/master/src/parse.js#L43)).

**Comment by maxkunes** [comment]
@dcodeIO how does one do that?

I tried like so, but this is not working

> protobuf.load("radarcomm.proto",{keepCase: true},function(err, root) {

**Comment by dcodeIO** [comment]
Just do this instead:

```js
var root = new protobuf.Root();
root.load("radarcomm.proto", { keepCase: true }, function(err) {
  ...
});
```

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by bitmage** [comment]
Can you please document this choice in your README?  I found it very confusing.  There's no errors when I get it wrong, just silent failure to set/get fields.

I see the [style guide for protobufs](https://developers.google.com/protocol-buffers/docs/style) recommends using underscores for field names in the definitions, and gives the Java example in camel case.  So I guess we are following that.  But it would be nice to know this upfront about the library.

**Comment by zyfyy** [comment]
> Just do this instead:
> 
> ```js
> var root = new protobuf.Root();
> root.load("radarcomm.proto", { keepCase: true }, function(err) {
>   ...
> });
> ```

it works!

**Comment by markotom** [comment]
Why we can't use just:
```
profobuf.load("radarcomm.proto", { keepCase: true }, function(err) {
  ...
});
```
Can anyone explain it?

**Comment by Neofield-Dylan** [comment]
I am using protobufjs 7.2.4 and I am having this issue missing snake case fields after decoded message.
Does protobufjs 7 still has this issue ?
I tried to use the mention solution
`protobuf.loadSync('myProtoFile.proto', {keepCase: true});`

But I receive a typescript error: `Object literal may only specify known properties, and 'keepCase' does not exist in type 'Root'.`

Can anyone help me, please ?
