### ISSUE TITLE
Error: illegal buffer with Uint8Array

### ISSUE THREAD

**Issue by yangyongh** [dcodeIO/protobuf.js#963]
First, thanks for protobuf.js 

protobuf.js version: 6.8.3

There is an illegal buffer error when I decode the message which is got from MQService.
The code as flowing :
onCtlMessageArrived : function(message){
    console.log(message.payloadBytes); //console print : Uint8Array(289) [10, 11, 48, 49, 48, 48,....]
    try{
        // var reader = protobuf.Reader.create(message.payloadBytes);
        // MessageService.ResponseMsg was got with root.lookupType("ResponseMsg") , it's right.
        responseMsg = MessageService.ResponseMsg.decode(message.payloadBytes) ;
    }catch(e){
        console.log(e) ;
        // console print : 
        // Error: illegal buffer
        //    at Function.create_typed_array [as create] (protobuf.js:4712)
        //    at Type.ResponseMsg$decode [as decode] (eval at Codegen (protobuf.js:283), <anonymous>:5:12)
        //    at Type.decode_setup [as decode] (protobuf.js:6670)
        //    at Object.onCtlMessageArrived [as onArrived] (status.js:485)
    }

I add debug code at line 4707 of protobuf.js as flowing:
var create_array = typeof Uint8Array !== "undefined"
    ? function create_typed_array(buffer) {
		console.log(buffer) ;   // Uint8Array(289) [10, 11, 48, 49, 48, 48,....]
		console.log(buffer instanceof Uint8Array) ;   // false
		console.log(Array.isArray(buffer)) ;    //false
        if (buffer instanceof Uint8Array || Array.isArray(buffer))
            return new Reader(buffer);
        throw Error("illegal buffer");
    }
    /* istanbul ignore next */
    : function create_array(buffer) {
        if (Array.isArray(buffer))
            return new Reader(buffer);
        throw Error("illegal buffer");
    };

**Comment by yangyongh** [comment]
There is no error for encoding, and MQService decode successfully.
encode result is : Uint8Array(129) [10, 13, 49, 53, 49, 51, 55, 52, 48......]

**Comment by yangyongh** [comment]
sorry for wrong operation make the issue closed.

**Comment by dcodeIO** [comment]
```js
console.log(buffer) ; // Uint8Array(289) [10, 11, 48, 49, 48, 48,....]
console.log(buffer instanceof Uint8Array) ; // false
```

Any idea how this happens?

**Comment by yangyongh** [comment]
I was puzzling over that too. 
`.....`
`var msg = MessageService.ResponseMsg.encode({`
`    id: 2,`
`}).finish();`
`MessageService.ResponseMsg.decode(msg);  // successful`
`......`
with above code, debug log print is looked right, as flowing:
console.log(buffer) ; // Uint8Array(38) [10, 0, 18, 3, 97, 98, 99, 26.....]
console.log(buffer instanceof Uint8Array) ; // true 
console.log(Array.isArray(buffer)) ; // false

I am verifying how did the message create, but I do not think it made instatceof to false .

**Comment by yangyongh** [comment]
I checked 'message.payloadBytes' befor decode.
`console.log(message.payloadBytes instanceof Uint8Array) ; // print true `
is there any operation make parameter to change ?
I used paho-mqtt V1.0.2 to receive message.

**Comment by dcodeIO** [comment]
Are you using node.js? If so, what's your node version?

**Comment by yangyongh** [comment]
No, I am not using node.js.

**Comment by yangyongh** [comment]
I found the cause why instanceof Uint8Array was false. 
I build MessageService.ResponseMsg object in parent page, and received message in another page which was include with iframe. 
instanceof operator uses === to compare MessageService.ResponseMsg.__proto__ with Uint8Array.prototype , so two Uint8Array in two pages are different.
I read message.payloadBytes to a new Uint8Array object in parent page , it's working well.
`var content = new Uint8Array(message.payloadBytes,0,message.payloadBytes.length);`
