### ISSUE TITLE
Exception Loading Root with JSON Descriptor containing Enums 

### ISSUE THREAD

**Issue by dharmusharma1981** [dcodeIO/protobuf.js#964]
protobuf.js version: <6.8.3>

<please describe the expected and actual behavior>
Exception 
ExceptionsManager.js:65 (intermediate value)(intermediate value)(intermediate value) is not a function
<please provide a code snippet for reproduction>
```
Im trying to load json file which contains enums
` "PlatformType": {
      "values": {
        "UNKNOWN": 0,
        "RAY_DESKTOP": 1,
        "RAY_MOBILE": 2
      }
    },

after drilling down the code 

i find this Enum.fromJson is undefined in the libarary
![screen shot 2017-12-21 at 2 30 46 pm](https://user-images.githubusercontent.com/10889920/34277738-e9c17c52-e65b-11e7-927a-a5addfcca539.png

<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
That's strange, [Enum.fromJSON](https://github.com/dcodeIO/protobuf.js/blob/master/src/enum.js#L74) should be there.

**Comment by dharmusharma1981** [comment]
im using react native,
Used pbjs to convert proto to json format

**Comment by dcodeIO** [comment]
> im using react native

I see. There have been similar issues in the past and iirc these are caused by recursive dependencies in the sources that only react native isn't able to solve for some reason. This can be solved, usually, but requires checking all the dependencies. Have you tried using the dist files instead?

**Comment by dharmusharma1981** [comment]
dist files work fine

**Comment by adambom** [comment]
I'm seeing this as well (version 0.51.0 of react-native). The circular dependency arises when namespace.js requires enum.js and enum.js requires namespace.js.

@dharmusharma1981 how were you able to import the dist files into the app?

**Comment by adambom** [comment]
Downgrading to version 6.8.0 worked for me (I was on 6.8.3).

**Comment by LeonardPauli** [comment]
for quick fix until PR merged:

`yarn add LeonardPauli/protobuf.js#964-enum-circular-dep-react-native`

(in essence 7 char diff from 6.8.6)

**Comment by pbaer** [comment]
@dcodeIO any plans to merge this PR? We are blocked from using protobufjs in React Native due to this issue.
