### ISSUE TITLE
Is there any version that doesn't use Function and Function.apply?

### ISSUE THREAD

**Issue by faace** [dcodeIO/protobuf.js#967]
protobuf.js version: 6.8.1

In some environment，
Function is Not support, so error occurs when Codegen() is called，

Is there some way to avoid to use Function?

**Comment by dcodeIO** [comment]
Have you tried to use statically generated code instead? This basically runs the codegen step ahead of time.

**Comment by faace** [comment]
Not yet. Do you mean to use command line to generate the JS file to run?
