### ISSUE TITLE
Create message from JSON data

### ISSUE THREAD

**Issue by peteh02** [dcodeIO/protobuf.js#970]
protobuf.js version: 6.8.4

I'm trying to create a message from JSON data (without default values). This JSON data is currently sent from a Server Backend. With an older version (pre v6.X), I was able to load the data with the decodeJSON() method. 

This method isn't available any longer, so I'm wondering how to proceed.

My Proto file looks something like this

```
syntax = "proto3";
package mypkg;

message ObjectInformation {
    repeated Object objects = 1;
    message Object {
        string id = 1;
        string name = 2;
        uint32 order = 3;
    }    
}
```
I load it this way

```js
define("MyModule", ["protobufjs"], function(ProtoBuf) {
	var ObjectInformationType = null;
	ProtoBuf.load(myProtoFile).then(root => {
        	 ObjectInformationType = root.lookupType("mypkg.ObjectInformation");
        };
        // ...
}
```
My JSON data is basically the whole message information minus default values

`var msg = {"objects": [{"id": "Object1","name": "Object 1","order": 1}]}`

```js
var obj = ObjectInformationType.create(msg);
console.log(obj);
```
gives me
`Object { 0: "{", 1: "\"", 2: "o", 3: "b", 4: "j", 5: "e", 6: "c", 7: "t", 8: "s", 9: "\"", … }`

Continuing with

```
var encoded = ObjectInformationType.encode(obj).finish();
var decoded = ObjectInformationType.decode(encoded);
console.log(decoded);
```
gives me

`Object { objects: [] }`

With the older protobufjs version, I was able to create and access a message successfully as follows:

```js
try {
   var proto = ObjectInformationType.decodeJSON(msg);
} catch (err) {
    console.error("Failed to parse message received from server: "
          + err.message);
    return;
}
var objects = proto.getObjects();
```

Any ideas appreciated! Thanks!

**Comment by dcodeIO** [comment]
Have you tried `ObjectInformationType.fromObject(msg)`?

**Comment by peteh02** [comment]
Hi,
thanks for the hint. I tried fromObject(), I get a valid message; however, with objects length 0. 
So maybe something else is expected in the JSON data? 
With decodeJSON() it worked fine.

```js
{…}
   objects: []
       length: 0
       __proto__: Array []
   __proto__: {…}
       "$type": Object { name: "ObjectInformation", resolved: false, filename: "./proto/messages.proto", … }
       constructor: function ObjectInformation()
       initialPosition: null
       objects: Array []
       __proto__: Object { toJSON: [21]</r.prototype.toJSON(), … }
```

**Comment by dcodeIO** [comment]
What about `ObjectInformationType.fromObject(JSON.parse(msg))`?

**Comment by peteh02** [comment]
Thanks a lot, JSON.parse() did the trick!

**Comment by sanderpick** [comment]
I landed here searching for a `fromJSON` method. I have a server that returns JSON representations of protobuf objects. In some cases, the JSON value is not what the plain object value would be, e.g., a timestamp. JSON format is an ISO string, object format is the protobuf time object with a seconds and nanos field. So, if one was to use the plain JS object parsed from JSON with `fromObject`, you would not get a valid message, or at least, the timestamp would not come though.

In Golang this is solved with the jsonpb package: https://godoc.org/github.com/golang/protobuf/jsonpb. You would unmarshal the JSON into a protobuf object.

Do you think something like this could work here?

**Comment by mohajerimasoud** [comment]
Have anybody found a way to solve this issue ?
