### ISSUE TITLE
API stability between versions, along with ByteBuffer

### ISSUE THREAD

**Issue by astoeckley** [dcodeIO/protobuf.js#971]
protobuf.js version: 2

I inherited a code base that uses V2 of this library from a few years ago. I'd like to upgrade at least the library, but it looks like the current API is different from V2, and I don't want to make code changes just yet. In looking through the branches, it *appears* that up to version 5 used the same api as V2, is that right? Because the examples/ directory did not change between those versions. Is that a safe bet, should I go with V5 or are there not enough reasons to upgrade necessarily? If I do upgrade, which version of ByteBuffer should I use?

**Comment by dcodeIO** [comment]
> it appears that up to version 5 used the same api as V2, is that right? 

Iirc, somewhat, yeah. Though, some internals changed over time, incl. between bytebuffer.js versions.

> If I do upgrade, which version of ByteBuffer should I use?

The one in protobuf.js's package.json at that time.

**Comment by astoeckley** [comment]
Thanks. Version 2 has been very fast and stable for years on the code base without any issues. Awesome! But that also means there is hesitancy to upgrade to a new version in the absence of clear issues with V2. Can you comment on what might have changed in the implementation between V2 and V5 or even the current version to convince an upgrade?

**Comment by dcodeIO** [comment]
Up to v5 there's mostly compatibility fixes and new features, while v6 is a complete rewrite focusing on improving the API and (much better) performance.
