### ISSUE TITLE
could this tools generate a has_xxx() function for every optional fields?

### ISSUE THREAD

**Issue by yyf1990cs** [dcodeIO/protobuf.js#977]
I use a lot of optional fields in my game to update gameplay units. like hp, speed...
and my code like this: 

_if(updateMsg.hasOwnProperty("speed"))
{
      unit.speed = updateMsg.speed;
      //do update unit....
}_

because the _prototype.speed = 0_, so if I read the property by _updateMsg.hp_ ,I'll got 0, and I dont know if the unit's speed is setted to 0 or dosen't changed.

but the code like above is bad for maintenance bucause of the string "speed" wont throw an error if the field name changed and then mismatched.

so could this tools generate a function for every optional fields like:

_function hasSpeed()
{
    return this.hasOwnProperty("speed")
}_

or just provide a cmd param like
--default null instead of 0/empty-string
to make the _prototype.speed = null_ so that I can use _if(msg.speed != null)_ to see if the field is setted.

thank you.

**Comment by dcodeIO** [comment]
`hasOwnProperty` is actually the intended way to check this condition because it is basically free as it doesn't add to code size. From your description I understand that you might maybe just be missing an assertion somewhere that the `speed` field didn't change its name for some reason?

One example would be to extend the Unit prototype:

```js
const UnitType = root.lookupType("Unit");

const F_SPEED = "speed";
assert(UnitType.fields[F_SPEED]);

UnitType.ctor.prototype.hasSpeed = function() {
  return this.hasOwnProperty(F_SPEED);
}
```

**Comment by yyf1990cs** [comment]
Thank you for reply.
I know the assert() could be a good method to detect the field name change.

My problem is , Once my server-side partners changes the `*.proto` files' optional field, such as `hp` -> `hitpoint`, and I generate `*.js` and `*.d.ts` files by this tools, the IDE can throw an error at the position where I typed `unit.hp` by typescript's syntax checker, but those codes like `unit.hasOwnProperty("hp")` or `const F_HP = 'hp'` in my project wont be detected and those codes were actually meaningless.

I try to get a way to detect and resolve these problems before the app being complied, not using a assert function to crash the app on the fly.

**Comment by dcodeIO** [comment]
I see. What about a simple NOP to detect this case? Should result in a TS2339 error (Property 'hp' does not exist on type 'Unit'.) when compiling:

```js
Unit.prototype.hp;
```

**Comment by yyf1990cs** [comment]
![qq 20180124121248](https://user-images.githubusercontent.com/26414146/35314265-f9c964d4-00ff-11e8-9a48-834f25bb5dc7.png)

look at this case.
the code at Line108 & 109 can report an error, so I can easly fix those codes.
But the Line 113's error will be hidden and maybe sometimes I'll forget to fix it.

Unless there is a defination like 
`const UNIT_UPDATE_FIELD.HP = "hp";`
in the generated files,
then I can use
`unit.hasOwnProperty(UNIT_UPDATE_FIELD.HP)`

once the hp changes to hitpoint, the generated defination will be 
`unit.hasOwnProperty(UNIT_UPDATE_FIELD.HITPOINT)` 
automatically.

and my code
`unit.hasOwnProperty(UNIT_UPDATE_FIELD._HP_)`
will report an error.

**Comment by dcodeIO** [comment]
What about...

```js
CreatureUpdate.prototype.hasHp = function() {
  this.hp;
  return this.hasOwnProperty("hp");
}
```

`this.hp` will be optimized away anyway by either TSC or the VM.

**Comment by yyf1990cs** [comment]
yes the best solusion maybe wirte the field name string "hp" very close to the .hp like this , so I hardly to  forget to fix it.

And this function is what I want at the issue title, I wonder if the tools cound automatically gen this function. Because optional field is used frequently in my project, so I have to type those boring "has" functions by my self。

**Comment by dcodeIO** [comment]
The tools certainly can, but I'd prefer not to add this so others not requireing this functionality won't get additional code they don't actually need. Changing definitions are relatively unusal for a couple of reasons. Also, even if the other side changes the name of a field, this doesn't matter for your side as long as the other end is still using the same id. And these really shouldn't change.

**Comment by yyf1990cs** [comment]
yes, I can understand , for others not requireing this, it'll be a redundant function.
could the function be a default-off and can turn on by commandline param?

If it's hard to add a function that may be a redundant function in this tools, It dosent matter.
Because I found a way to resolve it thanks for our above discusion, I can make a file parser that run after your tools be executed in bat command, using regexp to read the optional field in every proto files , and generate a simple FieldName.ts class file which maybe like this: 
`const UNIT_UPDATE_FIELD.HP = "hp"` 
`const UNIT_UPDATE_FIELD.SPEED = "speed"` 
`const ............` 

and replace every string in `hasOwnProperty("string")`  to these const variable 
`hasOwnProperty(XXX_FIELD.NAME)`.

Once someone changes the fieldname, the FieldName Class will alse be re-generated and I will got the error.

**Comment by dcodeIO** [comment]
You could also use the reflection API to obtain all sorts of information from a proto file in your build step, while still generating static code from your protos. You don't have to parse manually.

For instance, when loading a .proto file dynamically, you'll get a `Type` for each message with a `fields` property that holds all the type's fields by name.

**Comment by yyf1990cs** [comment]
Yes, I can handle this myself.  
I'll close this issue.
thank you for your advice.
