### ISSUE TITLE
edcode result has a buffer of 8192bytes?

### ISSUE THREAD

**Issue by Bulala-liu** [dcodeIO/protobuf.js#978]
protobuf.js version: <please fill in>
6.8.6
<please describe the expected and actual behavior>
after encoding a message, I get a Unit8Array(36), I want get the exact Arraybuffer, but the buffer byteLength is 8192. so the backEnd cannot parse the message as expected.
```js
`WSMessage = root.lookupType("message.LoginRequest");
var wsmessage = WSMessage.create({token: 'd43f28d212544ee98d21b3af378e480e', platform: 1});
var message_send = WSMessage.encode(wsmessage).finish();
console.log( message_send.buffer);
// Uint8Array(36), buffer:ArrayBuffer(8192)`
```

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Similar issue: https://github.com/dcodeIO/protobuf.js/issues/852

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
