### ISSUE TITLE
Can't npm install protobufjs

### ISSUE THREAD

**Issue by chevin99** [dcodeIO/protobuf.js#979]
Not sure if this is the best place to report this, but protobufjs doesn't seem to be install-able via npm (this example is with npm 5.6.0):

```
$ npm i protobufjs
npm ERR! code E404
npm ERR! 404 Not Found: @protobufjs/utf8@^1.1.0

npm ERR! A complete log of this run can be found in:
```

I'm guessing it's related, but it looked a little fishy on the npm page that there's 0 downloads in the last day and 240k+ in the last week:

<img width="987" alt="screen shot 2018-01-24 at 12 44 41 pm" src="https://user-images.githubusercontent.com/7562346/35353584-d8d61ce0-0104-11e8-8ac7-cbb48b78162b.png">

**Comment by dcodeIO** [comment]
Hmm, the package exists, actually: https://www.npmjs.com/package/@protobufjs/utf8

**Comment by chevin99** [comment]
Interesting 🤔 So are you able to download it ok then @dcodeIO ?

**Comment by dcodeIO** [comment]
Just checked, yes, I can install it.

**Comment by chevin99** [comment]
Whoa, something's strange.  It shows a different package isn't found each time I try it.

![install](https://user-images.githubusercontent.com/7562346/35354242-b2eff5bc-0106-11e8-9d87-45e40eed7fe0.gif)

**Comment by dcodeIO** [comment]
Does this only happen with scoped (@protobufjs) packages?

**Comment by chevin99** [comment]
Looks like it is only happening on scoped packages.  Others I've tried are ok.

**Comment by dcodeIO** [comment]
What does `npm -v` show exactly?

**Comment by chevin99** [comment]
5.6.0

**Comment by dcodeIO** [comment]
Really strange, just asked because it looks like older versions of npm that didn't yet support scoped packages.

**Comment by chevin99** [comment]
Looks like you narrowed it down to scoped packages though, so that helps.  Thanks.  We can close this, since I noticed I'm seeing the same with non protobuf scoped packages too.

**Comment by chevin99** [comment]
Strangely, it worked ok for me by reverting back to npm v4.
