### ISSUE TITLE
Reading multiple messages

### ISSUE THREAD

**Issue by Luckydok** [dcodeIO/protobuf.js#986]
protobuf.js version: 6.8.4

Hello,

I have a file which contains multiple types of messages (always stored in the same order). They are encoded with their length prepended before them (I am able to parse them one by one with decodeDelimited()).
I want to decode the whole file, using the good .proto type at each time, to get the right message. As the file always stores the messages in the same order, I know when to use each .proto type. I tried various things, I'm now using the Node.js fileSystem.createReadStream() method, to read from an index to another (allowing me to, first, get the prepended size of the message (with Reader.uint32()), and then read till we reached this size, and use decode to decode my message).
I got some problems with getting the real size of the messages, and the createReadStream method is not always easy to use. Is there a simpler way to do this ?
Please excuse me if my question is stupid, I am very new to Protocol Buffer ...

Thanks

**Comment by dcodeIO** [comment]
Can't you use an outer message in this case? Like

```proto
message Container {
  Message1 message1;
  Message2 message2;
  ...
}
```

Otherwise you could read the file using a `protobuf.Reader`, for example:

```js
var reader = protobuf.Reader.create(myFileContents);
var message1 = Message1.decodeDelimited(reader);
var message2 = Message2.decodeDelimited(reader);
...
```

**Comment by Luckydok** [comment]
Thanks !
It works well with the reader (just had to wrap the Buffer in an Uint8Array to avoid the "illegal buffer" exception).
For my repeated fields I used the Reader, reading firstly the number of repeated fields (on one byte), then the size of each message (on another byte) and finally decoding one by one those repeated fields.
Thanks a lot for your help !

**Comment by dcodeIO** [comment]
> just had to wrap the Buffer in an Uint8Array to avoid the "illegal buffer" exception

`protobuf.Reader.create` should actually take care of both `Uint8Array` and node `Buffer`s. When a buffer is given, a `protobuf.BufferReader` should be returned. Could be a bug.
