### ISSUE TITLE
How to decode unknown type?

### ISSUE THREAD

**Issue by bauerj** [dcodeIO/protobuf.js#996]
Assuming I have a .proto file like this:

```proto
// awesome.proto
package awesomepackage;
syntax = "proto3";

message AwesomeMessage {
    string awesome_field = 1; // becomes awesomeField
}

message AwfulMessage {
    string awful_field = 1;
}
```

and I receive a `buffer` from some kind of API endpoint, how would I decode the `buffer` without knowing its type beforehand?

The examples show usage like this:

```js
let decoded = AwesomeMessage.decode(buffer);
````

But how would I decode the message without knowing if it's an `AwesomeMessage` or an `AwfulMessage`?

Surely this can't be the expected procedure:

```js
let buffer = API.getMessage();
try {
    let decoded = AwesomeMessage.decode(buffer);
    console.log("This is an awesome message 😃", decoded);
}
catch (e) {
    let decoded = AwfulMessage.decode(buffer);
    console.log("This is an awful message! 😟", decoded);
}
```

**Comment by dcodeIO** [comment]
You could wrap the varying messages in a wrapper message that uses a [oneof](https://developers.google.com/protocol-buffers/docs/proto#oneof) to indicate which one is present.

**Comment by bauerj** [comment]
Thanks, that makes sense!

From reading [Encoding  |  Protocol Buffers  |  Google Developers](https://developers.google.com/protocol-buffers/docs/encoding) I get the impression that the message type is not even part of the message itself. Is that correct?

**Comment by dcodeIO** [comment]
Yeah, it's id is part of the parent message.
